### ISSUE TITLE
Bruno meta file for folder

### ISSUE THREAD

**Issue by ajaishankar** [usebruno/bruno#100]
Not sure if this is already supported, but having a meta file in a folder makes configuring the collection runner insanely simple!

```js
meta.bru

collection-runner:vars {
  $iterations: 10
  $delay: 1000
  transactionId: _.random(42)
}
```

**Comment by helloanoop** [comment]
Yup, this is planned.
We need to support folder level tags which apply for all requests inside the folder.

A good example is the `auth` which we are yet to introduce which automatically decorates all requests inside the folder with the token.

I was thinking of naming it as `index.bru` , similar to how node module resolution treats `index.js` or

**Comment by ajaishankar** [comment]
yes `index.bru` is clean and nice! 👍

**Comment by helloanoop** [comment]
Closing this as we have `folder.bru` and `collection.bru` files in folder root and collection root.
When we add support for yaml storage, this will be `folder.yml` and `collection.yml`
