### ISSUE TITLE
Long integer gets truncated and altered

### ISSUE THREAD

**Issue by jmizv** [usebruno/bruno#1000]
I have a REST endpoint written in Java Spring Boot. When I call it via Bruno, my path variable get truncated, see:

![grafik](https://github.com/usebruno/bruno/assets/37914724/33c2e14b-cced-443c-acf8-93f2ee3766fe)

1. In the background is my debugger session in IntelliJ, exactly where the call is intercepted.
2. In the foreground is Bruno and you can see the passed in parameter for my `agency`.
3. It seems that the original value of `2017236094450943841` entered in Bruno gets somehow altered to be `2017236094450943700`.
4. When I mimic the exactly same call via `curl`, I don't see this truncation.

Is this a bug?

I'm using
```
Bruno: v1.1.0
electron: 21.1.1
chrome: 106.0.5249.103
node: 16.16.0
v8: 10.6.194.17-electron.0
```

**Comment by helloanoop** [comment]
Can you try putting quotes around it `"2017236094450943700"` ?

JS does not handle big int and that could be a potential reason. 

Also, Bruno typecasts the vars and convert it into a number if the var is a number. Will have to revisit the design tradeoffs of typecasting and see whether it's causing more problems than the issue its trying to solve.

**Comment by jmizv** [comment]
> Can you try putting quotes around it `"2017236094450943841"` ?

Thanks, this helps:

![grafik](https://github.com/usebruno/bruno/assets/37914724/491b0b1c-1009-468e-9dee-48ac8c40e237)

**Comment by helloanoop** [comment]
Cool.

Here is a long term solution I am thinking of
In our parser, We could do is check if the value is a long int and then automatically typecast it as string itself.

**Comment by dorfiman** [comment]
I am having this issue of a long integer being rounded on the response. 
The application is returning
`
{
  "id": 816003404684853249
}
`
but Bruno shows
`{
  "id": 816003404684853200
}`
I am trying with Bruno v1.10.0.
Are you addressing this issue as well?

**Comment by open2bonobo** [comment]
faced the same issue in response window. My aspnet controller return             return Content("123456789012345678901234567890", "text/plain");

and i see 1.2345678901234568e+29 in Response tab. Bruno 2.2.0

<img width="358" height="260" alt="Image" src="https://github.com/user-attachments/assets/7a37c5ac-bc01-43eb-8459-5893684ea2e1" />
