### ISSUE TITLE
Error invoking remote method 'send-http-request': TypeError: Cannot read properties of undefined (reading 'toUpperCase')

### ISSUE THREAD

**Issue by cyrilgeorge153** [usebruno/bruno#1002]
Getting error added in title while using Digest Auth in Bruno.

![image](https://github.com/usebruno/bruno/assets/52770689/371104f6-d79f-4e27-a6e6-6e807fa34a48)

**Comment by rahul-kumar-sdet** [comment]
Similar issue is faced while using any JS function like Match etc in the script section
