### ISSUE TITLE
JSON Body validation

### ISSUE THREAD

**Issue by kwinso** [usebruno/bruno#1007]
Hi! First things first, thanks for the great project, I've been really enjoying using it, I really like the minimalist approach you've chosen.

But yesterday I've spent around 3 hours trying to understand why my backend framework refuses to parse my JSON request properly.

The issue was extra comma in my JSON that I put there accidentally and didn't even notice.
I think, it's essential to have some kind of validation of JSON body input for stupid mistakes like this. As I remember, Postman yells at you when you try to use invalid JSON. I think, Bruno should do it too

**Comment by helloanoop** [comment]
@kwinso Json linting was shipped yesterday in  v1.2.0
