### ISSUE TITLE
Handle invalid cookie host

### ISSUE THREAD

**Issue by rbideau** [usebruno/bruno#1012]
When a request returns cookie with invalid host, there is an error ` Error: Cookie not in this host's domain` and the response is displayed at all.

![image](https://github.com/usebruno/bruno/assets/7304827/8e09f386-34f8-4020-b25f-a2a89a128477)  
![image](https://github.com/usebruno/bruno/assets/7304827/d7f1f254-bf6b-4762-a4b3-e192ee0c168a)

Sample CURL output (host name changed for privacy)

<details><summary>Click to expand</summary>
<pre>
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 2620:1ec:46::42:443...
* Connected to test.com (2620:1ec:46::42) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=IE; L=Waterford; O=Test Limited; CN=*.test.com
*  start date: Jun  6 00:00:00 2023 GMT
*  expire date: Jun 10 23:59:59 2024 GMT
*  subjectAltName: host "test.com" matched cert's "*.test.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x55a94b8fde90)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /core/company/number-search/GB/9565115 HTTP/2
> Host: test.com
> user-agent: curl/7.81.0
> accept: */*
> authorization: SECRET
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 200 
< date: Tue, 21 Nov 2023 16:36:35 GMT
< content-type: application/json; charset=utf-8
< content-length: 589
< access-control-allow-origin: *
< access-control-expose-headers: Request-Context
< cache-control: no-cache
< expires: -1
< pragma: no-cache
< set-cookie: ARRAffinity=25ba318c5a47d3b0fdcf83fe52d0c1ee0bd8ea49304c0325ea5168bdbc6f307c;Path=/;HttpOnly;Secure;Domain=sub-domain.not-test.net
< set-cookie: ARRAffinitySameSite=25ba318c5a47d3b0fdcf83fe52d0c1ee0bd8ea49304c0325ea5168bdbc6f307c;Path=/;HttpOnly;SameSite=None;Secure;Domain=sub-domain.not-test.net
< x-aspnet-version: 4.0.30319
< request-context: appId=cid-v1:2e5de438-bb7d-48dc-824c-d5e243e82f17
< x-powered-by: ASP.NET
< x-azure-ref: 20231121T163635Z-ne4xbav52h72h17a697yeb7bcw0000000h2000000000szxr
< x-cache: CONFIG_NOCACHE
< accept-ranges: bytes
< 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection #0 to host test.com left intact

</pre>
</details>

I could not find any information in the dev tools but let me know if I should look somewhere specific.

- Bruno version: 1.2.0

**Comment by helloanoop** [comment]
@rbideau This has been fixed in `v1.3.0`

Please reopen if the issue persists

**Comment by rbideau** [comment]
> @rbideau This has been fixed in `v1.3.0`
> 
> Please reopen if the issue persists

Thanks, I've tested my request with the new release and it's fixed ✅
