### ISSUE TITLE
[feature request] Extended cookies support

### ISSUE THREAD

**Issue by Sl-Alex** [usebruno/bruno#1023]
The recent change e1a96e0f2356c46293b791b6a99a8552f20f1f1b, that introduced cookies, also introduced some problems that I can't fix.

Before this change, I implemented cookie support in my collection using pre- and post-request scripts. That was easy to do, and I had a complete _scriptable_ control over my cookies. For example, I could delete them whenever I wanted, I could create any in my scripts. Now I don't have this control anymore.

Simple example: I have a test that checks the behavior when session cookie is not set. It does not work anymore because there is no way to delete this cookie after it was set by the previous test. Now I need to close and re-open Bruno to run this single request in the GUI

Fortunately, as of now cookies are not supported in the CLI, so I still can use Bruno, although not that easily. If CLI will also persist cookies without any option to disable or override this behavior, then it will make Bruno unusable for me

**Comment by helloanoop** [comment]
@Sl-Alex 

I am thinking of supporting an app level toggle that allows disabling cookies functionality. Would this solve your issue ?
Later, we can support this toggle at the collection level.

![image](https://github.com/usebruno/bruno/assets/9350733/befa382e-1350-4a7a-9e17-e560b9a7407c)

**Comment by Sl-Alex** [comment]
@helloanoop Yes, that would be a perfect fix.
It will still be possible to use the scripting approach to have a full control over cookies

**Comment by Sl-Alex** [comment]
In case if someone is interested, this is how I handle session cookie without cookies support:
1. Extract it from "set-cookie" response header on the ```login``` page and store them to a variable in a post-request script:
```js
const cookieName = bru.getEnvVar("SessionCookieName");
let cookie = res.headers['set-cookie']
  ?.[0]
  ?.match(new RegExp(`^${cookieName}=(.+?);`))
  ?.[1];

console.log(cookieName + ": " + cookie);
bru.setVar('SessionCookieContent', cookie);
```

2. Take the cookie out of the variable and add it to the "cookie" header for all other requests in a pre-request script:
```js
const cookieName = bru.getEnvVar("SessionCookieName")
const cookie = bru.getVar('SessionCookieContent')

req.setHeader("Cookie", cookieName + "=" + cookie + ";")
```
If I don't need a session cookie, then I just don't add it to the "Cookie" header :)

**Comment by pete-mantell-giffgaff** [comment]
I had a similar script which did the same cookie handling, which has now broken. I can't downgrade to Bruno 1.1.0 as its no longer available on brew, so this feature has made Bruno unusable for me. Given how fast Bruno is progressing, some UI for enabling/disabling beta/new features would be incredibly valuable.

**Comment by helloanoop** [comment]
@Sl-Alex @pete-mantell-giffgaff You can disable cookie functionality in `1.3.0`

![image](https://github.com/usebruno/bruno/assets/9350733/9efc34a1-294b-45ca-b0df-d4dc0fdd239b)

**Comment by pete-mantell-giffgaff** [comment]
Sorry for being slow to respond ... this did fix my issue so that the scripts work again. Thanks!

**Comment by Ansis100** [comment]
@Sl-Alex this is also a perfect solution to everyone missing cookie editing and deleting functionality. I can just use a collection-wide script to add the necessary cookies. Thanks for that!
