### ISSUE TITLE
[BUG] Response headers doesn´t include set-cookie header

### ISSUE THREAD

**Issue by KalleJoP** [usebruno/bruno#1026]
Hey folks,

I have a session authentification with http only cookie, but the cookie doesn´t get recognised by bruno.

I´ve tested with Insomnia (exactly same request) and there the response contains the set-cookie header.

![grafik](https://github.com/usebruno/bruno/assets/61844416/61d1df94-4846-4bde-8f99-2038ba5bf32e)

For better understanding:

I run a elixir phoenix application with the basic auth from phx.gen.auth.

btw: thanks for the amazing work ❤️

**Comment by helloanoop** [comment]
This issue has been fixed in the latest version of Bruno.
Please reopen if the issue persists.
