### ISSUE TITLE
[BUG] JSON formatter fails to handle non-string variable placeholder

### ISSUE THREAD

**Issue by the8tre** [usebruno/bruno#1038]
When trying to assign a non-string value from the collection/environment to a JSON field the formatter reports a parsing error:
`Expecting 'STRING' , '}' got '{'`
Sample valid JSON:
```json
{
  "SomeField": 42
}
```
Sample failing JSON:
```json
{
  "SomeField": {{someVar}}
}
```

![image](https://github.com/usebruno/bruno/assets/7083377/14233654-afd6-442b-9a49-6f1edd319b69)

Tested in Bruno `1.2.0`

**Comment by n00o** [comment]
You have to put collection/environment variables inside of a string for it to work. So it would look like something like this:
```json
{
  "SomeField": "{{someVar}}"
}
```
It's understandably confusing since the text turns orange implying that it is correctly formatted. I guess it could be possible to interpolate collection/environment variables outside of quotes if they are numbers but it would be programmatically complicated. The other solution would be to provide a hint that it needs to be inside of a string to work.

**Comment by the8tre** [comment]
I get the idea of wrapping things as strings.
But this will lead to a 400 error if the API being called expects a number or a boolean instead of a string.

I agree that dispite the error in the editor (without string wrapping)  the call will still work, but the the prettifier can't prettify anymore.

**Comment by n00o** [comment]
This relates to the pull request I made here #1025. I can make sure the JSON linting errors doesn't show for Bruno collection/environment variables.

**Comment by n00o** [comment]
It appears that the Prettify button for JSON bodies doesn't work anymore if you use `{{someVar}}` in the without quotes inside of it. Might need to fix that too.

**Comment by IgorArnaut** [comment]
This also happens when sending a String as a response.

Java code:
```Java
@DeleteMapping("{id}/delete")
public ResponseEntity<String> deleteListing(@PathVariable int id) {
    listingServ.deleteListingById(id);
    return ResponseEntity.ok("Listing with the id " + id + " is deleted successfully.");
}
```
![Image](https://github.com/user-attachments/assets/3f4cb900-f863-4d2b-b0a4-9e1f153775ea)

**Comment by anusree-bruno** [comment]
@IgorArnaut 
Could you check what Content-Type the server is sending in the response headers? This will help us understand if Bruno should be treating it as JSON or plain text.
