### ISSUE TITLE
Undefined variables in request should not be replaced with empty strings

### ISSUE THREAD

**Issue by syedmoizurrehman** [usebruno/bruno#1056]
When using strings surrounded with double braces, e.g. `{{some_content}}`, as part of the request, Bruno replaces them with empty strings before sending the request, if the content inside the braces is not a defined variable. Since this disables the user from sending such strings as part of the request, I propose that such unresolved variables should be sent verbatim as part of the request. This is the behavior in Postman as well.

### Reproduction
Use following cURL to reproduce this behavior:
```
curl --request POST \
  --url 'https://webhook.site/d9fea9ac-2eb6-45b8-80e0-25f2a7030b20?q=-%3E%7B%7Bmy_q%7D%7D%3C-' \
  --header 'Content-Type: application/json' \
  --header 'my_header: ->{{my_header}}<-' \
  --data '{
  "name": "->{{my_name}}<-"
}'
```

![image](https://github.com/usebruno/bruno/assets/17818950/7f980a56-0a00-4f04-9cd6-ab5be4ea1201)

**Comment by mdreano** [comment]
Hello, could you just not use the arrows ?

**Comment by syedmoizurrehman** [comment]
Hello, the arrows `->` and `<-` are used just to demonstrate that only the content surrounded by braces is replaced by empty strings. So, if we send following request body,
```json
{
  "name": "This is my {{my_name}}!"
}
```
and `my_name` is not a Bruno variable, what Bruno actually sends to the server is following.
```json
{
  "name": "This is my !"
}
```

Let me know if there's any confusion.

**Comment by Its-treason** [comment]
If you don't want `{{my_var}}` to be considered a variable by Bruno you can escape it using a `\` like this `\{{my_var}}`.

**Comment by mat178** [comment]
I also think that replacing stuff with an empty string is not a good idea from a user perspective. It was there for a reason, so it should either throw an error or stay as is, not just simply disappear.

**Comment by wboyle-erwin** [comment]
I am finding that adding the slash to escape the placeholder is leading to unexpected results. I am finding that there are cases where I want to use the data as-is and not resolve the variable.

**Comment by sanjai0py** [comment]
Closing this issue because it appears to be resolved. Please open new issues for any related discussions.
