### ISSUE TITLE
Japanese Localization

### ISSUE THREAD

**Issue by MichaelCharles** [usebruno/bruno#1064]
I'm loving Bruno and plan on trying to get my coworkers on board as well.

However, it being English only will definitely be a roadblock. 

I know that localization is a huge undertaking, and so I don't expect this to be accomplished anytime soon, but I am making this anyway in hopes that it can become part of the pipeline down the road. At the very least, Japanese documentation would be helpful.

**Comment by yutakobayashidev** [comment]
I am a native Japanese speaker and I believe I can contribute to translating the documentation. I will send a pull request when I have time!
