### ISSUE TITLE
Cookie not in host's domain error

### ISSUE THREAD

**Issue by flabbert** [usebruno/bruno#1074]
![Screenshot 2023-11-28 091528](https://github.com/usebruno/bruno/assets/14343943/de7c2a29-adf5-4a70-9426-5c9f7d669b38)

`Refused to connect to 'https://app.posthog.com/batch/' because it violates the following Content Security Policy directive: "connect-src 'self' api.github.com".`

I have not specified any cookie of any kind in bruno

using bruno 1.2.0

**Comment by Charchad** [comment]
I'm experiencing the same issue. Is there anything that can be done to "temporarily" fix this?

**Comment by tcelestino** [comment]
I'm having the same problem here, but in my case it's using an internal API for my company.

**Comment by helloanoop** [comment]
@tcelestino @flabbert @RalfNaujokat @tcelestino 

This should be fixed in `v1.3.0`

Please reopen if the issue persists
