### ISSUE TITLE
delete collection variables?

### ISSUE THREAD

**Issue by BoBNelson1971** [usebruno/bruno#1095]
I added a second collection variable using a similar name to the one I actually need, any way to delete the unused variable?

**Comment by cwalvoort** [comment]
Collection variables are currently cleared when you close and reopen the application.

**Comment by helloanoop** [comment]
We now support `bru.deleteVar()` to support Runtime Variables (Note: These were called Collection Vars in the past)

Variable Docs: https://docs.usebruno.com/get-started/variables/overview
