### ISSUE TITLE
pre-populate headers name field with commonly used headers

### ISSUE THREAD

**Issue by sanbhattdeep** [usebruno/bruno#110]
Change the Name field under Headers to a dropdown and show commonly used header values like content-type, Authorization etc.. for user to select
![image](https://user-images.githubusercontent.com/99815301/221539127-202568a9-2232-4ffe-9c46-03887b09c7b0.png)

**Comment by helloanoop** [comment]
Sure @sanbhattdeep 
Will have this feature made available soon.

**Comment by helloanoop** [comment]
Closing this as this is a duplicate of #54 
@vijayh1907 will be working on this in FOSS Hack 3.0
