### ISSUE TITLE
Upon creating a New Request it should open automatically

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#111]
Upon creating a New Request it should open automatically
Currently, the old tab remains active.

**Comment by paulius-valiunas** [comment]
I would like to take this a step further and allow opening a "temporary" tab without adding it to a collection. Just like you can open a new tab/file in VSCode without necessarily choosing a save location yet.

**Comment by sanjai0py** [comment]
Closing this!

As the [PR](https://github.com/usebruno/bruno/pull/373) adding the feature was already merged and released in [v0.20.0](https://github.com/usebruno/bruno/releases/tag/v0.20.0)
