### ISSUE TITLE
[FEATURE] Add right click on response panel to generate tests

### ISSUE THREAD

**Issue by survivant** [usebruno/bruno#1120]
It will be useful to be able to generate tests from a response.  If I right-click on a word, we could have a popup to contains a sub-menu : Generate tests -> : equals, not equals, contains... on a specific word

![image](https://github.com/usebruno/bruno/assets/191879/4e0fa037-d853-4d6a-a85c-a601424e751a)

Like in this picture the button could suggest equals and that will generate the testcase.

ex : 
````javascript
test("args.patate should equals", function() {
  const data = res.getBody();
  expect(data.args.patate).to.equal("Duis posuere augue vel cursus pharetra. In luctus a ex nec pretium...");
});

test("headers.x-forwarded-proto should equals", function() {
  const data = res.getBody();
  expect(data.headers.x-forwarded-proto).to.equal("https");
});
````

**Comment by survivant** [comment]
PS.  right now the keys with "-" seams to case issue
![image](https://github.com/usebruno/bruno/assets/191879/d358ef9c-81e9-4875-b02b-fecf3548e76f)

**Comment by survivant** [comment]
Ah.  if the keys contains "-" you need to change the structure to : 
![image](https://github.com/usebruno/bruno/assets/191879/23fc824d-0a45-45ea-997d-100480412993)

**Comment by helloanoop** [comment]
Closing this as this does not align with our UX roadmap.
Open to revisit if there is broader interest from the community on the flow suggested.
