### ISSUE TITLE
[FEATURE] Add the option to generate tests from the response

### ISSUE THREAD

**Issue by survivant** [usebruno/bruno#1125]
We could auto-generate a test template from the response.  I have a response and the tests generated should look like this
````json
{
  "args": {
    "patate": "Duis posuere augue vel cursus pharetra. In luctus a ex nec pretium..."
  },
  "data": {
    "text": "Duis posuere augue vel cursus pharetra. In luctus a ex nec pretium..."
  },
  "files": {},
  "form": {},
  "headers": {
    "x-forwarded-proto": "https",
    "x-forwarded-port": "443",
    "host": "postman-echo.com",
    "x-amzn-trace-id": "Root=1-656cb448-1e8107376a539933791cc451",
    "content-length": "80",
    "accept": "application/json, text/plain, */*",
...
````

![image](https://github.com/usebruno/bruno/assets/191879/4a6e6900-8169-4bad-834e-6c5c6bc43376)

**Comment by survivant** [comment]
This feature is part of 3 features : 

- https://github.com/usebruno/bruno/issues/1125
- https://github.com/usebruno/bruno/issues/1126
- https://github.com/usebruno/bruno/issues/1127

combined together those could generate tests/assert for the line that we want form the response.

**Comment by helloanoop** [comment]
After careful consideration, we've decided that adding checkboxes to each line of the response editor introduces a UX tradeoff that may not be justified by the added functionality of test automation. 

We'll reopen this if there is significant interest from the broader community for this feature.
