### ISSUE TITLE
[FEATURE] Generate tests/asserts from the response using checkboxes

### ISSUE THREAD

**Issue by survivant** [usebruno/bruno#1127]
once we are a response, we could select the lines that we want and generate tests/assert from those lines.

Something like that
![image](https://github.com/usebruno/bruno/assets/191879/d40c8890-787d-409a-9c3d-0f84ebd0f36a)

**Comment by survivant** [comment]
This feature is part of 3 features : 

- https://github.com/usebruno/bruno/issues/1125
- https://github.com/usebruno/bruno/issues/1126
- https://github.com/usebruno/bruno/issues/1127

combined together those could generate tests/assert for the line that we want form the response.

**Comment by helloanoop** [comment]
Closing this issue. See https://github.com/usebruno/bruno/issues/1125#issuecomment-2329691822
