### ISSUE TITLE
tooltip on mouse hover over environment variable value does not work in case of more than 1 variable

### ISSUE THREAD

**Issue by sanbhattdeep** [usebruno/bruno#113]
when constructing an URL for an API request using environment variables, hovering the mouse over the variable shows the variable value

This works only if the variable expression contains only 1 variable for e.g. https://{{base_url}}

if the variable expression contains more than 1 variable it only shows the last variable value and not for both for e.g. 
hovering over base_url or resource under https://{{base_url}}{{resource}} shows the resource variable only

**Comment by barathrajramachandran** [comment]
@helloanoop I am picking up this issue.

**Comment by helloanoop** [comment]
This has been fixed in `v0.16.5` Thanks to @brahma-dev !
