### ISSUE TITLE
Feature Request - Support for MultipartFile in request body of POST requests

### ISSUE THREAD

**Issue by sgowris2** [usebruno/bruno#114]
Sending a POST request with a file as part of the request body is a common use-case for applications of all sorts. For example:
1. Uploading photos and videos
2. Uploading documents 
3. Uploading datasets in compact file formats

Postman supports this in the following fashion:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/2262740/221892411-caea5691-b4f9-4453-8070-50219122de41.png">

...where "File" and "Text" are two options given to each item in the form.

**Comment by helloanoop** [comment]
This is planned. Not able to pin a deadline on when this will be available, but this definitely a priority.

**Comment by chrisnagel** [comment]
@sgowris2 Is it possible that this requirement has now been implemented as part of https://github.com/usebruno/bruno/pull/1130?

**Comment by sanjai0py** [comment]
Closing this as the [PR](https://github.com/usebruno/bruno/pull/1130) implementing the feature has already been merged and released in [v1.8.0](https://github.com/usebruno/bruno/releases/tag/v1.8.0)
