### ISSUE TITLE
[Feature]: Add automatic tests and scripts mapping from postman import 

### ISSUE THREAD

**Issue by bpoulaindev** [usebruno/bruno#1147]
**pm.variable** and **pm.environment** get and set commands can be translated into **bru commands**
Need to improve import function to enable this translation and comment non-translatable commands

**Comment by sanjai0py** [comment]
Closing this issue as the pull request adding the feature has already been merged into Bruno and released in [v1.12.0](https://github.com/usebruno/bruno/releases/tag/v1.12.0).
