### ISSUE TITLE
1st occurrence of process.env.{{VARIABLE}} is not handled when used in Body

### ISSUE THREAD

**Issue by GarlicPunk** [usebruno/bruno#1148]
When using `{{process.env.VARIABLE}}` within the payload body to reference the `.env` secret variables, the first use does not populate.

[Bruno v1.3.1]

_cat .env_
``` 
DOT_VAR1=fromDotFile
```

_Payload body_
```
{
  "key0" : "Value0",
  "Key1" : "{{process.env.DOT_VAR1}}",
  "Key2" : "{{process.env.DOT_VAR1}}",
  "Key3" : "{{process.env.DOT_VAR1}}"
}
```

_data passed to server_
```
{
  "key0": "Value0",
  "Key1": "",
  "Key2": "fromDotFile",
  "Key3": "fromDotFile"
}
```

If key1 is deleted from payload body, key2 is then blank on submit.

It can worked around but using a pre-request script to set as collection variable and updating payload body variable.

```
bru.setVar("DOT_VAR1", bru.getProcessEnv("DOT_VAR1"));
``` 

<img width="1525" alt="Screenshot 2023-12-05 at 12 10 09 PM" src="https://github.com/usebruno/bruno/assets/152979750/24e2503b-3228-4e2d-93c3-fdc8c1065687">

<img width="833" alt="Screenshot 2023-12-05 at 12 31 35 PM" src="https://github.com/usebruno/bruno/assets/152979750/dd9d50a4-1de8-454a-9241-88b9e20e78de">

**Comment by Its-treason** [comment]
This seems to be a bug caused by #964 / [#bad9d0](https://github.com/usebruno/bruno/commit/bad9d0a3ef642980941528ba5a57a89265e285a2) and related to #1143. I think @nelup20 is already working on a fix.
