### ISSUE TITLE
[bug] Scripts are being send it with extra square bracket

### ISSUE THREAD

**Issue by iuri-aramos** [usebruno/bruno#1150]
I have a request that creates the payload on the script tab.
I create a sample payload, stringify it and set it in the req.setBody function.
When I checked the Bruno request, the payload has an extra square bracket at the end of the payload where there is no array to close.

![image](https://github.com/usebruno/bruno/assets/13989950/cb577a26-e89b-4a00-b451-3ed1237cbeb8)

I suppose that the problem is in the replace function existent in the packages/bruno-electron/src/ipc/network/interpolate-vars.js

**Comment by Its-treason** [comment]
This seems to be a bug caused by #964 / [#bad9d0](https://github.com/usebruno/bruno/commit/bad9d0a3ef642980941528ba5a57a89265e285a2) and related to #1143. I think @nelup20 is already working on a fix.
