### ISSUE TITLE
[Feature] Markdown links opening in Docs section

### ISSUE THREAD

**Issue by Wapax** [usebruno/bruno#1156]
Hi,

When writing links to the Docs section, Bruno currently opens them in the current window without the availability to navigate into this window or close it to return to Bruno's interface. The only way I found to return to Bruno is to close the entire program and reopen it.

https://github.com/usebruno/bruno/assets/62053576/2fe55614-9f3e-434d-ac88-81a6b343e58d

What should be good is to open the links into the default system browser instead.

**Comment by bpoulaindev** [comment]
I solved it i'm sending the PR in a few hours

**Comment by Wapax** [comment]
Hi, the problem seem to be not fixed

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/1176) adding the feature had already been merged and released in [v1.6.0](https://github.com/usebruno/bruno/releases/tag/v1.6.0). Please try the latest version of bruno [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0)

**Comment by Wapax** [comment]
Well @sanjai0py, we can now navigate through the web page but how to quit and go back to bruno's interface ?
