### ISSUE TITLE
req.getHeader and req.getHeaders()  methods not working in Bruno 1.4.0

### ISSUE THREAD

**Issue by cyrilgeorge153** [usebruno/bruno#1161]
![image](https://github.com/usebruno/bruno/assets/52770689/4b8c72b8-6172-47a6-9780-8176df85b9d8)

**Comment by Its-treason** [comment]
I think you mixed up request "req" and response "res"

![grafik](https://github.com/usebruno/bruno/assets/39559178/dcd57049-8661-4bcb-91b2-416e8a096bbc)

**Comment by cyrilgeorge153** [comment]
@Its-treason  Thanks for pointing out res.getHeader and res.getHeaders()  methods are working but req.getHeaders is not working or is something wrong from my side?

![image](https://github.com/usebruno/bruno/assets/52770689/83dfc99d-cbfc-4b30-84ad-9a38bb61d2f9)

![image](https://github.com/usebruno/bruno/assets/52770689/57dba7d4-ad3d-464d-8992-5eacf344350c)

**Comment by Its-treason** [comment]
In the last example, you're trying to concatenate an object with a string and JavaScript will convert that object with your headers into the string `[object Object]`.

Try to pass "headerValues" as the second parameter to console.log like this: 
```
const headerValues=req.getHeaders();
console.log("headerValues are:",headerValues);
```

**Comment by cyrilgeorge153** [comment]
@Its-treason Thanks!

**Comment by Its-treason** [comment]
I think the response Headers object is generated by axios and has a custom [toString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString?retiredLocale=de) method.

**Comment by cyrilgeorge153** [comment]
@Its-treason Thanks for the clarification.
