### ISSUE TITLE
Generate Guid (UUID4) - Pre-request variable

### ISSUE THREAD

**Issue by GKotfis** [usebruno/bruno#1163]
I would like to have pre-generated uuid for every request call. Since I didn't find anything in the docs about built-in variables like `{{$guid}}` I tried to assign var based on JS template literal. But unsuccessfully. May I ask you, for example, how literals should be defined?
![image](https://github.com/usebruno/bruno/assets/7391978/6dfb4683-0a0c-407c-aa42-8ea96def737c)

**Comment by GKotfis** [comment]
Thanks @cyrilgeorge153 
I came up with a similar solution with Script usage:
```js
const { v4: uuidv4 } = require('uuid');
bru.setVar("event_id",uuidv4());
bru.setVar("event_date", new Date().toISOString());
```

I'll review your solution because, with mine, I'm not comfortable defining variables in a 'global' scope.

**Comment by sanjai0py** [comment]
Closing this issue as it appears to be resolved. Please don't hesitate to reopen this issue if I am wrong!
