### ISSUE TITLE
[BUG] Variable evaluation before submit request

### ISSUE THREAD

**Issue by survivant** [usebruno/bruno#1165]
Not all the variable are resolved before submitting the request.

here the result.  You can see that the variable `uuid`didn't resolve it's value
![image](https://github.com/usebruno/bruno/assets/191879/13e37977-6d3b-4979-a1ce-55f502f9ad9a)

here How the variable was set
![image](https://github.com/usebruno/bruno/assets/191879/e30a8dae-452e-4042-a5f8-bc4b9ba0e2f1)

**Comment by survivant** [comment]
in ``bruno/packages/bruno-electron/src/ipc/network/interpolate-vars.js`` it should replace the value of a variable, if the variable value is a variable, we look until all the variable are replaced

**Comment by Zomzog** [comment]
I think it's the same issue as #956

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/2234) implementing the feature has already been merged into Bruno and released in the latest [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0). 
 
https://github.com/usebruno/bruno/assets/84461672/65389639-34ec-42e6-a3ad-3c7b38e40a90
