### ISSUE TITLE
Unable to make request when used with Proxy

### ISSUE THREAD

**Issue by satrox28** [usebruno/bruno#117]
Hi,

Thanks for creating such a nice tool.

When I am trying to explore the tool for any request, am getting certificate error since am using a http proxy.

```
Error invoking  remote method "send-http-request": Error: unable to verify the first certificate.
```

As its a nodejs application, I would like to set the environmental variable for NODE_EXTRA_CA_CERTS and pass the proxy certificate.

Can you help me on how to pass this env for this application.

**Comment by SanichKotikov** [comment]
I have almost the same error: `unable to get local issuer certificate`.

**Comment by satrox28** [comment]
@helloanoop 

Thanks for checking on the feature request. Only concern I have on your proposal is, if we have multiple collections have to modify the json every where correct?.

**Comment by helloanoop** [comment]
@satrox28 
When you mentioned
> I would like to set the environmental variable for NODE_EXTRA_CA_CERTS and pass the proxy certificate.

I thought you were talking about postman environment variables. 
If I am understanding correctly, you are talking about setting a system env variable called as `NODE_EXTRA_CA_CERTS`. Is that right ?

> if we have multiple collections have to modify the json every where correct?

Good point. It makes sense to setup one time at one place.

**Comment by satrox28** [comment]
> @satrox28 When you mentioned
> 
> > I would like to set the environmental variable for NODE_EXTRA_CA_CERTS and pass the proxy certificate.
> 
> I thought you were talking about postman environment variables. If I am understanding correctly, you are talking about setting a system env variable called as `NODE_EXTRA_CA_CERTS`. Is that right ?
> 
> > if we have multiple collections have to modify the json every where correct?
> 
> Good point. It makes sense to setup one time at one place.

Yes, when the app launches it should have the env injected. I already have http and https proxy as system env variable but it doesn't work with it.

**Comment by DRob1260** [comment]
Was anyone encountering this issue able to solve this or work around it? I'm definitely interested in using Bruno (coming from Postman). But I need a way to use it with a custom cert

**Comment by DRob1260** [comment]
I am indeed on a Mac. Looking forward to the update. Thanks!

**Comment by helloanoop** [comment]
@DRob1260 Mac builds have been released. Yuu should be able disabled ssl verification in the app preferences.

**Comment by DRob1260** [comment]
> @DRob1260 Mac builds have been released. Yuu should be able disabled ssl verification in the app preferences.

I saw that, thanks so much!

**Comment by vdavid** [comment]
I bumped into this on a Mac. [This StackOverflow thread](https://stackoverflow.com/questions/77952356/getting-error-unable-to-get-local-issuer-certificate-in-bruno) solved it for me in no time, linking it here for others to find. The gist:
1. Go to Preferences (`⌘,` on Mac)
2. Uncheck "SSL/TLS Certificate Verification".
