### ISSUE TITLE
Feature Request: Script and tests at folder level

### ISSUE THREAD

**Issue by tho-gru-38** [usebruno/bruno#1174]
It would be very useful if it is possible to execute scripts or tests at folder level.

My use case is that the service i am testing runs on a system where changes are applied very frequently. Therefore I have the demand to repeat all requests in a folder in case an error occurred. But because I can not execute at folder level I can only rerun the complete collection. this is frustrating because the collection needs one hour or more but the changes are applied ever five minutes.

If scripts and tests are available at folder level I can count errors an retries at this level. So I can decide where to skip using the new bru.setNextRequest feature.

**Comment by kyleboe** [comment]
I commented on #1334 as well but I think this may be a solid case to remove "Folders" altogether and allow for Collections to be nested.

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/2529) adding the ability to add folder level Headers, Scripts, and Tests has already been merged into Bruno and released in the latest [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0)
