### ISSUE TITLE
environment selection option is disabled

### ISSUE THREAD

**Issue by pbmugade** [usebruno/bruno#1178]
when I open bruno app then environment selection option(top right corner) is not visible
<img width="1719" alt="Screenshot 2023-12-07 at 3 03 16 pm" src="https://github.com/usebruno/bruno/assets/75826365/4b8a38c6-11f2-4b38-8755-0317a39c33a9">

**Comment by Its-treason** [comment]
You have to open a collection / request first

**Comment by saul9402** [comment]
There are some way to create a global environment or something similar?

What I wanted to do is to have my collections separate by bussines logic but using a single environment for all oh them instead of using an environment for each folder or collection.

**Comment by helloanoop** [comment]
@saul9402 Global environments are on the roadmap. Hoping to have it shipped before end of Dec.

**Comment by saul9402** [comment]
> @saul9402 Global environments are on the roadmap. Hoping to have it shipped before end of Dec.

@helloanoop thanks for the information!

**Comment by sanjai0py** [comment]
Closing this issue as it appears to be resolved!
