### ISSUE TITLE
Scroll bar for collections pane

### ISSUE THREAD

**Issue by rsb-23** [usebruno/bruno#118]
Collections pane(left) need a separate navigation from right pane. 
In case of 20+ apis in collection, all fields of right pane scrolls up. So in case, one has to work with last 5 APIs, then they have to keep scrolling. This can be easily solved by separating the navigation.
 ![image.png](https://user-images.githubusercontent.com/57601627/223023014-b1adc51e-9dd7-41eb-950e-b13cb4c284a6.png)

**Comment by helloanoop** [comment]
@rsb-23 Yes, This makes sense. Should be fairly straightforward to get this done.

**Comment by sreevenkat** [comment]
This seems to be a good first issue for me to start on. I'll pick this up. @helloanoop

**Comment by helloanoop** [comment]
Thanks @sreevenkat !

**Comment by helloanoop** [comment]
This has been fixed and is available in the latest release of Bruno.
