### ISSUE TITLE
Feature: Clear response button

### ISSUE THREAD

**Issue by kernwig** [usebruno/bruno#1182]
My team uses Bruno to perform sprint demos. We prepare the requests and practice first. When it comes time to demo to the customer, it's quite the spoiler to have the practice responses showing in the results.

We switched to Bruno from Postman, which has a button to clear the output. This is a feature request to add such a button.

**Comment by CRAZy-Monk3Y** [comment]
@helloanoop this issue is interesting. I am new to opensource and I want to try fix this.

**Comment by smebberson** [comment]
I just raised #1184 to resolve this.

**Comment by CRAZy-Monk3Y** [comment]
Hello @smebberson, great work finding the solution! I was also working on it, but looks like you beat me to it ;)

**Comment by smebberson** [comment]
> Hello @smebberson, great work finding the solution! I was also working on it, but looks like you beat me to it ;)

Sorry @CRAZy-Monk3Y 😅
