### ISSUE TITLE
SSL error while sending request

### ISSUE THREAD

**Issue by aravindMylsamy** [usebruno/bruno#1195]
Hi, getting the below error while sending the request using axios from the script

```
"Error: self signed certificate in certificate chain
    at AxiosError.from (/Applications/Bruno.app/Contents/Resources/app.asar/node_modules/@usebruno/js/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/Applications/Bruno.app/Contents/Resources/app.asar/node_modules/@usebruno/js/node_modules/axios/dist/node/axios.cjs:3029:25)
    at RedirectableRequest.emit (node:events:527:28)
    at eventHandlers.<computed> (/Applications/Bruno.app/Contents/Resources/app.asar/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)"

code: "SELF_SIGNED_CERT_IN_CHAIN"

```

**My axios post request is**

```
axios.post(url,data).then((res) => {
   console.log("RESPONSE ==== : ", res);
 })
 .catch((err) => {
   console.log("ERROR: ====", err);
 });
```

**Comment by Its-treason** [comment]
Axios in scripts does not inherit any request options like custom certificates or disable SSL from Bruno.

You currently need to do this manually inside your script. Here is an example of disabling SSL verification: https://github.com/axios/axios/issues/535#issuecomment-607439471

**Comment by Its-treason** [comment]
Axios in scripts does not inherit any request options like custom certificates or disable SSL from Bruno.

You currently need to set these options manually inside your script. Here is an example of disabling SSL verification: https://github.com/axios/axios/issues/535#issuecomment-607439471

**Comment by sanjai0py** [comment]
Closing this issue as completed due to inactivity.

**Comment by Bottleface** [comment]
@Its-treason, I have tried this approach a few different ways and Bruno gives the following error:

`Error invoking remote method 'send-http-request': Error: Error: Cannot find module https`

Which is perplexing given that the https module should be built in and native to node.js.  I'm not even sure how to manually install it through npm, or if that's even possible.

This is what my script looks like;

```
const https = require('https');
const axios = require('axios');
const agent = new https.Agent({
        rejectUnauthorized: false
      });

axios.get('https://www.google.com', { httpsAgent: agent });
```

Has anyone been able to successfully use the https module in their bruno scripts?

**Comment by Bottleface** [comment]
> > @Its-treason, I have tried this approach a few different ways and Bruno gives the following error:
> > `Error invoking remote method 'send-http-request': Error: Error: Cannot find module https`
> > Which is perplexing given that the https module should be built in and native to node.js.  I'm not even sure how to manually install it through npm, or if that's even possible.
> > This is what my script looks like;
> > ```
> > const https = require('https');
> > const axios = require('axios');
> > const agent = new https.Agent({
> >         rejectUnauthorized: false
> >       });
> > 
> > axios.get('https://www.google.com', { httpsAgent: agent });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Has anyone been able to successfully use the https module in their bruno scripts?
> 
> Did you make sure to whitelist `https` and enable developer mode for scripts?

Enabling Developer Mode was the trick.  I didn't need to whitelist the module.  I should have read the documentation more thoroughly.
![image](https://github.com/user-attachments/assets/0251fbd8-6cbe-47ea-a440-2d7d6633525b)

Thanks @Its-treason, I appreciate your help =]

**Comment by vijaiendransv** [comment]
Is this solved?  How do I enable developer mode for making use of this https package?  I am still seeing that error as mentioned earlier.
```
Pre-Request Script Error
Error: Cannot find module https
```

**Comment by anusree-bruno** [comment]
@vijaiendransv 

You can click on the safe mode on top right side and then this tab will open here you can choose developer mode when you want to switch. 

Note: This only applies to that particular collection.

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/e8c5a7db-78e4-4c43-bf80-2f9fdbc9ad1e" />

https://docs.usebruno.com/get-started/javascript-sandbox
