### ISSUE TITLE
Bug: Select all key board shortcut on Mac (Command + A) does not work in "Environment Name" text box. 

### ISSUE THREAD

**Issue by sgowris2** [usebruno/bruno#120]
Several textboxes do not support the "Select All" keyboard shortcut on Mac. However, copy and paste keyboard shortcuts work as expected.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/2262740/223321268-0601bf1e-1655-433f-a71e-64d83af29ac9.png">

Have not tested app on any other OS. 

Good for "First Issue" label.

**Comment by helloanoop** [comment]
At long last Bruno Version 0.15.0 happily bids adieu to this issue 🎉 🎉

PS: Duplicate issue that tracked dev on this is #131
