### ISSUE TITLE
Include Auth headers into Generate code output

### ISSUE THREAD

**Issue by vladimirkl** [usebruno/bruno#1208]
Hi, currently Auth headers are not included into output for Generate Code. The only workaround is to add these headers manually to requests. It would be great to fix this.

Bruno v1.4.0 for Mac

**Comment by gustavo-fior** [comment]
fixed in PR #1316 @helloanoop 

:)

**Comment by vladimirkl** [comment]
Not fixed in 1.6.1

**Comment by DivyMohan14** [comment]
@helloanoop https://github.com/usebruno/bruno/pull/1246 this ideally should fix this

**Comment by sanjai0py** [comment]
Closing this as completed. Please open a new issue if it is not resolved!
