### ISSUE TITLE
Assertions still displayed in Tests tab after deletion

### ISSUE THREAD

**Issue by githubaja** [usebruno/bruno#121]
Ver: 0.10.2
OS: Win 11

Steps to reproduce:

Create a request
Add assertions in Assert tab.
Save and execute request.

Assert results should display in Tests tab.

Now delete assertions using the garbage bin button.
Save and execute request.

Assert results are still displayed in Tests tab.
![image_2023-03-07_100329849](https://user-images.githubusercontent.com/55830353/223374408-ba5056ef-887f-4641-9dac-22e70483e94b.png)

**Comment by helloanoop** [comment]
This has been fixed by @bharathbdev in https://github.com/usebruno/bruno/pull/133
and should be available in our upcoming v0.11.0 release.

**Comment by helloanoop** [comment]
@githubaja The fixes are now available in v0.11.0
