### ISSUE TITLE
[BUG] Collection Runner not performing tests nor assertions

### ISSUE THREAD

**Issue by RicardoVizcaya** [usebruno/bruno#1215]
Using v1.4.0 I see that Assets and Tests are not shown in the Runner when they fail:

Assertion and Test Results from Assertion and Tests from a single request:
![grafik](https://github.com/usebruno/bruno/assets/119726103/a53f66fb-0f43-484c-bdf0-c230bc9d1c01)

Using the Collection Runner (Green mark as if all tests where OK and no mention whatsoever of the tests in the right pane):
![grafik](https://github.com/usebruno/bruno/assets/119726103/38206692-a5ae-487d-bb13-90426a548fca)

**Comment by EwaldBorger** [comment]
I was just checking so see if this was a known issue, so a plus one for me.
Bruno cli does work correctly, it is only in the case of running a collection of tests in the GUI.
Love bruno by the way! Converting our Postman collection at the moment.

**Comment by MelGrubb** [comment]
After updating from 1.3.1, my tests no longer seem to be executing in the runner, which renders my regression suite pretty useless. I had hoped that maybe this was just a display issue, but I invalidated one of my tests to check, and I still got a green check mark in the collection runner.

**Comment by helloanoop** [comment]
@mj-h The commit https://github.com/usebruno/bruno/commit/d76253ea04bffeeada116401d38c61fb0f35c7ca had caused a bugs in collection runner where assertionResults were not getting populated (the changes were merged as a part of pr: #619 )

I have reverted the changes in `packages/bruno-app/src/providers/ReduxStore/slices/collections/index.js`

**Comment by helloanoop** [comment]
@RicardoVizcaya @EwaldBorger @MelGrubb This issue has been fixed in `v1.5.0`

**Comment by domgom** [comment]
In my case (version [1.8.0](https://github.com/usebruno/bruno/releases/tag/v1.8.0) I can see the test and assertions showing in the runner but it doesn't stop the runner from executing subsequent requests (which is my expected behaviour).

<img width="381" alt="imagen" src="https://github.com/usebruno/bruno/assets/867231/b787d936-7085-4678-a17e-a5e1ad4413d6">

**Comment by sanjai0py** [comment]
Closing this issue as the reported bug seems to have already been fixed or is not reproducible in the latest version of bruno [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0).
