### ISSUE TITLE
Environment Variables Not Working

### ISSUE THREAD

**Issue by ApproachingApathy** [usebruno/bruno#1221]
For some reason I can't get environment variables to work. Am I missing something simple?

Here, the value of `vod_server_url` is not in the url. 
![Watershot_14-12-2023_11:06](https://github.com/usebruno/bruno/assets/26229099/dda70b0f-2f4c-4964-af46-441c61bce68a)

Even though it's set here:
![Watershot_14-12-2023_11:09](https://github.com/usebruno/bruno/assets/26229099/6173f39a-24a8-4180-9075-e88d8d5062dd)

Version: v1.4.0
OS: Arch Linux
Distribution: aur/bruno-bin

**Comment by martinsefcik** [comment]
@ApproachingApathy Based on the first screenshot you have space before and after variable name. Remove them and it should be working.

**Comment by ApproachingApathy** [comment]
Oh that worked! Did this change recently? My collection is full of things just like this that used to work.

**Comment by Its-treason** [comment]
> Oh that worked! Did this change recently? My collection is full of things just like this that used to work.

Yes, this was changed in #971, but this is more of a side effect of the change.

**Comment by ApproachingApathy** [comment]
Thanks, it might be a good idea to put this in the release notes. My entire collection just stopped working with no warning. Since my issue is fixed I'm closing this now.
