### ISSUE TITLE
Runner with data import

### ISSUE THREAD

**Issue by dan-raa** [usebruno/bruno#123]
Hi, I am not sure if it's not implemented or I can't find it.

Is it possible to use CSV files and generate variables from it like in Postman when using the runner?

Would be great! Thanks, Dan

**Comment by helloanoop** [comment]
Hi @dan-raa !
Yes, this is on the roadmap. Hoping to support this by the end of March 2023.

**Comment by dan-raa** [comment]
Hi @helloanoop,

I'm happy to hear that and a big thank you for the tool and the further development.

**Comment by zackman0010** [comment]
@helloanoop Hi! Is this still on the roadmap? With Postman having now restricted unlimited use of their Collection Runner to their $100/user Enterprise plan, this feature is needed more than ever.

**Comment by helloanoop** [comment]
@zackman0010 Yes, it is. Will get to this soon after some key issues have been completed.

**Comment by RustedAperture** [comment]
@helloanoop has this been implemented. I'm not able to do this atm, preventing me from using bruno full time

**Comment by helloanoop** [comment]
Closing this issue as this feature has been implemented.

Demo: https://www.youtube.com/watch?v=FLJ-stjoeXI
