### ISSUE TITLE
Header assertions not working in collection runner

### ISSUE THREAD

**Issue by MelGrubb** [usebruno/bruno#1234]
Here is a screenshot of a test run as part of a collection run. As you can see, the test against the content-type header fails here. If I run this test individually, however, it passes just fine. I have several of these tests in my collection that are checking for anonymous users getting a 403 back when they try to access a resource that requires authentication. They all fail in this way, but only when run as a group. They all pass when run individually.

![image](https://github.com/usebruno/bruno/assets/1153287/93abcf4e-f407-4982-9cdc-ced1d720e461)

As you can see in the screenshot, it's complaining that the header is undefined. Over in the right-hand pane, however, you can see that the header is not only defined, but it's the exact value that the test was trying to validate. This only happens on the tests in my suite that are expecting something other than a 200 response code. All of the "happy path" tests are able to test the header value without any issues.

**Comment by sanjai0py** [comment]
Closing this issue as the reported bug seems to have already been fixed or is not reproducible in the latest version of bruno [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0).
