### ISSUE TITLE
JSON error response differs from Postman

### ISSUE THREAD

**Issue by r-glebov** [usebruno/bruno#1238]
Hi, first of all thanks for a great new API client! 

I've just started migrating collections from Postman, and noticed a different error 409 response for the same request:

This is postman one:

```
{
    "errors": [
        {
            "code": "600.001.000",
            "title": "Price Changed Error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```

And this is Bruno response:

```
{
  "error": "App::Errors::PriceChangedError"
}
```

Not sure why it happens, but It'd be better to have options how the response look alike.

**Comment by r-glebov** [comment]
One more example.

Postman:

```
{
    "errors": [
        {
            "code": "400.001.006",
            "title": "Total price is invalid or missing"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}

```

Bruno:
```
{
  "error": "App::Errors::Collection"
}
```

**Comment by sanjai0py** [comment]
Is there any way to reproduce this behaviour?

**Comment by r-glebov** [comment]
> Is there any way to reproduce this behaviour?

Unfortunately no, those are endpoints from work. I'm wondering if the reason could be jsonapi response format.

**Comment by Its-treason** [comment]
I can't think of a way that Bruno transforms your response like this.

Can you make sure all requests headers are the same? And if the request works with something like Curl?

**Comment by r-glebov** [comment]
@Its-treason Those are imported requests from Postman, with variables imported as well. I've just checked headers and it seems `Accept` header was not passed. Basically only visible headers were exported from Postman (or imported by Bruno). The hidden ones (where Accept was) were skipped.

Now it is working properly. Thanks folks!
