### ISSUE TITLE
[Bug] Vars pre request trims leading zeros

### ISSUE THREAD

**Issue by nicco09** [usebruno/bruno#1241]
The following sets `identifier` to `1` but it's meant to be a string value `0001`:

<img width="592" alt="Screenshot 2023-12-18 at 2 04 05 PM" src="https://github.com/usebruno/bruno/assets/24377741/02eb02ed-0fd4-4fbe-9605-f43494b6d385">

**Comment by Its-treason** [comment]
Bruno casts vars that look like a number into a number. You can prevent this by quoting your string with double quotes: `"0001"`

**Comment by Deuchnord** [comment]
> Bruno casts vars that look like a number into a number. You can prevent this by quoting your var with double quotes: `"0001"`

I'm sorry to exhume this almost six month-old issue, but why does Bruno cast variables?
Wouldn't it be simpler and less error-prone to take all of them as strings, as they are meant to be used in requests anyway?

**Comment by ion-storm-chaser** [comment]
Agreed. No idea why you would cast variables in a URL string.
