### ISSUE TITLE
[Bug] Headers set at collection level not reflected in generated code snippet

### ISSUE THREAD

**Issue by DivyMohan14** [usebruno/bruno#1245]
When headers are being set at collection level they are not reflected in the generated code snippet, the same header works fine when it is used at request level.

The reason seems to be that the headers injected in the template uses the item request headers, which does not include the collection level headers as of now.

I can pick this up if this makes sense cc: @helloanoop 

seems to be related: https://github.com/usebruno/bruno/issues/1208

**Comment by sanjai0py** [comment]
Closing this as completed because the pull request (https://github.com/usebruno/bruno/pull/1316) that implements the feature has already been merged.
