### ISSUE TITLE
[Feature]: Upgrade to Tailwind V3 to enable children selector

### ISSUE THREAD

**Issue by bpoulaindev** [usebruno/bruno#1248]
A migration to **Tailwind V3** (3.3.6 now) is needed, to enable **child selectors** and stop being dependant on StyledWrapper, which doesn't use the same styling variables as our tailwind config.

This migration is a **non-breaking change**, i already did a PR which also corrects **alias imports** not using an "@", although those can be separated : [Tailwind V3 migration](https://github.com/usebruno/bruno/pull/1083)

Children selector are stable and would enable us to target children when we can't directly give them classnames : 
<img width="282" alt="image" src="https://github.com/usebruno/bruno/assets/64689165/87a2ae09-be34-4b46-b370-c1889eaed0be">

**Comment by helloanoop** [comment]
Bruno now uses Tailwind V3 (3.4.1)
