### ISSUE TITLE
Tests cases added in Tests tab is not getting picked up in Ubuntu Linux system. Asserts are working fine! Test seems to be working after using Ctrl+S. Is this intended behaviour? Or Auto save is not working? An alert box would be a nice addition if user forgets to save the Test details

### ISSUE THREAD

**Issue by cyrilgeorge153** [usebruno/bruno#125]
![Bruno Tests Issue](https://user-images.githubusercontent.com/52770689/225572351-8ed1e930-369c-4f88-a9cb-cd2401fcd472.png)

OS Name:Ubuntu 20.04.5 LTS
OS Type:64 bit

**Comment by helloanoop** [comment]
HI @cyrilgeorge153 

This is a bug.
The intended behaviour is that any changes made in the tests should get reflected without having to save it first.

We will be providing a feature later in the settings to turn on auto save by default.

**Comment by cyrilgeorge153** [comment]
Ok. Thank you.

**Comment by helloanoop** [comment]
@cyrilgeorge153 I have fixed this in the latest version v0.11.0

Also tracking the auto save functionality at #142

**Comment by cyrilgeorge153** [comment]
@helloanoop  Thanks for the quick fix!
