### ISSUE TITLE
{{this}} will fail {{here}} 

### ISSUE THREAD

**Issue by TimSusa** [usebruno/bruno#1254]
I see a problem as for example having more than one var in a route it will only respect the first one, but never respect the second one.

Example:

Sending: {{my.url}}/users/{{id}}

It misses to fill in the id part, even it it was set in the vars. If I take out the my.url part it will correctly set the id part. So it seems to be a bug

**Comment by cyrilgeorge153** [comment]
![image](https://github.com/usebruno/bruno/assets/52770689/22526b14-6d6e-4481-9e25-b999f18240fa)
Working for me. Verified in 1.5.0 snap version ubuntu.

**Comment by TimSusa** [comment]
I will double check this. Thanks for pointing that out. Probably you can close this issue.

**Comment by cyrilgeorge153** [comment]
@TimSusa I have also checked above case in 1.5.1 snap version ubuntu as well and it seems to be working. I cannot close the issue. You can do that from your side. If you are still facing any issue, you can reopen it later.

**Comment by anusreesubash** [comment]
Closing this issue as this has been fixed. Please reopen if the issue persists.
