### ISSUE TITLE
Error on installation - Ubuntu 20.04

### ISSUE THREAD

**Issue by kirstyannepollock** [usebruno/bruno#1267]
Following the install instructions for Linux, I get

`W: GPG error: http://debian.usebruno.com bruno InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 56333D3B745C1FEC
E: The repository 'http://debian.usebruno.com bruno InRelease' is not signed.
`

**Comment by sanjai0py** [comment]
Did you try installing using snapstore?

**Comment by kirstyannepollock** [comment]
Yes, I did, and that worked! I guess that's the solution. Maybe you could update the readme to suggest that?On 22 Dec 2023 10:30, Sanjai Kumar ***@***.***> wrote:
Did you try installing using snapstore?

**Comment by sanjai0py** [comment]
I'm marking this as completed since the issue has been resolved!
