### ISSUE TITLE
Cannot build web app

### ISSUE THREAD

**Issue by DeJayDev** [usebruno/bruno#1268]
Hi,

I am having issues with getting Bruno to build or run locally, `npm run build:web` and `npm run dev:web` both fail with `ReferenceError: document is not defined`.

This issue stems from the `codemirror` dep, which after quickly bumping it to `5.65.16` (and `codemirror-graphql` to `1.3.2` for good luck) this issue seems to go away. 

```
error - ReferenceError: document is not defined
    at /home/dj/oss/bruno/node_modules/codemirror/lib/codemirror.js:88:3
    at /home/dj/oss/bruno/node_modules/codemirror/lib/codemirror.js:11:83
    at Object.<anonymous> (/home/dj/oss/bruno/node_modules/codemirror/lib/codemirror.js:14:2)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.codemirror (/home/dj/oss/bruno/packages/bruno-app/.next/server/pages/_app.js:848:18) {
  page: '/'
}
```

**Comment by balaji-sivasakthi** [comment]
Local setup 
https://github.com/usebruno/bruno/blob/main/contributing.md

```
# use nodejs 18 version
nvm use

# install deps
npm i --legacy-peer-deps

# build graphql docs
npm run build:graphql-docs

# build bruno query
npm run build:bruno-query

# run next app (terminal 1)
npm run dev:web

# run electron app (terminal 2)
npm run dev:electron
```

**Comment by sapjr** [comment]
I still run into the same issue with codemirror version 5.65.16

**Comment by sanjai0py** [comment]
this issue still persists as the merged pull request #1269 is reverted. is there any walk around for this??

**Comment by sanjai0py** [comment]
update: removing the `/node_modules` and all the sub `node_modules` and runnning `npm i --legacy-peer-deps` fixed it. i cant even figure why this works. any ideas?

**Comment by sindhubb** [comment]
Same, is there a workaround. Trying to run bruno locally as a webapp.

**Comment by helloanoop** [comment]
Hi @sindhubb !

Bruno cannot be loaded directly on web.
You need to load it on electron.

You need to follow these steps: https://github.com/usebruno/bruno/blob/main/contributing.md
```bash
# use nodejs 18 version
nvm use

# install deps
npm i --legacy-peer-deps

# build packages
npm run build:graphql-docs
npm run build:bruno-query
npm run build:bruno-common

# run next app (terminal 1)
npm run dev:web

# run electron app (terminal 2)
npm run dev:electron
```

**Comment by mutairibassam** [comment]
@helloanoop Followed the mentioned steps and still the same error.

**Comment by Its-treason** [comment]
> BTW, I am using node v22.2.0, and don't have `nvm`.

Try it with Node v20. I also had some weird problem with node v22. I would highly suggest installing `nvm` for that.

**Comment by mutairibassam** [comment]
Thank you @Its-treason. It's working with node v20.
