### ISSUE TITLE
Not able to user timestamp in request header as in Postman

### ISSUE THREAD

**Issue by xiaohel** [usebruno/bruno#1273]
In Postman I can use {{timestamp}} as request id in request header, I cannot use the same in Bruno.

**Comment by rsilvr** [comment]
You can have a similar feature if you define `timestamp` as a variable in the Pre Request script:

![image](https://github.com/usebruno/bruno/assets/5250902/3aa0c996-2fb3-4040-bd79-3830a1856b3e)

**Comment by xiaohel** [comment]
@rsilvr Thanks. This works. Now I have an JSON in the response like {"token": "abcdefg"}, how can I get it and set a global variable "token" ?

**Comment by rsilvr** [comment]
@xiaohel I know two ways of doing this:
- In "Vars" tab you can assign directly to the variable "token" the content of this response field in the "Post Response"
![image](https://github.com/usebruno/bruno/assets/5250902/d4530d04-8e9c-419b-9261-25c091dd4160)
- You can also do it "manually" in the "Post Response" section of "Script" tab:
![image](https://github.com/usebruno/bruno/assets/5250902/7255664e-b9f5-46ed-ab3e-e96c0c767972)

**Comment by sanjai0py** [comment]
I'm marking this as completed since it seems like the issue has been resolved!
