### ISSUE TITLE
[Issue] Resize the response window

### ISSUE THREAD

**Issue by hi2rashid** [usebruno/bruno#1275]
Click run -> Run the tests in your collection.

Click on individual test to see its result (response).

You cant see full text if its lengthy (or small monitor)

Proposed change:
Would be nice if it has a small Textarea resize button to see full response. 

<img width="947" alt="image" src="https://github.com/usebruno/bruno/assets/10250923/d314b5ce-952c-4409-ad84-1fe0411624ef">

<img width="519" alt="image" src="https://github.com/usebruno/bruno/assets/10250923/d969b8a7-cc5b-4296-9ae6-30eb51b62bd9">

**Comment by Its-treason** [comment]
There is already a PR open to fix this #1272

**Comment by sanjai0py** [comment]
Closing this as the [PR](https://github.com/usebruno/bruno/pull/1272) adding the feature had already been merged into Bruno and released in [v1.6.0](https://github.com/usebruno/bruno/releases/tag/v1.6.0). Please try the latest version of Bruno [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0).

**Comment by Felixmurithi** [comment]
the issue still persists just downloaded Bruno
