### ISSUE TITLE
fix misspelling

### ISSUE THREAD

**Issue by ghost** [usebruno/bruno#1280]
only HTTP, HTTPS, SOCKS4 and SOCKS5 are the correct spelling

![bruno](https://github.com/usebruno/bruno/assets/154873486/eff04f25-e8f3-480d-9219-40c7ca5d8ac2)

**Comment by CRAZy-Monk3Y** [comment]
Hi @helloanoop, I made a pull request that fix this. Can you please approve this pull request #1299

**Comment by helloanoop** [comment]
@CRAZy-Monk3Y 

I feel the smallcase is cleaner, less noisy and elegant. 
Is this just a preference / Is there a technical reason why it should be Capitalised ?

![image](https://github.com/usebruno/bruno/assets/9350733/cda68877-5138-4f46-aec9-f05b26286a9a)

**Comment by CRAZy-Monk3Y** [comment]
@helloanoop It was an issue requested by an user. 
Although there is no direct technical reasoning. Using standardized spellings like HTTP, HTTPS, SOCKS4, and SOCKS5 aligns with globally accepted conventions and industry standards. Consistent terminology enhances code readability and maintains cohesion with widely recognized naming conventions. This conformity fosters a more accessible and comprehensible codebase, facilitating collaboration and reducing potential confusion among developers.

**Comment by helloanoop** [comment]
Hmm..

> It was an issue requested by an user.

Do you have a link to the issue / conversation ?

I actually prefer smallcase, its clean and eleqouent.
@Its-treason @mirkogolze Do you guys have a strong stance that we should capitalize it ?

**Comment by Its-treason** [comment]
I think we should use the correct / most used spelling for all words, and [HTTPS](https://de.wikipedia.org/wiki/Hypertext_Transfer_Protocol_Secure), [SOCKS5](https://de.wikipedia.org/wiki/SOCKS) etc. seems to be written in UPPERCASE everywhere. So I would vote for merging https://github.com/usebruno/bruno/pull/1299.

**Comment by mirkogolze** [comment]
In alignment to the often used environment variables for proxies, I'd would prefer upper case too.

**Comment by CRAZy-Monk3Y** [comment]
> Do you have a link to the issue / conversation ?

Actually this is the issue thread raised by @ghost where I got to know about this.

**Comment by helloanoop** [comment]
Thank you @CRAZy-Monk3Y @Its-treason @mirkogolze !

Merged!
