### ISSUE TITLE
CLI: add a flag to only run queries with asserts & tests.

### ISSUE THREAD

**Issue by Aditeya** [usebruno/bruno#1287]
flag `--only-asserts` will run queries with asserts filled out.
flag `--only-tests` will run queries with tests filled out.
flag with both will run queries that have both.

Also i think there could be a better name that `--only-asserts` and `--only-tests`.

**Comment by jeff-edmondson-pci** [comment]
I created a PR for this here

**Comment by helloanoop** [comment]
Would love to add support for this in Bruno CLI

@Aditeya @jeff-edmondson-pci @ahmad-elafify-pci
Can you help me answers to these 2 questions

1. Could you describe the use case where this really useful
2. In case if you used another tool in the past, was this feature supported.

**Comment by Aditeya** [comment]
> 1. Could you describe the use case where this really useful

I want to use `bruno-cli` in my CI/CD pipeline to run tests but I don't want to test endpoints that have no asserts or tests. Those endpoints could be planned or not implemented properly so we don't want to run those requests.

> 2. In case if you used another tool in the past, was this feature supported.

[hurl](https://hurl.dev/) has a `--test` flag that runs the queries with only asserts & tests.

**Comment by jeff-edmondson-pci** [comment]
@helloanoop I added a example API collection workflow to the PR as well

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/1314) adding the feature had already been merged and released in version [v1.7.0](https://github.com/usebruno/bruno/releases/tag/v1.7.0).
