### ISSUE TITLE
Bruno CLI output format

### ISSUE THREAD

**Issue by pisix** [usebruno/bruno#1307]
### Discussed in https://github.com/usebruno/bruno/discussions/1068

<div type='discussions-op-text'>

<sup>Originally posted by **eddimcbenz** November 27, 2023</sup>
I just switched from Postman to Bruno, because Bruno looks very promissing. By the way, you all are doing a great job!

But now I came to a point where I have no adequate solution with Bruno. I use Bruno CLI with Jenkins like I used Postman newman with Jenkins in the passed. This works till now really good. But the output format of the json file that is produced by Bruno CLI is not working with Jenkins in the way I used to have it integrated with Postmans newman CLI. With newman, there was the possibility to have a second reporter that created junit files.

Are different reporters maybe planned to be integrated into Bruno CLI, or does somebody have an idea how to get the json format of the output file transformed to a junit format?

Thank you in advance for help and an answer.
Eddi</div>

**Comment by awinder** [comment]
Make sure you upgrade to the latest version of bruno (`npm update -g @usebruno/cli` if you've already installed, `npm install -g @usebruno/cli` if a new install). You should be able to use the `--format` flag in the cli:

`bru run --output results.xml --format junit`
`bru run --help # to see more options`

**Comment by sanjai0py** [comment]
I have closed this issue as resolved!
