### ISSUE TITLE
[Bug] Application crashes when trying to configure an environment with a large array

### ISSUE THREAD

**Issue by sapjr** [usebruno/bruno#1318]
I have a script which adds 1000 Ids of a request to an environment variable (array). This works all fine and I can use the array in the next request. However once I click on "Configure" for environments the app crashes.

<img width="3001" alt="image" src="https://github.com/usebruno/bruno/assets/26542732/ab4b2890-6f74-4499-81a2-9911d013e6da">

**Comment by sanjai0py** [comment]
Hey @sapjr, can you please help me with this? Could you share the script that you used and, if possible, the `.bru` file? Or at least check if this bug is still present in the latest version of Bruno [v1.20.1](https://github.com/usebruno/bruno/releases/tag/v1.20.1)?

**Comment by sapjr** [comment]
Hi @sanjai0py I'm so sorry I never closed the bug report. Actually I just created it to fix it myself but already noticed back then that it doesn't occur anymore in the latest master from git. So I did not investigate further. Based on your comment I now just tested and can confirm that the issue is fixed in v1.20.1
