### ISSUE TITLE
isJson assertion returns the error "Invalid Chai property"

### ISSUE THREAD

**Issue by dcoomber** [usebruno/bruno#132]
## Description

isJson assertion returns the error `Invalid Chai property: json. Did you mean "to"?`

## Test collection

Test collection:  https://github.com/dcoomber/exploring-bruno/tree/dpc_session_1/exploration/02-create/EE%20Bookings

Test request:  "Retrieve a booking"

## Screenshot

<img width="1279" alt="Screenshot 2023-03-18 at 11 54 53" src="https://user-images.githubusercontent.com/47242934/226098679-ec4d70f7-596a-4b8d-be29-78e74766c55d.png">

**Comment by helloanoop** [comment]
Thanks for catching this @dcoomber !

Would you be able to work on fixing this?
The code is [here](https://github.com/usebruno/bruno/blob/main/packages/bruno-js/src/runtime/assert-runtime.js#L227)

**Comment by dcoomber** [comment]
I have ended up proposing the use of https://github.com/chaijs/chai-http, but am uncertain if this is what you're looking for. 
 `chai-http` `.to.be.json` is merely a check that the response headers includes `Content-Type: application/json`.  In this form, the assertion would only ever be valid when comparing against `res` and would not be usable for comparisons of subsets of the response structure.

Please let me know if you had a different solution in mind.

**Comment by dcoomber** [comment]
After reviewing https://www.chaijs.com/api/plugins/ along with stepping through some of the other assertions, I realised that we're looking to `addProperty` and not `addMethod`.

PR updated.
