### ISSUE TITLE
Only sends the last element of POST array

### ISSUE THREAD

**Issue by deimios** [usebruno/bruno#1320]
Passing arrays as POST body variables requires repeating the variable name and appending square brackets.
Example: 
- item[] = 1
- item[] = 2
- item[] = n

So the sent/urlencoded POST data should look like:
`item%5B%5D=1&item%5B%5D=2&item%5B%5D=n`

However Bruno only sends:
`item%5B%5D=n`
Effectively it is ignoring all the prior instances of the same variable name.

The request settings I used:
![Bruno-Array-Screenshot](https://github.com/usebruno/bruno/assets/2050407/8bc4c4b0-4477-40e0-aa20-d25ee054397d)

**Comment by helloanoop** [comment]
This will be available in upcoming version `v1.29.0`
