### ISSUE TITLE
[Bug] Unexpected Prepended Character Found in JSON String Sent in the Request Body

### ISSUE THREAD

**Issue by varvay** [usebruno/bruno#1321]
When sending a JSON string with double closed curly brackets `}}` in a request body, the brackets in the request sent got prepended with an opened square bracket `]`. Here's the screenshot,
![image](https://github.com/usebruno/bruno/assets/24355851/40390ef7-70c1-4d2f-bfee-73ceb237def3)

The detail of Bruno app I'm using is written below,
* Version: v1.5.1
* Electron: 106.0.5249.103
* Node: 16.16.0
* V8: 10.6.194.17-electron.0

And here a bit of my workstation information,
* OS: Windows 11 Enterprise
* OS version: 22H2

**Comment by varvay** [comment]
I suspect the `interpolate(str)` function in the vars interpolation is the cause of these prepended character since the pair of opened and closed double curly braces commonly used to indicates variable to be replaced in the string template.

**Comment by Its-treason** [comment]
This is the same issue of #1143 and should be fixed when #1154 is merged
