### ISSUE TITLE
[Bug] GraphQL body syntax highlightning stopped working in Bruno 1.6.0

### ISSUE THREAD

**Issue by Napam** [usebruno/bruno#1330]
It worked fine before upgrading from 1.5.1 to 1.6.0. I am using a Macbook Pro 14 using MacOS Sonoma 14.2.1. Maybe this is caused by the CodeMirror bump introduced in 1.6.0?

<img width="697" alt="image" src="https://github.com/usebruno/bruno/assets/47104226/56e97a9f-5ce1-4e32-ba06-b863a7ee8c4e">

**Comment by helloanoop** [comment]
The fixes are now available in `v1.6.1` 🎉🎉
