### ISSUE TITLE
query args with percent `%` say they save, but don't properly update save status

### ISSUE THREAD

**Issue by tanj** [usebruno/bruno#1339]
The file gets written, but the dirty marker does not clear.

![image](https://github.com/usebruno/bruno/assets/90219/09fbda86-c292-4f9f-8ede-104232e9f071)

**Comment by adarshlilha** [comment]
As per my findings, when `%` is used in query param value, `item.draft` has reference to itself(the item object), due to which the `circle` marker is still shown and unsaved changes popup is shown on closing the tab

**Comment by adarshlilha** [comment]
bruno electron watcher calls `change` method onSave of request each time

here `file.data = bruToJson(bru);` is being called to parse the request using ohm js library
Error is thrown in `parse` method while trying to validate the input `const match = grammar.match(input);`

example input: `'meta {  name: percent req  type: http  seq: 1}post {  url: https://jsonplaceholder.typicode.com/posts?item=21%  body: none  auth: none}query {  item: 21%}';`

output: URI malformed, parsing fails when `%` is used in query
![Screenshot 2024-01-19 at 02 40 23](https://github.com/usebruno/bruno/assets/13575704/e38c30e9-7c37-4248-b7c7-b1ce25c577a6)

@helloanoop I guess a fix will be needed when ohm. grammar is initialized, any pointers?

**Comment by sanjai0py** [comment]
I have resolved this issue as it has already been fixed.
