### ISSUE TITLE
Bug: Custom font Size not working in the desktop app

### ISSUE THREAD

**Issue by yaten2302** [usebruno/bruno#1340]
Hi @helloanoop,
The custom font size option in the desktop app is not working, is this issue only with me or everyone? If this is with everyone, can anyone please let me know, I would like to give it a try to solve this issue 👍

https://github.com/usebruno/bruno/assets/129659514/e6904cd0-0349-4e11-98e3-c7a02d048d91

### OS
Windows 10

### Bruno Version
V1.6.1

**Comment by yaten2302** [comment]
Hi @Its-treason, thanks for answering the query 👍
Also, I would like to ask that are there some open issues for beginners, I'm very keen to contribute to this project, could you please guide me in contributing to this project.

**Comment by Its-treason** [comment]
You can search for issues with the Tag "Good first issue" → https://github.com/usebruno/bruno/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
