### ISSUE TITLE
no console output is displayed for tests

### ISSUE THREAD

**Issue by insureyang** [usebruno/bruno#1342]
Is there something wrong with my operation? Please have a look, thanks！

![Snipaste_2024-01-08_01-14-19](https://github.com/usebruno/bruno/assets/64629972/e59d974b-bd36-4e4c-beb5-2967c34ace49)

**Comment by cyrilgeorge153** [comment]
@insureyang  Click on View tab and select Toggle Developer Tools to see token value. You have not added any tests.
