### ISSUE TITLE
[BUG] Text is colored incorrectly in "system" set dark mode

### ISSUE THREAD

**Issue by TylerCode** [usebruno/bruno#1347]
As the title says, font color for editing docs in dark mode is black, making it impossible to see.

![image](https://github.com/usebruno/bruno/assets/18288340/4ece0cef-8da1-4c53-a3e0-6606f7804635)

### To reproduce:

- On a Windows 11 PC, set the system's theme to "Dark". [Details here if needed](https://www.microsoft.com/en-us/windows/learning-center/when-to-use-dark-mode#:~:text=From%20your%20Start%20menu%2C%20navigate,a%20different%20default%20app%20mode.)
- Open Bruno and make sure the theme is set to "System"
- Edit the "Docs" of a request

### Expected result:
The "edit mode" text color is white or a lighter gray

### Actual result:
The "edit mode" text is black as shown in the screenshot

This doesn't happen if you manually select "Dark" from Bruno's theme.

### Light
![image](https://github.com/usebruno/bruno/assets/18288340/b730ab51-f0c4-4a1a-9ea3-a5fd841bbcd5)

### Dark (what I expected)
![image](https://github.com/usebruno/bruno/assets/18288340/fc896645-3c93-45ab-be1b-2df5141f8bba)

### System (bugged)
![image](https://github.com/usebruno/bruno/assets/18288340/16590f6d-95de-4a36-9115-7f0f80b2e1bf)

**Comment by TylerCode** [comment]
Realized as I hit post this seems to be the case for much of the application.

### Dark
![image](https://github.com/usebruno/bruno/assets/18288340/17ad352b-2357-4e2c-882b-3e5f3ea6d9ed)


### System Set Dark
![image](https://github.com/usebruno/bruno/assets/18288340/1a05395a-cc40-41ae-823e-d2e99615c818)

**Comment by Fabbi** [comment]
This affects macOS as well.

**Comment by danilo-alm** [comment]
Linux is also affected. Changing theme to "dark" fixes it. Thanks

**Comment by TylerCode** [comment]
> Linux is also affected. Changing theme to "dark" fixes it. Thanks

I wondered if it would happen in Linux somewhere. On KDE Plasma I don't even get the "System" option, but assumed GNOME might have the same issue.

**Comment by danilo-alm** [comment]
Yep. I'm using gnome 45. Maybe kde needs some compatibility lib to show the "System" option

**Comment by theodorejb** [comment]
It looks like this was fixed by #1595 (released in v1.10).

**Comment by TylerCode** [comment]
Can confirm in Windows this is fixed: 
![image](https://github.com/usebruno/bruno/assets/18288340/e06bb3c0-777b-4518-a9a9-ee60cf5ed8bc)

I can check KDE and Gnome on linux later.

**Comment by helloanoop** [comment]
This has been fixed in the `v1.10.0` release 🎉 

Thanks for taking care of this @lohxt1 !
