### ISSUE TITLE
VMError: Cannot find module 'node:buffer', when trying to extract data from JWT with 'jose' lib

### ISSUE THREAD

**Issue by bsleczko** [usebruno/bruno#1348]
Hi,
I need to access the content of the JWT token, more specifically parse claims assigned to the authenticated user, to correlate test results against the claims (EP forbidden for end-user, but available to the admin).
I have found that the 'jose' package is probably my best candidate for the job, so I installed it with `npm install`:
```javascript
### package.json
{
  "version": "0.0.0",
  "dependencies": {
    "jose": "^5.2.0"
  }
}
``` 
Now, when I am trying to run the following post-response script:
```javascript
console.log(`Node version: ${process.version}`);
console.log(`Versions: ${JSON.stringify(process.versions)}`);
const jose = require('jose');   // <-- Point of Failure
const claims = jose.decodeJwt(res.getBody().accessToken);
console.log(claims);
```
I get the following result:
```
[Console] Node version: v16.16.0
[Console] Versions: {"node":"16.16.0","v8":"10.6.194.17-electron.0", [...]}
[UI] Error invoking remote method 'send-http-request': VMError: Cannot find module 'node:buffer'
```
Which I do not understand, since this is a node version nowhere to be found:
```powershell
PS C:\bruno> npm version
{
  npm: '10.2.5',',
  v8: '11.8.172.17-node.18'
}
PS C:\bruno> node -v
v21.5.0
PS C:\bruno> nvm list
    20.10.0
    15.6.0
    14.15.4
PS C:\bruno> nvm current
v21.5.0
``` 

The Internet suggested updating nodeJs, which I initially did, but it did not change anything.
I suppose that buffer lib needs to be added [here](https://github.com/usebruno/bruno/blob/1e27427d09b40e5aaf95cf59b36c914f0c5feb5d/packages/bruno-js/src/runtime/script-runtime.js#L79), but I have no idea what the consequences might be, and no idea if this would even solve my issue.

1. Is the issue related purely to node:buffer being available in nodejs, but not being whitelisted in the sandbox VM?
2. Is the issue related to my nodeJS installation?
2.1. If so, where does the 16.6 come from? 
I know that my nodejs installs are a mess, but I was looking everywhere and cannot find the sources for the 16.6 version, which is reported in the Developer Tools' Console in Bruno.
3. How is the runtime version resolved?
From some electron installation? 
From envVars in OS? I checked them and they all point to higher versions of nodeJS.

Am I doing something wrong?

**Comment by Its-treason** [comment]
Hey @bsleczko, this is currently not documented, but you can whitelist the `buffer` module yourself by expanding the `bruno.json` inside your collection root with:

```json
  "scripts": {
    "moduleWhitelist": ["node:buffer"],
    "filesystemAccess": {
      "allow": true
    }
  }
```

Your bruno.json should look something like this in the end:

```json
{
  "version": "1",
  "name": "My Collection",
  "type": "collection",
    "scripts": {
    "moduleWhitelist": ["node:buffer", "jose"],
    "filesystemAccess": {
      "allow": true
    }
  }
}
```

**Comment by bsleczko** [comment]
Hey @Its-treason, thank you for your help, indeed I have successfully loaded the module, but in the end, it failed to parse JWT.
For future reference I am placing the necessary config:
```javascript
{
  "version": "1",
  "name": "Collection name",
  "type": "collection",
  "scripts": {
    "moduleWhitelist": [
      "buffer",
      "crypto",
      "events",
      "jose"
    ],
    "filesystemAccess": {
      "allow": true
    }
  }
}
```
And the script:
```javascript
const { TextDecoder, TextEncoder } = require('node:util');
global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;

const jose = require('jose');
const authHeader = req.getHeader('authorization');
const accessToken = authHeader.replace("Bearer ", "");
const claims = jose.decodeJwt(accessToken);
console.log(claims);
```
In the end, I went with JS implementation of JWT parsing from StackOverflow:
```javascript
function parseJwt (token) {
    return JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString());
}

const authHeader = req.getHeader('authorization');
const accessToken = authHeader.replace("Bearer ", "");
console.log(parseJwt(accessToken));
```
I am closing this issue, thank you for your help!
