### ISSUE TITLE
Fresh install cannot create Collections

### ISSUE THREAD

**Issue by Angusross111** [usebruno/bruno#1357]
I have a fresh install of Bruno and I cant seem to be able to create any Collections.
My system is
```
Static hostname: pop-os
Icon name: computer-laptop
Chassis: laptop
Operating System: Pop!_OS 22.04 LTS               
Kernel: Linux 6.5.6-76060506-generic
Architecture: x86-64
Hardware Vendor: Lenovo
Hardware Model: ThinkPad P14s Gen 1
  ```
  I installed bruno from the Pop!_Shop which installed version `v1.5.1` 

  When I choose my location I navigate to my Documents folder which is located at:
  `/home/angus.ross/Documents` but when after selecting the string in the **Location** field is `/run/user/1000/doc/bc284510/Documents`. Pressing create gets the error 
  ```
An error occurred while creating the collection
```

![image](https://github.com/usebruno/bruno/assets/44857236/d79c0c4b-d2c0-4442-adb6-80ebbb87ee56)

**Comment by Angusross111** [comment]
Looks like it might be a permissions issue but I dont see any errors in the devtools console when trying to create a Collection. I was able to open the github example Collection, but I am not able to delete any Requests or Folders. I do get the following error in the console when I try to delete
```
Uncaught (in promise) Error: Error invoking remote method 'renderer:delete-item': Error: EACCES: permission denied, unlink '/run/user/1000/doc/62eab525/github-rest-api-collection/Repository/Search Repos.bru'
```
After installing the .deb package it seems like it has the correct permissions to create and delete Collections/Requests.

**Comment by rsilvr** [comment]
Being a permission issue, maybe you can solve it using [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal)?
It's an application to manage Flatpak apps permissions.
Try to enable this permission:

**Comment by PeterH220** [comment]
Sorry to jump in on another person's thread, but I have the same issue. I use Windows 10. New user, fresh installation, can't create folder for collection. Tried to make folder manually and just click on it, same notification- "An error occurred while creating the collection".

**Comment by nexovec** [comment]
I also encountered this issue, fix proposed by @rsilvr worked for me.

But this effectively makes the app useless for new users installing through flatpak, there should at least be more discussion on this...

**Comment by bastian-src** [comment]
@rsilvr thanks for the hint! I ran into the exact same issue & just opened a PR to add such permission from the beginning: https://github.com/flathub/com.usebruno.Bruno/pull/9

**Comment by sanjai0py** [comment]
I am closing this issue as it seems to be resolved.
