### ISSUE TITLE
Feature Request: Remove friction to run a one-off request

### ISSUE THREAD

**Issue by 0xalecks** [usebruno/bruno#1379]
I just want to run off a quick request. 
- Open Bruno
- Create collection
- Select path, name..arrghh
- now click the ... icon > Create request
- give it a NAME and url....argghhh
- FINALLY looking at a UI I recognize, where I can edit the url/bod make the request etc...

This is way too much friction to just make a quick request. Please add the ability to create a one off request:
- Open Brun
- Ctrl + N
- Presented with the request tab.

**Comment by Its-treason** [comment]
So ephermal requests like described in #25?

**Comment by 0xalecks** [comment]
Yes, but wow, a year on that issue and not even a comment.
