### ISSUE TITLE
Can't Move Request to New Folder

### ISSUE THREAD

**Issue by lukedegruchy** [usebruno/bruno#1387]
# Steps to reproduce:

1. Create a folder
2. Create a request within that folder
3. Create a second folder
4. Attempt to move the request within the first folder to the second

# Expected results

* The request appears in the second folder

# Actual results

* The request stays in the first folder

# Additional context

* I reproduced this on the latest version of macOS with Bruno 1.6.1

**Comment by bpoulaindev** [comment]
Can you provide a screen record of this behaviour ? I tried to reproduce but the requets did move to the 2nd folder.

**Comment by devsales** [comment]
This works for me as well. But what I can't do is move a request in another collection. Is this a known limitation?

**Comment by sanjai0py** [comment]
Closing this as it cannot be reproduced in the latest version of Bruno [v1.20.1](https://github.com/usebruno/bruno/releases/tag/v1.20.1)
