### ISSUE TITLE
Flathub marks Bruno as proprietary

### ISSUE THREAD

**Issue by CodeShakingSheep** [usebruno/bruno#1398]
Hi,

I just wanted to download and check out Bruno as alternative to Postman. When I headed to [Bruno's Flathub page](https://flathub.org/apps/com.usebruno.Bruno) I saw that it's marked as proprietary app. Should be open source, right?

![image](https://github.com/usebruno/bruno/assets/19874562/2c578461-5c0c-43ba-be80-e3a6c58a03ea)

**Comment by helloanoop** [comment]
Majority of the code is opensource.
In fact, what we have today is entirely opensourced under MIT

We will be introducing [Golden Edition](https://www.usebruno.com/pricing) with some paid addons.
Which means the builds in the future will have features of Golden Edition (which is closed)

So, I am not sure if its valid to mention the code as open (specifically flathub being a package artifact repo)
Perhaps marking it as opensource and adding that some part of code is closed might be a middle ground.

If you are interested to know about the monetization strategy and long term plans of Bruno, I am documenting the journey publicly in this discussion thread: https://github.com/usebruno/bruno/discussions/269

**Comment by CodeShakingSheep** [comment]
Thanks for your reply @helloanoop and thank you for the great project! Today I just imported all my Postman collections and environments to Bruno. It worked like a charm  :raised_hands: 

When [searching for an alternative to Postman on Flathub](https://flathub.org/apps/search?q=API%20client), when I first saw Bruno marked as proprietary this was kind of a deal breaker to me as I assumed that it was fully proprietary (such as Postman). So, first I went with Insomnia instead. When I look at [Flathub's Insomnia page](https://flathub.org/apps/rest.insomnia.Insomnia) it is marked as community built although they also offer [paid features](https://insomnia.rest/pricing). I dropped Insomnia again because I didn't want to create an account with them and the UI was a bit bloated. Then there was an Insomnia plugin which redirected me at using Bruno as open source alternative (don't remember the plugin's name unfortunately).

Having in mind Insomnia is marked as community built despite their paid features, I believe it should be possible to mark Bruno as community built as well. I strongly vouch for that to avoid other potential users being scared away by Flathub's proprietary label for Bruno (as it happened with me).

**Comment by helloanoop** [comment]
As per this https://github.com/flathub/com.usebruno.Bruno/issues/1#issuecomment-1942030580 we will have to distribute two binaries.

We currently are not in a position to do it with Bruno. Below is our reasoning.

We have opensourced almost all functionality in Bruno. For majority of the people there is no need to purchase a paid license at all (unless you happen to need [GRPC support](https://github.com/usebruno/bruno/issues/79#issuecomment-1939342282) )

The long term vision of Bruno is to be an independent and strong company and build products around developer tooling. We are fully bootstrapped. And we have explicitly said no to VC funding (despite inbound interest from VCs).

Having a single binary which can be upgraded by entering a license for [Golden Edition](https://www.usebruno.com/pricing) is an important functionality for us.

As a company, we are striving to strike that delicate balance between opensource and sustainability, and we have documented our [journey publicly here](https://github.com/usebruno/bruno/discussions/269) and [here](https://www.usebruno.com/blog/bootstrapping)

Thank you,
Anoop
