### ISSUE TITLE
Pretty Print XML Response

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#140]
We should pretty print XML response in the Response pane. We can detect the mime type of the content in the response headers.

**Comment by GarryGibson** [comment]
Please do. Without this capability Bruno is pretty much useless for anyone using XML / SOAP messaging, and I'd LOVE to replace Postman with this!

**Comment by helloanoop** [comment]
@GarryGibson This has been fixed and is now available in the latest version of Bruno!
