### ISSUE TITLE
No good error message/validation in GUI when attempting to create a new request with a slash (/) character in the name

### ISSUE THREAD

**Issue by spephton** [usebruno/bruno#1401]
Attempting to create a request with a slash character (/) in the name fails with an unhelpful error message.

It looks like Bruno attempts to create a file with an illegal character in the file name.

![image](https://github.com/usebruno/bruno/assets/71482036/d92739ab-535c-4cbf-ae8e-f909bdcacab3)

Bruno should either transparently escape illegal FS characters or provide a helpful error message in this case, such as "Could not create a request with this name because this name contains illegal characters ({presentIllegalChars})"

Present in 1.6.1 on Windows

**Comment by reilee** [comment]
It appears the heading slash can be used in a name (macos) though.

**Comment by yojeek** [comment]
it's not validation message what is a problem, forward slashed absolutely must be allowed in request names. It's natural that request name represents some part of url.

**Comment by helloanoop** [comment]
I have merged the PR https://github.com/usebruno/bruno/pull/3274 that will now better warnings and prevent file deletion.
This will go out in the upcoming `v1.36.0` release scheduled to be released on 4 Dec 2024
