### ISSUE TITLE
Using bru.EnvVar doesn't update environment file 

### ISSUE THREAD

**Issue by Gabriel-Espinoza** [usebruno/bruno#1414]
Hello,

The environment file does not update when using `bru.setEnvVar` in Post Response Scripts.

So within bruno I see the environment being updated but the environment file does not update

is this the expected behavior? 

This is a problem for me because I make an auth call in Bruno but then execute a bru CLI to massively call my API for whatever time that token lasts. I have to execute the Auth call in Bruno, manually copy the auth string to the environment file and then run the script.

**Comment by koljatm-edeka** [comment]
Maybe for this kind of case (getting temp credentials to use in multiple requests) another kind of vars could be useful, like session variables? Don't need to be persisted, but are valid until app is closed or some kind of reset event?

**Comment by sanjai0py** [comment]
Hey @Gabriel-Espinoza, just a reminder that it's expected that the environment variables set using `setEnvVar` are not saved to the environment file.

Please check out this comment https://github.com/usebruno/bruno/issues/2160#issuecomment-2197051417 where further improvements are discussed.

Give a thumbs-up reaction [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to [important issues](https://github.com/usebruno/bruno/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) you find.

Closing this issue.
