### ISSUE TITLE
[Feature Request]: Creating yaml issue templates

### ISSUE THREAD

**Issue by yaten2302** [usebruno/bruno#1422]
Hi @Its-treason, could you please have a look at this issue and let me know if this is required, I'll create a PR for this 👍

# About
This is a feature request for creating `yaml` issue templates which will allow the users to file new issue with ease as the default issue template can't be edited.

# Currently is use
Currently the default issue template by GitHub is in use.

# Expected
By creating custom `yaml` based issue templates, it will ease the work for identifying issues whether it's a bug or a feature request or something else.

**Comment by Its-treason** [comment]
Could you link a repository that already uses Yaml issue Templates?

**Comment by yaten2302** [comment]
> Could you link a repository that already uses Yaml issue Templates?

If I've understood correctly, should I create a separate repository containing custom Yaml issue templates and then put it here?

**Comment by Its-treason** [comment]
I wanted to see a YAML template that is already in use in a different Repository. I just found it used in [mantinedev/mantine](https://github.com/mantinedev/mantine/tree/master/.github/ISSUE_TEMPLATE) and it looks very interesting.

Quick Idea of what we could add:
- A Bug template
  - Checkbox: `I use the newest version`
  - Checkbox: `I searched existing Issue and have found nothing related to my issue` to maybe prevent duplicates
  - Textare: `Describe the Bug`
  - Textare: `Screenshots, Images or Error messages`
  - Textare: `.bru file to reproduce the bug (If applicaple)`
- A feature requests template
  - Checkbox: `I searched existing Issue and have found nothing related to my issue` to maybe prevent duplicates
  - Textare: `Describe the feature you want to add`
  - Textare: `.bru file to reproduce the bug (If applicaple)`
- A link to the discussions page for questions, feadback etc.
- A link to the Discord server for questions, feadback etc.

These are some general idea's, if anyone has more/other idea's please share them.

**Comment by yaten2302** [comment]
Thanks for your suggestions 👍, I'll create the issue templates by today.
