### ISSUE TITLE
Add count of matches for searches

### ISSUE THREAD

**Issue by barnesyard** [usebruno/bruno#1432]
In the response field it is really convenient to be able to do a search for something like "error" and see a count of how many errors there are.

![image](https://github.com/usebruno/bruno/assets/9060889/b850fc7c-9965-4f29-8e42-9a3eb5f3a9f5)

**Comment by helloanoop** [comment]
Bruno now lists the count of matches

<img width="653" alt="image" src="https://github.com/user-attachments/assets/5b357ed2-2210-479b-85ef-9c517c281265">
