### ISSUE TITLE
[Feature request] Close other tabs, Close tabs on the left, on the right, close all tabs

### ISSUE THREAD

**Issue by blured75** [usebruno/bruno#1446]
It would be helpfull to have on the ui, the ability to Close other tabs, Close tabs on the left, on the right, close all tabs as it is in Chrome or IntelliJ.

:)

**Comment by kevinrenskers** [comment]
Related: don't automatically open a new tab for every request. Reuse the same tab by default, I can open tabs myself if I want to. When working with many different requests in one collection I end up with many many open tabs.
