### ISSUE TITLE
[Feature Request] Add function to set next request 

### ISSUE THREAD

**Issue by rafaelromas** [usebruno/bruno#1453]
Hello everyone.

You could add a function to manipulate /set next request via script or tests.

Example of use: 
- Execute a collection runner;
- During the execution, the first request is called, but it fails (i.e. HTTP status code 500);
- Set next request to execute the same request via script or test;
- Execute the same request again;
- Got HTTP status code 200;
- Proceed to next request.

The purpose of this feature is to retry some calls that may fail for some reason during the collection run.

EDIT: Postman has a feature like this... We can call the function `pm.setNextRequest("name_of_the_request_to_be_called");` via tests.

**Comment by mj-h** [comment]
This exists, but documentation has not been merged yet: https://github.com/usebruno/bruno-docs/pull/39

**Comment by deepakthankachan** [comment]
Hi, trying to use this inside the collection runner and getting an error as the bru class is not instantiated in the runner. It works fine inside a normal request without using the runner.

**Comment by deepakthankachan** [comment]
The error was due to being on an old version. After the upgrade the error has gone now but setting the next request in test script and running it via the UI runner doesn't do anything

**Comment by sanjai0py** [comment]
Closing this issue as it appears to be resolved. Please open a new issue if you face any further problems.
