### ISSUE TITLE
Duplicate collection import/create error does not shows on the screen but console error caughted

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#1457]
when we try to import/create the duplicate collection, the alert says imported successfully but in the console the uncaught

![image](https://github.com/usebruno/bruno/assets/44080743/1bcfe98d-cdfe-49a2-b9b8-72e4687fc5e5)

**Comment by subiabre** [comment]
+1

Haven't found a way to update a collection initially created via an OpenApi V3 Spec import.

@helloanoop what do we do when the spec changes?

**Comment by sanjai0py** [comment]
Closing this issue as the pull request (https://github.com/usebruno/bruno/pull/2455) that adds a better error message has already been merged.
