### ISSUE TITLE
Environments box cut off the copy and delete button when the environment name is too long

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#1458]
when we give the environment name as long as (max char of 50) the copy and delete button cuts off on the screen to main window

![image](https://github.com/usebruno/bruno/assets/44080743/c49ef621-5a5d-426f-9006-98212167c199)

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/1464) fixing the overflow issue has already been merged.
