### ISSUE TITLE
Renaming Request Overrides current unsaved state of the request

### ISSUE THREAD

**Issue by therealrinku** [usebruno/bruno#1462]
When user renames the request without saving the current changes, it reverts back to last saved state
overriding the current unsaved changes.

I was thinking about working on it but I'm not sure if it should be treated as a bug, or we should just add like a alert message prompting user to save unsaved request or something like that. 

So I'm creating a issue here, in case someone have any ideas or suggestions

Video::
[Screencast from 2024-01-28 11-53-56.webm](https://github.com/usebruno/bruno/assets/76877078/b31cad2e-1d6c-4677-9c16-b8f0fc581f57)

**Comment by giemic8** [comment]
I also don’t think this is a "bug". It is more like an missing feature. Maybe we can add the same Message if bruno will closed and get a modal.

**Comment by therealrinku** [comment]
yeah that make sense!

**Comment by helloanoop** [comment]
Thank you @therealrinku !
This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
