### ISSUE TITLE
Response headers in post response script

### ISSUE THREAD

**Issue by adri1g** [usebruno/bruno#1468]
Hello,
When launching a standalone request the res.getHeaders() API returns a dictionary. Everything ok.
But when launching several requests using runner on a folder the API returns a list. This is a bug.
Behavior should be harmonized and the API should return a dict all the time.
Regards,

Adrien

**Comment by helloanoop** [comment]
@adri1g 

I am unable to reproduce this. I am seeing a dict during a folder run too. Can you check if you are on the latest version `v1.6.1` ?

![image](https://github.com/usebruno/bruno/assets/9350733/5758a8f0-1a41-41c5-88b8-a9cfb2f4dfab)

**Comment by adri1g** [comment]
@helloanoop I will close the issue because I cannot reproduce anymore ...
Sorry and many thanks for your support.

**Comment by helloanoop** [comment]
Hey @adri1g 

I think the issue happens when there is a 400 response on one of the request. See #1436 
I have fixed this. It should be available in the next outgoing release.
