### ISSUE TITLE
Form URL Encoded requests do not expand variables to their value

### ISSUE THREAD

**Issue by kzndzhiro** [usebruno/bruno#148]
Thank you team for developing this nice looking tool. 

I was exploring by importing a collection and noticed an odd behaviour with respect to Form URL encoed request. 
When in the body I have a param with a variable value it seems that the variable is not expanded prior to sending the request: 

![image](https://user-images.githubusercontent.com/383553/234516227-1c36416c-6c84-43f5-ac39-11ef67a3cb20.png)

The message on our systems led me to belive that this is the issue: 

"message": "invalid_grant: Invalid refresh token: xxxx..._ui}}",

**Comment by helloanoop** [comment]
@kzndzhiro 

Thanks for filing this issue.
This has been fixed in v0.12.1

**Comment by kzndzhiro** [comment]
Thank you for fixing it so quickly @helloanoop.
