### ISSUE TITLE
choco has outdated packages

### ISSUE THREAD

**Issue by vivaladan** [usebruno/bruno#1486]
The docs explicitly reference choco installation option, but the package is out of date.

Currently choco has 1.6.1 as the latest package. At the time of writing 20 hours as passed since 1.7.0 was released.

If this is a manual process for pushing to choco - then could it be automated?

**Comment by helloanoop** [comment]
@vivaladan The push process to choke is already automated.

@majkinetor maintains this.
It usually takes 1 day for the chocolate package (there is a step where it has to pass moderation testing) to get reflected in the choco repo.

**Comment by majkinetor** [comment]
> At the time of writing 20 hours as passed since 1.7.0 was released.

It runs once a day. Then it needs approval from chocolatey team. 

BTW, the package is already there: https://community.chocolatey.org/packages/bruno/1.7.0

You can install it before it gets approved by using `choco install bruno --version 1.7.0`

**Comment by vivaladan** [comment]
It was just chance I noticed the update when i did, pre-approval. Thanks for clarifying. I'll close this issue.
