### ISSUE TITLE
Collection variables are not removed when we removed the var from the request

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#149]
i have created below highlighted variables and I removed them later from the variables but still its not removed them from collections variables

![image](https://user-images.githubusercontent.com/44080743/234573520-b1a7bb59-f672-489f-b80c-1e478a6eafaf.png)

**Comment by helloanoop** [comment]
This is now fixed, In the past request variables as shown in the screenshot would get leaked to the collection variable scope/
This no longer happens in the latest version of Bruno
