### ISSUE TITLE
Preview and download is broken

### ISSUE THREAD

**Issue by valentin78** [usebruno/bruno#1490]
update version from 1.4.0 to 1.7.1 and looks like you lost ability to preview (PDF). It was working in 1.4.0 :
![image](https://github.com/usebruno/bruno/assets/4290501/b1fef8fb-38fe-466d-8be6-6a24c17b7754)

Also if I try to save response (application/pdf) to file, I'm getting error message
![image](https://github.com/usebruno/bruno/assets/4290501/9643b263-c680-4510-8661-394dc3237226)

**Comment by therealrinku** [comment]
Added PR for this #1499
