### ISSUE TITLE
Ignore common folders in collection

### ISSUE THREAD

**Issue by peledies** [usebruno/bruno#1496]
When `opening` a collection, ignore common directories such as `.vscode` and `.idea` so they don't show in Bruno.

possibly using the `.gitignore` file to exclude directories.

**Comment by helloanoop** [comment]
We need to implement this. I am thinking of adding a `ignore` option inside `bruno.json`

```json
{
  "version": "1",
  "name": "bruno-testbench",
  "type": "collection",
  "scripts": {
    "moduleWhitelist": ["crypto"],
    "filesystemAccess": {
      "allow": true
    }
  },
  "ignore": [
    "utils",
    ".vscode",
    ".idea"
  ]
}

```

**Comment by peledies** [comment]
@helloanoop that would be a welcome implementation.
