### ISSUE TITLE
Cannot cancel request on preview (zIndex issue)

### ISSUE THREAD

**Issue by valentin78** [usebruno/bruno#1501]
![image](https://github.com/usebruno/bruno/assets/4290501/73883038-ffa9-48af-a0af-d60f3dd92775)
button unclickable, due zIndex I believe

**Comment by helloanoop** [comment]
Thanks for the PR @ialloyd !

This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
