### ISSUE TITLE
Preview / Raw elements missing in Bruno 1.7.1

### ISSUE THREAD

**Issue by Ogalesha** [usebruno/bruno#1506]
Upgrading Bruno from 1.6.1 to 1.71, the Preview / Raw elements are missing.

![image](https://github.com/usebruno/bruno/assets/40427205/a32fd5aa-bbb7-47e4-b334-e77e3022b76f)

What I see now (in Bruno 1.7.1) is a bar without Preview / Raw:

![image](https://github.com/usebruno/bruno/assets/40427205/fc381ef3-26f1-4bf7-8401-7db3f6e2b949)

**Comment by gmutinel** [comment]
I can confirm this issue arised in 1.7.0, also Headers count is missing too

**Comment by therealrinku** [comment]
for me it's showing, in v1.7.1
![image](https://github.com/usebruno/bruno/assets/76877078/82456c9f-7072-4901-87a9-e263e26bfd65)

and there is PR already for missing headers count too #1488

**Comment by gmutinel** [comment]
It might not be working with HTML, with a PDF is working for me too

**Comment by werc** [comment]
Sometimes I'm var dumping (in PHP Symfony var dumper) and the result is only in raw mode. (Can't switch between raw/preview). Before 1.7. it was working.

![vardump](https://github.com/usebruno/bruno/assets/1354251/c1e1e9c8-22b6-4b54-a860-b030c0ef6cc0)

**Comment by Ogalesha** [comment]
@werc same thing is happening to me with the Laravel dd() [dump and die]; I can see only the raw mode, without having the possibility to choose between Preview and Raw. (In 1.6.1 I was able to)

![image](https://github.com/usebruno/bruno/assets/40427205/30fcdf6e-a4ef-4556-a3e3-97beb3de27fb)

It was convenient to view the preview of the dd() for some testing situations.

**Comment by therealrinku** [comment]
sorry, actually this screenshot and the last one I added, both are from the development version. 
I think this will fixed in the new release. #1499 should fix this issue

![image](https://github.com/usebruno/bruno/assets/76877078/0fef8fec-f6fe-4b3a-ba56-726a46db4b90)

**Comment by sanjai0py** [comment]
Closing this as the [PR](https://github.com/usebruno/bruno/pull/1499) resolving the issue had already been merged into bruno!
