### ISSUE TITLE
When sending request to AWS SQS using Bruno CLI, Its throwing 403 Forbidden. Getting the response as expected when sending the same from Bruno UI.

### ISSUE THREAD

**Issue by sushriti** [usebruno/bruno#1508]
Hi,

We are in a process of moving from Postman to Bruno but seeing this issue. While using the Bruno CLI in our CI/CD jobs to send request to Amazon SQS we are getting 403 Forbidden error. We are able to send the same request from Bruno UI.

![403_SQS](https://github.com/usebruno/bruno/assets/93635495/35aeddfc-6249-46d1-8db8-28483ad3ecf4)

**Comment by sushriti** [comment]
We are still seeing the issue. Any update on this?

**Comment by Its-treason** [comment]
Could you provide more info?

Do you see all headers being sent on CLI? Try to log them in your Pre/Post-Request-Script using console.log, they will be printed into stdout / the browser console.

**Comment by sushriti** [comment]
Hello,
Thanks for replying.
Sharing more information below:

This how our auth looks like :

![authentication](https://github.com/usebruno/bruno/assets/93635495/9e062621-2624-434d-a347-1e2628a42920)

This is the body what we are sending to SQS {We send a Json body to Amazon SQS :

![body](https://github.com/usebruno/bruno/assets/93635495/acdc7722-3cf5-44eb-895c-4a99e971474b)

This is the response we are getting back : 

If you can see I tried to get both access and secret keys from the env variables and logged them in Pre/Post-Request-Script.
It's logging the keys in pre scripts but not in post script (As you can see below).

![Responses](https://github.com/usebruno/bruno/assets/93635495/b8e374f3-8bbf-44ac-b129-b7f218364f4b)

Without solving this issue, we are not able to choose Bruno as our replacement. 

FYI only that, when sending the same Amazon SQS requests from Newman CLI we are not seeing any issues. 

Hope to hear back soon on this issue.

**Comment by sushriti** [comment]
I have also tried to get the headers from the response and logged it in console as below : 

![20240207_133543](https://github.com/usebruno/bruno/assets/93635495/94e7296f-9059-4027-abba-927dafb29537)

I am not adding any headers to the headers tab of my request. Anything I am missing here to make it work .

**Comment by sushriti** [comment]
Hoping for a update or help on this .. Thanks
