### ISSUE TITLE
Env Var not set inside tests

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#151]
Issue reported by @sseenivasan89
```javascript
bru.setVar("foo", "bar");
```

The above script works in `Scripts` tab but does not work in `Tests` Tab

**Comment by mirkogolze** [comment]
I tried that out and it is working. I first checked the value i want to store with an `expect` and than stored as variable.
Later I requested the variable again in an another stet and got it.

**Comment by helloanoop** [comment]
This has now been fixed in v0.14.0
