### ISSUE TITLE
Preferences/cookies modals overlapping with response search dialog

### ISSUE THREAD

**Issue by aleixmarsa** [usebruno/bruno#1511]
Both preferences an cookies modals overlap with CodeMirror response search dialog:
 
<img width="1194" alt="Screenshot 2024-02-02 at 15 23 27" src="https://github.com/usebruno/bruno/assets/98183799/08ff05d2-d61b-4a3d-9a73-930e5b1b080d">

**Comment by vayalildanie** [comment]
Wish there were more details as to how to reproduce this bug @aleixmarsa; but concerning the fix @sanjai0py, shouldn't this be added as #1512 is a XS change?

**Comment by sanjai0py** [comment]
Closing this issue as it has already been fixed. Please use the [latest](https://github.com/usebruno/bruno/issues/2517) version of Bruno.
