### ISSUE TITLE
No option to select the env variables when we are outside of the request 

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#152]
unable to run the collection without opening any request tab, since we do not have the option to select the env variables when the request tab is not open

in the below screenshot if I try to run the collection it's not running since the env is set to no env

![image](https://user-images.githubusercontent.com/44080743/234898057-a852fa61-c49d-417d-bd0b-7e902c16098a.png)

**Comment by sanjai0py** [comment]
Closing this issue as it has already been resolved. Thank you for taking the time to report this!

https://github.com/usebruno/bruno/assets/84461672/5dc199b7-8bf8-4843-a0c7-91d75f5dc4b8
