### ISSUE TITLE
Vars value persistence

### ISSUE THREAD

**Issue by epestela** [usebruno/bruno#1526]
Hello, I'm facing this issue (in v1.8.0 - windows)
In a request of this kind

example: {{baseUrl}}/document/{{id}}/lock

I can easily replace both value with the environment variables
And I can override the values with pre request vars

However, if i remove the override, I'd expect to go back to the environment value (or to no value) but this is not the case.
the VARS remains in memory and keeps being used in the queries

(also some nice to have:
- be able to set query path vars directly in the query tab
- have collection variables)

**Comment by andrerfcsantos** [comment]
I'm also experiencing this, but with the auth token I set at collection level.

Steps to reproduce:

1. Set a Bearer Token at collection level
2. Make an authenticated request that requires the bearer token
3. Change the Bearer Token at the collection level to another one and save
4. Repeat the request in step 2

**What happens:** The request in step 4 uses the token set in step 1
**What I expected to happen:** The request in step 4 to use the token set in step 3

**Comment by SoulKa** [comment]
duplicate of #1101

**Comment by epestela** [comment]
I agree, it's a duplicate of #1101
