### ISSUE TITLE
Text overlay and collapsed when we zoom in (ctrl++)

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#153]
when we zoom in (ctrl++) the screen collapsed and texts are overlayed 

![image](https://user-images.githubusercontent.com/44080743/234901456-88deed50-3dc5-42de-add4-9d16b2452f4c.png)

![image](https://user-images.githubusercontent.com/44080743/234903143-39c32948-64ee-4d1b-9f45-4a96269e50dd.png)

**Comment by helloanoop** [comment]
This has been fixed in the latest release `v0.16.5`
