### ISSUE TITLE
Run shell commands in scripts

### ISSUE THREAD

**Issue by jacob-horton** [usebruno/bruno#1540]
It would be really useful if we could run a shell command in the pre/post-request script. This would allow for a lot more flexibility in the scripting.

I have tried using `child_process`, but that doesn't appear to be accessible (as it's nodejs specific). I've looked into some npm libraries, but all the ones I came across were wrappers for `child_process`, so also didn't work

Is there some way to do this already that I'm missing, or if not, would it be possible to add an internal library to do this?

Thanks!

**Comment by Its-treason** [comment]
You can use nodes `child_process` module after whitelisting it in the bruno.json of your collection like this:

```json
{
  "scripts": {
    "moduleWhitelist": ["child_process"],
    "filesystemAccess": {
      "allow": true
    }
  }
}
```
Your bruno.json should look like this in the end:
```json
{
  "version": "1",
  "name": "Test",
  "type": "collection",
  "scripts": {
    "moduleWhitelist": ["child_process"],
    "filesystemAccess": {
      "allow": true
    }
  }
}
```

**Comment by jacob-horton** [comment]
Perfect, that's exactly what I needed, thank you!

I've made a [PR](https://github.com/usebruno/bruno-docs/pull/40) in the docs repo to document this, so will close this issue :slightly_smiling_face:

**Comment by bpoulaindev** [comment]
@jacob-horton I'll add your PR to the new docs
