### ISSUE TITLE
Bug: Basic Auth with Empty Password

### ISSUE THREAD

**Issue by AnsgarLichter** [usebruno/bruno#1545]
My colleagues and I use a collection to share common requests. The authentication is configured as a basic auth at collection level with variables from the environment:
![image](https://github.com/usebruno/bruno/assets/43957906/a9adc44c-a7b7-4fb2-8135-0b677c556143)

The framework we use provides default users for testing purposes with an empty password. Therefore we want to use them in the collection. Unfortunately Bruno will not work with an empty password. I tried the following possibilities:
1. Use empty password value:
    ![image](https://github.com/usebruno/bruno/assets/43957906/783a5c22-159c-4594-b307-364dd6973b5b)
    Bruno creates the following authorization header for the user `authenticated`: 
    `authorization: Basic YXV0aGVudGljYXRlZDpudWxs`
    
    If I compare this value with an authorization header generator, this equals to the following:
    ![image](https://github.com/usebruno/bruno/assets/43957906/1d3efc0c-8c80-41a1-9b82-364f0a6380c0)
2. Don't provide the variable `password` in the environment:
    ![image](https://github.com/usebruno/bruno/assets/43957906/4d326014-d22a-41f6-9137-337fb687beb0)
    Bruno creates the following authorization header for the user `authenticated`: 
    `authorization: Basic YXV0aGVudGljYXRlZDp7e3Bhc3N3b3JkfX0=`
    
    If I compare this value with an authorization header generator, this equals to the following:
    ![image](https://github.com/usebruno/bruno/assets/43957906/2c1e3cc9-b865-4688-9ab9-be97766ae3d0)

Both variants lead to an `401 Unauthorized`.

**Expected Behaviour**:
If I supply an empty password variable (value `null`) or don't provide an variable at all, Bruno should use an empty string as a password resulting in the following authorization header:
![image](https://github.com/usebruno/bruno/assets/43957906/7b580eff-4e98-42f0-82e0-439cfc7dcd1d)

I am using the latest version of Bruno v.1.7.1.

**Comment by therealrinku** [comment]
@AnsgarLichter I think one workaround would be to add empty space in password value in environment.
seems to be working for me.

**Comment by AnsgarLichter** [comment]
@therealrinku How do you add an "empty space"? A normale space does not work for me.

**Comment by sanjai0py** [comment]
this might be an possible walkaround
![image](https://github.com/usebruno/bruno/assets/84461672/a68db818-773f-4275-837c-e9cbedcafa1d)

**Comment by AnsgarLichter** [comment]
> this might be an possible walkaround ![image](https://private-user-images.githubusercontent.com/84461672/303612839-a68db818-773f-4275-837c-e9cbedcafa1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODMyNzYsIm5iZiI6MTcwNzQ4Mjk3NiwicGF0aCI6Ii84NDQ2MTY3Mi8zMDM2MTI4MzktYTY4ZGI4MTgtNzczZi00Mjc1LTgzN2MtZTljYmVkY2FmYTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDEyNDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZWE1ZGNkYzFiY2UzOTY1MjFjYzI3MDc4NWE0M2UwNjE3MmY2NDk1MjkxY2I5NTdhZDVkYmQ5OTVjMzcwNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ltcCz8DDO74IMSHXGNTx_U_B9ObOQ5Ve8d87Er1dUDw)

This leads to the following authorization header:
`authorization: Basic YXV0aGVudGljYXRlZDoiICI=`

Therefore, my service still returns 401 unauthorized because this does not correspond to the expected header when the pasword is really empty.

**Comment by mato-meciar** [comment]
So far I was able to find 2 possibilities for a workaround:

1. don't even mention the `{{password}}` variable <img width="1125" alt="image" src="https://github.com/usebruno/bruno/assets/6736499/f034f07c-2893-4011-a729-f276909cb721">
2. write a simple Pre Request script that sets the auth header if `{{password}}` is `null` <img width="1132" alt="image" src="https://github.com/usebruno/bruno/assets/6736499/4d4c10a7-0543-411e-b8a5-1093b2aaffed">

The problem with 2. is that you'd need to change the Auth to be No Auth as otherwise it will overwrite the Pre Request-created header. You can modify the script to calculate the header as usual if it's not null but I didn't bother in this quick example (but in that case the problem of Auth being set to No Auth is resolved as the auth header would be set by that script).

**Comment by AnsgarLichter** [comment]
I appreciate that you all search for workarounds for this topic. Isn't there a possibility to change this in the coding?

My expected behaviour is that if the variable `{{password}}` is set without a value, an empty string is used for the password. This would be the most consistent and transparent behaviour in my opinion.

**Comment by mato-meciar** [comment]
So, wanted to give it a crack in fixing this but as it turns out - if you don't mark that field as secret you can have an empty value there... It's just when it's marked as secret it gets saved as `null`.

**Comment by AnsgarLichter** [comment]
> @AnsgarLichter dunno, prepared PR #1600 but then again one can argue just to not mark the value as secret.

Thanks. I agree but it offers much convenience if you switch between different users during testing. As we do this the support of this would be great.
