### ISSUE TITLE
[BUG] Deleted Request Variables are stilling being used

### ISSUE THREAD

**Issue by peerb** [usebruno/bruno#1546]
Deleted Request Variables are stilling being used in the request.

Steps to reproduce:
1) Create new a new collection
2) Create new "GET" Request with variable in path: https://run.mocky.io/{{version}}/3561f32c-66a5-44d9-9c2f-7398b118468a
3) Go to the "Vars" tab in this request and send the request
4) Add the var with the name "version" and value "v3"
5) Send request and check the "Timeline" tab to verify "v3" is used for "version" in the path
6) Go to the "Vars" tab and delete the "version" var
7) Send request
8) For the result go to the "Timeline" tab: After deleting the var "version" from the "Vars" tab, it is still used in the request.

![ezgif-5-eff3302b95](https://github.com/usebruno/bruno/assets/646566/6fe93ff7-7f3b-44e7-b613-e3163476ecfd)

**Comment by epestela** [comment]
Just my 2 cents: a clean solution could be to implement the delete as:
deactivate + delete.

**Comment by peerb** [comment]
@epestela how about one step at a time with the current quality? Pull request for activate/deactivate ist already open: #1101

**Comment by epestela** [comment]
I agree and i might have not bean clear:
I did not mean to ask to fix both cases together
I ment to use the disable feature for the (future) delete fix
- on delete request
  - disable the variable
  - remove the variable

but it was just a suggestion

**Comment by peerb** [comment]
@epestela thanks for clarifying. No it is understood, but this would be the case if the var would delete.

**Comment by DT209** [comment]
Entire request context should be cleared between calls.  If you create a variable using a script and then you don't create it on your next run of that same script (because you changed the script), the variable is still there.

**Comment by peerb** [comment]
@DT209 thank you for the input. This is already addressed in #1539 and the pull request is waiting for approval.

**Comment by helloanoop** [comment]
The `Request Variables` are supposed to be scoped only under the context of request execution.
Before `v1.20.2` the request variables were being persisted and were getting leaked into the global scope.

**Comment by helloanoop** [comment]
The `Request` variables - in the `Vars` Tab are supposed to be scoped only under the context of request execution.

Before v1.20.2 the request variables were being persisted and were getting leaked into the global scope.
This was a bug and it has been fixed in the latest release.

We have also added support for Folder Level Variables which gets applied to all requests under the folder.
