### ISSUE TITLE
Return a non-zero exit code if collection run fails on CLI

### ISSUE THREAD

**Issue by dpods** [usebruno/bruno#155]
First off, thanks for building Bruno. I think this could be really useful and I'm hoping to recommend it to more teams to increase adoption for our organization. 

While looking at what it would take to integrate Bruno with our CI pipeline, I noticed the CLI collection runner returns a zero exit code even when requests, tests, or assertions fail. 

I think returning a non-zero exit code of `1` for test failures should be enough to allow our CI pipelines to fail the build stage for our API tests.

I wouldn't mind making the change myself, but I need to determine if company policies would allow me to do so. 

Thanks!

**Comment by helloanoop** [comment]
Hi @dpods 
Glad that you like Bruno!

I have updated the cli runner to return a non zero exit code upon any test or assertion failures
https://github.com/usebruno/bruno/commit/51e0ea2c2d17e5fffdc62c1d576ff047541b619b

I have tested the latest fixes by running a jeninks pipeline script.
Here is the pipeline script for your reference
```groovy
pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/usebruno/github-rest-api-collection.git', branch: 'main'
      }
    }

    stage('Install Bruno CLI') {
      steps {
        sh 'npm i @usebruno/cli -y'
      }
    }

    stage('Run tests') {
      steps {
        sh 'node_modules/.bin/bru run --env Github'
      }
    }
  }
}
```

**Comment by dpods** [comment]
Thank you for the quick fix @helloanoop
