### ISSUE TITLE
Sending requests becomes sluggish after uploading a file

### ISSUE THREAD

**Issue by binaryfire** [usebruno/bruno#1552]
Hi all

I've been using the file upload feature introduced in v1.8.0 and have noticed that sending requests becomes quite sluggish after a file has been uploaded. To reproduce:

1. Upload a file to an endpoint (do it a couple of times)
2. Click the `->` button on any request to send the request. You'll notice that there's a delay before the request is sent.

This persists until the program is restarted.

**Comment by mateo-gallardo** [comment]
On it. I think chaging from `readFileSync` to `createReadStream` will do the trick.
