### ISSUE TITLE
Dark mode bug in GOLDEN EDITION modale

### ISSUE THREAD

**Issue by mrleblanc101** [usebruno/bruno#1555]
The modale here does not respect the dark mode theme.
<img width="1912" alt="Screenshot 2024-02-08 at 3 36 31 PM" src="https://github.com/usebruno/bruno/assets/17392251/b5becee7-45d6-457e-a1b3-b483871887ca">

**Comment by helloanoop** [comment]
Hi @mrleblanc101 This was fixed in the latest `v1.8.0` version which also adds support for file uploads.
Can you confirm which version you are on?

**Comment by mrleblanc101** [comment]
@helloanoop Indeed it has ! I did not know Bruno doesn't auto-update, but I've seen its on the 2.0 roadmap.
