### ISSUE TITLE
File upload goes application unresponsive and shutdown the app

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#1556]
Upload the file with a larger size (10 MB) you can see that the app crashes and shuts down

![image](https://github.com/usebruno/bruno/assets/44080743/1ef281fc-a312-4638-b6cd-f0a7454b4b85)

**Comment by therealrinku** [comment]
@sseenivasan89 nice catch!
 Seems like this is a issue, I was able to reproduce it too.

**Comment by rinkufetchly** [comment]
this should be resolved now by #1562

**Comment by therealrinku** [comment]
this should be resolved now by #1562

**Comment by sanjai0py** [comment]
I am closing this as resolved!
