### ISSUE TITLE
How to activate filesystem

### ISSUE THREAD

**Issue by Silence-TP** [usebruno/bruno#1560]
Hi,
This is may be a little bit newby but it would be great if somebody could help me with this.

I try to upload a file via bruno like:
`curl -X 'POST' \
  'https://xxx.xxx.xxxx.com/sboms' \
  -H 'accept: application/json' \
  -H 'Authorization: token xxxx' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@abc.json;type=application/json'`
but bruno tells me:
_Error invoking remote method 'send-http-request': VMError: Module 'C:\...\bruno\fs' is not allowed to be required. The path is outside the border!_

I have read in #385 that I need to activate the filesystem in bruno.json and use a pre-request scripts to do so, but I can't find such a file on my filesystem. I found it in the repository but not in my lokal installation of bruno.

It would be great if someone could tell me how to activate the filesystem in bruno!

Bruno Version:
1.8.0 for Windows X64
https://github.com/usebruno/bruno/releases/download/v1.8.0/bruno_1.8.0_x64_win.exe

thx in advance
regards

**Comment by sanjai0py** [comment]
hey @Silence-TP! remember that little pop-up window that appeared when you created the collection? 
![image](https://github.com/usebruno/bruno/assets/84461672/9a9b60b7-5522-4560-89a8-b1e540a850f4)
That's where you can find the `bruno.json` file. If you can't recall where you saved your collection, don't worry, it happens to me all the time. Just click the three dots on your collection, select `settings`, then `info`, and finally `location`. Once you find the `bruno.json` file, just copy and paste the following code snippet into it:
```json
"scripts": {
    "filesystemAccess": {
      "allow": true
    }
``` 
Hope that helps!

**Comment by Silence-TP** [comment]
Hi @sanjai0py 

Great, thanks for the hint! It seems to work now. I don't know why i couldn't find that by my own :-D 
I still need to customize the pre-script in a way to achive somethin simular like with curl -F 'file=@abc.json;type=application/json' but therefore I just need to get a little bit more familiar with nodejs. I think I can achive that by my own.
Your reply realy helped me.
Thx again!

**Comment by Silence-TP** [comment]
I finally got it running!
thx again 4 your help!

**Comment by pkfox** [comment]
Brilliant @sanjai0py  it solved my problem to thanks
