### ISSUE TITLE
Custom HTTP Verbs (Duplicate of #1473)

### ISSUE THREAD

**Issue by edbrannin** [usebruno/bruno#1561]
Please allow specifying [custom HTTP verbs](https://webconcepts.info/concepts/http-method/), so we can interface with services that use WebDav & other HTTP extensions.

I just spot-checked Httpie & Insomnia 8, and they both have a "Custom" entry at the bottom of the Verb selector:

<img width="249" alt="image" src="https://github.com/usebruno/bruno/assets/121909/78c147a2-ca20-44fb-8f83-33903ba79e07">

**Comment by Its-treason** [comment]
Duplicate of #1473

**Comment by edbrannin** [comment]
Whoops!  I forgot these are called "methods" too while searching.  I've updated the title, and I'll close this one.
