### ISSUE TITLE
Import multiple collections at once

### ISSUE THREAD

**Issue by Sironheart** [usebruno/bruno#157]
It should be possible to import multiple postman/ insomnia collections at once. 
In my head you can give the GUI a list of files and a base directory (for example a bruno-base repository) and it will import all collections into this folder

**Comment by l0new4nder3r** [comment]
This would indeed benefit people migrating large collections from Postman or Insomnia

**Comment by driden** [comment]
Hello, after seeing what Insomnia did with their new v8 update I'm in the same bandwagon, looking for an alternative http client. 

I'm +1'ing this request

**Comment by OutRunner** [comment]
Yeah +1 for this. I've got a relatively meagre 22 files to import and it's a bit of a pain.

**Comment by Allanio** [comment]
+1

**Comment by grahamauty** [comment]
+1 vote.
Also, during the import of a single item, you have to select where the item being imported is, and then where the Bruno folder is, but it doesn't remember either of these, meaning you have to select them each time you import a collection. This is a time-consuming and tedious process for lots of imports.

**Comment by hugobarroca** [comment]
+1, as someone who has just had to import around 30ish collections, it would definitely help a bunch 👍

**Comment by suricat89** [comment]
+1
I just did a full export of my postman collections and there are literally 201 collection json files and 94 environment json files to import.
This feature sure would help a LOT

Even if it was not available in the GUI, but if there was something that I could automate through CLI would be awesome

**Comment by lacikawiz** [comment]
+1
In the same boat. Only 9 collections to import from Insomnia but it's still a lot of extra work.

**Comment by drizzitielloasendia** [comment]
+1

**Comment by hugobarroca** [comment]
If no one is taking a look at this yet, I wouldn't mind taking a look into it

**Comment by TheRealRyanReynolds** [comment]
Hi @hugobarroca - we're building this now. The ability to import from an ["Export Data Dump"](https://learning.postman.com/docs/getting-started/importing-and-exporting/exporting-data/#export-data-dumps) is planned for October 24th.

**Comment by hugobarroca** [comment]
> Hi @hugobarroca - we're building this now. The ability to import from an ["Export Data Dump"](https://learning.postman.com/docs/getting-started/importing-and-exporting/exporting-data/#export-data-dumps) is planned for October 24th. 

Alright, sounds cool @TheRealRyanReynolds! I've been messing around a bit with allowing the current file dialog to select multiple files, but in that case I'll wait to see the new feature release. Thanks for the heads up!

**Comment by ansorg** [comment]
An insomnia export can contain multiple (all) collections in one file. would the mentioned new feature consider this?

![image](https://github.com/user-attachments/assets/a1fc3738-d61d-4ac4-be0c-71c624984fb1)

**Comment by TheRealRyanReynolds** [comment]
Hi @ansorg - right now we're releasing this specifically for Postman collections to allow for import of an ["Export Data Dump"](https://learning.postman.com/docs/getting-started/importing-and-exporting/exporting-data/#export-data-dumps). Insomnia is planned, but not immediately. 

What's the current impact when you import an Insomnia file that you describe into Bruno?

**Comment by ansorg** [comment]
Importing the example, only the first collection gets imported and the rest ignored. No error otherwise. 

I guess it's related to the fact that I am asked for a storage location for one collection. It this were just asking for the location of a "root" folder and then creating the collection folders automatically this probably could work?

**Comment by jansenbe** [comment]
@rreyn-bruno : I just bought the golden edition under the assumption that the "export data dump" feature was advertised as premium would be there, but's it not. What am I doing wrong?

**Comment by rreyn-bruno** [comment]
@jansenbe - right now, the "export data dump" is available inside of our Ultimate Edition. Inside of open source, you do have the ability to multi-select collections.
