### ISSUE TITLE
No Hostname after importing OPEN API Collection

### ISSUE THREAD

**Issue by skilger** [usebruno/bruno#1586]
Hi,

I have imported a collection from OPEN API JSON which seemed to work fine.
The trouble I'm having is that in every imported request the URL is missing host or base-URL.
I.e. Prefilled is http://request, instead of https://myHost.test/v1/request
I tried to add a Base URL in the Collection Settings under Presets but this didn't change anything.
Is it possible to change this behavior without having to change every request (which would be quite tedious)?

Thanks a lot in advance.

Cheers,
Sebastian

PS: I'm using Bruno v1.9.0 under Windows

**Comment by ykarpeev** [comment]
I got around this by adding this to my open api json file before importing.

"servers": [
    {
        "url": "http://localhost:12345",
        "description": "Test"
    }
  ],

**Comment by bwirt-sbux** [comment]
Agree, would be nice to have an option for default host name when none is given (e.g. imported collection)

**Comment by bryant-ferguson** [comment]
I came over here just yesterday for this issue, but... today it started working, so I checked my update log and it updated today from 1.33.0 to 1.34.0 and now I am getting a {{baseUrl}} prefixed when I import OpenAPI documents.
