### ISSUE TITLE
Problem saving / opening collections in WSL2

### ISSUE THREAD

**Issue by binaryfire** [usebruno/bruno#159]
Hi. Great project!

I'm using Windows 11 + WSL2. I've installed the client in Windows and have specified the collection location as `\\wsl.localhost\Ubuntu-22.04\home\myhomedir\mycollection`. The `bruno.json` file is created correctly and requests are saved as `.bru` files but they don't appear in the UI. I'm guessing the format of the path is messing something up.

What is the recommended way of using Bruno with WSL2?

Cheers

**Comment by nicklargent** [comment]
I just ran into this same issue.  Decided to dig into the source a little and found this...

The issue appears to be a result of using fs.watch which isn't recommended for network paths (and WSL is accessed via network path). 

A simple workaround is to set the environment variable `CHOKIDAR_USEPOLLING=true` before launching bruno. This avoids the issue but means that all folders use polling though which could be less efficient for large projects. 

A more permanent fix could be conditionally setting the polling mode based on the path type. In watcher.js:415 the parameter `usePolling: false` could do something like `usePolling: watchPath.startsWith("\\\\") ? true : false,`

**Comment by SpiRanha** [comment]
Alternatively, if you validate the [prerequisites](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#prerequisites) for running GUI apps from WSL2, you can run bruno as GUI from the WSL itself and it seems to just work fine.

**Comment by Nikolai2038** [comment]
> Alternatively, if you validate the [prerequisites](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#prerequisites) for running GUI apps from WSL2, you can run bruno as GUI from the WSL itself and it seems to just work fine.

Yep, installing Bruno in WSL directly (I used apt) worked for me, thanks!

**Comment by GimpMaster** [comment]
Came here to say WSL paths do not work. Glad I'm not the only one. Hopefully one day bruno will support this.

**Comment by helloanoop** [comment]
@binaryfire @eblount @nicklargent @SpiRanha @GimpMaster This has been fixed in `v1.5.1` Can you download and check if it solves the issue ?

@gyunseo Many thanks for the PR!

**Comment by binaryfire** [comment]
Hey @helloanoop. Only had time to do a quick test but so far so good! I'll let you know if I have any other problems.

**Comment by eblount** [comment]
@helloanoop I don't see any change here, sorry:

- Installed 1.5.1 in Windows
- Created a new collection with the folder in WSL2
- Created a new request
- Request doesn't appear in the Bruno sidebar
- Request file is in the directory in WSL2
- Restarted Bruno, same result: Collection is there, request is not

**Comment by GimpMaster** [comment]
@eblount 

1.5.1 worked just fine for me.

![image](https://github.com/usebruno/bruno/assets/7818200/83166cc8-7270-4336-967f-0c51b073986a)


Basically clicked create new collection. Choose \\wsl$.localhost\Ubuntu\tmp\bruno

Created a request and it showed up. 
Did a GET request on google.com and it pulled down the webpage and rendered it.
Closed Bruno and re-opened and it still remained there.

Thanks @helloanoop

**Comment by eblount** [comment]
Okay, using the `\\wsl.localhost\...` path did work. I have my WSL distro mapped to a drive letter, and that was what I used last time. I can confirm that using the network path to WSL does work with 1.5.1. Thanks for the suggestion, @GimpMaster, and for the update @helloanoop

**Comment by nicklargent** [comment]
Works over here too, thanks!  No more workaround.

**Comment by binaryfire** [comment]
Is anyone else having problems renaming folders on WSL2? It'd be great if someone could test this and let me know - I'm not sure if it's a bug or if it's something to do with my system.

To reproduce: right click on a folder inside a collection, click "Rename" and try and change the name to something else. The name doesn't change.

**Comment by binaryfire** [comment]
I've opened a new issue here: https://github.com/usebruno/bruno/issues/1302

Looks like there are issues with several file operations in WSL2
