### ISSUE TITLE
The last selected environment is not persisted across app startups

### ISSUE THREAD

**Issue by StylianosGakis** [usebruno/bruno#1598]
Not necessarily a bug, it may be how you intend this to be, but I do find that it adds a little bit of friction to my workflow having to select the environment each time I open Bruno.

Optimally I would like to have that be persisted and if I had selected something before, it should stay after quitting the application and opening it again later.

I am on macOS if that matters ✌️

**Comment by melroy89** [comment]
Yes, please!! This is a must-have feature IMO.

**Comment by mathisgauthey** [comment]
It would be much beneficial indeed.

**Comment by tngranados** [comment]
I think this would be very useful. Alternatively, being able to set a default environment will also be good.

**Comment by berlingoqc** [comment]
Is this in the works ? it's really annoying having to manually select each time

**Comment by berlingoqc** [comment]
https://github.com/usebruno/bruno/pull/1971
https://github.com/usebruno/bruno/pull/2238

There is two PR for this

**Comment by helloanoop** [comment]
This functionality is now available in Bruno `v1.32.0` 🎉

**Comment by ZatsuneNoMokou** [comment]
That feature has been removed or broken in v2 ?

**Comment by anusree-bruno** [comment]
> That feature has been removed or broken in v2 ?

No this should be working as expected, if it is not persisting for you can you share a screen recording?

**Comment by ZatsuneNoMokou** [comment]
When/How it is saved ?

**Comment by anusree-bruno** [comment]
> When/How it is saved ?

It is being saved in the ui-state-snapshot.json file located in the AppData path.
You can go through the codebase for more info
https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/store/ui-state-snapshot.js#L8
