### ISSUE TITLE
Importing Collection can result in invalid directory name with trailing space on Windows/NTFS

### ISSUE THREAD

**Issue by fxsth** [usebruno/bruno#160]
After importing a postman collection that has some subfolders with trailing spaces in the name, Bruno created the directories with the same names on the filesystem. Problem is, on Windows / on NTFS leading or trailing spaces are invalid and it is a painful task to remove the folder again.

Is it possible to trim spaces from the collection/subfolder name before creating same-named directory on filesystem?

**Comment by helloanoop** [comment]
@Pragadesh-45 Can you provide an update on this. Is this behaviour still present in Bruno?

**Comment by Pragadesh-45** [comment]
Sure, Anoop. At present, I am able to reproduce this issue. It is possible to create folders with leading and trailing spaces. I thought it would be better to remove those spaces, as it would be really hard to navigate through those folders in the filesystem. So, I added sanitation steps wherever needed in the PR: [pull/3559](https://github.com/usebruno/bruno/pull/3559). Currently, this PR is in the internal review process.

**Comment by helloanoop** [comment]
Just merged the PR. This should go out in `v1.37.0` release.
