### ISSUE TITLE
Auto update or new version alert ?

### ISSUE THREAD

**Issue by bourpie** [usebruno/bruno#1611]
Really appreciate all the the work being done with all the frequent updates!

Not an issue but more of a feature request. Would it be possible to add an auto update feature whenever Bruno has a new version or an alert telling us there's a new version update ?

Thanks a lot!

**Comment by smdedar** [comment]
There is an old PR about this auto update

https://github.com/usebruno/bruno/pull/493

**Comment by sanjai0py** [comment]
Duplicate of #103
