### ISSUE TITLE
Collection removal should be called as collection close

### ISSUE THREAD

**Issue by jikuja** [usebruno/bruno#1619]
At the moment collection has context menu `remove` to remove collection in the UI. All the data: collection directory, subdirectories, requests and even entries on secret storage are being kept.

This option should be renamed to `close` to describe match with the current behaviour.

**Comment by rsilvr** [comment]
In version 1.9.0 this improvement is already implemented:
![image](https://github.com/usebruno/bruno/assets/5250902/2641f908-d44e-4e34-bcb4-aa759227402d)

**Comment by jikuja** [comment]
Updated.

Cool. Looks like other features I would have requested have been implemented recently
