### ISSUE TITLE
Nested Variable references are not resolved

### ISSUE THREAD

**Issue by drventure** [usebruno/bruno#1622]
Say I have an environment like this

serverName: test1.ibm.com
baseServer: http://{{serverName}}/
baseService: {{baseServer}}api/myendpoint

if I then try to use {{baseService}} in a request, it only resolves to "{{baseServer}}api/myendpoint"

I would expect any variable reference within that value to ALSO be resolved, and any variable within the result of that to also be resolved, etc etc.

**Comment by igorasantos** [comment]
looks similar to #956

**Comment by sanjai0py** [comment]
Closing this as the nested variable reference feature has been implemented into Bruno through this [PR](https://github.com/usebruno/bruno/pull/2234) and released in [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0).
