### ISSUE TITLE
cannot access new collection environment

### ISSUE THREAD

**Issue by igorasantos** [usebruno/bruno#1623]
When I create a new collection, add some request and create one environment, and finally close and open Bruno again, the environment list doesn't show the env I just created.

Following are the collection files with my local scenario (I replaced my real data preserving strings length):

`./eeeeeee-www/bruno.json`:
```json
{
  "version": "1",
  "name": "eeeeeee-www",
  "type": "collection",
  "ignore": [
    "node_modules",
    ".git"
  ]
}
```
`./eeeeeee-www/collection.bru`
```
headers {
  User-Agent: Bruno v1.9.0
}
```
`./eeeeeee-www/.env`
```
eee_ggg_ttttt_pppp=any_value
```
`./eeeeeee-www/environments/cccc-eee-ppp.bru`
```
vars {  
  bbbbbbb_cc_aaa_iii: https://eeeeeee.com
  bbbbbbbb_ffff_gggg_kkkk_mmmm_www_oo1: some/path/url
}
```
`./eeeeeee-www/iiiiiiiiii/aaa-gggg-eeeeeee_cc/v1/eeeeeeeeeeeee.bru`
```
meta {
  name: eeeeeeeeeeeee
  type: http
  seq: 1
}

get {
  url: {{bbbbbbb_cc_aaa_iii}}/{{bbbbbbbb_ffff_gggg_kkkk_mmmm_www_oo1}}/some_resource/{{foo}}
  body: none
  auth: none
}

vars:pre-request {
  foo: "0000000000"
}
```
Screenshot with the files tree:
![image](https://github.com/usebruno/bruno/assets/27933937/c9aa01bf-c86f-449c-a14d-8af9d8f7e2c7)

And the screenshot with the environment list on Bruno empty:
![image](https://github.com/usebruno/bruno/assets/27933937/2752c7ba-7213-4e16-825b-cdb8204cfac7)

**Environment**:

- OS: Ubuntu 22.04.4 LTS
- Bruno: 1.9.0 (installed with snap)

Maybe related:
- #1606
- #1616 

I noted too that when I edit my environment file on vscode and get back to Bruno, the values aren't updated, they're showing only the values I filled on Bruno.

Does anyone:

- already face this?
- know how to fix this config scenario?
- know if this is some bug of this Bruno version (1.9.0)?

**Comment by igorasantos** [comment]
Just fixed the problem.
My `environments/env-name-file.bru` was with trailing spaces at the final of 1st line 😅

**Comment by DJTILBUD** [comment]
I imported the wrong folder (the parent folder of the collection). Importing the correct folder worked funnily enough...
