### ISSUE TITLE
[Feature Request] clone request should open the new request

### ISSUE THREAD

**Issue by stacy-rendall** [usebruno/bruno#1624]
When cloning a request the newly created request is not opened. This makes it really easy to accidentally edit the old request not the new one.

Ideally once a request is cloned the new request should be opened.

**Comment by cdlftw** [comment]
Hard agree.  It's counter intuitive to clone an item and NOT be focused on the newly created item, it often results in modification of the original item, even when being mindful of it.

**Comment by helloanoop** [comment]
Merged PR. Thanks @sanjai0py !
This will be available in the next outgoing release.
