### ISSUE TITLE
[BUG] Cannot re-edit document after first edition

### ISSUE THREAD

**Issue by hurlebouc** [usebruno/bruno#1626]
Once written a first version of the documentation of the collection, when re-edited again, new version of documentation is not saved anymore

**Comment by sanjai0py** [comment]
hey @hurlebouc, could you give me more details about the issue you're facing? Can you please describe the bug in more detail?

**Comment by hurlebouc** [comment]
> hey @hurlebouc, could you give me more details about the issue you're facing? Can you please describe the bug in more detail?

Sorry, I can't reproduce. I'll reopen this ticket if I found e reproducible path.

Thank you for your job!
