### ISSUE TITLE
Maximum characters request name

### ISSUE THREAD

**Issue by RichardArling** [usebruno/bruno#163]
Hi,

I'm looking for an alternative for Postman and came along Bruno. I really like the application. I have a lot of collections with a lot of requests. Some names of those requests exceed the maximum of 50 characters Bruno allows. The collections are imported from Postman and are visible in Bruno. Some names have more than 50 characters. However when I try to rename some requests (remove the server name from the name of the request) I get the message 'must be 50 characters or less'. The names of the requests are the same as the names of the endpoints and should not be changed. I can cange the name of file of the request and the contents. Afterwards the request just shows up fine. This is a hack of course and it takes a lot of time. Could the maximum of characters be removed? Also when the left pane has a lot of requests and you scroll down, the right pane also scolls down.

**Comment by helloanoop** [comment]
Hey @RichardArling 

Glad that you like Bruno!
Sure, I can increase the limit on the request name to 500 characters.
Do you think that would be sufficient?

> Also when the left pane has a lot of requests and you scroll down, the right pane also scolls down.

Will get this fixed as soon as I can.

**Comment by RichardArling** [comment]
Hi @helloanoop 

500 characters should be enough.

Thanks in advance.

**Comment by helloanoop** [comment]
Bruno no longer imposes a maximum character limit when creating or renaming requests and folders.

**Comment by rsteele1-seic** [comment]
@helloanoop We saw this was closed but looking at the code commit, there was only a change to the limit on the rename of collections, NOT on the create of collection or anywhere else that the 50 character limit is imposed.  Is this what was intended?
