### ISSUE TITLE
Sorting is Broken in Collections

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#164]
From mark99 on discord

I am also interested in how the sorting of methods in the collection is implemented: I use version 0.12.2 and new ones are always added at the end. Moving them somewhere seems to lead to a complete re-sorting with a random result ... %)

to solve this problem, I have sketched a small python script that will sort the collections alphabetically, but in git, using it leads to changes in almost all files in the repository - somehow this is wrong. it may be necessary to issue seq numbers for requests in increments of 1000, for example, 1st = 1000, 2nd = 2000, 3 = 3000, and so on. thus, when moving the request, it will be possible to put the number 999 - if it needs to be placed first and it will not change all the other files.
https://gist.github.com/mark99i/d9427e0f33c29066068063518529ddf1

**Comment by martinsefcik** [comment]
Shouldn't it be better to hold this information where I guess it belongs and it is in file which represents collection/folder settings? I'm not sure such file is currently supported. I see only bruno.json file in collection. I'm not sure something similar exists for folders, but if you want to support e.g. pre-requests scripts for collection/folder you will have to anyway introduce something like that.

**Comment by jthln** [comment]
I'm no JS expert, but principally I think it would make sense to

- add some unique ID to the request `.bru` files (which doesn't change when the request is renamed or updated) 
- remove `meta.seq` from the request `.bru` files
- add a `.bru` file to the collection folder, e.g. `MyCollectionFolder/MyCollectionFolder.bru`
- persist/manage the sort order of the unique request IDs in the `MyCollectionFolder.bru` file

This way request resorting would only change one file under version control.

**Comment by lared** [comment]
@jthln extraction of the folder to its own metadata file would also allow to use request names containing filesystem-agnostic names

**Comment by lared** [comment]
I think this issue is duplicate of #154, I did some digging and I think I'm getting somewhere but my gaps in FE knowledge are too large. It looks like stale data issue, as if some results of drag-and-drop are forgotten on subsequent drop.

**Comment by helloanoop** [comment]
Some pointers. And warning :)

The flow is quite complex. I honestly wish it was simpler. While I developed this, it was one of the hardest parts to ensure the requests could be drag-dropped anywhere within the collection. Despite its complexity, I would not recommend to think about rearchitect the approach at the moment. We just need to fix the bug for now.

This [code](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js#L384) is responsible for moving the collection items within a folder
The `moveCollectionItem` defined [here](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/utils/collections/index.js) essentially responsible for updating the pathnames stored in the collection

So far we are still in the redux internal state.

Next the [itemsToResequence](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js#L385) calculates which items has their `seq` property changed

Next an IPC event gets sent to electron to [resequence](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/providers/ReduxStore/slices/collections/actions.js#L387-L390)

The electron app writes the `seq` property updates to the respective files [here](https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/ipc/collection.js#L382-L397)

Next the [watcher](https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/app/watcher.js#L343-L361) picks up the file change and emits an event back to the renderer process.

The [ui code](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/providers/App/useCollectionTreeSync.js#L54-L59) picks up this change and updates the redux tree.

There is also this code that ensures the `requestUids` get preserved when the move happens [here](https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/cache/requestUids.js)

---
@martinsefcik @jthln Once we fix the sorting at a folder level, then we can move on to supporting folder sorting.

We will be storing a `index.bru` file under every folder. (This would mean that `index` name cannot be used in any request)
I had already envisioned this scenario and reserved the usage of this [keyword](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/components/Sidebar/NewRequest/index.js#L30-L34)

> but if you want to support e.g. pre-requests scripts for collection/folder you will have to anyway introduce something like that.

@martinsefcik  Yes, we will have to support folder level scripts that run for all requests and they will go inside `index.bru`

> persist/manage the sort order of the unique request IDs in the MyCollectionFolder.bru file

@jthln I had considered this approach of storing sequences at folder level file, I also even thought of storing the entire tree structure inside `bruno.json` that sits under the collection root. This was 8 months ago. After much thought about the tradeoffs I decided that storing `seq` was a better option. I don't remember the tradeoff's. At some point in the future, if the current process of sequencing becomes impossible to implement correctly, we can revisit the approach

**Comment by helloanoop** [comment]
Closing this as this is a duplicate of [#154].
