### ISSUE TITLE
Hide secrets in the UI

### ISSUE THREAD

**Issue by sanjai0py** [usebruno/bruno#1646]
### Discussed in https://github.com/usebruno/bruno/discussions/1645

<div type='discussions-op-text'>

<sup>Originally posted by **warlon** February 22, 2024</sup>
If a variable is set as a secret it should also be hidden in the UI and only revealed when requested. This would add additional security and prevent secrets being leaked for example when sharing your screen with someone.</div>

**Comment by JaceyPenny** [comment]
@sanjai0py This would be a great feature to have! I'll point out that secret are also revealed on-hover when templating them into requests:

![image](https://github.com/usebruno/bruno/assets/1887439/3cfaa309-94d0-4303-b244-0b71fdba52a5)
![image](https://github.com/usebruno/bruno/assets/1887439/d6557ed0-3114-42a7-8296-fb4f1676c20a)
