### ISSUE TITLE
[Question] Error handling with status code 500

### ISSUE THREAD

**Issue by Lupfson** [usebruno/bruno#165]
Hi there,

I'm currently looking for a Postman alternative and playing around with Bruno. I really love the folder / plain text files approach you are taking here. That said, I'm struggling a bit with the setup of API calls that are expected to fail.

I have to work with an older ASP.NET service hosted in IIS. It's expecting post requests with a json body containing some data. When that data is invalid, the service may simply return an HTTP 500 status code, with a response message containing some error details.

How can I setup a corresponding request in Bruno, so that the status code 500 is expected with that data and the run is ending up green? It seems that neither the post request script, nor a corresponding assertion or the test script code is running, since the execution is aborted before the runner gets there. Am I doing this wrong or is this expected behavior?

**Comment by helloanoop** [comment]
Hey @Lupfson !

Glad that you like Bruno.

Are you talking about setting up a test assertion so that it passes on a 500?
I just tried setting up a test assertion for a 400 response and it worked. Here is the screenshot.
<img width="1092" alt="image" src="https://github.com/usebruno/bruno/assets/9350733/73e795c1-a736-4f17-a126-cc779d2ea092">

Can you share a screenshot of the error you are seeing.

**Comment by Lupfson** [comment]
Hi Anoop,

thanks for the fast reply. Yes, that's what I want to achieve.

Currently this is a request that runs green:
![grafik](https://github.com/usebruno/bruno/assets/131516979/a238642f-a6c1-45b9-9451-675ff4f13541)

The same requests is failing with status code 500 when I use other parameters, which is expected and something I would want to test for:
![grafik](https://github.com/usebruno/bruno/assets/131516979/7552ecaf-3b47-40d7-b241-5188de455cdf)

Also, if I just throw an exception in the post response script, that never shows up. Doing the same in the pre-request script, the exception is shown. So it seems, as if that request returning 500 isn't fully processed or something?
![grafik](https://github.com/usebruno/bruno/assets/131516979/b3919b71-70b7-49d6-a400-3bff9b7d5f55)

**Comment by UnityStand** [comment]
Also faced with that. I tried to use the "Tests" feature, but that seems to not work.
![image](https://github.com/usebruno/bruno/assets/115578373/ee4491bb-3621-41e5-bf69-97489697787d)

**Comment by helloanoop** [comment]
@Lupfson @UnityStand 

This issue has been fixed in v0.13.0 and is available for Windows and Linux. Please go to [downloads](https://www.usebruno.com/downloads) to get the latest version

Note:
> The latest update, version 0.13.0, is now accessible for Windows and Linux users. Unfortunately, Mac builds are facing a delay due to notarization issues. As of now, the most recent Mac build available is version 0.12.2. The notarization challenges are expected to be resolved by September 15th, 2023.

**Comment by helloanoop** [comment]
The fix is now available for all operating systems.
