### ISSUE TITLE
Collection Runner does not respect "Form URL Encoded" body setting

### ISSUE THREAD

**Issue by DuncanDoyle** [usebruno/bruno#166]
In one of my Bruno collections, I use a POST method with "Form URL Encoded" body to request a new access-token from my Keycloak IDP using "client_credentials" grant. When I directly execute the request from the Bruno UI, the body format is correct. This is the output from Wireshark:

```
POST /realms/master/protocol/openid-connect/token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
User-Agent: axios/0.26.1
Content-Length: 96
Host: keycloak.example.com
Connection: close

client_id=portal-sa&client_secret=Rjg22ueDNVPFMq0gzk2WHG4r49jtziEG&grant_type=client_credentials
```

However, when I run the exact same request using the collection runner, the request is sent like this:

```
POST /realms/master/protocol/openid-connect/token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
User-Agent: axios/0.26.1
Content-Length: 110
Host: keycloak.example.com
Connection: close

{"client_id":"portal-sa","client_secret":"Rjg22ueDNVPFMq0gzk2WHG4r49jtziEG","grant_type":"client_credentials"}
```

As you can see, the body is now encoded as JSON, which results in a `400 - Bad Request` from the Keycloak server.

**Comment by vivobg** [comment]
@DuncanDoyle using the `bru run` CLI tool (Bru CLI 0.7.1) for running the collection does work as expected. The issue appears to only be in the GUI app.

**Comment by busy-panda** [comment]
This bug was fixed I guess, because I tested Form Url Encoded in both UI and CLI and the request generated is the following

![image](https://github.com/usebruno/bruno/assets/139650490/355bf1cb-c7e7-4eb4-a77d-cf7b23768aaf)

which is what is expected

So for me this bug can be closed

**Comment by anusreesubash** [comment]
Closing this issue as this has been fixed. Please reopen if the issue persists.
