### ISSUE TITLE
"Open Collection" dialog -- missing font?

### ISSUE THREAD

**Issue by Flonk** [usebruno/bruno#1666]
Hi, whenever bruno launches a file dialog, I get this view:

![image](https://github.com/usebruno/bruno/assets/5000133/6128ca56-6a6a-4713-abc9-95204c7b4240)

Am I missing a font?

The "import collection" dialog works fine (files omitted for reasons)

![image](https://github.com/usebruno/bruno/assets/5000133/c0a23392-abe1-4d9b-a7a1-39089e5812bc)

but all the other dialogs do not work as far as I can tell. I've installed bruno via `snap install bruno`.

---

OS: Ubuntu 23.10 x86_64
Host: 20TH000NGE ThinkPad P1 Gen 3
Kernel: 6.5.0-17-generic
Uptime: 1 hour, 36 mins
Packages: 2401 (dpkg), 114 (brew), 7 (flatpak), 21 (snap)
Shell: zsh 5.9
Resolution: 1920x1080, 3440x1440
WM: i3
Theme: Adwaita [GTK3]
Icons: Adwaita [GTK3]
Terminal: x-terminal-emul
CPU: Intel i7-10750H (12) @ 5.000GHz
GPU: NVIDIA Quadro T2000 Mobile / Max-Q
GPU: Intel CometLake-H GT2 [UHD Graphics]
Memory: 4373MiB / 31745MiB

**Comment by sanjai0py** [comment]
similar #1639
