### ISSUE TITLE
[QUESTION] Future or this application?

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#167]
I recently discovered Bruno, and the approach is very interesting and promising!

However, I'm a little bit worried about the future of the application as there wasn't any update since months, even in other branches.

Is there still some active developers in this projects? (And anyway many thanks to them for the job done !)

I'm not skilled enough to help in coding, but I should be able to help on something else if required...

Thanks

**Comment by helloanoop** [comment]
Hi @arnaduga

Glad that you like Bruno!
I have been a bit tied up since I switched jobs recently.

I very much look forward to improving the project and adding more features in the coming days.

**Comment by arnaduga** [comment]
Hi Anoop

Thanks for your reply. Congrats (I hope) for your new job ^^

Thank you for the confirmation of improvements! I really think there is a place for Bruno. I hope this project will last long!

(Closing the issue, as it is not really an issue)
