### ISSUE TITLE
Error importing external libraries

### ISSUE THREAD

**Issue by BoscoDomingo** [usebruno/bruno#1671]
I came across this bug while trying to set up some fake variables in one of my requests using faker-js.

I followed [the docs](https://docs.usebruno.com/scripting/external-libraries.html) to a T, created a `package.json` as well as installed the dependency, but for some reason the module cannot be found. The error is
```
Error invoking remote method 'send-http-request': VMError: Cannot find module '@faker-js/faker'
```

The pre-request script I'm trying to run is:
```js
const { faker } = require('@faker-js/faker');

bru.setVar("randomName", faker.name.fullName());
bru.setVar("randomUserAgent", faker.internet.userAgent());
bru.setVar("randomIp", faker.internet.ip())
```

If it helps, I'm running Bruno 1.9.0 on Windows accessing the WSL filesystem, which could be the reason.

**Comment by BoBNelson1971** [comment]
I have a similar issue with crypto module, but it is not an external library.

**Comment by traditio** [comment]
Same issue with Brno 1.9.0 on Windows, but not an WSL filesystem, just a normal drive.

**Comment by sanjai0py** [comment]
Hey @BoscoDomingo, it seems like you're having some trouble with your packages. That can be frustrating, but don't worry, I'm here to help! 

I'm curious, have you tried following these steps to create your `package.json` file? 

First, you'll need to click the three dots on your collection and select 'settings', then 'info', and finally 'location'. This is where you'll create your `package.json` file. You can either use your file explorer to get there or use your terminal by typing:

```bash
cd {{the location field you copied from the Bruno app}}
```

Once you're there, you can create a new `package.json` file by typing (only if you have npm installed on your machine):

```bash
npm init -y
```

Or, if you prefer, you can create the file manually by typing:

```bash
touch package.json
```

Then, copy and paste the following code into the file and replace the dependencies with the name of the package you want to install:

```json
{
  "name": "github-rest-api-collection",
  "version": "1.0.0",
  "main": "index.js",
  "homepage": "https://github.com/usebruno/github-rest-api-collection#readme",
  "dependencies": {
    "@faker-js/faker": "8.3.1"
  }
}
```

Once you've completed this step, you'll need to run:

```bash
npm install
```

Before running this command, make sure you're in the right folder by typing:

```bash
pwd
```

This will give you the current directory you're in, which should be equal to the 'info' > 'location' field you saw in the Bruno app. 

I hope this helps you solve your problem! Let me know if you have any other questions or if there's anything else I can help you with.

**Comment by BoscoDomingo** [comment]
Hey @sanjai0py I did in fact screw up the location stuff (I was working in Windows instead of Ubuntu, see #1672) but the problem now is that Bruno stops working for a bit:
![image](https://github.com/usebruno/bruno/assets/46006784/8c9f1511-4d60-4fce-a037-a7f607bda7ec)

It does work after a while, however, so I thought I should let you know
