### ISSUE TITLE
[Feature request] Save scripts to the .bru file

### ISSUE THREAD

**Issue by BoscoDomingo** [usebruno/bruno#1672]
As of right now, requests don't save the scripts, they are kept locally.

If I want to share a script with teammates, I have to copy paste the code elsewhere. It would make sense to include the script as part of the .bru file instead, as one of the sections.

This would be especially helpful when variables are set/modified and then used in the URL, body, params, etc...

**Comment by esmiralha** [comment]
Where are they actually kept? Inside the app's folder?

**Comment by BoscoDomingo** [comment]
> Where are they actually kept? Inside the app's folder?

Probably? Similar to environment secrets I would assume

**Comment by rsilvr** [comment]
Do you mean the pre-request and post-reponse scripts? As of version 1.9.0, here they are being written in the request .bru file normally.

![image](https://github.com/usebruno/bruno/assets/5250902/8a42b4fa-fbb8-4824-9b7d-76c4bb80faf0)

**Comment by esmiralha** [comment]
OK to close @BoscoDomingo ?

**Comment by BoscoDomingo** [comment]
Yes. I was being extremely dumb and used the Windows filesystem to save some collections back in the early versions, but I work with git in WSL, so the changes to requests weren't showing up because of that. Scripts work just fine 👍🏼
