### ISSUE TITLE
Warning from Windows when downloading and opening the latest version

### ISSUE THREAD

**Issue by tuyen-at-work** [usebruno/bruno#1678]
I encountered a warning from Windows when downloading and opening the latest version (v1.10) of Bruno:

![image](https://github.com/usebruno/bruno/assets/68000455/cea69c5e-6588-443c-ba12-2e17cca916a2)

This warning appeared on both my home and company PCs. I've downloaded several previous versions of Bruno without encountering this warning before.

Could anyone provide guidance on how to address this issue?

cc @helloanoop

**Comment by sk3674** [comment]
I encountered the same issue in Windows 11. This is my first time downloading Bruno so I can't speak to other versions having the same issue.

**Comment by tuyen-at-work** [comment]
@sk3674 @juliendiberardino could you try to build from source and see if the issue gone?

**Comment by SotoDucani** [comment]
This'll be due to the expired code signing cert, I opened #1696 earlier today as I didn't see this one. It looks like it only affected the 1.10.0 build, previous releases are ok.

**Comment by sanjai0py** [comment]
Closing this as the issue causing the Windows warning popup has been resolved. Please use the latest version of the app [v1.20.2](https://github.com/usebruno/bruno/releases/tag/v1.20.2).
