### ISSUE TITLE
Option to ignore "self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by Nosceteipsum** [usebruno/bruno#168]
An option to ignore **"self signed certificate in certificate chain"**.
Postman got this option and it would be nice to have this option when you trust the endpoint.
![image](https://github.com/usebruno/bruno/assets/7213547/5baa794d-ff73-4891-9f3e-fc5a5746da88)

Error from Bruno:
_Error invoking remote method 'send-http-request': Error: self signed certificate in certificate chain_

**Comment by ace90210** [comment]
literally hit this today, is there no way to disable this?

**Comment by helloanoop** [comment]
@ace90210 @Nosceteipsum 
I am working on this. Expecting to release this update this week.

Here is a screenshot of the ongoing work.
![image](https://github.com/usebruno/bruno/assets/9350733/4e18998c-2786-4c8e-8547-cd2d0f95b5f2)

**Comment by mschojoh** [comment]
any progress on this?

**Comment by helloanoop** [comment]
@mschojoh 
I plan to release this on Windows on Linux tomorrow.
I am resolving notarisation issues for Mac Builds (this will take some time).

Which OS are you currently using Bruno on ?

**Comment by mschojoh** [comment]
i use it on windows and really appreciate your work.

**Comment by mschojoh** [comment]
when will you publish a new release with the option to disable ssl verification?

**Comment by helloanoop** [comment]
@mschojoh @Nosceteipsum @ace90210 
This issue has been fixed in v0.13.0 and is available for Windows and Linux. Please go to [downloads](https://www.usebruno.com/downloads) to get the latest version

Note:
> The latest update, version 0.13.0, is now accessible for Windows and Linux users. Unfortunately, Mac builds are facing a delay due to notarization issues. As of now, the most recent Mac build available is version 0.12.2. The notarization challenges are expected to be resolved by September 15th, 2023.

**Comment by mschojoh** [comment]
> @mschojoh @Nosceteipsum @ace90210 This issue has been fixed in v0.13.0 and is available for Windows and Linux. Please go to [downloads](https://www.usebruno.com/downloads) to get the latest version
> 
> Click on the gear icon on the bottom left to open the preferences window where you can disable SSL verification
> 
> Note:
> 
> > The latest update, version 0.13.0, is now accessible for Windows and Linux users. Unfortunately, Mac builds are facing a delay due to notarization issues. As of now, the most recent Mac build available is version 0.12.2. The notarization challenges are expected to be resolved by September 15th, 2023.

when i download the new version for windows it says it is still verison 0.12.2 and i cannot find the pereference to disable ssl, but the file name says 0.13.1

**Comment by helloanoop** [comment]
@mschojoh The Gear Icon is in the left side corner. 
You should see the preferences modal upon clicking it.

![image](https://github.com/usebruno/bruno/assets/9350733/6c156c1b-c73b-4422-a8a2-2062a20eeb7e)

**Comment by mschojoh** [comment]
Yes, but it seems that it is still version 0.12.2 behind the 0.13.1 file as it shows version 0.12.2 within the gui and it has no gear.Am 01.09.2023 um 09:08 schrieb Anoop M D ***@***.***>:﻿
@mschojoh The Gear Icon is in the left side corner.
You should see the preferences modal upon clicking it.

**Comment by helloanoop** [comment]
Ah! Got the issue. Please standby, I am releasing a patch version.

**Comment by helloanoop** [comment]
@mschojoh I have released a patch version `0.13.2` Can you install the latest version and check?

**Comment by kauhat** [comment]
My requests are working now, thanks for the update! It was perfect timing for me, as I only found this tool yesterday after searching for an alternative to my previous alternative for Postman.

It seem like most REST testing tools are destined to become cloud services, in the same way to crustaceans convergently evolving into a crab-like form.

**Comment by mschojoh** [comment]
now its the correct versions, thanks a lot.

> @mschojoh I have released a patch version `0.13.2` Can you install the latest version and check?

it works, thank you for your investigations!

**Comment by helloanoop** [comment]
@kauhat In earlier days I thought Brouno could offer a cloud based service. But once I envisioned the benefits of a local file based approach, there was no going back.

I wrote about that experience here https://www.usebruno.com/blog/the-saas-dilemma

**Comment by Nosceteipsum** [comment]
Thank you, it works perfectly.
