### ISSUE TITLE
Code signing certificate on Windows .exe expired for v1.10.0 release

### ISSUE THREAD

**Issue by SotoDucani** [usebruno/bruno#1696]
Just started taking a look at this as a alternative to Postman and I love it so far, kudos!

Dropping this as I haven't seen it in a issue yet, it looks like the code signing certificate used for the v1.10.0 windows executable just recently expired on 2/24/2024. This causes a fun little "Windows has protected your PC" message to appear when launching the application.

![image](https://github.com/usebruno/bruno/assets/8963875/384c98b6-8c6d-4969-a4ff-21e5b5363b10)

**Comment by helloanoop** [comment]
Thank you.
I have started the process of getting a new code signing certificate.
This is expected to take a few days for the pre configured hardware token signing device to arrive.
Hoping to get this completed soon.

**Comment by jwbowen** [comment]
I also hit this. It looks like the 1.12.1 release is signed with a current cert, but the downloads page still points at 1.11.0, which has the outdated cert.

**Comment by SpoonOfDoom** [comment]
1.12.2 still has an expired certificate:
![grafik](https://github.com/usebruno/bruno/assets/649040/df96ce6d-4835-4b5d-9b30-ad32461c9f49)

**Comment by kovacsdongo** [comment]
i have still gotton this firewall error with 1.12.3 as well

**Comment by vholmer** [comment]
I'm still seeing this with 1.12.3

**Comment by helloanoop** [comment]
This issue has been resolved in the latest release of v1.13.0
You can download the latest version from: https://www.usebruno.com/downloads

Please reopen the ticket if you are still facing issues.
