### ISSUE TITLE
Oauth2: Support PKCE

### ISSUE THREAD

**Issue by clocklear** [usebruno/bruno#1703]
Hello!

The new OAuth 2.0 features introduced in #1654 are awesome, but they don't support PKCE flows.  Adding this functionality is critical to the usability of OAuth 2.0 features within Bruno.

https://oauth.net/2/pkce/
https://blog.postman.com/pkce-oauth-how-to/

Thanks!

(This is for Bruno v1.10.0)

**Comment by sjw1066** [comment]
Agreed - PKCE is _the_ way for mobile applications, so support is really important.

**Comment by elovelan** [comment]
PKCE is working great! Can this be closed?

**Comment by clocklear** [comment]
Yep! Have used it myself multiple times; forgot this was open tbh.
