### ISSUE TITLE
[Bug] Corner not clickable in request tab

### ISSUE THREAD

**Issue by lucasmbrute2** [usebruno/bruno#1715]
After https://github.com/usebruno/bruno/pull/1649 i noticed that is not possible to close the tab clicking in corners or even out of the text, wich is not true for select (focus) the request tab. It seems a CSS problem that impacts UX.

![not-clickable-corner](https://github.com/usebruno/bruno/assets/68877260/b4d1f5d4-b79b-46a1-8116-a834aad3ee4e)

**Comment by helloanoop** [comment]
Hey @lucasmbrute2 !

Thanks for taking time to work on this PR.
The functionality to close the tab on middle-click of mouse is already available in the latest versions of Bruno.

Increasing the clickable area in the request tabs could have the unintended consequence of someone attempting to click on the tab to open it, but instead closing the tab.
