### ISSUE TITLE
brackets [ ] %5B %5D in URL not working

### ISSUE THREAD

**Issue by atpanos** [usebruno/bruno#1717]
When trying to send a request with brackets [ ] in the URL, i get an error:

`Invalid character found in the request target https://host/api/test?config[field]=testfield ... The valid characters are defined in RFC 7230 and RFC 3986`

Trying to use the encoded URL does not result in an error, but the parameter are somehow ignored.
encoded: `https://host/api/test?config%5Bfield%5D=testfield`

In Postman and IntelliJ HTTP Client its working. Any idea?

**Comment by Alge97** [comment]
Hi
I had the exact same error when using path parameters in requests.
With the latest version my problem has been solved.
Maybe you can try again 😀

**Comment by atpanos** [comment]
seems to work now
