### ISSUE TITLE
Using quotes in queries breaks code generation

### ISSUE THREAD

**Issue by captn3m0** [usebruno/bruno#1732]
## Steps to Reproduce

1. Create new Request
2. Any name
3. URL=`https://httpbin.org/anything?x=" "`
4. Trigger request. Request imports successfully, and works fine.
5. Generate Code

Error generating code snippet.

**Comment by helloanoop** [comment]
Issue has been fixed.
This will go out in the `1.13.1` release.

Please follow us on [Discord](https://discord.com/invite/KgcZUncpjq) / [Twitter](https://twitter.com/use_bruno) to stay notified on the releases.
