### ISSUE TITLE
Importing without selecting a location doesn't show an error

### ISSUE THREAD

**Issue by bannmann** [usebruno/bruno#1738]
### Problem
After I selected an Insomnia file for importing, a dialog appeared that displayed the name of the collection and a box labelled "Location" with a "Browse" link beneath. I suspected the latter would be needed so that Bruno knows where to store the newly created .bru files, but I wasn't entirely sure. So I decided to just leave it empty and clicked the "Import" button.

Bruno said the import was successful, but nothing else happened:
- the new collection did not appear in the sidebar
- If Bruno created any .bru files anywhere on my disk, I didn't find them. (I checked the directory of the import file and the Bruno program directory.)

When I repeated the process and selected a location, everything worked as expected.

### Suggestion
The location field should be clearly marked as being required and the "Import" button should be grayed out until a location was selected.

### Notes
Tested with Bruno v1.10.0 on Windows.

**Comment by anusree-bruno** [comment]
This issue has been fixed. App now shows the _Location is required_ message if location is not added.

I am closing this issue
