### ISSUE TITLE
Helping With The Website

### ISSUE THREAD

**Issue by TomGranot** [usebruno/bruno#1748]
I run a technical product marketing consultancy.

Would be happy to contribute to the comparison tables & articles between you guys and every other API client on the planet, as well as suggest a few use case pages that might get you to win in f2f combat with postman. 

Not sure how to go about adding pages for the site, but if you guys are interested in help we're game:
tom@granot.io

**Comment by helloanoop** [comment]
Thanks for reaching out, @TomGranot!

We're currently in the process of revamping our website and will definitely reach out if we need any assistance.
