### ISSUE TITLE
Wrong screenshot in documentation

### ISSUE THREAD

**Issue by yari-may** [usebruno/bruno#175]
Hi everyone,

just started using Bruno and I really like it! I just noticed a small issue in the documentation (I would have fix it myself but it is in the screenshot). In chapter Testing -> Get Started the code in the screenshot seems wrong. If you tun this you get "res.getData() is not a function". The code snippet is anyhow correct using "res.getBody()" even if I am not sure if this call is really needed there. I left here a screenshot, I hope this is helpful.
![image](https://github.com/usebruno/bruno/assets/7069135/299d33c4-040d-47eb-992c-3aa0e2ac7730)
Cheers,
Yari

**Comment by ganesh-bruno** [comment]
Hi @yari-may,

Thanks for reporting this issue.

As you mentioned, `res.getBody()` is working fine because it's currently supported, whereas previously it was `res.getData()`. The example shown in the image is incorrect, and I’m currently working on a fix for this.

**Comment by ganesh-bruno** [comment]
Hey @yari-may,

I’m closing this issue now as it has been resolved. You can find more details [here](https://docs.usebruno.com/testing/introduction).

<img width="723" alt="testing-introduction" src="https://github.com/user-attachments/assets/4718db3c-ad50-4b1f-af50-7b0cc4f6246d">
