### ISSUE TITLE
Unable to generate code

### ISSUE THREAD

**Issue by steveicode** [usebruno/bruno#1750]
Unable to generate the code if the space in the query parameter isn't encoded.

For example, 

![image](https://github.com/usebruno/bruno/assets/68050102/d7a64274-9df4-4114-918c-cd438b56029f)

![1](https://github.com/usebruno/bruno/assets/68050102/91c85bd1-a02f-429b-ada5-222b9c479bac)

**Comment by merc1er** [comment]
Are you able to share your request to reproduce?

**Comment by steveicode** [comment]
```
curl --location 'https://130a4881ed014d83a3e13a2c332cb5a2.api.mockbin.io?contain=Middle%20of'
```
For instance, when I enter "Middle%20of" in the query-value of this request, it functions properly. However, problems arise if I input "Middle of".

**Comment by Liamhhhhh** [comment]
You can try [Apidog](https://apidog.com/), which also serves as a replacement for Postman and is very useful for generating code.

**Comment by helloanoop** [comment]
Issue has been fixed.
This will go out in the `1.13.0` release.

Please follow us on [Discord](https://discord.com/invite/KgcZUncpjq) / [Twitter](https://twitter.com/use_bruno) to stay notified on the releases.
