### ISSUE TITLE
BigInteger on response 

### ISSUE THREAD

**Issue by MeskaKeyne** [usebruno/bruno#1753]
When recieve response , BigInteger is not parse correctly
thanks for help :-)
EDIT: sorry for my mistake on title

**Comment by Its-treason** [comment]
We recently merged a fix for BigInt that is not yet released: #1710 that might fix your issue. You can either wait for the next Bruno release, clone the repository and start Bruno locally or [try a prebuild binary from my fork](https://github.com/Its-treason/bruno/releases/tag/nightly) it includes the BigInt fix.

**Comment by MeskaKeyne** [comment]
Many thanks

**Comment by Raffine64** [comment]
json response:
{
  "id": 1.0000000000001147e+21
}

still same issue, tested with Bruno v1.17.0

**Comment by azzamsa** [comment]
@Its-treason I think it is not included in the latest release. Or Am I missing something?
Bruno still does not get it right.

Bruno:

![image](https://github.com/user-attachments/assets/9c8fdc90-e830-4f44-a94d-3c07c54c1cec)


Insomnia

![image](https://github.com/user-attachments/assets/620f919a-60d7-4ff7-a1d0-2ffe64b0d285)

**Comment by Raffine64** [comment]
@azzamsa, problem still remains, tested with Bruno v1.22.0:

{
    "id": 1.0000000000000325e+21,

@Its-treason can you see that it's getting fixed ?

It's very annoying in our day-to-day operations.

**Comment by Its-treason** [comment]
> @azzamsa, problem still remains, tested with Bruno v1.22.0:
> 
> { "id": 1.0000000000000325e+21,
> 
> @Its-treason can you see that it's getting fixed ?
> 
> It's very annoying in our day-to-day operations.

Yes, is just looked into it and found a fix. I need to do some testing and will submit a PR later

**Comment by helloanoop** [comment]
PR https://github.com/usebruno/bruno/pull/2773 has been merged, This will go out in the v1.27.0 release.

**Comment by Raffine64** [comment]
Hello,

I still have the same issue in responses.

tested with Bruno 1.30.1
{
  "id": 1.0000000000000104e+21,
...
}

**Comment by Raffine64** [comment]
thanks for your answer @Its-treason.

but the problem is that now my responses are not pretty printed (not formatted).
