### ISSUE TITLE
Extra quotes added when request body is a simple text as JSON

### ISSUE THREAD

**Issue by 0y0y** [usebruno/bruno#1755]
When I pass a text in the request body as JSON, Bruno add extra quotes.

Text is set (without quotes) in request body, the timeline shows "Text" : 
`> data "Text"`

The server received  the string but with extra quotes : ""Text""

Bruno should  send the string Text without quotes : 
`> data Text`

**Comment by gms8994** [comment]
Just a note that this does *not* happen inside the GUI when using a JSON request and plain text, but does happen on the CLI. IMHO, this is definitely inconsistent and should be fixed.
