### ISSUE TITLE
.env file not recognized

### ISSUE THREAD

**Issue by NiklasBr** [usebruno/bruno#1757]
I'm unable to load variables via .env file configuration, it seems `REST_API_PASSWORD` does not resolve to anything. What am I doing wrong here?

At project root:

`.env` file with content:
```env
REST_API_PASSWORD=abc123456789123
```

`data/api-configurations/environments/dev.bru` file with contents:
```bru
vars {
  REST_API_PASSWORD: {{process.env.REST_API_PASSWORD}}
}
```

Collection file `data/api-configurations/articles.bru`:
```bru
meta {
  name: articles
  type: http
  seq: 1
}

get {
  url: {{domain}}/{{api_base}}/{{api_version}}/articles?lastModified=2023-09-21T10:12:24Z&pageSize=25
  body: none
  auth: basic
}

query {
  lastModified: 2023-11-21T10:12:24Z
  pageSize: 25
}

auth:basic {
  username: api_user
  password: {{REST_API_PASSWORD}}
}

vars:pre-request {
  domain: https://internal.domain
  api_base: api
  api_version: v1
}
```

And the final file `data/api-configurations/bruno.json`
```json
{
  "version": "1",
  "name": "TEST - LOCAL DEV",
  "type": "collection",
  "ignore": [
    "node_modules",
    ".git"
  ]
}
```

**Comment by tlaloc911** [comment]
Have you tried with quoted strings? `REST_API_PASSWORD="abc123456789123"` instead of `REST_API_PASSWORD=abc123456789123`
