### ISSUE TITLE
Running Request with return code 400 don't run tests

### ISSUE THREAD

**Issue by mirkogolze** [usebruno/bruno#177]
When I have a request answering with return code 400, the request fails an no tests run.
Now when my test case is exactly this, I can't check the content of the response returned by the server.
E.g. to check the delivered error codes.

So every running request should invoke the assertions and tests and post response scripts.

**Comment by helloanoop** [comment]
@mirkogolze This issue has been fixed in v0.13.0 and is available for Windows and Linux

Note:
> The latest update, version 0.13.0, is now accessible for Windows and Linux users. Unfortunately, Mac builds are facing a delay due to notarization issues. As of now, the most recent Mac build available is version 0.12.2. The notarization challenges are expected to be resolved by September 15th, 2023.

**Comment by mirkogolze** [comment]
Hi,

I tried that out. Now the tests are running correct. But the following requests are not executed.
I have a folder with four requests and the third is delivering a 400. The test is executed, but the forth request does not run anymore. When I change the sequence of the requests so that the 400 request is the last one, the all tests run.

**Comment by helloanoop** [comment]
Thanks @mirkogolze 
I just fixed this issue and a patch fix has been released `0.13.1`

Please download the latest version

**Comment by mirkogolze** [comment]
Thank. It is working now.
