### ISSUE TITLE
Microsoft Defender Smart Screen

### ISSUE THREAD

**Issue by zandercodemonkey** [usebruno/bruno#1782]
Blocking current download for windows. 
Latest Version.

**Comment by tuyen-at-work** [comment]
Same issue with https://github.com/usebruno/bruno/issues/1678 and https://github.com/usebruno/bruno/issues/1696.

Happen for both 1.10 and 1.11.

cc @helloanoop

**Comment by spawnrider** [comment]
Hi, 
Same issue for 1.12.1 here

**Comment by riesinger** [comment]
Interesting, according to @jwbowen, 1.12.1 should have the new certificate: https://github.com/usebruno/bruno/issues/1696#issuecomment-2008137930

**Comment by oliverdoesereck** [comment]
Still happening for 1.12.3. Defender also enjoys blocking script files now too

**Comment by helloanoop** [comment]
This issue has been resolved in the latest release of v1.13.0
You can download the latest version from: https://www.usebruno.com/downloads

Please reopen the ticket if you are still facing issues.

**Comment by dbacvetkov** [comment]
Same issue with 2.2.0

**Comment by anusree-bruno** [comment]
@dbacvetkov Please see https://github.com/usebruno/bruno/issues/4283
