### ISSUE TITLE
BUG: Bruno inserting right square bracket into request body.

### ISSUE THREAD

**Issue by piyh** [usebruno/bruno#1788]
Given this .bru file

```
meta {
  name: InsertedCharacter
  type: http
  seq: 34
}

post {
  url: test
  body: json
  auth: none
}

headers {
}

body:json {
  {
    "zyx": "1",
    "foo": "}}"
  }
}

script:post-response {
  bru.setEnvVar("approval_id", res.body.approvalRequestId);
}
```

Run the request. Navigate to Bruno timeline.  
<img width="1164" alt="image" src="https://github.com/usebruno/bruno/assets/10518137/3e1ee042-bd8e-47fa-a279-f96069f140c3">

Look at `data {"zyx":"1","foo":"]}}"}`.  The value of `foo` was mutated by Bruno into `]}}`.  It should be `}}`.

**Comment by j4ln** [comment]
Hey @piyh. I'm unable to reproduce this issue with your .bru file. Are you using the latest version of bruno? It looks like in [v1.7.0](https://github.com/usebruno/bruno/releases/tag/v1.7.0) a fix was made for this (https://github.com/usebruno/bruno/pull/1154).

**Comment by piyh** [comment]
Unable to recreate after updating verison
