### ISSUE TITLE
Basic and Bearer Token is not exported with gerate code

### ISSUE THREAD

**Issue by leoferreiralima** [usebruno/bruno#1791]
When click the generate code button the Authorization headers with token (Bearer or Basic) is not exported

![bruno-auth-token](https://github.com/usebruno/bruno/assets/36305985/8f28cbc5-4aee-4430-83f0-2bcf2cdffc06)

**Comment by RRusu66** [comment]
+1, please fix this

**Comment by Moribund7** [comment]
Do you have any updates in this topic?

**Comment by helloanoop** [comment]
The PR for this issue has been merged.
This is set to go out in the upcoming `v1.20.0` release.
