### ISSUE TITLE
Visiting a bru file with only meta definition

### ISSUE THREAD

**Issue by gmesml** [usebruno/bruno#1813]
When visiting a .bru file on Bruno Client, considering the file content only has meta part defined and nothing else. Bruno Client shows a blank page (crashes) and one must perform Force Quit to reopen the client.

**Comment by sanjai0py** [comment]
Closing this issue as it is not reproducible in the latest version [v1.20.2](https://github.com/usebruno/bruno/releases/tag/v1.20.2) of Bruno. 

https://github.com/usebruno/bruno/assets/84461672/f444b9c2-4ebe-4136-9dcc-7e8c3e04779e
