### ISSUE TITLE
Environments not being loaded on the second run after being imported

### ISSUE THREAD

**Issue by CptOrange16** [usebruno/bruno#1816]
Hello

Yesterday I imported a big collection from postman with 4 different environments and everything worked fine after importing.
Today when i started bruno the collections are visible but the environments are not showing, even though the .bru files are there.

I'm using linux debian.

Not sure what info can help you debug the issue but i can provide whatever you need

**Comment by bpoulaindev** [comment]
Hi, there are no environments at all in the top right corner dropdown ? And your environments with a .bru extension are placed in the environment folder at the right location ?

**Comment by CptOrange16** [comment]
Sorry i created a duplicated issue, for some reason when i searched i could not find it a first.

The issue was the same mentioned [here](https://github.com/usebruno/bruno/issues/1623), which are the spaces in the names of the .bru files for the environments. After removing the spaces everything is ok.

**Comment by CptOrange16** [comment]
Sorry i created a duplicated issue, for some reason when i searched i could not find it a first.

The issue was the same mentioned [here](https://github.com/usebruno/bruno/issues/1623), which are the spaces in the names of the .bru files for the environments. After removing the spaces everything is ok.
