### ISSUE TITLE
Using system theme in Windows dark mode could make the text theme still be in white mode

### ISSUE THREAD

**Issue by Feldrise** [usebruno/bruno#1822]
I've encountered a minor yet persistent issue related to the application's theme compatibility with Windows' dark mode.

Specifically, when Windows is set to dark mode, the Bruno interface successfully adapts to this setting with a dark background. Unfortunately, the text color does not adjust accordingly and remains in a light color scheme, which compromises readability and overall user experience. This issue appears to be consistent across multiple Windows machines, as confirmed through testing with several of my colleagues' computers. This suggests that the problem might be unique to the Windows version of Bruno.

For your reference, I've documented this issue with a screenshot, available here:
![Screenshot 2024-03-15 090746](https://github.com/usebruno/bruno/assets/15325126/a5b23644-6dd1-41a1-87ea-0fc2765e98bf).

I have already developed a fix for this issue and plan to submit a pull request (PR) very soon. This contribution is intended to enhance the Bruno experience for users who prefer dark mode on Windows.

**Comment by devon-wolf** [comment]
I can confirm this happens on Mac and Linux (Pop OS) machines as well when the theme is 'system'

**Comment by helloanoop** [comment]
PR Merged. Will be shipped in next outgoing release (in the next 2 days)
