### ISSUE TITLE
Clicking a link in a Request doc opens the link in an uncloseable window on Mac (Apple silicon) v1.11.0

### ISSUE THREAD

**Issue by braveterry** [usebruno/bruno#1825]
Version: v1.11.0
MacOS Sonoma 14.4 (23E214) running on Apple Silicon

* * *

Steps to reproduce.

1. Create a link in a Request doc:
    ![image](https://github.com/usebruno/bruno/assets/527650/80f2558a-dccc-4a66-af61-b0aa6de93abe)
2. Click the link:
    ![image](https://github.com/usebruno/bruno/assets/527650/7175ddfc-ba76-49e5-b2d2-d5e5a742afc7)
3. Browser view that opens is uncloseable.  (I have to force quit.)
    ![image](https://github.com/usebruno/bruno/assets/527650/10d3fb33-79b4-41b0-8b9d-1e17c02d3101)

If I'm doing something wrong, please let me know.

**Comment by sanjai0py** [comment]
Closing this as the issue has been fixed in the latest version of Bruno! Please use Bruno [v1.20.2](https://github.com/usebruno/bruno/releases/tag/v1.20.2)
