### ISSUE TITLE
[Bug] Prettify not working if JSON body contains comments

### ISSUE THREAD

**Issue by asonkeri** [usebruno/bruno#1830]
Similarly to #1553 prettifying the JSON body fails if the body contains comments:
![image](https://github.com/usebruno/bruno/assets/19153764/fb84324c-e99c-4034-b5be-935263508674)

Tested on v1.11.0 on Windows 11

**Comment by UlrichEckhardt** [comment]
Formally, comments are not part of [JSON](https://www.json.org/json-en.html) and many tools will tell you about that, too.

**Comment by asonkeri** [comment]
As documented in #396, Bruno supports JSON with comments in the request body whether they are part of JSON spec or not.

**Comment by helloanoop** [comment]
This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
