### ISSUE TITLE
[Enhancement] Adding Tool-tips on icons

### ISSUE THREAD

**Issue by myNameArnav** [usebruno/bruno#1832]
![image](https://github.com/usebruno/bruno/assets/35961071/1503efdb-d3b1-4ad0-8a83-ea99438f3ed5)

Currently there is tool-tip on the save request icon.
> ![image](https://github.com/usebruno/bruno/assets/35961071/a8744e06-5e7e-4259-a6c4-ccf0040e84b5)

But there aren't any on the other icons
> ![image](https://github.com/usebruno/bruno/assets/35961071/f826b686-8967-48f4-8498-48d1fff4ca61)
> ![image](https://github.com/usebruno/bruno/assets/35961071/29706961-8be4-4942-bf88-fee78b557ae2)

Adding tool-tips greatly enhances the experience as one doesn't have to press to see what does what do.

**Comment by J-Swift** [comment]
It seems like the referenced issue only added tooltips to _one_ area. I think the request overall should be that icons _in general_ should always have tooltips, so likely there should be an icon component that forces specifying tooltip-text.

I dont see https://github.com/usebruno/bruno/pull/1888 in v1.17.0 to confirm, but it appears to only address one of the two areas shown above.
