### ISSUE TITLE
[Bug] Large integers are represented in scientific notation

### ISSUE THREAD

**Issue by savchenko** [usebruno/bruno#1834]
## Steps to reproduce

1. Issue `GET` to an endpoint that returns sufficiently large integer.
2. Observe something like `8.578104535446252e+37` in the output window.

## Expected result

1. Output window renders `85781045354462519659203341338323982205` as it is.

**Comment by sanjai0py** [comment]
Closing this as the issue has already been resolved. Please use the latest version of bruno [v1.20.2](https://github.com/usebruno/bruno/releases/tag/v1.20.2).
