### ISSUE TITLE
Highlighted text is illegible when choosing System theme

### ISSUE THREAD

**Issue by perdomon** [usebruno/bruno#1846]
If my macOS system theme is dark and I've selected the Bruno Theme option 'System,' highlighted text is illegible:

<img width="443" alt="Screenshot 2024-03-18 at 9 46 00 PM" src="https://github.com/usebruno/bruno/assets/101995665/c08df271-7980-470e-87ac-a9c20a695e36">

This issue is resolved by selecting either the 'Light' or 'Dark' Theme option. 

I have not tested highlighted text legibility with macOS light mode and any of the Bruno themes. 

macOS Sonoma 14.4
Bruno 1.6.1

**Comment by helloanoop** [comment]
@sanjai0py Can you take this up on high priority. This should be a small fix.

**Comment by sanjai0py** [comment]
On it @helloanoop!

**Comment by afrianjunior** [comment]
This feature has been released, You can close this issue.
