### ISSUE TITLE
Request Code Generator Doesn't Work Anymore After v1.12.1 Upgrade

### ISSUE THREAD

**Issue by Arnaldino** [usebruno/bruno#1853]
It seems I can not generate code from requests after upgrading to latest v1.12.1.

Setup:

Mac M1
Bruno v1.12.1
Clean Install.

<img width="788" alt="73387" src="https://github.com/usebruno/bruno/assets/39277295/d2014ace-b54a-4924-80ed-83424ebc39e6">

**Comment by rsau** [comment]
Same issue

M1
1.12.1

Error in console

![image](https://github.com/usebruno/bruno/assets/29110027/213e907b-4821-41e8-88cd-e75d5294a06c)

**Comment by oklaiss** [comment]
Same issue here

Intel Mac
v1.12.1

Same console error as @rsau

**Comment by Arnaldino** [comment]
Solved in latest 1.12.2. update. Closing this.
