### ISSUE TITLE
[Bug] Postman collection fails to import

### ISSUE THREAD

**Issue by kaankeskin** [usebruno/bruno#1855]
# Steps to reproduce
- Import a postman collection
- Importing fails without showing an error to the user

# Expected result
- Import should be successfull

Bruno version: 1.12.1
electron: 21.1.1
chrome: 106.0.5249.103
node: 16.16.0
v8: 10.6.194.17-electron.0

I also got this in the console in developer tools:
![image](https://github.com/usebruno/bruno/assets/11148471/04e584a8-8a4e-494c-9067-baf978b16321)

I suspect it is because of a typo in:
https://github.com/usebruno/bruno/blob/2b0ad29b9377ea3c2b9d7ecca190fe3ca137b7da/packages/bruno-app/src/components/Welcome/index.js#L32

**Comment by JSSAggie** [comment]
Moved back to 1.11.0 and import works now

**Comment by kaankeskin** [comment]
I upgraded to v1.12.2 and still does not work

**Comment by chw-webops** [comment]
Same issue on latest. But v1.11.0 works.

**Comment by danutzcodrescu** [comment]
Same issue for me. On 1.12.2 I cannot import from insomnia because of this error

**Comment by philcruz** [comment]
Same for me on v1.12.2. I see the same "enableTranslation is not defined" error in the devTools console.

**Comment by jpblair** [comment]
+1 on Apple Silicon, worked on reverting to 1.11.0.

**Comment by amalrajvinoth** [comment]
I see the [fix](https://github.com/usebruno/bruno/pull/1867) is part of the release [1.12.2](https://github.com/usebruno/bruno/releases/tag/v1.12.2), but why it is not working 🤔 ?

**Comment by uranderu** [comment]
> I see the [fix](https://github.com/usebruno/bruno/pull/1867) is part of the release [1.12.2](https://github.com/usebruno/bruno/releases/tag/v1.12.2), but why it is not working 🤔 ?

Yeah I'm having the same issues, I've left a comment on the PR.

**Comment by Its-treason** [comment]
> > I see the [fix](https://github.com/usebruno/bruno/pull/1867) is part of the release [1.12.2](https://github.com/usebruno/bruno/releases/tag/v1.12.2), but why it is not working 🤔 ?
> 
> Yeah I'm having the same issues, I've left a comment on the PR.

I think it's a problem with the 1.12.2 build Anoop released, might be caused by the merge with golden Edition. But not sure, it's hard to debug without sourcemaps.

**Comment by bpoulaindev** [comment]
> > > I see the [fix](https://github.com/usebruno/bruno/pull/1867) is part of the release [1.12.2](https://github.com/usebruno/bruno/releases/tag/v1.12.2), but why it is not working 🤔 ?
> > 
> > 
> > Yeah I'm having the same issues, I've left a comment on the PR.
> 
> I think it's a problem with the 1.12.2 build Anoop released, might be caused by the merge with golden Edition, because it works when starting Bruno locally. But not sure, it's hard to debug without sourcemaps.

As @its-treason said, can't reproduce it locally, can't find "enableTranslation" within my file, this must be a cache issue with the build

**Comment by josejames** [comment]
+1 and as people have said Installing v1.11.0 on Apple Silicon resolve the issue

**Comment by helloanoop** [comment]
Just released v1.12.3 with fixes by @bpoulaindev

**Comment by cjchand** [comment]
@helloanoop, just an FYI that #1855 isn't in the release notes for 1.12.3. Thanks!
