### ISSUE TITLE
Show tooltip on hover over icon buttons

### ISSUE THREAD

**Issue by goto-dev-null** [usebruno/bruno#1860]
It's not horrendous but the feeling of having to click an icon button to know what it actually does makes the experience feel unpolished.

Some of them have tooltips, like Save shown below, but many others do not - the Run, View, or Gear.

![image](https://github.com/usebruno/bruno/assets/2322497/a3c9075e-5b2d-4f8c-bd2e-d6c3a96cdd73)

Same with bottom left: Preferences, Cookies, Support, and Notifications. Not sure how many other places might benefit from a tooltip.

I would hope that this is not a huge effort but I have not looked into Bruno's guts so I cannot know how big of an ask it is.

**Comment by Its-treason** [comment]
Already has been request here: https://github.com/usebruno/bruno/issues/1832 nevertheless I agree, tooltip would be very helpful
