### ISSUE TITLE
Unable to get local issuer certificate when activating Bruno Golden Edition

### ISSUE THREAD

**Issue by hanneswidrig** [usebruno/bruno#1870]
Hello,

I'm trying to activate Bruno Golden Edition, however I met with this error. My computer is behind a ZScaler VPN. I tried adding a custom CA certificate in the setting but doesn't seem to help either. I'm wondering if I could use a tool like `keytool` to import the ZScaler certificate. I've done that before for some applications.

<img width="350" alt="image" src="https://github.com/usebruno/bruno/assets/3399497/66eae66a-e3f8-4bce-88bb-3e83e1dfa113">
 

<img width="371" alt="image" src="https://github.com/usebruno/bruno/assets/3399497/7ac5bb76-c72d-4023-b4ca-47b69898f379">

**Comment by sjw1066** [comment]
Same here.  Also behind ZScaler, though I often wish I could rip that piece of **** out with hot tongs.
