### ISSUE TITLE
Could not see Bru file in collection

### ISSUE THREAD

**Issue by varshabandgar** [usebruno/bruno#1877]
Even afetr adding new file, its not showing under collection in Bruno aap

**Comment by foliveiracamara** [comment]
Same with me, cant import or open files with .bru extension

**Comment by AngelaSYuan** [comment]
Hi! I'm curious how I can replicate this issue?

**Comment by KilFer** [comment]
To be honest, I'm not sure how if it's not a common bug. Maybe it's easy to share some logs?

In a fresh instalation (both Snap & .deb installation on Kubuntu) create a new collection. After that, create a new request. The request won't be opened on the app and won't be shown on the collection list at the sidebar; but the file will be created on the folder on the device. Same for importing collections: the Requests won't be shown after importing even when they exists on the folder.

**Comment by foliveiracamara** [comment]
Guys, as I'm new to Bruno, my problem was very simple to solve with some knowledge of the tool. All i had to do was add the "bruno.json" file to be able to import the .bru files into bruno.

**Comment by LeonardoDaLuz** [comment]
same here
![image](https://github.com/usebruno/bruno/assets/80224694/a248241b-0d9e-42d8-9042-236a4ae24281)

**Comment by LeonardoDaLuz** [comment]
Solved using HTTPie:
https://github.com/httpie/desktop#linux

**Comment by KilFer** [comment]
It's not a solution to use a rival app, you know. :P 

Needless to say, the bug has fixed miraculously for me. I tried reinstalling, rebooting the system, anything... But today has started working without any change. That's strange, and this will be a bug pretty difficult to find if anything.

**Comment by marcelopio** [comment]
Just installed Bruno to try it and have the same problem.

I am also um Kubuntu 22.04

**Comment by marcelopio** [comment]
I may have found the problem, for me when I opened through terminal it was throwing a lot of:
```inotify_init failed: Too many open files```

So I just did:
```echo 256 | sudo tee /proc/sys/fs/inotify/max_user_instances```

**Comment by koriit-kontakt** [comment]
This was actually my first experience with Bruno. It saddened me beyond measure and almost made me drop Bruno. 

Fortunately for me, I persevered, opened Bruno with the terminal, and found the same logs.

Ultimately, the problem lies in the system settings (Ubuntu here), but Bruno could communicate it better in UI.

As described [here](https://www.suse.com/support/kb/doc/?id=000020048), adding this to `/etc/sysctl.conf` finally permanently fixed the problem for me:
```
fs.inotify.max_user_instances=8192
fs.inotify.max_user_watches=524288
```

**Comment by drubb** [comment]
Same problem or me, with Bruno 1.33 (AppImage):

When I start Bruno, collections are listed on the left side, but sometimes empty. The only way to fix this is closing the collections and reopening them again. On the command line, there are no inotify errors, as I have the recommended settings already.

**Comment by hairullana** [comment]
[I have same issue, it because I import collection from postman export
but on path params, there are params name with space

before is: "laporan id" and "kelompok pertanyaan id" and after that I change to "laporan_id" and "kelompok_pertanyaan_id" (replace space with underscore)
and then it showing

you can change it from location with file with extension .bru

after that close and re open the bruno app

![image](https://github.com/user-attachments/assets/50c4a963-9ef9-4a50-9dcf-57ff71d53df3)
](https://github.com/usebruno/bruno/issues/1771#issuecomment-2415738279)

**Comment by NicoCaldo** [comment]
> This was actually my first experience with Bruno. It saddened me beyond measure and almost made me drop Bruno.
> 
> Fortunately for me, I persevered, opened Bruno with the terminal, and found the same logs.
> 
> Ultimately, the problem lies in the system settings (Ubuntu here), but Bruno could communicate it better in UI.
> 
> As described [here](https://www.suse.com/support/kb/doc/?id=000020048), adding this to `/etc/sysctl.conf` finally permanently fixed the problem for me:
> 
> ```
> fs.inotify.max_user_instances=8192
> fs.inotify.max_user_watches=524288
> ```

I can confirm it fixed the issue for me as well

**Comment by asirota** [comment]
On windows how does one do that?

**Comment by NicoCaldo** [comment]
> > This was actually my first experience with Bruno. It saddened me beyond measure and almost made me drop Bruno.
> > Fortunately for me, I persevered, opened Bruno with the terminal, and found the same logs.
> > Ultimately, the problem lies in the system settings (Ubuntu here), but Bruno could communicate it better in UI.
> > As described [here](https://www.suse.com/support/kb/doc/?id=000020048), adding this to `/etc/sysctl.conf` finally permanently fixed the problem for me:
> > ```
> > fs.inotify.max_user_instances=8192
> > fs.inotify.max_user_watches=524288
> > ```
> 
> I can confirm it fixed the issue for me as well

EDIT: again when opening Bruno no saved requests of my collection are loaded.

LOG
```
nicola@Ubuntu:~$ bruno
Preferences file is located at: /home/nicola/snap/bruno/58/.config/bruno/preferences.json

(bruno:3506): Gtk-WARNING **: 14:24:17.965: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(bruno:3506): Gtk-WARNING **: 14:24:17.974: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(bruno:3506): Gtk-WARNING **: 14:24:17.976: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name

(bruno:3506): Gtk-WARNING **: 14:24:20.928: Theme parsing error: gtk-dark.css:1413:23: 'font-feature-settings' is not a valid property name

(bruno:3506): Gtk-WARNING **: 14:24:20.935: Theme parsing error: gtk-dark.css:3286:25: 'font-feature-settings' is not a valid property name

(bruno:3506): Gtk-WARNING **: 14:24:20.936: Theme parsing error: gtk-dark.css:3748:23: 'font-feature-settings' is not a valid property name
[3605:1019/142423.258510:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
[3621:1019/142423.689626:ERROR:command_buffer_proxy_impl.cc(132)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
watcher add: /home/nicola/Documents/Content Bridge/Article Create.bru
watcher add: /home/nicola/Documents/Content Bridge/Check Article.bru
watcher add: /home/nicola/Documents/Content Bridge/Check Website.bru
watcher add: /home/nicola/Documents/Content Bridge/Create Website.bru
watcher add: /home/nicola/Documents/Content Bridge/Delete Website.bru
watcher add: /home/nicola/Documents/Content Bridge/Supabase Websites.bru
watcher add: /home/nicola/Documents/Content Bridge/Website IDs.bru
watcher add: /home/nicola/Documents/Content Bridge/bruno.json
```
![Screenshot from 2024-10-19 14-26-59](https://github.com/user-attachments/assets/ed2526af-299d-4a36-9b24-fd35326d423d)

I think this issue must be re-open
