### ISSUE TITLE
Can not install 1.12 due to firewall

### ISSUE THREAD

**Issue by kovacsdongo** [usebruno/bruno#1878]
I would like to install the latest version, because i have a key for golden , but get a windows popup
"Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk."

**Comment by riesinger** [comment]
This is a duplicate of https://github.com/usebruno/bruno/issues/1696

**Comment by sanjai0py** [comment]
Closing this! Please open a new issue if you still face this issue.

**Comment by kovacsdongo** [comment]
unfortunatelly, i get the same error with: bruno_1.12.3_x64_win, with portable too

**Comment by helloanoop** [comment]
This issue has been resolved in the latest release of v1.13.0
You can download the latest version from: https://www.usebruno.com/downloads

Please reopen the ticket if you are still facing issues.
