### ISSUE TITLE
Cannot update Bruno via flatpak

### ISSUE THREAD

**Issue by yannickincyberatlantis** [usebruno/bruno#1879]
I already had Bruno installed as a flatpak via Flathub and I tried updating it this morning, which fails due to a 404:

```
~ 
❯ flatpak update
Looking for updates…


        ID                          Branch         Op         Remote          Download
 1. [✗] com.usebruno.Bruno          stable         u          flathub         1.0 kB / 106.1 MB

Error: While downloading https://github.com/usebruno/bruno/releases/download/v1.11.0/bruno_1.12.2_x86_64_linux.AppImage: Server returned status 404
Updates complete.
error: There were one or more errors
```

It seems like URL to the latest AppImage is incorrect, the URL should be (I believe):

https://github.com/usebruno/bruno/releases/download/v1.12.2/bruno_1.12.2_x86_64_linux.AppImage

Is it possible to change the download link for a release in the Flathub backend?

**Comment by Abdull** [comment]
@yannickincyberatlantis is right, see [`com.usebruno.Bruno.yml` at `flathub/com.usebruno.Bruno`](https://github.com/flathub/com.usebruno.Bruno/blob/e5e33d30daae1e67fa1be49795ca70886ef1fceb/com.usebruno.Bruno.yml#L33).

Fixing this over there also is a great opportunity to [fix the wrong flathub license issue](https://github.com/flathub/com.usebruno.Bruno/issues/1#issuecomment-1984195610).

**Comment by WendelVolm** [comment]
same issue here

**Comment by gchait** [comment]
can't install :(

**Comment by Donkere-vader** [comment]
It's working for me again (wasn't working yesterday). So give it a try again

**Comment by yannickincyberatlantis** [comment]
Seems to be working for me as well!
