### ISSUE TITLE
Password and credential inputs should use the password type input in html

### ISSUE THREAD

**Issue by evoltafreak** [usebruno/bruno#1886]
Password and credential inputs should use the password type input in html.
They occur in the proxy and the client cert settings.

Before
![image](https://github.com/usebruno/bruno/assets/11610680/b3e936a5-0626-4c2e-8d6f-152b204573cb)

After
![image](https://github.com/usebruno/bruno/assets/11610680/c02d7906-b6ca-4d34-a179-8be33927036f)

**Comment by helloanoop** [comment]
Issue has been fixed.
This will go out in the `1.13.1` release.

Please follow us on [Discord](https://discord.com/invite/KgcZUncpjq) / [Twitter](https://twitter.com/use_bruno) to stay notified on the releases.
