### ISSUE TITLE
Importing PFX in Client Certificates should not require Key File

### ISSUE THREAD

**Issue by kanetik** [usebruno/bruno#1889]
Unless I'm mistaken, a PFX file should work without a key file. However, when I try to import a PFX into a collection in Bruno, with the base URL and cert's password supplied, it fails with a "keyFilePath is a required field" message.

**Comment by kabforks** [comment]
+1

**Comment by gwennael-jean** [comment]
+1

**Comment by gwennael-jean** [comment]
+1

**Comment by samuelbosch** [comment]
+1

**Comment by helloanoop** [comment]
The PR for this has been merged.
This is slated to be released in the upcoming `v1.20.0` release.
