### ISSUE TITLE
Allows header key/value to be empty

### ISSUE THREAD

**Issue by AntoninHuaut** [usebruno/bruno#1898]
I have multiple environments and some need a header key with a header value. But my requests collections are the same. To handle it, all my environments have the header key and the header value as variable, but for the environment or is not useful, these values are empty.  

There are two problems:

- First, we can't save environments variable with an empty string, it's not persistent
- Second, I can't send request with empty header name: "Error invoking remote method 'send-http-request': Error: header name must be a non-empty string". It is possible to make this check optional or be configurable to be skipped.

Using Bruno v1.11.0

**Comment by helloanoop** [comment]
Thanks for the PR @AntoninHuaut !

This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
