### ISSUE TITLE
Unable to rename folders

### ISSUE THREAD

**Issue by jcbbs** [usebruno/bruno#1900]
#### Steps to Reproduce
1. Open bruno collection
2. Right-click a folder and select "Rename"
3. Enter a new name and click "Rename"

#### Expected Results
1. Folder is renamed in bruno collection (and on disk)

#### Actual Results
1. Error message
2. Error invoking remote method 'renderer:rename-item': TypeError: flatMap mapper function is not callable

**Comment by jcbbs** [comment]
Version v1.12.2 on Windows 11.

Could you be more specific about what "more information" I could get for you?

**Comment by jcbbs** [comment]
![image](https://github.com/usebruno/bruno/assets/158070507/9f4195be-c47b-43b3-9488-6cc354839f79)
![image](https://github.com/usebruno/bruno/assets/158070507/6bebc4b3-f45b-4484-a463-5ec96f342b31)
![image](https://github.com/usebruno/bruno/assets/158070507/f0eb0361-f1a1-4c6e-aa10-58c1ad9c0ad4)

**Comment by digzom** [comment]
Same error here.

**Comment by digzom** [comment]
> I also tried and can confirm this issue on Windows 11.
> 
> Tried below cases but end up getting the same error as @jcbbs captured:
> 
> * The new folder name includes a space.
> * The new folder name includes no space.
> 
> And if you rename a folder with the same name (which is allowed), you get a slightly different error saying that the path already exists.
> 
> Using latest version `1.12.2`.
> 
> Workaround:
> 
> Rename the folder in Windows' File Explorer instead, it will be reflected in the app automatically.
> 
> By the way, I tried running the `main` branch in local env but it works and I cannot reproduce the issue.

Exacly the same here. But on Ubuntu 22.04.

Tried to reproduce the bug running `main` branch but it works perfectly. Renaming the folder in the OS explorer works as well.

**Comment by Its-treason** [comment]
Seems to be an issue with the golden edition then. The error modal also does not exist on the main branch.

**Comment by sanjai0py** [comment]
Hey! I tried recreating the bug on Bruno OS and Bruno Golden, but couldn't reproduce it. I'm on version 1.12.2.

**Comment by digzom** [comment]
Just tried on tag v1.12.2 and couldn't reproduce the bug. Really odd

**Comment by Its-treason** [comment]
I made a small recording of the bug. Could be platform specific. I'm currently using Windows 11 and Bruno without the activated golden edition.

https://github.com/usebruno/bruno/assets/39559178/3ef6cfce-20c9-4389-a168-0e686d7b7dd1

**Comment by matthewb531** [comment]
Also seeing this on MacOS, on Bruno v1.12.3, Golden not activated.
![image](https://github.com/usebruno/bruno/assets/17405829/dcfcf395-68e5-4cd9-9c05-b34c9174609e)

**Comment by Camilapinz18** [comment]
Same error here! Im trying to change a folder name from PaymentLink} to PaymentLink.

I'm using Free Bruno version 1.12.3 in WIndows 11:
<img width="193" alt="image" src="https://github.com/usebruno/bruno/assets/83082880/4c05c758-e1a0-4d42-b7aa-69e20c3693cb">  

Error:
<img width="256" alt="image" src="https://github.com/usebruno/bruno/assets/83082880/df245785-707a-4a29-bc8e-946cfaa344d3">

**Comment by Arnaldino** [comment]
Hello guys. Same issue here when trying to rename any folder inside a Collection:

<img width="449" alt="92296" src="https://github.com/usebruno/bruno/assets/39277295/7d423b9b-821c-457f-993f-eaa5ecf11fd0">

Config:

Bruno Golden Edition v1.12.3
Mac OS M1 Sonoma

This seems to happen after the Golden edition release. Minor thing, I can still work without that ;-).

Best.

**Comment by sanjai0py** [comment]
This issue has been fixed and will be available in the next release! Thanks for taking your time to report this y'all!
