### ISSUE TITLE
[bug]: Installing Bruno from FlatHub fails because of incorrect URL

### ISSUE THREAD

**Issue by garrlker** [usebruno/bruno#1905]
When I try to install from from FlatHub I'm met with this error

![image](https://github.com/usebruno/bruno/assets/7344576/37e59481-d52a-47aa-84b8-9c85a451c8d3)

###Error text
```
While downloading https://github.com/usebruno/bruno/releases/download/v1.11.0/bruno_1.12.2_x86_64_linux.AppImage: Server returned status 404
```

Simple fix, the release url FlatHub points to should be this instead
```
https://github.com/usebruno/bruno/releases/download/v1.12.2/bruno_1.12.2_x86_64_linux.AppImage
```

**Comment by ravioli158** [comment]
+1

**Comment by satokenta940** [comment]
Perhaps you can try [Apidog ](https://apidog.com/)and download it directly for more convenience.

**Comment by helloanoop** [comment]
This has been fixed.  Please re-open if the issue persists.
