### ISSUE TITLE
Support for Collection or environment vars in Header Names as we support in Header Values like {{varName}}

### ISSUE THREAD

**Issue by yuvanakannan** [usebruno/bruno#191]

**Comment by helloanoop** [comment]
@yuvanakannan 

This functionality is now available in v0.16.0 🎉

Thanks @mirkogolze for getting this completed.

**Comment by yuvanakannan** [comment]
Thanks @helloanoop @mirkogolze 

For some reason, the env vars used inside the body is no longer getting replaced by the values. Example "{{env}}" within the body goes as "{{env}}" instead of "DEV" or "QA".

**Comment by mirkogolze** [comment]
For me it is working with release 0.16.1
Its working with collection variables. In Header, Names and Values and in Body
Its working with environment variables on all places. Too with variables from .env-File

**Comment by helloanoop** [comment]
@yuvanakannan I got the issue, please see https://github.com/usebruno/bruno/issues/233
This is being fixed.
