### ISSUE TITLE
Wrong number of requests in collection info

### ISSUE THREAD

**Issue by blackr1234** [usebruno/bruno#1912]
How to reproduce:

1. Right-click on the collection on the left panel.
2. Open "Settings" on the context menu.
3. Click the "Info" tab in the center panel.
4. The number of "Requests" is always the actual number `+ 1`.

This number does not match the number shown on the Runner page.

**Comment by sanjai0py** [comment]
Hey @blackr1234, what version of Bruno are you using right now? I tried recreating the issue on the latest version [v1.12.3](https://github.com/usebruno/bruno/releases/tag/v1.12.3), but I wasn't able to.

**Comment by blackr1234** [comment]
@sanjai0py 
Sorry forgot to mention, it was `1.12.2`.
Let me try the new version tonight, thanks!

**Comment by blackr1234** [comment]
The issue is still happening in `1.12.3`.

Please find below screenshot.

![image](https://github.com/usebruno/bruno/assets/13590610/e29853b2-fe04-41fb-991b-27afe951b716)

As you can see above, I have a brand new collection named `abc` and there is no request at all (the tree navigation menu is already expanded). However, the number of requests is `1`.

Now, I add a new request:

![image](https://github.com/usebruno/bruno/assets/13590610/b7c9f69f-2e6c-44e6-a136-0fb88ad1270b)

As you can see above, the number of requests is now `2`.

---

OS: Windows 11
Bruno version: `1.12.3`

**Comment by blackr1234** [comment]
I would suggest reusing existing function for calculating the number of requests rather than writing two different implementations and using them in different places.

The calculation for the Runner page:

> You have <span className="font-medium">{totalRequestsInCollection}</span> requests in this collection.

comes from below function:

https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/utils/collections/index.js#L616

The wrong one from Collection page - Info tab:

https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/components/CollectionSettings/Info/index.js#L4
