### ISSUE TITLE
Feature: Add pretty option to XMLrequest the same way that JSON request

### ISSUE THREAD

**Issue by tlaloc911** [usebruno/bruno#1913]
Add pretty option to xml request the same way that JSON request

Current JSON REQUEST

<img width="375" alt="image" src="https://github.com/usebruno/bruno/assets/29415755/856d26a2-ca0b-4a2e-a6ef-a573f20695b7">

Current XML REQUEST

<img width="364" alt="image" src="https://github.com/usebruno/bruno/assets/29415755/f0a0ec46-cdee-481e-ac77-0615dc459e97">

Expected XML REQUEST

<img width="384" alt="image" src="https://github.com/usebruno/bruno/assets/29415755/7d8fb35b-6630-4e5e-a5d5-ff58a7768524">

**Comment by helloanoop** [comment]
Thanks for the PR @tlaloc911 !

This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
