### ISSUE TITLE
Postman export fails with "Cannot read properties of undefined (reading 'tests')"

### ISSUE THREAD

**Issue by furious-cat** [usebruno/bruno#1916]
![image](https://github.com/usebruno/bruno/assets/130594089/31f9cd76-0051-4acd-bf82-ee19701b0c54)

No tests are present in any of the requests in the collection. This is on attempt to output to Postman. Export to Bruno collection works fine.

**Comment by uvarvu** [comment]
I can also reproduce this 1.12.3 (not golden edition).

<img width="1325" alt="Screenshot 2024-03-26 at 11 02 45" src="https://github.com/usebruno/bruno/assets/8590819/67c9c5d1-54a9-4c6e-97fd-540a34464b95">

**Comment by bpoulaindev** [comment]
@uvarvu, could you please share the postman JSON export file? Kindly ensure that all sensitive information is removed or transformed.

**Comment by uvarvu** [comment]
[ARM_Locations.zip](https://github.com/usebruno/bruno/files/14790347/ARM_Locations.zip)

I can't but I have attached the bruno collection that I'm attempting to export from.

**Comment by sanjai0py** [comment]
Closing this as the bug cannot be reproduced in the latest version [v1.20.2](https://github.com/usebruno/bruno/releases/tag/v1.20.2) of bruno. Please update to the latest version.
