### ISSUE TITLE
What version is needed for AWS SDK V3

### ISSUE THREAD

**Issue by BoBNelson1971** [usebruno/bruno#1919]
trying to use aws-sdk/client-dynamodb. Bruno throwing error cannot find module 'os'.  Bruno v1.9.0. Node version 18.17.1. npm 9.6.7. thoughts on how to move forward? Tried using earlier version of aws-sdk, but did not have impact.

**Comment by sanjai0py** [comment]
Hey @BoBNelson1971, are you still having trouble? Can you please share more details about the issue?

**Comment by sanjai0py** [comment]
Closing this issue is being marked as stale. Please reopen a new issue if the problem persists!
