### ISSUE TITLE
While importing from Postman, Request Body type is set as TEXT even though it is JSON in Postman

### ISSUE THREAD

**Issue by yuvanakannan** [usebruno/bruno#192]

**Comment by yuvanakannan** [comment]
Cannot reproduce. May be an adhoc case. Will reopen if encountered again

**Comment by helloanoop** [comment]
Thanks @yuvanakannan !

**Comment by mirkogolze** [comment]
I encountered the same problem. The problem is the export of postman. It seems to happen for older exports. Then sometimes the language is missing.

```
"request": {
	"method": "POST",
	"header": [
		{
			"key": "Content-Type",
			"value": "text/xml; charset=UTF-8"
		}
	],
	"body": {
		"mode": "raw",
		"raw": "<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  <soap:Body>\n  </soap:Body>\n</soap:Envelope>"
	}
}
```

**Comment by helloanoop** [comment]
@mirkogolze Can you share a sample postman collection file so that I can reproduce this ?

**Comment by helloanoop** [comment]
@mirkogolze I see that you already raised the PR for the fix.
I have merged it.

Many Thanks!
