### ISSUE TITLE
Auth2.0 Authorization Code fails to open login screen - Error: ERR_ABORTED (-3) loading

### ISSUE THREAD

**Issue by gustavokath** [usebruno/bruno#1920]
When setting up an HTTP call which uses OAuth2.0 with Authorization Code grant type, after I provided all URL and credentials details, when I click in "Get Access Token" then I receive the following error:

```
Error invoking remote method 'send-http-request': Error: ERR_ABORTED (-3) loading 'https://xxxx.authentication.sap.hana.ondemand.com/saml/discovery?returnIDParam=idp&entityID=https://xxxxx.authentication.sap.hana.ondemand.com&idp=xxxxxxx.ondem&isPassive=true'
```

<img width="1597" alt="Bruno Issue" src="https://github.com/usebruno/bruno/assets/6647241/46e5d5c5-22b6-4d8d-a6a0-ddf787481999">

I don't have much more details so far as there are no extra logs on console. And unfortunately I had to hide some internal information on the URLs.

I'm ok to try to sove this on my own later and push a PR

**Comment by thekalinga** [comment]
I have very similar problem.

```
Error invoking remote method 'send-http-request': ReferenceError: responseBody is not defined
```

If we have ability to inspect raw request & raw response, that will simplify this. As of now, I dont know if such an option exists.

**Comment by helloanoop** [comment]
Thank you for the PR @thekalinga !

This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
