### ISSUE TITLE
Cant import postman collection at all

### ISSUE THREAD

**Issue by ruvlesh** [usebruno/bruno#1922]
I have a collection exported in JSON format.
When I try to import it, I get asked for the file name and the location of the file
The import button is clickable but not responding, i.e. nothing happens.
![2024-03-25_18-20-56](https://github.com/usebruno/bruno/assets/40966575/497408c1-10c9-4291-917f-442e2b896d33)

**Comment by josejames** [comment]
Seems like there is an issue with the latest version, look at this thread
https://github.com/usebruno/bruno/issues/1855

It you install v1.11.0 you should be able to import collections
