### ISSUE TITLE
Provide logo as SVG to add it to VS Code Icon themes

### ISSUE THREAD

**Issue by tw-pocket** [usebruno/bruno#1926]
https://github.com/PKief/vscode-material-icon-theme/tree/main/icons

**Comment by tw-pocket** [comment]
I created an Issue on the `vscode-material-icon-theme` repository:
https://github.com/PKief/vscode-material-icon-theme/issues/2258

**Comment by bpoulaindev** [comment]
The Bruno logo is available both in PNG and SVG formats at the following address : https://openmoji.org/library/emoji-1F436/

**Comment by jwetzell** [comment]
@helloanoop this looks closable unless a in-house SVG would need to be provided.

**Comment by sanjai0py** [comment]
The Bruno icon has been successfully added to the [vscode-material-icon-theme](https://github.com/PKief/vscode-material-icon-theme/commit/a1f23c6ffef3fd46dfca35cf3d3e0d385e0d9172). Thanks @tw-pocket! Closing this issue now.
