### ISSUE TITLE
I want to see the request body corresponding to the request I sent, but there is nothing in the developer tool view, and the current request cannot be captured in real time.

### ISSUE THREAD

**Issue by bite-Wilson-Liang** [usebruno/bruno#1927]
![test0326001](https://github.com/usebruno/bruno/assets/152937555/7df96b8f-31c0-43b9-89b1-42001feb816a)

**Comment by subiabre** [comment]
+1

But maybe the developer tools is not the right place for this. Maybe in the timeline tab.

**Comment by bpoulaindev** [comment]
@bite-Wilson-Liang  The request is sent on the Electron side, you won't be able to see it in the devtools.
However you can access this in **pre request scripts** : 
`console.log(res.body)`

**Comment by bite-Wilson-Liang** [comment]
> @bite-Wilson-Liang The request is sent on the Electron side, you won't be able to see it in the devtools. However you can access this in **pre request scripts** : `console.log(req.body)`

Thank you~
