### ISSUE TITLE
Underlying components sometimes overlap modals

### ISSUE THREAD

**Issue by david-reichert-ef** [usebruno/bruno#1935]
Underlying components, such as the prettier button in a POST body, sometimes overlap modal windows.

![Before](https://github.com/usebruno/bruno/assets/132946012/6ce28e32-da15-4f49-b4b2-d74f908b3bbd)

**Comment by helloanoop** [comment]
Thanks for the PR @david-reichert-ef !

This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
