### ISSUE TITLE
Bruno License never delivered 

### ISSUE THREAD

**Issue by adiastra** [usebruno/bruno#1941]
Hello, 
i paid for a license and it was never delivered. There was an issue with the email address/ I have tried reaching out multiple times over the past 5 days and got no response.

**Comment by helloanoop** [comment]
Hey @adiastra !

Sorry about this.
I have replied to you yesterday from our support email.

I hope you have received the email response.
Let me know if you haven't, I'll send the keys again from my email id

I'm here to help.

**Comment by onlyutkarsh** [comment]
@helloanoop - I have the same issue. I purchased it yesterday and dropped an email with purchase details to the support email address. I have not yet received the license key.

**Comment by onlyutkarsh** [comment]
A day passed and still no update nor any response from mobile/email messages. Without any ETA and money already paid from my bank, I am frustrated not having the license key.

Not having a license key even after 2 days is an awful experience for anyone who wants to support your effort.

**Comment by helloanoop** [comment]
Hey @onlyutkarsh 

Thanks for the feedback and my apologies for the delay in getting the license keys delivered.

> nor any response for my mobile/email messages

So we do a batch process every 15 mins on all the successful orders.
There were 2 issues that were causing the licenses not being sent
 - timezone related issue
 - email sending issue post license keycreation

Both of them has been fixed. We will continue monitoring the batch process.
