### ISSUE TITLE
Error while exporting the collection as POSTMAN collection

### ISSUE THREAD

**Issue by dhanabal-thangavel-maersk** [usebruno/bruno#1943]
I'm using **bruno version V1.12.3** , while exporting the collection as "POSTMAN collection" getting the below error , I have not set any variable as tests

![image](https://github.com/usebruno/bruno/assets/85998743/3a5ffea7-d85b-4466-8990-6c6aa866bd72)

**Comment by HospitalBus** [comment]
Having the same issue. I'm using Bruno because it is much faster. My team still uses Postman so this is a very important feature for me.

**Comment by DmytroCrawford** [comment]
Just want to assign myself to fix this bug if possible. Will be doing it for a class.

**Comment by martinmckenna** [comment]
came here to post the same thing

**Comment by joevo2** [comment]
having this same exact issue

**Comment by kaonmir** [comment]
Same issue here

**Comment by DmytroCrawford** [comment]
@kaonmir @joevo2 @martinmckenna @HospitalBus and @dhanabal-thangavel-maersk does Burno Collection export work? if so can you make sure to remove all pii and private data (scramble links to give the general idea) and possibly drop the file in a comment tagging me? likewise can someone also copy and paste the entire error you are getting?

**Comment by martinmckenna** [comment]
@DmytroCrawford you can literally just create an empty collection, try to export and it will fail. Nothing about the data is making it error out

**Comment by martinmckenna** [comment]
that's the fix ^

**Comment by helloanoop** [comment]
Thank you @martinmckenna !

This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
