### ISSUE TITLE
[BUG]: Unable to rename uppercase file to lowercase file

### ISSUE THREAD

**Issue by dannydel** [usebruno/bruno#1948]
Hello! 

While using Bruno I attempted to rename my one file "Detect" into "detect". But I was met with the following error:
![image](https://github.com/usebruno/bruno/assets/24323045/1acdb11b-cf7f-4532-ad25-f28f330b5b19)

Steps to Recreate:
1. Create a new file and name it with a capital letter. EX: "Get"
2. Right click on that file in the left pane and click "Rename"
3. Rename it to "get".
4. Note error that appears

Application Type:
 Mac Silicon

**Comment by Its-treason** [comment]
I think this is a known issue with file-systems that are non-case-sensitive (e.g. `Detect.bru` and `detect.bru` would point to the same file). See https://github.com/usebruno/bruno/pull/531 for the long discussion on this topic. I implemented a fix on my fork: https://github.com/Its-treason/bruno/releases/tag/nightly

**Comment by dannydel** [comment]
Awesome, thank you. Yeah, I saw it was a bug before. But that issue was closed, so I figured it was a regression.

**Comment by anusree-bruno** [comment]
This has been fixed in the version v.1.32, so I am closing this ticket
