### ISSUE TITLE
App not starting up on M3 chip

### ISSUE THREAD

**Issue by deanhaleem** [usebruno/bruno#1950]
I've tried installing the latest version in all possible ways, as well as trying some older versions, and all don't start up on my M3 mac. I've tested the same steps on M1 and it works perfectly fine. 

Does Bruno support the latest M3 chips? Apologies if I've missed this in the docs/previous ussyes

Running the /Bruno file directly, I see a seg fault error:

```
[1]    45983 segmentation fault   ./Bruno
```

**Seg fault environment:**
Mac
OS: Sonoma 14.4
Chip: M3 Max

**Working environment:**
Mac
OS: Monterey 12.6.3
Chip: M1 Pro

**Comment by bpoulaindev** [comment]
Additional informations, i'm on an M2 Pro and Sonoma 14.0, i don't know how we could replicate this as the M3 Max is not very widespread

**Comment by andreassiegel** [comment]
I'm using an M3 Pro and cannot reproduce the issue. Bruno is working just fine.

I used Homebrew to install Bruno on my machine.

**Comment by sanjai0py** [comment]
Closing this issue as stale or not reproducible. Please open a new issue if the problem persists, and provide more information if possible.
