### ISSUE TITLE
Error invoking remote method 'send-http-request': ReferenceError: pm is not defined

### ISSUE THREAD

**Issue by arvigeus** [usebruno/bruno#1962]
This is not a bug report, this is an issue I had while importing my Postman collection. In case someone from the future has the same problem, here's the solution:

Your Postman request has Tests defined, which Bruno imports. Example: I had

```js
if(pm.response.code == 200) {
    pm.environment.set("authToken", pm.response.json().access_token);
}
```

in my tests. Either delete `Tests`, or modify them for Bruno

**Comment by 165280** [comment]
可以具体一点步骤吗  我没有导入 Postman 集合也有此问题

**Comment by 165280** [comment]
Can you be more specific about the steps thks  I do not import Postman collections also have this problem

**Comment by arvigeus** [comment]
Click on the request. Go to Scripts, Tests tabs. Make sure you have no code there.

Right click at the collection (top level) and select properties. Go to Scripts tab and make sure no code there as well.

Last ditch option: create a new collection and a new request. See if the request passes.
