### ISSUE TITLE
Prettify Icon overlap dialog box

### ISSUE THREAD

**Issue by rrguhan6** [usebruno/bruno#1989]
Prettify icon in the query tab is overlapping the dialog box. 

![Screenshot from 2024-04-03 10-51-22](https://github.com/usebruno/bruno/assets/63386495/1a79b959-0a39-4738-82b9-d8d8fd8f919d)
![Screenshot from 2024-04-03 10-46-31](https://github.com/usebruno/bruno/assets/63386495/58ef9211-e3c0-4644-9da0-f0ff38b8fbc7)
![Screenshot from 2024-04-03 10-55-32](https://github.com/usebruno/bruno/assets/63386495/d71010dc-6091-42bd-82e2-7a650a265f75)

**Comment by helloanoop** [comment]
This issue has been fixed and will go out in the 1.13.0 release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
