### ISSUE TITLE
Prettify Changes JSON Data Types From Float To Int

### ISSUE THREAD

**Issue by DJSaunders1997** [usebruno/bruno#1996]
Hi

I'm running the latest Bruno release and I've come across an issue with running prettify converting float values to ints.

Before running prettify:
![image](https://github.com/usebruno/bruno/assets/34069335/eacb6b90-9409-424c-8950-914ce8bc69e4)

After running prettify:
![image](https://github.com/usebruno/bruno/assets/34069335/f092d206-fd11-4494-b70e-659614dd49af)

This completely changes the datatype if there are trailing .0's which is raising validation errors by my service.

I've not tested any other datatype conversions so I'm unsure the extent of this issue.

For reference Postman's Beautify behaves how I would expect a formatter too:
![image](https://github.com/usebruno/bruno/assets/34069335/3ab541d7-14d3-4b5a-a40b-4b9c89b81516)
![image](https://github.com/usebruno/bruno/assets/34069335/c5bc8e75-fe32-4a38-807c-1ce6acf0f0f2)

Thanks

**Comment by Its-treason** [comment]
Probably because the "prettifying" is done using `JSON.stringify`/`JSON.parse`, we need to start using the `lossless-json` everywhere.

**Comment by JohnStokes228** [comment]
is there a ticket for the lossless-json work? i agree this is an important change

**Comment by DJSaunders1997** [comment]
I've implemented the lossless-json changes in the PR #2006

**Comment by helloanoop** [comment]
Thanks for the PR @DJSaunders1997 !
It has been merged.

This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
