### ISSUE TITLE
Setting for "follow / don't follow redirects" on a per request basis.

### ISSUE THREAD

**Issue by jkblume** [usebruno/bruno#200]
First of all. Thank you for providing this great tool. I'm currently looking at alternatives and really have the feeling that a lot is being done right here. 

To my question: Is it possible to set the follow redirects behaviour in general or on a per request basis? We actually need this because we want to extract a value from a response header that is only available without the redirect.

**Comment by helloanoop** [comment]
Hey @jkblume 

Glad that you like Bruno!

> Is it possible to set the follow redirects behaviour in general ?

Currently it's not supported. We will support it soon. By default all requests follow up to 5 redirects. 

> Is it possible to set the follow redirects behaviour on a per request basis? 

Currently it's not supported. But I'd love to understand the requirement more and see if we can support it.
Bruno uses axios under the hood. And we can expose an api that would allow you to set the maxRedirects for a request to 0.

Thinking something like this which can be written in the [pre request script](https://docs.usebruno.com/scripting/introduction.html) section
```javascript
req.setMaxRedirects(0);
```

**Comment by jkblume** [comment]
Yeah, this would be totally fine!

Some insights to the use case:
I am building a collection, that needs to get some value (a code challenge value, in an oauth2 workflow). This header value is present on an Response with status code 302, but gets lost if you follow the redirect. Hope this helps to understand, why this setting is important for us :)

Thanks for the fast response 👍

**Comment by helloanoop** [comment]
Hey @jkblume 

This is now available in `v0.15.0`
Please download the latest version.

Here is how you can disable max redirects at the request level.
![image](https://github.com/usebruno/bruno/assets/9350733/a4e5f467-1414-4a01-8fd3-720187c9be3f)

**Comment by helloanoop** [comment]
I also wrote some tests on our testbench to verify this.
In case you are interested, the testbench repo (with test server and a collection) is at https://github.com/usebruno/bruno-testbench

![image](https://github.com/usebruno/bruno/assets/9350733/5c0ae15b-f31b-4f0f-a475-4992d3d57712)

**Comment by jkblume** [comment]
Thanks, I will try this out the next days!

**Comment by jasniec** [comment]
I think we could also add this to the collection settings so there is no need to dig in the documentation

**Comment by junlongzzz** [comment]
图形界面设置是否重定向或者重定向次数，比手动添加 `Pre Request Script` 的方式更直观友好

**Comment by snird** [comment]
I hear @AndreiaSofia .
Ran into a similar issue, I suspect with the same authentication format - with CAS:
https://codenoble.com/blog/cas-authentication-explained/

In the flow, the last step is a page with the cookie set on it, and then a redirect.
It works fine on the browser because the browser keeps the cookie - but not in a direct API flow like when using Bruno.

There should be an option not to follow redirect and that the request will not error because of that

**Comment by lacikawiz** [comment]
I just tried this on Bruno v1.26.2 and it worked without an error message. I could see the response with the redirect header. 

A setting for this at the request would be nice, so that it could be easily found when needed.

**Comment by nikolawannabe** [comment]
So when I was using bruno to call a URL, I would get 405 from the URL. I expected it to CURL and ran it and got a 301 instead, which is when I realized that it wasn't following the redirect from URL to www.URL.  Strange though that I got a 405 instead of the 301 that the exported curl gave me!  Anyway, thought I'd drop this by as a point in favor here.

**Comment by OpenOrangeData** [comment]
The pre request script should be fine for my needs at the moment.

However, could you please mention this possibility in the [docs](https://docs.usebruno.com/)? A search for "follow redirects" (or similar) doesn't yield any results.

**Comment by helloanoop** [comment]
In the latest version of Bruno, we have added support for request level settings in the UI  🎉 

<img width="553" height="568" alt="Image" src="https://github.com/user-attachments/assets/2c498053-5334-4f59-a853-2d96c43ad470" />
