### ISSUE TITLE
[Bug] Crash on openning environments screen

### ISSUE THREAD

**Issue by gabrielcartellivia** [usebruno/bruno#2001]
**What?**
After populling a variable with a post response script, when I open the enviroments screen, Bruno crash.

**How?**
1) Create a variable without value. Ex.: `vars { incidentId: }`
2) Config a post response script. Ex.: `bru.setEnvVar("incidentId",res.body.incidentId);`
3) Execute the request
4) Open the enviroments screen => The screen will crash

**Screenshot:**
![image](https://github.com/usebruno/bruno/assets/72199278/a8a67c36-2216-48f0-a6c9-ae5ee2b9aaff)

**Comment by gabrielcartellivia** [comment]
https://github.com/usebruno/bruno/pull/1947 fix the problem

**Comment by helloanoop** [comment]
This issue has been fixed and will go out in the 1.13.0 release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
