### ISSUE TITLE
Creating request with curl, -g parameter doesn't work

### ISSUE THREAD

**Issue by liujigang** [usebruno/bruno#2010]
example：
```shell

curl -X GET \
  -H "X-Id: appid" \
  -G \
  --data-urlencode 'limit=100' \
  https://host/1/classes

```

**Comment by helloanoop** [comment]
This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
