### ISSUE TITLE
When I run the Collection, then I get "expected undefined to be a number or a date" error for the assertion. Please follow the below Attachments 

### ISSUE THREAD

**Issue by QA-jass** [usebruno/bruno#2021]
Code : 
![image](https://github.com/usebruno/bruno/assets/142493254/ce2bf6c1-dd27-4188-a5e6-34cc57765dc7)
error : 
![image](https://github.com/usebruno/bruno/assets/142493254/1774eff0-c217-4cd2-9928-ae1e17d94ef2)

**Comment by sanjai0py** [comment]
Duplicate #1145

**Comment by helloanoop** [comment]
Issue has been fixed.
This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
