### ISSUE TITLE
isNull is not defined, when using in ACTIVATE LICENSE with proxy

### ISSUE THREAD

**Issue by PushpenderSaini0** [usebruno/bruno#2029]
## Error Description 
 
I am trying to activate LICENSE, with a proxy and getting this error !
> Error invoking remote method 'renderer:request-license-activation-otp': isNull is not defined

#### Steps to reproduce
 1) ACTIVATE LICENSE window
 2) LICENSE SETTINGS
 3) Set your proxy
 4) Save
 5) Activate License 
 6) Error :( 

### Possible Fix

The code suggest this is caused as the function `isNull` was not imported.

![image](https://github.com/usebruno/bruno/assets/54404738/aeed3acf-e150-4e3d-9f80-f0ce709bd207)

**Comment by pstader** [comment]
This prevents me from activating as well in a corporate environment. I might be able to convince decision makers here to buy licences but don't want to demo Bruno when I'm unable to activate.

**Comment by sanjai0py** [comment]
The issue has been resolved and the fix will be included in the upcoming patch. Thank you for bringing it to our attention.

**Comment by helloanoop** [comment]
@PushpenderSaini0 @pstader 
This issue has been fixed in `v1.15.0`

I am closing this issue. Please re-open if the issue persists.
