### ISSUE TITLE
User should have access to About menu to find out what version they are currently using

### ISSUE THREAD

**Issue by jeffprinty** [usebruno/bruno#203]
Many apps will provide an About page in the help menu to allow users to know what version of the app is currently being used. Bruno should also have this too.

Example: As a Mac user I want to see if I have the latest Mac version of the app to know if the collections scrolling should be working. Currently there is no way to know what version of Bruno is running

Proposal: Use [electron-about-window](https://github.com/rhysd/electron-about-window) package to implement a basic About window in the Help menu

**Comment by helloanoop** [comment]
This is cool !!

PR Merged. Thanks @jeffprinty !

**Comment by helloanoop** [comment]
I have released this changes.

This works in local
![image](https://github.com/usebruno/bruno/assets/9350733/feae2191-2641-4482-a458-27b459bc60a8)

But is broken in the released build. Need to investigate.
![image](https://github.com/usebruno/bruno/assets/9350733/19653b39-ec70-4c85-9cfe-fc3531acbdf8)

**Comment by mirkogolze** [comment]
you could try
```
icon_path: join(process.cwd(), '/resources/icons/png/256x256.png'), 
```

**Comment by alefteris** [comment]
An issue from another user has also been opened for the broken app image in the about window #254. Since the about window is already implemented and released, I think the current issue can be resolved and track the icon issue in the new one?

Also a feature request for the about window has been opened at #231, requesting for the version text to be able to be copied.

**Comment by helloanoop** [comment]
This is now working in latest release `v0.16.5`
![image](https://github.com/usebruno/bruno/assets/9350733/169cf7be-7cde-4aac-9ac6-a639f87671b9)

Thank you @mirkogolze and @jeffprinty !
