### ISSUE TITLE
Import Collection OpenAPI v3 Spec does not seem to work

### ISSUE THREAD

**Issue by Gitznik** [usebruno/bruno#2035]
Hey there, thanks for developing this tool!

I managed to import json openapi specs once on v1.12.2, but except that one occasion, every time I select the openapi.json file, a location and then nothing happens when I click import.

I also tried converting my openapi json to yaml, but I still can't successfully import it.

In the dev tools I see this warning printed every time I click Import:

```
Warning: An unhandled error was caught from submitForm() ReferenceError: enableTranslation is not defined
    at handleSubmit (708-91b98ba4d9a5d350.js:1:34731)
    at onSubmit (708-91b98ba4d9a5d350.js:1:32368)
    at _app-3dfff338a00a1088.js:11:43927
    at _app-3dfff338a00a1088.js:11:47917
    at _app-3dfff338a00a1088.js:11:43100
```

**Comment by prupke2** [comment]
I am experiencing the same issue and see the same error in the dev console. I also recall being able to import a v3 openapi spec about 3 months ago on my old laptop, but I don't know which version of Bruno that was.

Given the error message, I suspect this is related to the `Auto translate postman scripts` option that is given in the "Import Collection" modal. I get the same error message whether or not this option is checked.

**Comment by sanjai0py** [comment]
Closing this as stale/not reproducible. Please create a new issue if the problem persists and provide more details for debugging.
