### ISSUE TITLE
JSON body is quoted when invalid

### ISSUE THREAD

**Issue by GregoireBellon** [usebruno/bruno#2043]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Hello, 

VERSION : 1.12.3. 
---

When sending a POST request with valid JSON in the body, the body is sent without any modification. 

When sending a POST request with invalid JSON in the body, the body is quoted before being sent.

This behavior only occurs when the selected content type is JSON. When sending text, invalid XML or SPARQL, the body is not quoted. There is no indication in the timeline view that the body is quoted.

--- 
I'm conscious that I'm complaining that Bruno prevents me from shooting myself in the foot, but I'm working on an API that, for legacy purposes, needs to accept requests containing invalid JSON in the body, and a text/json content type. And I can't test my implementation because of this behavior. 

A setting to configure this behavior, and some cues that it happens would be nice.

I would be glad to contribute to fix this issue !

### .bru file to reproduce the bug

[reproduce-bug.zip](https://github.com/usebruno/bruno/files/14918530/reproduce-bug.zip)

### Screenshots/Live demo link
Here are the bodies the requests recieved by a beeceptor endpoint : 
![Capture d'écran 2024-04-09 143041](https://github.com/usebruno/bruno/assets/45675498/cbf7a520-f1c1-4284-b389-2fe25bbac99a)
![Capture d'écran 2024-04-09 143059](https://github.com/usebruno/bruno/assets/45675498/6ec5b3e3-49ce-4bab-afb8-e51057476628)

As you can see, the data section doesn't show that quotes are being added to the request
![Capture d'écran 2024-04-09 143321](https://github.com/usebruno/bruno/assets/45675498/69ece7cd-5ef2-4a19-b3d9-03250e700154)
![Capture d'écran 2024-04-09 143237](https://github.com/usebruno/bruno/assets/45675498/49ffca96-d94e-4724-b4be-300ff5e13390)

**Comment by Fabiensk** [comment]
I'm facing the exact same issue. With Bruno 1.16.1 (desktop, not CLI),  I could use in a Pre Request Script `req.setBody(Buffer.from("the text")) ` and the raw value without quotes was sent. With Bruro 1.17 this hack stopped working.

**Comment by zlfn** [comment]
This issue has deteriorated after 1.27.0,
Bruno now **IMPLICITLY** sends quoted requests.
![image](https://github.com/user-attachments/assets/0a23d2b3-0a58-451d-be71-38de67377c17)
![image](https://github.com/user-attachments/assets/41942cb5-ca77-4119-9905-4b26cbbdb5e1)

**Comment by helloanoop** [comment]
Just merged the PR for this. This should be available in the upcoming `v1.29.0` release

**Comment by st-faan** [comment]
From version 3.2.2 (tested also 3.3.0) the Bruno CLI has the same issue as described above (The GUI works as expected).
Tried some workarounds but without success.
