### ISSUE TITLE
[FEAT] View Collection properties in Bruno UI

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#205]
Today, there is no way to retrieve collection properties after creation in Bruno UI.

For instance, I've previsouly added collection

<img width="331" alt="image" src="https://github.com/usebruno/bruno/assets/56150873/127cb014-a1c4-4ef1-b0dd-ac1a176cfa05">

... but I do not know in which folder it is located anymore: where it is physically stored?

Having a Properties option to edit collection name and get the collection location would be very helpful

**Comment by helloanoop** [comment]
@arnaduga Makes sense.

I have personally run into this issue many times where I forget where the physical storage location is.

**Comment by helloanoop** [comment]
@arnaduga This is now available in the latest release.
Please install it from the website.

Dropdown

![image](https://github.com/usebruno/bruno/assets/9350733/12485697-df27-476a-9897-a8381dc2c024)

Collection Properties

![image](https://github.com/usebruno/bruno/assets/9350733/7a2c53d0-f440-4475-86f3-a5a76bfc8c74)
