### ISSUE TITLE
Renaming a request will discard changes without warning

### ISSUE THREAD

**Issue by Rmaan** [usebruno/bruno#2050]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I make a lot of custom requests to an API and it involves a lot of edits, sometimes after editing I figure out there's a better name for the request and I rename it. Recently I found it this will discard all the changes.

In honestly, I think this it the byproduct of not having auto save, I for one, see no value in saving each request independently. If I want to go back to previous version I rather to use undo. With manual save there's risk of losing my work in case of forgetting to save, a crash, ...

### Screenshots/Live demo link

1- Open a request
2- Do some edits but don't save
3- Rename the request

All your edits are gone.

**Comment by Its-treason** [comment]
This is already merged with: #2018 and will be released with 1.13 in a few days.

**Comment by Rmaan** [comment]
Ah I think I searched in open issues, thanks.
