### ISSUE TITLE
Need to update link to docs for secrets management

### ISSUE THREAD

**Issue by bSolt** [usebruno/bruno#2055]
Link to the secrets management page is dead.

The code here:

https://github.com/usebruno/bruno/blob/65dbf9c8baf603819a79b9f9f2d89d2218c11f52/packages/bruno-app/src/components/Environments/EnvironmentSettings/ManageSecrets/index.js#L16

should link here: https://docs.usebruno.com/secrets-management/secret-variables

**Comment by sanjai0py** [comment]
Issue closed! Thanks, @bSolt, for taking the time to report this bug.
