### ISSUE TITLE
Make Docs tab more prominent

### ISSUE THREAD

**Issue by MelGrubb** [usebruno/bruno#2069]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

The current Docs tab has no indication whether it has contents or not. Several other tabs display a count indicating the number of entries on that "tab", but the Docs tab doesn't. I don't think a count is appropriate, but some indication that there's something to be read would be nice. Maybe a simple asterisk?

### Mockups or Images of the feature

![image](https://github.com/usebruno/bruno/assets/1153287/3d1497f4-a615-4b11-b943-24ae02ed45ec)

**Comment by helloanoop** [comment]
This has been implemented.

<img width="556" alt="image" src="https://github.com/user-attachments/assets/3d9f3884-bc59-44a7-8d0b-78c7838a5076">
