### ISSUE TITLE
"Failed to save request" on specifically Oauth 2 (Authorization code) unless PKCE checkbox was checked once

### ISSUE THREAD

**Issue by Gremious** [usebruno/bruno#2070]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I create new empty request: I can save it ok.

I select Auth tab and OAuth 2.0 with grant type "Authorization Code": I can no longer save, message "Failed to save request" pops up.

Other grant types work.

I click the "Use PKCE" checkbox - saving works from here on out.

Using fresh non-portable installer on Windows from the website.

I attched video with me pressing Ctrl+S after every action.

### Screenshots/Live demo link

https://github.com/usebruno/bruno/assets/21365711/5703b0ca-9334-4f31-b804-8505154a1d2d

**Comment by helloanoop** [comment]
I have merged the PR. Will ship this in the upcoming patch release `v1.13.1`

Please follow us on [Discord](https://discord.com/invite/KgcZUncpjq) / [Twitter](https://twitter.com/use_bruno) to stay notified on the releases.
