### ISSUE TITLE
Import collection missing key property

### ISSUE THREAD

**Issue by PushpenderSaini0** [usebruno/bruno#2078]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Import collection has a missing key property used by react when rendering the list !

This can be fixed by adding a key prop to the div [here](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/components/Sidebar/ImportCollection/index.js#L81-L82) !

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/54404738/42216104-12ac-48ca-b399-3aff07bba041)

**Comment by helloanoop** [comment]
Thanks for the PR @RashidUjang !

This will be released in `v1.14.0`

Please follow us on [Discord](https://discord.com/invite/KgcZUncpjq) / [Twitter](https://twitter.com/use_bruno) to stay notified on the releases.
