### ISSUE TITLE
OAuth 2.0 Authorization Code - Unable to Get Access Token at Collection Level

### ISSUE THREAD

**Issue by bigsing** [usebruno/bruno#2085]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Running Bruno v.1.13.0 i'm unable to retrieve an Access Token at the Collection level. This occurs with or without checking Use PKCE. This was working previously on 1.12.3, such that I could run a post-response script and store the token for use by requests in my collection. The error displayed is `Error invoking remote method 'send-collection-oauth2-request': ReferenceError: item is not defined`

### Screenshots/Live demo link

![bruno-error](https://github.com/usebruno/bruno/assets/11449598/65996641-cc72-4e10-b42f-4a4125066cba)

**Comment by VictorioBerra** [comment]
Same. This is broken in 1.13 Works fine on the request level, bug at the collection level.

Ref https://github.com/usebruno/bruno/issues/1987

Ref https://github.com/usebruno/bruno/pull/2039

CC @helloanoop

**Comment by helloanoop** [comment]
Issue has been fixed.
This will go out in the `1.13.1` release. (In another 2 hrs)

Please follow us on [Discord](https://discord.com/invite/KgcZUncpjq) / [Twitter](https://twitter.com/use_bruno) to stay notified on the releases.
