### ISSUE TITLE
Bug: UI: Code completion hint dismissed with Esc re-appear immediately

### ISSUE THREAD

**Issue by pietrygamat** [usebruno/bruno#2087]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I run into this issue both in Flatpack and Windows releases. The code completion hint is dismissed with using Esc key, but if it feels like it's needed, it will reappear immediately without any delay. In certain situaltions it makes using the editor very hard, like in the screen below, where Enter and direction keys are not doing what I am expecting them to, causing me to apply unwanted suggestions
All I wanted is add a line above current one (Home + (optional Esc to close dropdown)  + Enter to add newline).

### Screenshots/Live demo link

![Bruno_vYKJ3ogimo](https://github.com/usebruno/bruno/assets/2108093/7d667788-be6d-4c65-af22-f95d7ec6a638)

**Comment by krummbar** [comment]
I came across the exact same issue. I raised a PR for this, but not sure if I overlooked something since this is my first PR here.
https://github.com/usebruno/bruno/pull/2091

**Comment by helloanoop** [comment]
PR related to the issue has been merged.
This will go out in the `1.14.0` release.

Please follow us on [Discord](https://discord.com/invite/KgcZUncpjq) / [Twitter](https://twitter.com/use_bruno) to stay notified on the releases.
