### ISSUE TITLE
Toggle password visibility in proxy and client cert settings.

### ISSUE THREAD

**Issue by sanjai0py** [usebruno/bruno#2094]
### I have checked the following:

Improving #1824.

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Consider adding an eye icon next to the input field. It can be clicked to show or hide input values, providing convenience and simplicity to the design.

### Mockups or Images of the feature

https://github.com/usebruno/bruno/assets/84461672/5a54e94b-54dc-4a9d-9419-f32cd3ef36e0

**Comment by gustavofdasilva** [comment]
hey @sanjai0py, I solved this issue here: #2127 

I'm a beginner so it would be awesome to hear some suggestions about it.

Thanks!

**Comment by sanjai0py** [comment]
Hey @gustavofdasilva, I appreciate you taking the time to work on this issue. However, I wanted to let you know that I already have a draft PR #2105 with the feature implemented. 

> The only problem is that when the password is too long, the button gets covered. 

Thanks for bringing this edge case to my attention. I haven't yet solved the issue in my PR, so would you mind trying to fix it?

**Comment by sanjai0py** [comment]
Keep working on your PR, @gustavofdasilva! Great job!

**Comment by gustavofdasilva** [comment]
I just finished the overlap button issue in the new commit #2127. Let me know what you think!
