### ISSUE TITLE
Requests with Variables in Queries are sent without "Equals (=)"

### ISSUE THREAD

**Issue by RicardoVizcaya** [usebruno/bruno#2095]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Requests URLs with Queries are built with "=" whenever the Value field has a Text value, and without the "=" when the Value comes from a Variable. In my case, this leads to different results depending on how I fill the Value.

As you can see from the screenshots, when the Value comes from a Variable, the "=" after trackingId in the URL is missing.

I believe the Equal sign should also be sent in the Response when the Value a Variable is.

### Screenshots/Live demo link

![grafik](https://github.com/usebruno/bruno/assets/119726103/01531ee0-2527-46bd-b58f-a31398b2bdc4)

![grafik](https://github.com/usebruno/bruno/assets/119726103/c1867cad-5b18-4907-a67e-9ce0a306c105)

**Comment by pietrygamat** [comment]
Can you share a .bru file that reproduces this? It does not happen to me, but it looks intriguing.

**Comment by RicardoVizcaya** [comment]
Thanks for your reply and for trying to reproduce this behaviour.
I created a new .bru collection from scratch to try to recreate the issue and discovered that the cause of this behaviour was a PreRequest script at collection level which I have forgotten about.
Thus, I would close this issue.
