### ISSUE TITLE
Environment secret variable checkbox not saving or applying

### ISSUE THREAD

**Issue by Don011** [usebruno/bruno#210]
I just downloaded v0.15.1 and immediately went to convert all of my authentication variables to secrets. However it doesn't seem to work.

If I tick the Secret box on either an existing or new variable and then click the Save button, when I exit the Environments screen or go to a different environment and come back the Secret box is unticked again. The environment file also shows all variables listed as non-secrets. I also tried making a new test environment and uninstalling/reinstalling but the results were the same in both cases.

I'm using the Windows desktop version if that helps.

**Comment by helloanoop** [comment]
Hey @Don011 !

Thanks for testing it out.
It appears there were some dependency issue in the libraries.

I have released a patch `v0.15.2`
Can you install it and retest it.

I have tested it on my Mac (Intel 64), and it appears to be working fine.

**Comment by Don011** [comment]
That seems to have fixed it. I've installed v0.15.2, the checkbox in the GUI saves now and the `vars:secret []` part of the environment .bru file is now being generated.
Thanks for the quick response. 😃
