### ISSUE TITLE
Add option to accept self-signed certificates

### ISSUE THREAD

**Issue by adambarreiro** [usebruno/bruno#211]
Hi,

First of all, thanks for creating and developing Bruno!
I started to migrate my Postman collections to Bruno, and I'm facing the following error when running requests:

```
Error invoking remote method 'send-http-request': Error: self signed certificate in certificate chain
```

The target server is indeed using **self-signed certificates**, as it is a development server used for testing.
Would it be possible to add an option to ignore this case?

I could do a tiny workaround in macOS using the terminal:

```
NODE_TLS_REJECT_UNAUTHORIZED='0' /Applications/Bruno.app/Contents/MacOS/Bruno
```

Thanks in advance!

**Comment by adambarreiro** [comment]
I just found the option in the UI. Apologies for the noise!

**Comment by helloanoop** [comment]
No worries :)

**Comment by piyh** [comment]
For all those finding this through search, the option is on settings off the gear icon on the bottom left, not the top right.

**Comment by itsups-sia** [comment]
for all those that got a preference save error
- one has to set the proxy.port to a number e.g. 1000 even when not used

( output from devtools :)
Error: Error invoking remote method 'renderer:save-preferences': ValidationError: proxy.port must be a `number` type, but the final value was: `NaN` (cast from the value `""`). )

**Comment by ebricca** [comment]
for those that got a preference save error

one has to set the proxy.port to a number e.g. 1000 even when not used

( output from devtools :)
Error: Error invoking remote method 'renderer:save-preferences': ValidationError: proxy.port must be a number type, but the final value was: NaN (cast from the value ""). )

**Comment by Schm1tz1** [comment]
Hi all, seems like I'm running into the same issue. I am using a self-signed cert with my own custom CA. Deactivating SSL Certificate Validation does not work even after restart of Bruno - I am still getting `Error invoking remote method 'send-http-request': Error: self signed certificate in certificate chain`. Setting the env-var as @adambarreiro mentioned works for me.

**Comment by geraintwjones** [comment]
I'm getting `Error: socket hang up` now. Works fine with Insomnia, so I know the server's responding. Must be something I've not done, or have done incorrectly in Bruno.

**Comment by Shackelford-Arden** [comment]
I'm in the same boat as @Schm1tz1 :

- I've disabled SSL Verification
- I've opened Bruno w/ the same environment variable (`NODE_TLS_REJECT_UNAUTHORIZED=0`)

I'm on Bruno 1.3.0 MacOS 14.1.2

**Comment by BrandonGillis** [comment]
Hello @Shackelford-Arden and @geraintwjones , could you please try again on Bruno 1.3.2, as it include fixes related to localhost environment if you was having the SSL issue on localhost

**Comment by geraintwjones** [comment]
I'm getting `Error invoking remote method 'send-http-request': Error: socket hang up`.

**Comment by geraintwjones** [comment]
<img width="1392" alt="Screenshot 2023-12-04 at 20 50 43" src="https://github.com/usebruno/bruno/assets/4315762/3b66f4a0-4292-4b06-9450-4de13e8be1b5">

**Comment by geraintwjones** [comment]
<img width="1348" alt="Screenshot 2023-12-04 at 20 56 16" src="https://github.com/usebruno/bruno/assets/4315762/062a6a84-1aa3-453e-b1b0-9419307b2ba8">

It's really annoying that I can't see what's in that client certificate.

**Comment by Shackelford-Arden** [comment]
@BrandonGillis having updated to 1.3.2, I still need to set the environment variable when opening Bruno to make calls against self-signed certs w/ validation turned off.

Just for clarity, here is the SSL/TLS Cerficiate Verification turned off:

![image](https://github.com/usebruno/bruno/assets/7362263/0b0df559-598d-4591-b9c0-129f745f1eba)

Error when attempting to make call against self-signed resource:

![image](https://github.com/usebruno/bruno/assets/7362263/50e9f9ec-348f-42ad-ab81-bb3cab075770)

Same settings but running Bruno like this:

```NODE_TLS_REJECT_UNAUTHORIZED='0' /Applications/Bruno.app/Contents/MacOS/Bruno```

Gets the response I expected.

**Comment by geraintwjones** [comment]
@Shackelford-Arden I tried that. I get the same error as before. Also, by starting Bruno like this...
```
NODE_TLS_REJECT_UNAUTHORIZED='0' /Applications/Bruno.app/Contents/MacOS/Bruno
```

I get the following output...

[bruno-log.txt](https://github.com/usebruno/bruno/files/13551821/bruno-log.txt)

**Comment by helloanoop** [comment]
Support for specifying Custom CA is now available in v1.6.0 🎉 🎉
Thank you @BrandonGillis for working on this.

@Shackelford-Arden  @Schm1tz1  @geraintwjones The release also involves fixes for the issue you were facing. Can you download 1.6.0 and see if it solves your issue ?

**Comment by ivycristina** [comment]
I downloaded version 1.6.0 and I'm getting this error, can anyone help me?
![image](https://github.com/usebruno/bruno/assets/68569199/25666849-7d18-466a-bc3f-5deb51880a2b)

**Comment by helloanoop** [comment]
@ivycristina Can you share more details

Did you try disabling ssl?
Are you using custom CA cert ?

**Comment by ivycristina** [comment]
I disabled SSL because it was giving another error and I threw it on the internet and said to disable it, I'm not using a certificate, I just brought the collection directly from postman to Bruno and there in postman it works without any token or certificate and here it doesn't want to work

> @ivycristina Can you share more details
> 
> Did you try disabling ssl? Are you using custom CA cert ?

I disabled SSL because it was giving another error and I threw it on the internet and said to disable it, I'm not using a certificate, I just brought the collection directly from postman to Bruno and there in postman it works without any token or certificate and here it doesn't want to work

**Comment by ivycristina** [comment]
> @ivycristina Can you share more details
> 
> Did you try disabling ssl? Are you using custom CA cert ?

I disabled SSL because it was giving another error and I threw it on the internet and said to disable it, I'm not using a certificate, I just brought the collection directly from postman to Bruno and there in postman it works without any token or certificate and here it doesn't want to work

**Comment by Schm1tz1** [comment]
@helloanoop  - at least for me I can say that the issues are gone now, thanks a lot!

**Comment by Shackelford-Arden** [comment]
@helloanoop I'm on Bruno 1.6.1 and I still need to use the following to successfully make HTTPS.

Again for reference, I do have SSL verification disabled:

![image](https://github.com/usebruno/bruno/assets/7362263/715b5f3e-e158-4fc5-84b4-f68b365947f0)

I do have a SOCKS5 proxy for these requests in particular. 

Error message I'm getting:

![image](https://github.com/usebruno/bruno/assets/7362263/fca1135e-f649-44fd-858c-a510268b1a5e)

Seems like there needs to be a way to make sure that validation for _all_ certificates that are presented is skipped.

**Comment by Shackelford-Arden** [comment]
As an additional point there, if I run the same request via cURL while telling it to use the same proxy, the request is successful

**Comment by martinsefcik** [comment]
@helloanoop @Shackelford-Arden 
I think problem is in implementation of SOCKS proxy support.

Currently it is implemented like this:
```js
if (socksEnabled) {
      const socksProxyAgent = new SocksProxyAgent(proxyUri);
      request.httpsAgent = socksProxyAgent;
      request.httpAgent = socksProxyAgent;
} 
```
So it completely ignores SSL verification and certificates configuration in `httpsAgentRequestFields` variable.

I think it should be changed to something like this:
```js
    if (socksEnabled) {
      const socksProxyAgent = new SocksProxyAgent(proxyUri);
      request.httpsAgent = new SocksProxyAgent(
          proxyUri,
          Object.keys(httpsAgentRequestFields).length > 0 ? { ...httpsAgentRequestFields } : undefined
      );
      request.httpAgent = new SocksProxyAgent(proxyUri);
} 
```
the same way how it is implemented for http(s) proxy.

**Comment by Shackelford-Arden** [comment]
@martinsefcik Nice find :)

As a quick test, I did the following to see if that would work:

- Cloned the repo
- Edited the following files w/ your suggestion:
  - `packages/bruno-cli/src/runner/run-single-request.js`
  - `packages/bruno-electron/src/ipc/network/index.js`
- Following the steps provided in the contributing [README](https://github.com/usebruno/bruno/blob/main/contributing.md) on building Bruno
- Ran Bruno from the source build
- Ran the requests as I had before, and it worked :smile:

**Comment by martinsefcik** [comment]
@Shackelford-Arden 

> * Ran the requests as I had before, and it worked 😄

Great! I can prepare PR for that tomorrow.

**Comment by martinsefcik** [comment]
@geraintwjones @ivycristina Were you using also SOCKS proxy as @Shackelford-Arden when you had these errors ?

**Comment by martinsefcik** [comment]
> @Shackelford-Arden
> 
> > * Ran the requests as I had before, and it worked 😄
> 
> Great! I can prepare PR for that tomorrow.

I created separate issue #1419 for that and PR #1420

**Comment by ivycristina** [comment]
hello, I am using bruno-cli and wanted to generate a reports of the tests in html does it have this option?

**Comment by sanjai0py** [comment]
It seems that the issue has been resolved, so I am closing this.

**Comment by irharrier2** [comment]
@sanjai0py bruno-cli does not support this option. I think the best way to get around this is to enable accept self-signed certificates in collection setting so it can be picked up by bruno-cli. What do you think? should I create a separate issue?

**Comment by starlocke** [comment]
> @sanjai0py bruno-cli does not support this option. I think the best way to get around this is to enable accept self-signed certificates in collection setting so it can be picked up by bruno-cli. What do you think? should I create a separate issue?

Bruno's CLI supports "self-signed CA certificates" using the `--cacert` option. That did the trick for me today.

**Comment by g54799** [comment]
I am getting this error while using an http proxy. 
v1.32.1 and SSL/TLS verification is disabled.

**Comment by jmduke239** [comment]
Not working in Bruno 1.39.0 ...

**Comment by soffensive** [comment]
Try this to disable certificate validation entirely

`export NODE_TLS_REJECT_UNAUTHORIZED=0; bruno `
or to allow your specific CA:
`export NODE_EXTRA_CA_CERTS=~/yourca.pem; bruno`
