### ISSUE TITLE
Linux Homebrew

### ISSUE THREAD

**Issue by marcinjahn** [usebruno/bruno#2110]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Linux build on homebrew would be nice

### Mockups or Images of the feature

...

**Comment by AligningEntropy** [comment]
I believe this is not a feature that can be pursued as this application would be installed as a Cask which [Linux homebrew explicitly does NOT support](https://github.com/Linuxbrew/brew/issues/742#issuecomment-403657950).

**Comment by marcinjahn** [comment]
Right, flatpak is the way to go anyway
