### ISSUE TITLE
Linux flatpak

### ISSUE THREAD

**Issue by marcinjahn** [usebruno/bruno#2112]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Adding flatpak releases (on [flathub](https://flathub.org)) would be great

### Mockups or Images of the feature

.

**Comment by pietrygamat** [comment]
Adding verified, updated and correctly described release - that would be great Currently it looks a bit sketchy: https://flathub.org/apps/com.usebruno.Bruno.

**Comment by AligningEntropy** [comment]
Getting the Flatpak marked as verified I feel is increasingly important as some distros such as [Mint](https://www.phoronix.com/news/Linux-Mint-Unverified-Flatpaks) are starting to hide unverified flatpaks by default. 
[Here are the Developer Docs from Flathub](https://docs.flathub.org/docs/for-app-authors/verification) detailing the steps to get verified. Should hopefully be a pretty easy process.

**Comment by sanjai0py** [comment]
Closing this issue is marked as completed because the request to add Bruno to flatpak has been fulfilled.
