### ISSUE TITLE
Variables in Collection -> Folder

### ISSUE THREAD

**Issue by crimsonvspurple** [usebruno/bruno#2120]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I'd like to define some variables but not at global or collection levels. Instead, for some variables, defining on `folder` level makes more sense.

For example, I always do `GET {{endpoint}}` and so on in a request where the folder defines the `endpoint` (e.g., `{{baseUrl}}{{apiVersion}}{{users}}` )

Benefit of this structure is that when you need a new set of CRUD stuff for a new entity, just copy a folder and change entity name in one place. Saves a lot of time and hassle down the road.

### Mockups or Images of the feature

One idea could be reading `.vars.bru` from folders when resolving variables.

So:
- Global `x=1`
  - Environment `x=2`
    -  Parent Folder `x=3`
      - ...
        - Folder `x=n`
          - Request `x==n`

Ultimately, the request should find {{x}} = n.

**Comment by sanjai0py** [comment]
Closing this as the request for folder-level config has been implemented in bruno via this [PR](https://github.com/usebruno/bruno/pull/2529) and released in [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0)
