### ISSUE TITLE
cli does not yield specific exit codes for different problems

### ISSUE THREAD

**Issue by jzorn** [usebruno/bruno#2122]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When using the cli in build pipelines, it's helpful to be able to identify the different reasons why an invocation failed:

- assertion failed
- non-existing output dir
- environment not found
- invalid output format
- ...

By providing specific, immutable exit codes for all these scenarios, the pipeline/engineer can react appropriately without having to debug the error.

I propose to yield different exit codes for different problems via `process.exit(...)`.

### Screenshots/Live demo link

Running a collection with a failing assertion yields an exit code `1`:

```
$ bru run
...
$ echo $?
1
```

Running a collection with a non-existing environment prints an error message, but exits with `0` (successful):

```
$ bru run --env foo
Environment file not found: environments/foo.bru
...
$ echo $?
0
```

**Comment by helloanoop** [comment]
This has been released in `v1.19.0`
