### ISSUE TITLE
"Save" and "Save All" prompts on application close don't work

### ISSUE THREAD

**Issue by rm-code** [usebruno/bruno#2130]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When closing bruno with unsaved changes a prompt shows up (introduced via #1317):
![image](https://github.com/usebruno/bruno/assets/11627131/94269d31-139d-4660-858f-9438a398e950)

When clicking "Save All" in this prompt, nothing happens and an error is logged in the console:

![image](https://github.com/usebruno/bruno/assets/11627131/713085ec-f8d4-40e1-9f4e-98ea38104815)

The same happens for single unsaved tabs as well.

### Screenshots/Live demo link

See above.

**Comment by coltonehrman** [comment]
@rm-code I would like to take on this one

**Comment by coltonehrman** [comment]
@rm-code I wasn't able to reproduce this. Can you share some more context on what the changes that you made are? Maybe it is an erroneous change that causes a crash?

https://github.com/usebruno/bruno/assets/12456288/c7a422bd-603f-40ed-9457-a0f46ecd68a2

**Comment by rm-code** [comment]
I only tried it on a Windows 10 system. There were mutliple collections open, which are saved in different locations on the harddrive (although the unsaved changes only were in a single collection).

I will try to set up a clean example tomorrow.

**Comment by rm-code** [comment]
@coltonehrman I just tested it with only one collection being open and the issue persists. I'm using the portable option instead of the installer on windows. Not sure if that makes any difference.

**Comment by ponei** [comment]
I usually only save files at the end of the day, and this bug gets quite frustrating when you have 10+ changed files and need to save each one manually. I found a simple setup to reproduce this:

Bruno v1.13.1
Electron 21.1.1

**Steps to reproduce**
1. Create new collection
2. Create 2 new requests
3. Name them something
4. Add a JSON body to them
5. Click to close and click `Save all`


https://github.com/usebruno/bruno/assets/28790957/fae3672a-0377-4047-a26d-ce888b67b4f8

**Comment by busy-panda** [comment]
The PR from @therealrinku fixes this bug.
Could you please merge it ?
Thanks

**Comment by helloanoop** [comment]
Merged. Will be in the next outgoing release `v1.16.0`
