### ISSUE TITLE
Regression: Double-{} wrapped VARS no longer resolved in scripts

### ISSUE THREAD

**Issue by mrhrzg** [usebruno/bruno#2134]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Where this came up:
It was possible to extract a sub-string from the value saved in an environment dependent environmental variable (saved in the .env file).

Breakage:
Now if I use define a Pre Request Var in the VARS tab and load it in my Script:
`const cookie = bru.getVar('Cookie');`
then it is no longer resolved:
`console.log({cookie});`
returns `{{cookie}}`, where it used to return the value of the cookie env var, which I could work with in the script.

### .bru file to reproduce the bug

const envvar1 = bru.getVar('ev1');

console.log({envvar1});

req.setHeader("test", envvar1);
console.log(req.headers);

### Screenshots/Live demo link

![Screenshot 2024-04-19 at 12 02 01](https://github.com/usebruno/bruno/assets/36134546/ca8f5ca5-31d6-43b7-a0f3-8f15c449a0a2)

**Comment by mrhrzg** [comment]
@busy-panda What you tried misses the part that broke: The requests `Vars` can refer to environmental variables. Those are not resolved any more.
https://github.com/usebruno/bruno/assets/36134546/a6b6954c-580a-4e1c-9f9c-8666b5967ee9

**Comment by busy-panda** [comment]
I am checking, but why you don't retrieve directly from environment variable, instead of retrieve a variable that retrieve an environment variable ?

**Comment by sanjai0py** [comment]
Closing this because the [PR](https://github.com/usebruno/bruno/pull/2479) implementing the fix has already been merged.
