### ISSUE TITLE
pull request for wsse authentication

### ISSUE THREAD

**Issue by dwolter-emarsys** [usebruno/bruno#2137]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I'd like to add native wsse authentication. Here's my pull request: https://github.com/usebruno/bruno/pull/2136

### Mockups or Images of the feature

![Screenshot 2024-04-19 at 11 29 31 AM](https://github.com/usebruno/bruno/assets/42273062/89da304b-9b67-4778-a4a0-3c5dbbb4f1f9)

**Comment by helloanoop** [comment]
Closing this as this feature is now available in Bruno.
