### ISSUE TITLE
Add CHANGELOG file(s)

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#214]
As the release rythm increases (good !! 👏🏻), it could be good to have a clear list of changes, by "product" (cli, gui, etc.)

Could be done by following the [Keep a Changlog](https://keepachangelog.com/) principles (very common), for instance.

**Comment by helloanoop** [comment]
The changelog is currently maintained in two locations:

[Website](https://www.usebruno.com/changelog) - A curated version for easier readability.
[Release Notes](https://github.com/usebruno/bruno/releases) - Automatically generated by GitHub.
