### ISSUE TITLE
 BUG: OAuth2 Authorization Code Flow fails for intermediate redirects with an auth code

### ISSUE THREAD

**Issue by dakshin-k** [usebruno/bruno#2147]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

On similar lines as #1778, the authorization flow fails when there is a multi-step authorization, and one of the redirect URLs also contains `code` as a query parameter.

My example scenario where this happened:

Auth server: Keycloak using OIDC, backed by Google accounts as an ID provider
On successful auth, Keycloak sends an intermediate redirect to the following URL (Note the `code=` at the end):
```
https://<keycloak URL>/realms/<realm>/broker/google/endpoint?state=<state>&code=<code>&...
```

Since this URL has `code` as a query param but the URL is not the expected callback URL, Bruno throws the following error:

```
Error occurred in handler for 'send-collection-oauth2-request': Error: Invalid Callback Url: {url}
    at onWindowRedirect (/Users/dakshin/projects/personal/bruno/packages/bruno-electron/src/ipc/network/authorize-user-in-window.js:37:18)
    at EventEmitter.willRedirectListener (/Users/dakshin/projects/personal/bruno/packages/bruno-electron/src/ipc/network/authorize-user-in-window.js:78:7)
    at EventEmitter.emit (node:events:527:28)
```

### Screenshots/Live demo link

<img width="486" alt="image" src="https://github.com/usebruno/bruno/assets/36289388/669ddf55-863b-489b-9d7b-64a2248a198c">

**Comment by helloanoop** [comment]
This has been released in `v1.19.0`
