### ISSUE TITLE
[Feature request] Please allow br.setNextRequest() in the Test section of a request

### ISSUE THREAD

**Issue by tho-gru-38** [usebruno/bruno#2155]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Hi,

It would be very nice to get bru.setNextRequest() in the "Tests" section of a request too. In the "Tests" section I check the correctness of the response. In my opinion this is the right part were to decide if the response is so bad, that it does not make sense to continue with the collection. As consequence I what to execute the bru.setNextRequest() to skip some requests or terminate the collection run at all.

As the current request is executed as all scripts (post response, tests) are finished I do not see any conceptional problem to set the next request in the test section too.

Kind Regards
Thomas

### Mockups or Images of the feature

![image](https://github.com/usebruno/bruno/assets/152491463/d5f10d6b-56a9-430f-8e1e-51fdda3536fd)

**Comment by BruAlcaraz** [comment]
Hi @tho-gru-38 I have created a PR with the changes to allow the use of bru.setNextRequest() at the test scripts. Let's hope that the maintainers approve it.

**Comment by TheBatman09** [comment]
Hello, just passing by looking for a feature, shouldn't this be closed ?

**Comment by tho-gru-38** [comment]
As this feature is implemented, it can be closed.
