### ISSUE TITLE
Error invoking remote method 'send-http-request': TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by petterjohansson** [usebruno/bruno#2158]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Simple get request throws the error message:
Error invoking remote method 'send-http-request': TypeError: Cannot read properties of undefined (reading 'data')

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/12429224/f84abd14-24a9-437d-bac8-f6ea2e6c3fcf)
![image](https://github.com/usebruno/bruno/assets/12429224/e6270031-2973-4283-a6b7-0588c11a054f)
<img width="389" alt="image" src="https://github.com/usebruno/bruno/assets/12429224/fc19289b-2af6-4ea0-9be1-c77902e8a913">

**Comment by MrMarlin** [comment]
I am also experiencing this bug on get and post requests on Manjaro.

**Comment by reneeshr** [comment]
Hey @petterjohansson 

Are you using any custom scripts in `Vars` or `Tests` for this API request? 
I faced similar issues when I started with Bruno and it was resolved when I fixed the script syntax in the Tests.

**Comment by petterjohansson** [comment]
Hi @reneeshr 
Just found the error, my firewall prevented https calls through Bruno. The error message from bruno didn't make much sense though. :)
