### ISSUE TITLE
Opening a collection properties panel shows up blank

### ISSUE THREAD

**Issue by gkohen** [usebruno/bruno#217]
On MacOS Intel Ventura When opening using the UI the properties it comes up blank.
Any idea what might be going wrong?
The collection is an imported Postman collection.
Thank you.

https://github.com/usebruno/bruno/assets/2158006/389293dd-248c-471e-8f53-1f43c3e5dbae

**Comment by helloanoop** [comment]
Hey @gkohen 

Collection Properties is a fairly small component.
I took a quick look at the code. I think this [part](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/components/Sidebar/Collections/Collection/CollectionProperties/index.js#L38) might be causing an undefined access error.

Can you create an environment inside the collection and see if you still see a blank screen ?

**Comment by gkohen** [comment]
Yup. That was it. It's not dealing with a non existing collection. It should probably be a bit more resilient. 
After I added an env I see the properties panel(alas with string overflowing which we can fix by changing the HTML). 
![image](https://github.com/usebruno/bruno/assets/2158006/9f380503-ce28-4e03-9fbb-79e0afb79c40)

**Comment by l0new4nder3r** [comment]
Same issue on windows, latest version (v0.15.2).
When there is no environment, when selecting "Properties", it turns to a blank page and the app needs to be restarted.

**Comment by helloanoop** [comment]
This has been fixed and been released in v0.15.3 🎉

**Comment by gkohen** [comment]
Thank you @helloanoop. Was 0.15.3, in fact, released as I see the latest as 0.15.2
![image](https://github.com/usebruno/bruno/assets/2158006/eea6ea73-7f11-4c7b-b4f0-eb9bd811f0dd)

**Comment by helloanoop** [comment]
Yes, it was released. You can download the latest version from the website.

We use GitHub badges on the readme and may take some time to reflect the latest tag.

**Comment by helloanoop** [comment]
The text overflow was not handled. 
Go ahead and take a crack at it @gkohen

**Comment by gkohen** [comment]
PR created: https://github.com/usebruno/bruno/pull/240

**Comment by helloanoop** [comment]
Thank you @gkohen !

This has been released in `v0.16.3`🎉
