### ISSUE TITLE
Import of freshly exported Bruno Collection fails

### ISSUE THREAD

**Issue by angelaatskandia** [usebruno/bruno#2182]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When importing a Bruno collection that was created using Export (GUI) the collection is not imported and tooltip saying "import collection failed".

The problem has been seen for other collections as well and on different versions  v1.12.1, v1.13.0, v1.14.0

How to reproduce (see screenshots)
1. Chose to Export the Collection 
3. Closed the Collection 
4. Chose to import Bruno Collection using the "three dots"
5. Selected the json file cerated under step 1
6. Received error tooltip saying "import collection failed"

### Screenshots/Live demo link

![1Export](https://github.com/usebruno/bruno/assets/166131467/af61127a-38fc-4e2b-a4c6-eea00804daef)

![2SelectingBrunoExport](https://github.com/usebruno/bruno/assets/166131467/750fd3c2-8512-4a71-a184-34abe40264db)

![3ImportUsingThreeDots](https://github.com/usebruno/bruno/assets/166131467/be960b27-1e59-49ae-9713-a5422afa2ce9)

![4SelectingBrunoCollection](https://github.com/usebruno/bruno/assets/166131467/59946146-da39-4513-851b-d401893486f0)

![5ErrorTooltip](https://github.com/usebruno/bruno/assets/166131467/9e591730-692e-4af8-9f60-d614a2e2a4ab)

**Comment by DmytroCrawford** [comment]
Is this failure not caused because the collection exported and the collection being imported have the same name?

**Comment by krummbar** [comment]
> Is this failure not caused because the collection exported and the collection being imported have the same name?

No this looks like a parsing issue. I tried it with [bruno-testbench](https://github.com/usebruno/bruno-testbench) collection. When exporting/importing, this error is dumped in the console

```
ValidationError: items[5].type must be one of the following values: http-request, graphql-request, folder
    at Object.createError (_app-9570891bf88d2432.js:36:69067)
    at Object.test (_app-9570891bf88d2432.js:39:3708)
    at validate (_app-9570891bf88d2432.js:36:69324)
    at runTests (_app-9570891bf88d2432.js:36:66715)
    at _app-9570891bf88d2432.js:39:758
    at _app-9570891bf88d2432.js:36:66448
    at _app-9570891bf88d2432.js:36:66968
    at _app-9570891bf88d2432.js:36:69388
897-fea41f0406a7d7c9.js:1 BrunoError: The Collection file is corrupted
    at 897-fea41f0406a7d7c9.js:1:5447
```

Looking at the JSON file, the fith element look like this

```json
  {
      "type": "json",
      "name": "bruno",
      "seq": 1
    }
```

After removing it, the collection imports just fine, also with the same name. I'd gladly try to fix this, but I'm not sure how to deal with this element. I'm wondering about the intention of that item

- Should it be excluded during the exporting?
- Should it be ignored while improting?
- Should it be considered on import, and what does it do?

**Comment by sanjai0py** [comment]
Closing this as the issue has already been fixed. Thank you all for taking the time to report the bug!

**Comment by jonas-lomholdt** [comment]
Just saving a collection and trying to re-open it like this fails.
