### ISSUE TITLE
Button freezes when quit without saving files.

### ISSUE THREAD

**Issue by deepraj02** [usebruno/bruno#2195]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Using the latest version of Bruno in my M1 Apple Silicon.

When I tried quitting the app without saving the files, a pop up appears with 3 options of which the save button is not working as intended and appear to be freezed..

### .bru file to reproduce the bug

It's an UI issue I guess

### Screenshots/Live demo link

https://github.com/usebruno/bruno/assets/63138398/b312943d-c5a6-4028-913c-8a43115ea6f7

**Comment by rm-code** [comment]
Check out #2130. There are currently two PRs waiting to fix this problem via #2156 and #2157.

**Comment by sanjai0py** [comment]
The latest version of Bruno has resolved the issue. Thank you for reporting it!
