### ISSUE TITLE
CLI Test Runner ignores auth:"inherit" in requests

### ISSUE THREAD

**Issue by gajanak** [usebruno/bruno#2206]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

If I run "bru run collection.bru" - it fails because its not a request.

If I run "bru run request.bru" - and the request use auth:"inherit" - the Collection Auth Settings are not read.
And there is no error - that inherit is not supported on cli.

Perhaps the cli runner should search for the collection  or
a command line parameter to specify the collection directory or file 
or cli runner should abort "Auth inherit is not supported..:"

### Mockups or Images of the feature

@usebruno/cli

bru run request.bru --env local

Error: Auth inherit is not supported. ?

Better:

Read Auth Settings from collection.bru

**Comment by pietrygamat** [comment]
@helloanoop please prioritize this - it's a trivial fix to a serious bug introduced in 1.16.0

**Comment by helloanoop** [comment]
Thanks for the PR @pietrygamat ! Merged!

I have release Bruno CLI `v1.16.0`
