### ISSUE TITLE
JSON String containing a number is sent as a number, not a string

### ISSUE THREAD

**Issue by e-moran** [usebruno/bruno#2207]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

If the body type is set to JSON and a JSON String containing a number is entered then it will be converted to a JSON Number before being sent.

### Screenshots/Live demo link

<img width="2330" alt="image" src="https://github.com/usebruno/bruno/assets/37004949/85b88c12-4ca4-42fe-a57c-1d8578575bb5">

This screenshot shows the result of hitting an endpoint that reflects the received bytes exactly.

**Comment by misaelvillaverde** [comment]
Something similar happens to me. If I send any number bigger than 15 digits (including `.`) it will convert it to a string
![CleanShot 2024-04-30 at 12 00 46@2x](https://github.com/usebruno/bruno/assets/30275501/d15f70b0-0908-4d0a-969e-d5e28485e760)

**Comment by jaakla** [comment]
My case:
a) converted from number to string, and **rejected** by my used server as 'wrong type':
```
          "lat": 53.07705961249196,
          "lng": -1.1654971750050664,
```
 b) not converted, works as number, **all good**
```
         "position": {
          "lat": 51.6552,
          "lng": -0.3471,
```

**Comment by jwetzell** [comment]
related to #2438 I believe. The JSON parser that is being used seems less than ideal.

**Comment by helloanoop** [comment]
This has been fixed as a part of PR https://github.com/usebruno/bruno/pull/2773, and will go out in the v1.27.0 release.
