### ISSUE TITLE
Pre Request vars in request not getting proper value

### ISSUE THREAD

**Issue by PAllisonVSO** [usebruno/bruno#2215]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

My apologies if this is reported, my search skills did not render it. After version 1.14 of bruno, Pre Request vars that are used in the request do not have the proper value the first time they are called. They may have a value from another request or no value. Submitted the request a second time yields the expected results.

### .bru file to reproduce the bug

meta {
  name: test
  type: http
  seq: 2
}

get {
  url: https://github.com/{{repository}}
  body: none
  auth: none
}

vars:pre-request {
  repository: usebruno
}

### Screenshots/Live demo link

First submit
![image](https://github.com/usebruno/bruno/assets/155454754/10186710-29a4-43f7-9f26-b9b956fc5ff2)
Second submit
![image](https://github.com/usebruno/bruno/assets/155454754/93fb9b92-751f-4640-90ec-29737b093631)

**Comment by PAllisonVSO** [comment]
I have tested version 1.17.0. The variable does get assigned the first time, but if I change the value, the new value is is not used the first time. So it takes two clicks to get the proper value to be sent after the initial usage.

![image](https://github.com/usebruno/bruno/assets/155454754/ccaf0f37-8ef9-4196-ae5d-c9b90058fc74)

**Comment by ggiambo** [comment]
> I have tested version 1.17.0. The variable does get assigned the first time, but if I change the value, the new value is is not used the first time. So it takes two clicks to get the proper value to be sent after the initial usage.

Hi @PAllisonVSO,
I had the same problem, thank you for reporting it, you saved me some headache.
Looks like the newest version 1.18.0, fixed the issue, can you confirm it?

**Comment by conor-carville** [comment]
@ggiambo I am still seeing this issue on version 1.18.0

**Comment by PAllisonVSO** [comment]
I am out of the office until next week. I will test it as soon as I can!

**Comment by PAllisonVSO** [comment]
I have checked and verified that this issue is fixed as reported.
