### ISSUE TITLE
Collection level auth not working anymore

### ISSUE THREAD

**Issue by shihabmridha** [usebruno/bruno#2223]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Collection level auth (bearer token) is not working anymore.
It used to work. After upgrading to the newest version, it's not working.

In the second screenshot below you can see the auth token is not included in the request.

### Screenshots/Live demo link

Collection level setup:
![image](https://github.com/usebruno/bruno/assets/3264156/37a2bdf7-d3a2-4858-b950-6f42fe168c74)

The timeline of a sample request:
![image](https://github.com/usebruno/bruno/assets/3264156/13ab4139-d926-4410-ae97-75e462f98857)

**Comment by igor-topolski** [comment]
Have you tried adding it in the header as `Authorization: Bearer {{token}}` - that's what I had to do for OAuth2.

**Comment by shihabmridha** [comment]
Hey, @lohxt1

Check with `inherit` and its working again.
_Note: I used to select the default one which is "No Auth" if I am not wrong._

![image](https://github.com/usebruno/bruno/assets/3264156/d5c53f6b-0b16-4881-8b9b-987af87c22d7)


Thanks
