### ISSUE TITLE
[BUG] Issue with eval()

### ISSUE THREAD

**Issue by tho-gru-38** [usebruno/bruno#2228]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Hi,

In my Pre Request script I used the following code:

``` js
console.log("010-Get-01: Pre Request");

let text = '{"employees":[' +
'{"firstName":"John","lastName":"Doe" },' +
'{"firstName":"Anna","lastName":"Smith" },' +
'{"firstName":"Peter","lastName":"Jones" }]}';

var obj = JSON.parse(text);
var employee = obj.employees[1].firstName + " " + obj.employees[1].lastName;
console.warn("employee[1] = " + employee);

var employeeStr = 'obj.employees[2].firstName + " " + obj.employees[2].lastName';
console.warn("employeeStr = " + employeeStr);

var employee = eval(employeeStr);
console.warn("eval(employeeStr) = " + employee);
```

When sending the request I get the message:
Error invoking remote method 'send-http-request': ReferenceError: obj is not defined

The last console message ist not displayed. So I assume that the eval statement causes the error.

When executing the same script directly in firefox everything work fine.

Kind Regards
Thomas

### .bru file to reproduce the bug

[010-GET-01.zip](https://github.com/usebruno/bruno/files/15198042/010-GET-01.zip)

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/152491463/d9c236a8-e869-4bbc-bd86-97e77be84e69)

**Comment by leoferreiralima** [comment]
Hi @tho-gru-38.

I think you dont need eval at all, you can as the employee[1], but if you want use eval try this

```js
console.log("010-Get-01: Pre Request");

let text = '{"employees":[' +
'{"firstName":"John","lastName":"Doe" },' +
'{"firstName":"Anna","lastName":"Smith" },' +
'{"firstName":"Peter","lastName":"Jones" }]}';

var obj = JSON.parse(text);

console.log(obj)

var employee = obj.employees[1].firstName + " " + obj.employees[1].lastName;
console.warn("employee[1] = " + employee);

var employeeStr = '(obj) => obj.employees[2].firstName + " " + obj.employees[2].lastName'; // return a method as string
console.warn("employeeStr = " + employeeStr);

var employee = eval(employeeStr)(obj); // pass the obj here
console.warn("eval(employeeStr) = " + employee);
```

**Comment by tho-gru-38** [comment]
Hi @leoferreiralima,

Thanks for your quick replay.

Your provided solution works well.

Kind Regards,
Thomas

**Comment by leoferreiralima** [comment]
@tho-gru-38 if the solution work maybe this issue can be closed!

**Comment by tho-gru-38** [comment]
Thanks for your reminder.

I did not know that I can close the issue.
