### ISSUE TITLE
Support formatting/prettifying GraphQL request variables

### ISSUE THREAD

**Issue by Eynorey** [usebruno/bruno#2265]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

There's already a "Prettify" button for GraphQL queries/mutations, but not for the JSON variables editor.

Would like to propose to add such a button to the `CodeEditor` component (should be opt-in for consumers of that component) so that it can be made available to the GraphQL variables editor and potentially other places (such as `QueryResultPreview` to allow for formatting response bodies).

As is already the case with the GraphQL query editor, `prettier` should be able to do the job just fine here.

### Mockups or Images of the feature

![image](https://github.com/usebruno/bruno/assets/20454271/59aa2e12-0c3f-44ef-b84a-42b724dc1adb)

**Comment by RyPeck** [comment]
This looks done! Thank you!
