### ISSUE TITLE
Cannot rename requests if collection folder is a WSL path

### ISSUE THREAD

**Issue by xav-pain** [usebruno/bruno#2269]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Similar matter to #159 : since WSL paths are network paths, the way bruno tries to rename request .bru files result in an error

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/167071380/cd9a7193-b3c2-4717-a623-4c5ee773c2c3)

**Comment by helloanoop** [comment]
Just merged the PR for the fix.
This will go out in `v1.26.2` release
