### ISSUE TITLE
No JSON response formatting

### ISSUE THREAD

**Issue by Blond11516** [usebruno/bruno#227]
The screenshot in the README appears to show the JSON response being formatted, with folding of arrays and objects. However, I am not seeing this functionality in Bruno 0.16.0. Here is an example of a response that I believe should be formatted:

<img width="1295" alt="Screenshot 2023-09-27 at 10 19 44 PM" src="https://github.com/usebruno/bruno/assets/44734484/7135d296-6615-4b2f-9f01-ef7762715a5b">

**Comment by helloanoop** [comment]
@Blond11516 This bug got accidentally introduced in a refactor effort. Thank's for filing the issue.

This has been fixed and released in `v0.16.1`
Please install and download the latest version.

**Comment by helloanoop** [comment]
Tested in `v0.16.1`

![image](https://github.com/usebruno/bruno/assets/9350733/1616d275-6070-477a-a5f2-65d84ba30415)

**Comment by Blond11516** [comment]
Thanks for the quick fix!
