### ISSUE TITLE
Feature Request: OAuth2 support for sending in state for Authorization Code flow

### ISSUE THREAD

**Issue by werge2121** [usebruno/bruno#2275]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Our OAuth2 provider requires a state param to be sent in. With the current implementation of Authorization Code we get back an error stating "The authentication request has an invalid 'state' parameter." A textbox under scope where we can enter the state param would be nice like other oauth clients.

### Mockups or Images of the feature

<img width="443" alt="image" src="https://github.com/usebruno/bruno/assets/1161543/a6423f18-c5a3-401e-912b-0411696cfb92">

**Comment by pietrygamat** [comment]
Implemented in #2114

**Comment by pietrygamat** [comment]
@werge2121 can we reopen this? It's important feature, but still not merged.

**Comment by anusree-bruno** [comment]
This has been added. Closing the ticket
