### ISSUE TITLE
Error invoking remote method 'renderer:new-request': TypeError: Cannot read properties of null (reading 'includes'), when create `form-urlencoded` request from cURL

### ISSUE THREAD

**Issue by leonardoyhl** [usebruno/bruno#2288]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

v1.17.0 on MacOS 10.15.7
When create a new `form-urlencoded` request from cURL, toast that `Error invoking remote method 'renderer:new-request': TypeError: Cannot read properties of null (reading 'includes')`.

### Screenshots/Live demo link

<img width="523" alt="image" src="https://github.com/usebruno/bruno/assets/34596552/f4497e20-e6d3-41e6-9f7c-0c33f6657ce5">

### How to reproduce the problem?

Some parameter(s) in `form-urlencoded` type data missing `=`, like `param2` parameter below.
e.g.:
```shell
curl 'https://example.com/api' \
  -H 'content-type: application/x-www-form-urlencoded' \
  --data-raw 'param1=1&param2'
```

**Comment by leonardoyhl** [comment]
### Why?

When parsing `cURL` command, app will use `query-string` to parse `form-urlencoded` type data string. If some parameter(s) in `form-urlencoded` type data string missing `=`, `query-string` will set value as `null`([Missing `=` should be `null` · sindresorhus/query-string](https://github.com/sindresorhus/query-string/blob/3d8fbf2328220c06e45f166cdf58e70617c7ee68/base.js#L364-L366)).
<img width="1234" alt="image" src="https://github.com/usebruno/bruno/assets/34596552/1c2e5d73-6650-4b70-af6d-46adbfab6c7b">
<img width="1006" alt="image" src="https://github.com/usebruno/bruno/assets/34596552/768070e9-78af-4c6e-bffb-7d01bd5a6b4e">

But it isn't a bug, just a feature following W3 specification(https://www.w3.org/TR/2012/WD-url-20120524/#collect-url-parameters).
<img width="1276" alt="image" src="https://github.com/usebruno/bruno/assets/34596552/c80a0194-7b90-4ab8-8fee-40edb3d8d14e">

**Comment by helloanoop** [comment]
I have merged the PR @leonardoyhl !
Thanks for taking time to go through the W3 spec and make these fixes in Bruno!

This will get shipped in the release scheduled to go out today.
