### ISSUE TITLE
[BUG] Certain requests result in blank white window

### ISSUE THREAD

**Issue by underhood** [usebruno/bruno#229]
#### OS
Fedora Workstation 38 AMD64
#### Bruno
appimage downloaded from usebruno.com
```
Bruno v0.16.1
electron: 21.1.1
chrome: 106.0.5249.103
node: 16.16.0
v8: 10.6.194.17-electron.0
```

### Description
Certain (always the same) seemingly innocuous GET queries result in bruno stuck in white window mode (for lack of better term). Same queries work with insomnia and wget/curl and the likes. See screenshot
![Screenshot from 2023-09-28 12-46-08](https://github.com/usebruno/bruno/assets/6674623/02dcf9ef-b54b-4740-87ae-474722d92ff8)

other queries work well.

Pre query execution all looks normal:

![Screenshot from 2023-09-28 12-48-47](https://github.com/usebruno/bruno/assets/6674623/c2b23719-6347-4449-9d98-14ae05448038)

**Comment by underhood** [comment]
in insomnia it works well:

![Screenshot from 2023-09-28 12-49-40](https://github.com/usebruno/bruno/assets/6674623/2342bf8e-23d9-4836-9e65-e5c232f22bd5)


![Screenshot from 2023-09-28 12-50-05](https://github.com/usebruno/bruno/assets/6674623/45fe2d26-d3ae-487e-a513-988fd7099918)

**Comment by helloanoop** [comment]
@underhood Can you toggle dev tools. There should be a stack trace in console that help us identify the cause.

**Comment by helloanoop** [comment]
We also need to configure the Error Boundary in nextjs code properly so that stack traces of crashes are displayed on the screen instead of showing a white page.

**Comment by underhood** [comment]
![Screenshot from 2023-09-28 13-12-42](https://github.com/usebruno/bruno/assets/6674623/c50b54a5-f895-4742-9a41-9f4e427e0d41)

**Comment by helloanoop** [comment]
Currently working on adding error boundary so that users can easily report bugs by sharing the stack trace
![image](https://github.com/usebruno/bruno/assets/9350733/0a45b6b0-58ba-4c6a-a55d-c8f9c003a94b)

**Comment by helloanoop** [comment]
@underhood I have fixed this in the latest release `v0.16.4`

Can you install the latest version and check it ?

**Comment by underhood** [comment]
Works as expected with latest version.
Thanks

**Comment by underhood** [comment]
@helloanoop nice and quick fix, any way to send a beer over the net?
