### ISSUE TITLE
Update Bruno to latest version from GUI

### ISSUE THREAD

**Issue by hornta** [usebruno/bruno#2300]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I want to easily update Bruno from the program itself instead of having to download a new binary.

### Mockups or Images of the feature

-

**Comment by marfranke** [comment]
Possible duplicate: https://github.com/usebruno/bruno/issues/103

**Comment by NiklasBr** [comment]
Also mentioned here: https://github.com/usebruno/bruno/issues/1331#issuecomment-1878506060

**Comment by sanjai0py** [comment]
Duplicate of #103
