### ISSUE TITLE
[SUGGESTION] About Bruno dialog should allow copy version info

### ISSUE THREAD

**Issue by underhood** [usebruno/bruno#231]
When reporting a bug I noticed bruno about dialog is not allowing me to copy the bruno version info text. This forced me to type the versions manually. The dialog should allow to mark and copy the text or have a "copy version data to clipboard" button.

![Screenshot from 2023-09-28 12-55-51](https://github.com/usebruno/bruno/assets/6674623/c3a57bba-28f9-4aba-838e-e6211677e901)

#### OS
Fedora Workstation 38 AMD64
#### Bruno

appimage downloaded from usebruno.com
```
Bruno v0.16.1
electron: 21.1.1
chrome: 106.0.5249.103
node: 16.16.0
v8: 10.6.194.17-electron.0
```

**Comment by helloanoop** [comment]
The icon has been fixed in `vo.16.5` thanks to @mirkogolze , and the text below the version number is copyable.
Ideally we also need to copy the version number.

Currently when you hover over the version number it becomes a pointer - upon click takes you to the website.
I think we don't need to redirect a user to website upon click, we need to configure it so that its just text and can be selected

![image](https://github.com/usebruno/bruno/assets/9350733/c4cc2a71-daf4-4656-abf6-8615b7c896fe)

**Comment by mirkogolze** [comment]
I am able to select all version information.

I made the title and version information selectable. Only the description will not be selected.
With the correct mouse position you can select all from top to down and from down to top works too.
![image](https://github.com/usebruno/bruno/assets/66121941/e15e04a4-47b0-42de-9551-dcc109c5dc5c)

**Comment by underhood** [comment]
Confirm icon is fixes in latest release. I can also select as per screenshot above. When I do CTRL+C with everything selected and paste here I get:
```
<h2 class="title clickable" style="margin: 0.2em; cursor: pointer; app-region: no-drag; user-select: text; color: rgb(51, 51, 51); font-family: Helvetica, Arial, &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS PGothic&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Bruno v0.17.0</h2><h3 class="description" style="margin: 0.2em 0.2em 1em; text-align: center; color: rgb(51, 51, 51); font-family: Helvetica, Arial, &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS PGothic&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Opensource API Client for Exploring and Testing APIs</h3><div class="copyright" style="margin: 0.2em; color: rgb(153, 153, 153); font-family: Helvetica, Arial, &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS PGothic&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div>

electron | : 21.1.1
-- | --
chrome | : 106.0.5249.103
node | : 16.16.0
v8 | : 10.6.194.17-electron.0

```
