### ISSUE TITLE
Headers are not saved 

### ISSUE THREAD

**Issue by jthln** [usebruno/bruno#232]
When adding headers to a request these seem not to be persisted (v0.16.1, Mac Apple Silicon).
When leaving Bruno and starting Bruno again, the headers entered for the request before are gone.

Is this a bug or a missing feature?

<img width="666" alt="image" src="https://github.com/usebruno/bruno/assets/11569543/4340b171-3e6d-4c6a-9f2d-14039152e6e9">

**Comment by helloanoop** [comment]
Did you save the request by pressing Cmd+S

If a request is not saved, you should see a tiny yellow dot in the request tab.

**Comment by jthln** [comment]
Using Cmd + S works, thank you :)

I didn't see a Save button and wrongly assumed that the values will automatically be saved.
