### ISSUE TITLE
Icons Lack Descriptions, Causing Usability Issues

### ISSUE THREAD

**Issue by jeevankumarj25** [usebruno/bruno#2327]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

In the Bruno API client, the icons at the top right  of the interface do not have descriptive tooltips or labels. This makes it hard for users to understand what each icon does. When users scroll through the interface, it is even more difficult to figure out the purpose of each icon. Clear descriptions or tooltips are essential for easy navigation and effective use of the tool.

### Screenshots/Live demo link

<img width="960" alt="no descriptions" src="https://github.com/usebruno/bruno/assets/118682799/9cb8e07a-4a12-414e-b83e-93148e1437b3">

**Comment by hugohutri** [comment]
👍🏻 
The bottom left icons could use some tooltips as well:
![image](https://github.com/user-attachments/assets/6a7ec750-912e-4f21-9fb0-58f3e76b93b5)
(Related note: The cog -icon is the same in bottom-left, and top-right icons, but they have completely different actions, making this even more confusing if tooltips aren't added)
