### ISSUE TITLE
[BUG] Variables don't work in Body, values not extracted.

### ISSUE THREAD

**Issue by Rzpeg** [usebruno/bruno#233]
Variable templates don't expand into values in body, like this JSON:

{
    "access_token": "{{token}}",
    "clientVersion": "1.0.0.0"
}

The {{token}} variable exists, and works if placed in URL segment.

v 0.16.1

**Comment by Rzpeg** [comment]
Windows 11, Update 2H2.
It works if I change body type from JSON to TEXT though.

**Comment by Rzpeg** [comment]
It also works if I set body type to JSON **and** remove the Content-Type header. 
But if I keep Content-Type = "application/json" it stops working

**Comment by helloanoop** [comment]
@Rzpeg Thanks for getting to the root of this. I have the fix ready. Will deploy a new version in 30min.

**Comment by helloanoop** [comment]
Fix has been released in `v0.16.2`

You can download and install the latest version.

Thanks again @Rzpeg !

**Comment by Rzpeg** [comment]
Works perfectly! Thanks!
P.S. I was wondering why you had no XPath implemented for XML response, but then I found out I can install and use external npm packages, so I wrote the script to parse XPath. Just leaving it here for the case if you want to implement XPath natively, as this might be the feature that the Insomnia refugees will miss here:

```
const xpath = require('xpath');
const dom = require('xmldom').DOMParser;

const doc = new dom().parseFromString(res.body, 'text/xml');
const query = "//*[local-name()='AuthToken']/text()";
const token = xpath.select(query, doc)[0].nodeValue;

bru.setVar("token", token);
```

**Comment by helloanoop** [comment]
> I found out I can install and use external npm packages

Isn't that beautiful?
That you can use any package of your choice at a collection level. Something that has been missing for an entire decade in the GUI API Clients ecosystem.

> I was wondering why you had no XPath implemented for XML response

Currently Bruno supports these inbuilt libraries - https://docs.usebruno.com/scripting/inbuilt-libraries.html
I agree that `xpath` and `xmldom` are great package candidates to support as an inbuilt library.

**Comment by Rzpeg** [comment]
> Isn't that beautiful?
> That you can use any package of your choice at a collection level. Something that has been missing for an entire decade in the GUI API Clients ecosystem.

Yep, that's a lot of possibilities! That is what allowed me to implement xpath :) And this is how I am planning to implement file upload, using fs-extra or something similar . 

This also could also eventually opens ways for people to write 3rd party plugins, and export functions to be consumed in bru 👍

**Comment by helloanoop** [comment]
Cool. `fs-extra` will not work in current build.
File access is disabled for security reason.

I will release a patch for today that will allow to turn off this restriction at collection level 

Something like this in `bruno.json`
```javascript
{
  ""allowScriptFilesystemAccess" : true
}
```

**Comment by Rzpeg** [comment]
> Cool. `fs-extra` will not work in current build. File access is disabled for security reason.
> 
> I will release a patch later today that will allow to turn off this restriction at collection level
> 
> Something like this in `bruno.json`
> 
> ```js
> {
>   ""allowScriptFilesystemAccess" : true
> }
> ```

Hey! Just wondering if the patch mentioned is included in the latest version? (v0.16.6)

**Comment by helloanoop** [comment]
@Rzpeg Can you share the way you solved your `xpath` and `xmldom` issue in Scriptmania- https://github.com/usebruno/bruno/discussions/385
It would benefit the community.

**Comment by standej** [comment]
Hello guys, I have same problem here. Here is my json body:
<img width="767" alt="image" src="https://github.com/usebruno/bruno/assets/6781221/c1831c4c-3466-4f97-9e7d-1efecab1b047">
This is what is created in database:
<img width="149" alt="image" src="https://github.com/usebruno/bruno/assets/6781221/0efb902f-ff63-406d-8b82-79ab7f5cca76">
and here are mine env vars:
<img width="326" alt="image" src="https://github.com/usebruno/bruno/assets/6781221/628e5402-dc41-4a42-9277-9df9088257f6">

Do you have any idea why my var "login" doesnt want to go green like other vars that are working?
I tried also with regular var (collection var) and it resulted same:
<img width="119" alt="image" src="https://github.com/usebruno/bruno/assets/6781221/403a81ed-c707-487b-baa9-de12d9ae605b">

Also here is my pre request script:
`bru.setEnvVar("login", Math.round(Math.random() * 100000));`

Bruno version 0.25.0

**Comment by fcmss** [comment]
Hello,
I noticed a bug related to that.
I have a variable named "PublishedOn" which is an array of string
![image](https://github.com/usebruno/bruno/assets/126145807/555a22ae-fe72-4c30-b129-c379dee76b0a)

However, I get a parse error when putting it into a JSON body, like so:
![image](https://github.com/usebruno/bruno/assets/126145807/40c3e12e-dbef-4931-aa49-24c4d8b9e806)

The quick fix that I found was to "prettify" the JSON. It still shows as an error, yet still manages to send the request with the correct variable (an array of string):
![image](https://github.com/usebruno/bruno/assets/126145807/626fd77d-6aca-42aa-99e5-a3f13016ed6e)

**Comment by marshall-davis** [comment]
> Working for me. Which OS? Would you be able to create and share a sample collection ?
> 
> On my mac I see this parsing working Parsing body ![image](https://private-user-images.githubusercontent.com/9350733/271280143-7190b583-05cb-4744-ae2d-312caf365363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjIxOTMsIm5iZiI6MTcxODEyMTg5MywicGF0aCI6Ii85MzUwNzMzLzI3MTI4MDE0My03MTkwYjU4My0wNWNiLTQ3NDQtYWUyZC0zMTJjYWYzNjUzNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMTYwNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNmZDEyMmM5M2I5ZTE1NjYwN2E5OTc3MzU5NGFjNTBjOWI1MjEzMDQwYzc4MjM3YzM4YWUzYmYzOGYzMTA0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e6_3daEE4Xfyi6kSTGtDDuCTrnmboMjcyzp8acSzqXM)
> 
> My Env ![image](https://private-user-images.githubusercontent.com/9350733/271280217-b821c476-5c86-45cc-a24c-adbda1e9a2bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjIxOTMsIm5iZiI6MTcxODEyMTg5MywicGF0aCI6Ii85MzUwNzMzLzI3MTI4MDIxNy1iODIxYzQ3Ni01Yzg2LTQ1Y2MtYTI0Yy1hZGJkYTFlOWEyYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMTYwNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNkZTNjYTBiZDYwODlhNDcxMGI0ZjBiODM2YTYzZmE0MjJjNzdhMGUxZmQ1ODFlNTUyZmUxZDNhNzcyOTMxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pGBlly4q_SfbBNV0FkhyPGxOiMJX-Z9S0Eb5Rrq6Fw0)

What about if it's in the request vars?
