### ISSUE TITLE
Can't rename request from Bruno Windows on WSL `.bru` files

### ISSUE THREAD

**Issue by mathisgauthey** [usebruno/bruno#2342]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I use Bruno Windows on my project that is store inside WSL. I code from VS Code Windows that is remotely connected to my WSL.

I get this error while trying to modify a request name.

```
Error invoking remote method 'renderer:rename-item': Error: ENOENT: no such file or directory, open '/wsl.localhost/Ubuntu/home/mat/documents/odoo-dev-env/addons/ERASED-odoo-addons/API/DEMO AUTH.bru'
```

### .bru file to reproduce the bug

```
meta {
  name: AUTH
  type: http
  seq: 7
}

post {
  url: {{BASE_URL}}/auth
  body: json
  auth: none
}

headers {
  Content-Type: application/json
}

body:json {
  {
    "params": {
      "login": "demo",
      "password": "demo",
      "db": "{{DB}}"
    }
  }
}
```

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/46576952/508d5e2e-37f8-4a6b-8628-28f40370185b)

EDIT: Mea culpa, I just found out another person had the same issue recently : #2269 

As a current workaround, I modify the `.bru` file from VS Code, but it is less than optimal. Saving cause no issues, creating new request as well, so I guess we can write inside the file without issue but can't rename a `.bru` file from Bruno.

**Comment by helloanoop** [comment]
Just merged the PR for the fix.
This will go out in `v1.26.2` release
