### ISSUE TITLE
Minor update needed in the French translation

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#2343]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Minor changes occurs in the English version of the Readme file that need to be translated into the French version (for isntance, the Github Sponsor link).

This issue is part the PR requirements.

### Mockups or Images of the feature

N/A

**Comment by jwetzell** [comment]
@sanjai0py @lohxt1 the PR for this issue was closed so this issue likely can be closed.
