### ISSUE TITLE
Following doc links to local filesystem causes fatal state

### ISSUE THREAD

**Issue by shawnsarwar** [usebruno/bruno#2349]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Links to the web inside bruno docs open in a web browser as expected. Links to the local filesystem, including non-resolvable links are opened within electron and there's no way back except to force quit the application.
Resolvable links for supported objects like images will be displayed, but it's still fatal as there's no way to go back. I experience this on MacOS, but it may be more prevalent.

```
- [This is the simple unsupported example which bruno wouldn't handle](/)
```

### .bru file to reproduce the bug
```bru
docs {
   - [this is a link](https://google.com)
   - [this is a link you won't come back from](/)
}
```

### Screenshots/Live demo link

<img width="999" alt="Screenshot 2024-05-22 at 12 58 42" src="https://github.com/usebruno/bruno/assets/4309669/3179ceec-491b-492c-92ce-3cb95c729597">
<img width="1002" alt="Screenshot 2024-05-22 at 12 58 52" src="https://github.com/usebruno/bruno/assets/4309669/d35cd983-6775-4f8b-a9ff-0ff6e5169503">

**Comment by shawnsarwar** [comment]
It seems you can also get into this state with web links (on MacOS) if the last browser you interacted with isn't your default for opening web pages. No back button and keyboard shortcuts aren't handled. The only way to get out is to ForceQuit bruno
<img width="998" alt="Screenshot 2024-05-22 at 13 21 38" src="https://github.com/usebruno/bruno/assets/4309669/53a88b97-28a4-4c6f-b9cf-9add84d39109">

**Comment by Its-treason** [comment]
Duplicate of #1156

**Comment by shawnsarwar** [comment]
Sorry for the duplicate, closing. Thanks!
