### ISSUE TITLE
[Suggestion] Previewing requests

### ISSUE THREAD

**Issue by LukeBillo** [usebruno/bruno#235]
# Problem

I have a (relatively) complicated set up involving quite a lot of variables at differing levels - environment, collection and request-specific. Before sending my request, I am prone to mistakes (forgetting to set a particular variable, being on the wrong environment) and may make an unintended request.

# Proposed Solution

In a similar to fashion to Insomnia, allow users to see the request that the currently selected environment and variables would result in. 

As an example:

```
meta {
  name: GET some resource
  type: http
  seq: 15
}

get {
  url: http://my-service{{ suffix }}/some-resource/{{ resourceId }}
  body: json
}

headers {
  Content-Type: application/json
  TenantId: {{ tenantId }}
}

body:json {
  {
    "testMe": {{ someValue }}
  }
}

vars:pre-request {
  resourceId: '12345'
  someValue: 'test'
}
```

When viewing this in the GUI, I'd expect to see the URL displayed something like:

`http://my-service[suffix: 'production.url']/some-resource/[resourceId: '12345']`

Assuming `suffix: 'production.url'` is set at an environment level, and `resourceId: '12345'` set at the request-level. This could also show in other places, such as when viewing the body:

```
{
  "testMe": [someValue: 'test']
}
```
----

Hopefully this issue format is alright - I couldn't find an issue template in your contributing guidelines. Feel free to close and ask me to open a new one with a particular format if it's unacceptable.

While I'm here, I'd just like to say that I've recently migrated from Insomnia (due to their recent changes) and I'm really enjoying Bruno. Thank you for a great tool, and I will consider contributing if I get some spare time.

**Comment by helloanoop** [comment]
Hey @LukeBillo 

It's been a long time 😃 
I hope you are still enjoying Bruno.

The latest versions of Bruno helps preview the vars upon hover.
<img width="561" alt="image" src="https://github.com/user-attachments/assets/61c631a3-eb68-4205-b297-59a0bc6a52fe">
