### ISSUE TITLE
Support relative local image path in markdown for docs.  

### ISSUE THREAD

**Issue by shawnsarwar** [usebruno/bruno#2350]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Currently, an absolute path of an image on the local filesystem can be resolved within the docs of a collection and shown via markdown. This isn't very useful since the absolute path is different for every git collaborator on the workflow.
Ideally local image path references in markdown would be resolved from the path of the .bru file which references them.

In the below example to resolve:
`/Users/A200301325/Documents/projects/bruno-demo/workflows/Demo-0/_docs/diagram.svg`
from:
`/Users/A200301325/Documents/projects/bruno-demo/workflows/Demo-0/collection.bru`
this should be a valid image reference:
```
 ![sadly I am broken...](./_docs/diagram.svg)
```

### Mockups or Images of the feature

<img width="1064" alt="Screenshot 2024-05-22 at 13 11 37" src="https://github.com/usebruno/bruno/assets/4309669/8c9dc475-3906-4c29-a741-e69bc32c9ef4">
<img width="1083" alt="Screenshot 2024-05-22 at 13 11 57" src="https://github.com/usebruno/bruno/assets/4309669/f4dfe9ef-8acf-40e2-b8ec-e73126f2f7d9">

**Comment by helloanoop** [comment]
Closing this as this was addressed in PR #2375
