### ISSUE TITLE
Unquoted Variables in JSON Body Break Comments and Prettier

### ISSUE THREAD

**Issue by prestonguillot** [usebruno/bruno#2362]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Using an _unquoted_ variable in the value of a field in a JSON body causes any comments in the body to be sent on the request instead of stripped. This also breaks the prettier.

e.g.

```
{
  "test": {{testVar}} //test
}
```

is sent as 

```
data "{\n \"test\": 1234 //test\n}\n"
```

and is prettied into

```
{
  "test": {
    {testVar
    }
  }     //test
}
```

whereas

```
{
  "test": "{{testVar}}" //test
}
```

is sent as

```
data {"test":"1234"}
```

and is unchanged by prettify.

### .bru file to reproduce the bug

```
meta {
  name: Demo
  type: http
  seq: 2
}

post {
  url: www.google.com
  body: json
  auth: none
}

body:json {
  {
    "test": {{testVar}} //test
  }
}

vars:pre-request {
  testVar: 1234
}
```

### Screenshots/Live demo link

<img width="772" alt="Screenshot 2024-05-24 at 10 25 54 AM" src="https://github.com/usebruno/bruno/assets/1053799/fc57e9dd-604c-4bf6-887d-8ba7629b2ec3">
<img width="733" alt="Screenshot 2024-05-24 at 10 26 20 AM" src="https://github.com/usebruno/bruno/assets/1053799/ca9974de-1383-4c23-8f4f-67cfb45c4af9">
<img width="455" alt="Screenshot 2024-05-24 at 10 26 03 AM" src="https://github.com/usebruno/bruno/assets/1053799/36cf4287-c99f-4598-a00e-e7480b2dd784">

**Comment by helloanoop** [comment]
This has been fixed as a part of PR https://github.com/usebruno/bruno/pull/2773, and will go out in the v1.27.0 release.
