### ISSUE TITLE
OAuth 2.0 support for "state" parameter

### ISSUE THREAD

**Issue by shaunek-hero** [usebruno/bruno#2364]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I'm connecting to an OAuth 2.0 authenticated api that requires "state" parameter to be specified. I'm sure there are other services that require the state parameter, but the specific service I'm having trouble with is Quickbooks Online (by Intuit). Quickbooks has relatively clear instructions on [how to setup the oath 2.0 authorization here](https://developer.intuit.com/app/developer/qbo/docs/develop/sandboxes/postman), although these instructions are specifically for Postman. I was able to get it to work in Postman without problem. However, in Bruno I entered all the same configurations fields except that the "State" field does not exist in Bruno. And when I attempt to get access token in Bruno the Quickbooks screen pops up, I login and then it gives me an error "The state query parameter is missing."

<img width="603" alt="Screenshot 2024-05-25 at 17 27 48" src="https://github.com/usebruno/bruno/assets/84192248/bb9de561-514c-48e3-8042-afe4f44b82d0">

Would it be possible to add "state" in the OAuth 2.0 screen?

### Mockups or Images of the feature

In terms of UI, here is what I am suggesting.
<img width="553" alt="Screenshot 2024-05-25 at 17 42 28" src="https://github.com/usebruno/bruno/assets/84192248/0ebb8317-cc44-438a-b8fd-e7e2f8574582">

I'm not expert on this topic, but I did find some documentation about Google's oath 2.0 implementation that also specifies information about the "state" field here: https://developers.google.com/identity/openid-connect/openid-connect?hl=en. Apparently one purpose of this field is to protect against xsrf.

**Comment by shaunek-hero** [comment]
I found that this ticket is a duplicate of #2357

**Comment by shaunek-hero** [comment]
Sorry I meant it is a duplicate of #2275

**Comment by helloitse** [comment]
So is this fixed?

**Comment by shaunek-hero** [comment]
Issue #2275 seems to be open still, so I'm guessing it hasn't been resolved.

I tried out Bruno a month ago and really loved some things about it, but seemed like it was a little too new/raw for my needs, I think I'll round back to it in a couple months to see how it is going. Seem really promising.

**Comment by nocturnalcodehack** [comment]
Agree.  Corporate OKTA configuration requires the use of state.  Can't use Bruno because of this.
