### ISSUE TITLE
Dutch translation of documentation files

### ISSUE THREAD

**Issue by anthonyringoet** [usebruno/bruno#2366]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Dutch translation of the docs.

### Mockups or Images of the feature

none (docs)

**Comment by anthonyringoet** [comment]
Follow-up: https://github.com/usebruno/bruno/pull/2365

**Comment by helloanoop** [comment]
Closing this as this has been taken care of in https://github.com/usebruno/bruno/commit/6d239929dad467137a1d8ab0e40cee174304903e
