### ISSUE TITLE
[SUGGESTION] Support for mutual tls

### ISSUE THREAD

**Issue by hamburml** [usebruno/bruno#237]
Would love to see support for mutual TLS.

**Comment by mado-vmob** [comment]
Does anyone know, is their at least a way to add this via a java script manually?

**Comment by pietrygamat** [comment]
@mado-vmob , mTLS was added I belive in #275.

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/275) adding the feature has already been merged. Thank you for taking the time to open a suggestion.
