### ISSUE TITLE
humanizeDate utility function returns inconsistent results based on the time zone

### ISSUE THREAD

**Issue by KameronKeller** [usebruno/bruno#2377]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

While writing tests for the utility functions found in `packages/bruno-app/src/utils/common/index.js`, I noticed that the `humanizeDate` function does not reliably return the date it is passed. This is caused by the Date object in JavaScript, which considers time zones when parsing a date.

See the discussions here for further explanation:

- https://stackoverflow.com/a/31732581/7100879
- https://stackoverflow.com/questions/47359812/why-does-adding-a-space-character-at-the-end-of-a-year-string-cause-javascript/47362875#47362875

File in question:
`packages/bruno-app/src/utils/common/index.js`

Code in question:
```js
export const humanizeDate = (dateString) => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
};
```

The below screenshot illustrates this phenomenon.

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/17558364/cd7093af-5325-4425-91a2-46cea76e3d9a)

**Comment by KameronKeller** [comment]
See this PR for a proposed fix and tests: https://github.com/usebruno/bruno/pull/2378

**Comment by helloanoop** [comment]
PR Merged
