### ISSUE TITLE
Blackia723

### ISSUE THREAD

**Issue by Blackia723** [usebruno/bruno#2380]
While writing tests for the utility functions found in packages/bruno-app/src/utils/common/index.js, I noticed that the humanizeDate function does not reliably return the date it is passed. This is caused by the Date object in JavaScript, which considers time zones when parsing a date.

**Comment by pietrygamat** [comment]
@Blackia723 's github activity is creepy to watch. It's like an AI pushing buttons strugling to gain consciousness...

**Comment by sanjai0py** [comment]
Duplicate/copy of #2377. Please use a descriptive title for the next issue you create.
