### ISSUE TITLE
Why Bruno has a dog as icon?

### ISSUE THREAD

**Issue by wandi34** [usebruno/bruno#2384]
Hi,
my team today really wondered why Bruno chose a dog as icon. We came to the idea, that maybe you chose it because dogs attack postmans. That idea was mindblowing. Was that already in your mind?

Cheers

**Comment by NiklasBr** [comment]
I bet it's also really good at `fetch()`:ing.

**Comment by Agulator** [comment]
haha，this is really an interesting explain.   : )

**Comment by tejesh-alimilli** [comment]
The name Bruno and the icon come from "Bruno". Source: https://youtu.be/7bSMFpbcPiY?si=B7h0XqR6kizyFqfn&t=870

<img width="959" alt="Bruno name and icon origin" src="https://github.com/usebruno/bruno/assets/1975262/c6d20c9f-6d67-4a83-b5c4-712bd91cbe1b">

**Comment by Liamhhhhh** [comment]
Another tool is also the dog icon, [Apidog](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1)， Is the icon a bone?

**Comment by fgrande** [comment]
Consider also that Bruno is not afraid of Postman. He happily goes in space....
![Default_an_happy_golden_retriever_floating_in_space_with_an_as_2](https://github.com/usebruno/bruno/assets/811941/8ae15be0-5feb-488e-95ab-95ee959ed38f)

**Comment by varmas18** [comment]
Name is good, but could change the icon to a little abstract. Feels out of place and not professional.

**Comment by jonathands** [comment]
everytime I'm working and my daughter sees the icon she says "doggy"  and it's the hightlight of my day, so If you could please keep it at least for a while, it'd be great, TY
