### ISSUE TITLE
Include GraphQL queries when exporting a collection to Postman

### ISSUE THREAD

**Issue by MouseEatsCat** [usebruno/bruno#2385]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

## Current functionality
Exporting a collection to Postman does not include GraphQL queries.
## Desired
Include GraphQL queries when exporting to Postman

## Current output
```JSON
{
  "name": "RequestName",
  "event": [],
  "request": {
    "method": "POST",
    "header": [],
    "url": "{{domain}}/graphql"
  }
}
```
## Desired output
```JSON
{
  "name": "RequestName",
  "event": [],
  "request": {
    "method": "POST",
    "header": [],
    "url": "{{domain}}/graphql",
    "body": {
      "mode": "graphql",
      "graphql": {
        "query": "..."
      }
    }
  }
}
```

**Comment by helloanoop** [comment]
Closing this as support for this was merged in #2386
