### ISSUE TITLE
Cancel runner via Script Pre Request/Post Response

### ISSUE THREAD

**Issue by jthln** [usebruno/bruno#239]
Imagine I have a collection of multiple requests, let's say 2 for example, in a folder and start the runner for this folder.

I want request 2 only be executed, if no test of request 1 fails.

Is this already possible with Bruno?

If not, I would like to suggest a feature that allows the user to control cancellation of the runner somehow, e.g. by simply using a specific command in the Script Pre Request/Post Response area.

**Comment by mj-h** [comment]
In my opinion, this is related to https://github.com/usebruno/bruno/issues/534
In Postman, many users used `pm.setNextRequest(null)` to achieve this.

**Comment by jthln** [comment]
> In my opinion, this is related to #534 In Postman, many users used `pm.setNextRequest(null)` to achieve this.

Yeah, #534 would close #239, too.
