### ISSUE TITLE
Bruno crashes when trying to save Multipart Form Requests with certain values

### ISSUE THREAD

**Issue by lwilli** [usebruno/bruno#2401]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bruno doesn't seem to handle certain Multipart Form values very well. Specifically, if the values include newlines or sometimes multiple spaces, Bruno fails to save the request file and will crash when quitting Bruno and selecting `Save` on the UNSAVED CHANGES dialog.

This issue seems to happen when the multipart values contain newlines and also happens if you type "  " (two spaces) as the part value.

I tested this with a fresh install of v1.18.0 on macOS.

Some more background: This particular functionality would be nice to have for GraphQL multipart requests, since the `operations` part is a JSON object value (we follow https://workday.github.io/graphql-multipart-request-spec/graphql-multipart-request-v3.html#sec-Operations-Part). It's not a complete blocker though since I was able to find the workaround of removing the newlines from the value, though that was not immediately obvious.

### .bru file to reproduce the bug

```
meta {
  name: Multipart bug demo
  type: http
  seq: 3
}

post {
  url: https://example.org
  body: multipartForm
  auth: none
}

body:multipart-form {
  operations: {
  	"query": "mutation ..."
  }
}
```

### Screenshots/Live demo link

Demo of me trying to save a request with a multiline part value:
![Bruno Multipart Form Save Bug Demo](https://github.com/usebruno/bruno/assets/5985351/4b257fb0-ff0f-486d-ae15-a111277d44f5)
Notice the toast notification indicates a successful save, but the request tab still has the little orange dot. And then when I try to quit Bruno, it tells me the request isn't saved. Then, when I click Save there, it crashes Bruno. After reopening Bruno, the request is not successfully loaded.

**Comment by helloanoop** [comment]
This has been released in `v1.9.0`
