### ISSUE TITLE
Bruno desktop app should automatically update when there is a new release.

### ISSUE THREAD

**Issue by wamiikechukwu** [usebruno/bruno#2402]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

The destop app should get a prompt for users to either update or cancel when there is a stable release. I was on 1.13.+ and was expecting a prompt to update whenever a new version is released.  I had to checked on the github page to discover that there have been other released version. 

### Mockups or Images of the feature

The prompt should be like how other apps send there update prompt. I believe its going to be like a dialog box with three button - update, cancel and remind later. With a description of the new release and the version number.

**Comment by aaronschendel** [comment]
100% agree :)
