### ISSUE TITLE
Add a new Assert : isArray

### ISSUE THREAD

**Issue by fgrande** [usebruno/bruno#2414]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Add a new Assert : isArray to state if a tag is actually an array

### Mockups or Images of the feature

<img width="185" alt="image" src="https://github.com/usebruno/bruno/assets/811941/d36dfe94-b700-4ff9-9afc-17be4afb84b8">

Add a new item in this enum

**Comment by fgrande** [comment]
Hi,
not clear how to link this Issue to my PR #2413

**Comment by pietrygamat** [comment]
> Hi, not clear how to link this Issue to my PR #2413

Just type somewhere in the description of your PR :
```
fixes: #2414
```
[Source](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
