### ISSUE TITLE
Unable to open existing collection on debian 

### ISSUE THREAD

**Issue by abkarim** [usebruno/bruno#2429]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I have an existing collection on my device on a secondary SSD folder name `.bruno`. While using bruno to open collection  it doesn't list the target folder. And while using file manager and opening with bruno, bruno just open the default window without loading the collection 

Although it's a hidden folder, I tried to open with bruno by renaming it to just bruno. Still doesn't works

## Bruno collection folder on my device
![image](https://github.com/usebruno/bruno/assets/84965867/cdc2453e-b73a-4a25-8c52-92f696c87962)

## While opening the collection from bruno - doesn't list the collection containing folder 
![image](https://github.com/usebruno/bruno/assets/84965867/54fd10db-e188-474f-8b85-8977582d0518)

## While opening the folder with bruno
![image](https://github.com/usebruno/bruno/assets/84965867/3b6f0413-af0f-4fa7-9fad-11467c2ff6db)

**Comment by Its-treason** [comment]
Your folder name starts with a dot (`.`) so its hidden by default. You con show hidden files by pressing `Ctrl` + `h`. This is also depending on your operating system / desktop environment and has nothing to do with Bruno.
