### ISSUE TITLE
Postman import silently drops url values

### ISSUE THREAD

**Issue by Slaviusz** [usebruno/bruno#2431]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When importing postman collection the url path of every request gets dropped and becomes empty.

How to reproduce:
* download official Atlassian postman collection export for Jira Cloud API https://developer.atlassian.com/cloud/jira/platform/jiracloud.3.postman.json
* Open bruno and import postman collection from downloaded file
* Observe all requests have no URL value

### .bru file to reproduce the bug

meta {
  name: Get all projects
  type: http
  seq: 1
}

get {
  url: 
  body: none
  auth: basic
}

query {
  ~expand: {{expand}}
  ~recent: {{recent}}
  ~properties: {{properties}}
}

headers {
  Accept: application/json
}

auth:basic {
  username: {{username}}
  password: {{apiToken}}
}

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/30972602/6b3834b5-be3c-407a-85be-f93c6d9731d5)

**Comment by gemiusz** [comment]
**After tests, Issiue confirmed for importing Postman Export in version 2.0.**

@Slaviusz if you want workaround you can Import this collection to Postman and Export it to version 2.1. I have do it already so you can just download it:
[The Jira Cloud platform REST API.postman_collection.2.1.json](https://github.com/user-attachments/files/15775357/The.Jira.Cloud.platform.REST.API.postman_collection.2.1.json)

Screen after import it:
![image](https://github.com/usebruno/bruno/assets/30750006/9bd70330-a3b3-48f2-8bb3-27c738965230)

**Comment by helloanoop** [comment]
I have merged the PR. The fix will be available in the upcoming `v1.31.0` release.
