### ISSUE TITLE
[Feature Request] Change response body before showing it: res.setBody()

### ISSUE THREAD

**Issue by marc0l92** [usebruno/bruno#2441]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I have a service that replies in base64 and I would like to intercept and modify the response body in order to decode it before it gets display.

There is a way to read the response body from the post response script using the function res.getBody(), but there is nothing to set it (like we have in the request body).

Could it be possible to implement the res.setBody() in order to override the body message displayed in the response panel?

The workaround I'm currently using is to print the decoded response in the console using `console.log`, but it will be more clean to show it directly in the response panel

**Comment by helloanoop** [comment]
Have merged the PR #3076 
This will be available in the upcoming release - `v1.29.0`

**Comment by nasu-oldhand** [comment]
Is this function only available in developer mode?
As it's not accessible in safe mode, I would appreciate if you could continue working on this issue.

**Comment by sethlopezme** [comment]
It appears that the functionality was added to the response object, but maybe it wasn't hooked up? I'm also unable to set the body of the response (in safe mode).
