### ISSUE TITLE
Error attempying to Generate Code

### ISSUE THREAD

**Issue by Willhoffman** [usebruno/bruno#2444]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am using version 1.19.0 on Mac Apple Silicon.
As soon as I click on the "Generate Code" option I get an error that says:

Oops! Something went wrong

If you are using an official production build: the above error is most likely a bug!
Please report this under:https://github.com/usebruno/bruno/issues

### .bru file to reproduce the bug

`meta {
  name: Random US
  type: http
  seq: 1
}

get {
  url: https://randomuser.me/api/?nat=us
  body: none
  auth: none
}

query {
  nat: us
}
`

### Screenshots/Live demo link

![Screenshot 2024-06-11 at 4 13 19 PM](https://github.com/usebruno/bruno/assets/23410014/4d6aa02e-c403-4259-906b-cff3265781a3)

**Comment by fgrande** [comment]
I have the same problem on the downloaded Bruno 1.19.0 (from homeBrew) - Previous release was working fine.

Instead, the forked repository looks working fine, it open the generation code panel.

**Comment by burkaman** [comment]
Same issue, same version, but running on Windows 11.

**Comment by kalimbra** [comment]
Same here.
Bruno 1.19.0 (snap install) on Ubuntu 20.04

**Comment by burkaman** [comment]
The stack trace is:

```
framework-80ea8c0f440c6a32.js:9 TypeError: Cannot read properties of undefined (reading 'externalSecrets')
    at getExternalCollectionSecretsForActiveEnvironment (_app-92e2050d0799eab9.js:17:186595)
    at getAllVariables (_app-92e2050d0799eab9.js:17:186042)
    at CodeEditor.addOverlay (443-87262752453bea5b.js:1:100581)
    at CodeEditor.value (443-87262752453bea5b.js:1:104274)
    at lk (framework-80ea8c0f440c6a32.js:9:90626)
    at jk (framework-80ea8c0f440c6a32.js:9:111105)
    at framework-80ea8c0f440c6a32.js:9:111116
    at Qk (framework-80ea8c0f440c6a32.js:9:111628)
    at Fk (framework-80ea8c0f440c6a32.js:9:96297)
    at jg (framework-80ea8c0f440c6a32.js:9:44900)
```

I guess this must be a bug in Golden Edition code with the new vault integration feature, as I don't see that function in this repository. I am a free user.

**Comment by alexnum** [comment]
Same here

**Comment by hungdh0x5e** [comment]
+1

**Comment by jeffhall-wk** [comment]
+1

**Comment by gemiusz** [comment]
+1 
Confirmed on Windows:

![image](https://github.com/usebruno/bruno/assets/30750006/3d4c600d-6f23-4379-95ff-6432fa005bed)

**Comment by SteliosGiannatos** [comment]
+1

**Comment by pomelo-chuan** [comment]
+ 1 also recurrent in my mac
<img width="1470" alt="截屏2024-06-17 15 23 59" src="https://github.com/usebruno/bruno/assets/18512356/8cf9ab94-806f-41c2-90ef-5a4f21ea6d16">

TypeError: Cannot read properties of undefined (reading 'externalSecrets')

**Comment by therox** [comment]
Fedora, flatpak, 1.19, same error here.

**Comment by vazome** [comment]
same

**Comment by mstaal** [comment]
I have the same issue on Mac M1

**Comment by drchiodo** [comment]
+1

**Comment by gustavogianordoli** [comment]
Same here, Fedora 40, Bruno 1.19.0, Flatpak. I also tested with appimage .

**Comment by emirozmen07** [comment]
Error doesn't appear on me anymore with version 1.34 in mac m2
