### ISSUE TITLE
RFE: Preview render of HTML responses

### ISSUE THREAD

**Issue by Svenito** [usebruno/bruno#245]
When using Django in debug for example, unhandled internal errors result in a HTML error page. It's difficult to parse this without rendering the HTML.
Alternative software provides a "preview" tab in the responses to render the HTML. It would be nice to have this in Bruno as well.

**Comment by not-known-person** [comment]
Should I place the preview tab next to 'Tests' tab , 
![image](https://github.com/usebruno/bruno/assets/134089980/cd76a390-a954-44b6-9271-8c70f660a4ca)
@helloanoop kindly elaborate , how does u want the feature to work like , giving reference may help to understand the feature more confidently

**Comment by not-known-person** [comment]
Sure @helloanoop

**Comment by helloanoop** [comment]
This was delivered by @Its-treason and is now available in `v0.18.0`
