### ISSUE TITLE
crashing when generating code from request

### ISSUE THREAD

**Issue by zhoushun123** [usebruno/bruno#2454]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

version：1.19.0
OS：Windows 10 Professional (19041.1826)
When I clicked on the "Generate Code" button from any saved request, the software crashed with a crashing page.
The previous version (1.18.1) didn't have this problem.

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/12932569/12014851-81ce-4224-83f3-bf9ad1375ee2)
![image](https://github.com/usebruno/bruno/assets/12932569/96f1fec9-c517-4c8d-bd49-2d7ae8afc4f2)

**Comment by sanjai0py** [comment]
Duplicate of #2444

**Comment by jwetzell** [comment]
this is resolved as of v1.20.0 @sanjai0py

**Comment by sanjai0py** [comment]
Closing this as the issue has been fixed in [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0).
