### ISSUE TITLE
Nested vars support?

### ISSUE THREAD

**Issue by darcien** [usebruno/bruno#2456]
### I have checked the following:

- [X] I use the newest version of bruno. (v1.19.0 atm)
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Variable value is not resolved when used in another variable.

See how the variable sent in the request is the literal text written in vars:
![image](https://github.com/usebruno/bruno/assets/19742419/d5ce0354-9f88-401c-8c5d-9f6d07f0252d)

Hovering cursor on the nested variable does show the actual variable value:
![image](https://github.com/usebruno/bruno/assets/19742419/edc377dc-94ae-45d5-9dc9-6d6c03ba72ba)

If Bruno does support nested variable, then the nested variable value should be resolved before the request is sent.

If not, the variable input should not indicate it's resolving to the referenced variable.
And [docs for vars][vars-docs] might need to be updated to note this behavior.

[vars-docs]: https://docs.usebruno.com/scripting/vars

### .bru file to reproduce the bug

```bru
meta {
  name: Example
  type: http
  seq: 5
}

get {
  url: https://example.com?q={{hello}}
  body: none
  auth: none
}

query {
  q: {{hello}}
}

vars:pre-request {
  foo: bar
  hello: world-{{foo}}
}
```

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/19742419/3ef9129b-238c-470d-a8fc-b2308eb9d00a)

**Comment by sanjai0py** [comment]
Duplicate of #956

**Comment by darcien** [comment]
Apologies, my search keyword was vars, I didn't see that one.
