### ISSUE TITLE
[Feature] Add command bru.rmVar(varType, key) and/or bru.rmEnvVar(key)

### ISSUE THREAD

**Issue by bpoulaindev** [usebruno/bruno#2464]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Add a command **bru.rmVar(varType, key)** that would allow users to unset a variable (equivalent of **pm.environment.unset** but more modular)
Javascript behavior (can be done in scripts tab) :
_replace "toDelete" with the key to delete, and "envVariables" by another varType_
```js
bru = Object.entries(bru).reduce((acc, [key, value]) => {
  acc[key] = key === "envVariables" ?
    Object.fromEntries(Object.entries(value).filter(([k]) => k !== "toDelete")) :
    value;
  return acc;
}, {});
```

### Mockups or Images of the feature

<img width="496" alt="image" src="https://github.com/usebruno/bruno/assets/64689165/6fba85c8-3dd6-487e-ae2d-3ebf26f9c85c">

**Comment by anusree-bruno** [comment]
These three commands are available now in bruno

```
bru.deleteEnvVar(key)
bru.deleteAllVars()
bru.deleteVar(key)
```
