### ISSUE TITLE
Cannot find fs/promises in Bruno scripting

### ISSUE THREAD

**Issue by luccitan** [usebruno/bruno#2481]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am trying to write a pre-request script for my whole collection, and that script relies on puppeteer.

With this import : 
```js 
try {
  const puppeteer = require('puppeteer');
} catch (error) {
  console.log(error.stack);
  throw error;
}
```

I get this as a response :
```
Error invoking remote method 'send-http-request': VMError: Cannot find module 'fs/promises'
```

I tried with multiple versions of puppeteer, but this does not seem relevant as `fs/promises` should be available for Node > 14, and current Bruno uses Node 16.16 if I'm not mistaken

## Error logged from catching described above :

<img width="564" alt="Capture d’écran 2024-06-18 à 15 47 09" src="https://github.com/usebruno/bruno/assets/10575146/b77efa4a-d5b1-4515-b0d6-8aa5feb64d12">

## Dump from `console.log(process.versions)` in my Bruno script :
<img width="777" alt="Capture d’écran 2024-06-18 à 15 46 57" src="https://github.com/usebruno/bruno/assets/10575146/59aff789-160b-45c8-b266-015e75b0de0c">

## My Bruno `package.json` :

```json
{
    "name": "<MY_PROJECT>",
    "version": "1.0.0",
    "main": "index.js",
    "dependencies": {
        "puppeteer": "^22.11.2"
    }
}
```

**Comment by bpoulaindev** [comment]
Have you tried enable puppeteer in bruno.json by [whitelisting it](https://docs.usebruno.com/scripting/whitelisting-modules) ?

**Comment by luccitan** [comment]
> Have you tried enable puppeteer in bruno.json by [whitelisting it](https://docs.usebruno.com/scripting/whitelisting-modules) ?

I managed to go beyond this error by whitelisting **bultin** modules that failed to be loaded : 

```
  "scripts": {
    "moduleWhitelist": [
      "fs/promises",
      "os",
      "child_process",
      "readline",
      "net",
      "tty",
      "tls",
      "crypto",
      "events"
    ],
    "filesystemAccess": {
      "allow": true
    }
  }
```

but now I have issues because `process.stderr` seems to be `undefined` under Electron

**Comment by bpoulaindev** [comment]
I'm not sure you can access `fs` in the scripts, as those are exectued on client side (nextJs), not on the backend (Electron)

**Comment by luccitan** [comment]
I ended up with a workaround for my needs, I'm closing the issue with no provided solution

**Comment by adamfdl** [comment]
May U know what is the workaround @luccitan ?

**Comment by luccitan** [comment]
Sorry for the very late answer.
The workaround was very specific to my use-case (some authentication workflow) and was completely independent of any automation script, rather documenting steps to execute manually with custom queries to ease the manual process.

Not really a workaround of the actual automation solution but a workaround of my actual root issue.
