### ISSUE TITLE
Does not generate the code

### ISSUE THREAD

**Issue by GianPierree** [usebruno/bruno#2483]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am using Bruno on Linux and I installed it through snap, but when I want to generate the code to export I get an error.

### Screenshots/Live demo link

Error: 
![image](https://github.com/usebruno/bruno/assets/2354651/475b349c-95aa-42bb-bc69-4c769f2c9cd4)

![image](https://github.com/usebruno/bruno/assets/2354651/9ae0bfd0-9f9a-4459-9d90-92cb7bc87f71)

**Comment by bpoulaindev** [comment]
Is there any error that show up when you open the Chrome Console within Bruno ?

**Comment by rammanokar-plateron** [comment]
I'm getting the same error too. Here are the logs from the Chrome console.


```
framework-80ea8c0f440c6a32.js:9 TypeError: Cannot read properties of undefined (reading 'externalSecrets')
    at getExternalCollectionSecretsForActiveEnvironment (_app-92e2050d0799eab9.js:17:186595)
    at getAllVariables (_app-92e2050d0799eab9.js:17:186042)
    at CodeEditor.addOverlay (443-87262752453bea5b.js:1:100581)
    at CodeEditor.value (443-87262752453bea5b.js:1:104274)
    at lk (framework-80ea8c0f440c6a32.js:9:90626)
    at jk (framework-80ea8c0f440c6a32.js:9:111105)
    at framework-80ea8c0f440c6a32.js:9:111116
    at Qk (framework-80ea8c0f440c6a32.js:9:111628)
    at Fk (framework-80ea8c0f440c6a32.js:9:96297)
    at jg (framework-80ea8c0f440c6a32.js:9:44900)
Mi @ framework-80ea8c0f440c6a32.js:9
Ri.o.componentDidCatch.a.callback @ framework-80ea8c0f440c6a32.js:9
ih @ framework-80ea8c0f440c6a32.js:9
lk @ framework-80ea8c0f440c6a32.js:9
jk @ framework-80ea8c0f440c6a32.js:9
(anonymous) @ framework-80ea8c0f440c6a32.js:9
Qk @ framework-80ea8c0f440c6a32.js:9
Fk @ framework-80ea8c0f440c6a32.js:9
jg @ framework-80ea8c0f440c6a32.js:9
(anonymous) @ framework-80ea8c0f440c6a32.js:9

```

**Comment by bpoulaindev** [comment]
Probably a **"?"** missing somewhere like `data?.externalSecrets`
Could have been prevented by using Typescript once again.
This is a part of code located in the golden edition part so there's nothing the community can do

**Comment by GianPierree** [comment]
> Is there any error that shows up when you open the Chrome Console within Bruno ?

How can I open the Chrome console from Bruno?

**Comment by GianPierree** [comment]
> Probably a **"?"** missing somewhere like `data?.externalSecrets` Could have been prevented by using Typescript once again. This is a part of code located in the golden edition part so there's nothing the community can do

How can I solve it?

**Comment by bpoulaindev** [comment]
> > Is there any error that shows up when you open the Chrome Console within Bruno ?
> 
> 
> 
> How can I open the Chrome console from Bruno?

You can use the three little dots in the top left corner of the app, and select "Chrome Console"

**Comment by kogamas** [comment]
> I'm getting the same error too. Here are the logs from the Chrome console.
> 
> ```
> framework-80ea8c0f440c6a32.js:9 TypeError: Cannot read properties of undefined (reading 'externalSecrets')
>     at getExternalCollectionSecretsForActiveEnvironment (_app-92e2050d0799eab9.js:17:186595)
>     at getAllVariables (_app-92e2050d0799eab9.js:17:186042)
>     at CodeEditor.addOverlay (443-87262752453bea5b.js:1:100581)
>     at CodeEditor.value (443-87262752453bea5b.js:1:104274)
>     at lk (framework-80ea8c0f440c6a32.js:9:90626)
>     at jk (framework-80ea8c0f440c6a32.js:9:111105)
>     at framework-80ea8c0f440c6a32.js:9:111116
>     at Qk (framework-80ea8c0f440c6a32.js:9:111628)
>     at Fk (framework-80ea8c0f440c6a32.js:9:96297)
>     at jg (framework-80ea8c0f440c6a32.js:9:44900)
> Mi @ framework-80ea8c0f440c6a32.js:9
> Ri.o.componentDidCatch.a.callback @ framework-80ea8c0f440c6a32.js:9
> ih @ framework-80ea8c0f440c6a32.js:9
> lk @ framework-80ea8c0f440c6a32.js:9
> jk @ framework-80ea8c0f440c6a32.js:9
> (anonymous) @ framework-80ea8c0f440c6a32.js:9
> Qk @ framework-80ea8c0f440c6a32.js:9
> Fk @ framework-80ea8c0f440c6a32.js:9
> jg @ framework-80ea8c0f440c6a32.js:9
> (anonymous) @ framework-80ea8c0f440c6a32.js:9
> ```

I get basically the same stack trace.

It's broken on Apple Silicon too.
only downgrade to 1.18.1 (last working version) helped.

**Comment by therealrinku** [comment]
same issues: #2444 #2454

**Comment by jose-cavalheri** [comment]
Same error after upgrade: Latest version

<img width="396" alt="image" src="https://github.com/usebruno/bruno/assets/138793867/a8f79aca-47d2-4111-b4b7-01df5c190738">

**Comment by jwetzell** [comment]
The string `externalSecrets` doesn't appear anywhere in the source code......

**Comment by VictorioBerra** [comment]
Same, blows up after I updated to 1.19.0

**Comment by GianPierree** [comment]
Thank you very much for your answers. I solved the problem by installing version 1.18.

**Comment by mstaal** [comment]
I am having the same issue. I hope it will soon be resolved.

**Comment by alissonpadua** [comment]
I just downloaded the latest version and I have the same error on MacOS latest version M1

**Comment by jwetzell** [comment]
@alissonpadua the latest version as of righting this is v1.19.0 which is the version mention in this issue as having the problem so that is expected.

**Comment by jwetzell** [comment]
@alissonpadua v1.20.0 was just released and includes a fix to this.

**Comment by alissonpadua** [comment]
> @alissonpadua v1.20.0 was just released and includes a fix to this.

Hello! I can confirm it is working well now, thank you! Super well done
