### ISSUE TITLE
RFE: apt repository for .debs

### ISSUE THREAD

**Issue by scop** [usebruno/bruno#249]
Would be nice to have the .debs in an apt repository for updates. There are some services available that provide this for free for open source projects (up to a limit), for example:
- Balto, https://www.getbalto.com/pricing (1GB storage, 10GB bandwidth)
- Cloudsmith, https://cloudsmith.com/pricing (50GB storage, 200GB bandwidth)
- Packagecloud, https://packagecloud.io/pricing/ (2GB storage, 10GB bandwidth)

I have some experience with Packagecloud (no affiliation) and could help set it up if that's what you'd like to go with. I couldn't find the setup that does the releases in the repo here on a very brief look, so not quite sure where the upload should be hooked up.

**Comment by scop** [comment]
In GitHub actions terms, the Packagecloud upload would be pretty much a matter of https://github.com/aakso/ssh-inscribe/blob/6ea9e244a1b92d582bc205cced096fc69b6498a1/.github/workflows/release.yaml#L24-L32
... + a Packagecloud account obviously (the above refers to the same org/repo as in github, so it should be registered as such there -- usebruno/bruno), and its API token here as `PACKAGECLOUD_TOKEN`.

10GB bandwidth is not that much for a large Electron app though.

**Comment by beeburt** [comment]
It would be nice if there were some beginner-friendly installation instructions in the docs.

**Comment by nrekretep** [comment]
In the Github Actions Marketplace there is also an action that makes it possible to use Github Pages as a simple debian package repo: https://github.com/marketplace/actions/github-pages-apt-repo

But I have no experience with that.
