### ISSUE TITLE
Export Collection as Postman Collection

### ISSUE THREAD

**Issue by thannebauer** [usebruno/bruno#2496]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When exporting an Collection as Postman Collection and importing it in Postman, the URL is broken.
URL "https://github.com/usebruno/bruno/issues/new?assignees=&labels=bug&projects=&template=BugReport.yaml" is imported in Postman as "github.com/?assignees=&labels=bug&projects=&template=BugReport.yaml"
URL "{{apiurl}}\somewhere\somehow?param1=123" (apiurl is variable from environment) is imported as "/"

Comparing both Postman Json collections I find these main differences:
* request.url.protocol element is missing for "fix URL"
* request.url.path is exported as empty array by bruno, but filled by postman
* request.url.host is empty for "Test Variable URL"

After fixing this for testing purpose, I could import the collection with correct URLs in Postman. 

In addition an empty request named "bruno" is ex- and imported. This is caused by an additional empty element:
`    {
      "name": "bruno",
      "event": []
    },`

[
![compare_json_collections](https://github.com/usebruno/bruno/assets/157024608/90074b25-8072-443b-9e96-ff3b18559ccb)
](url)

### .bru file to reproduce the bug

Bruno collection: [Sandbox.zip](https://github.com/user-attachments/files/15927091/Sandbox.zip)

exported Postman collection: 
[Sandbox.json](https://github.com/user-attachments/files/15927094/Sandbox.json)

Same collection content exported from Postman: 
[Postman-Sandbox.postman_collection.json](https://github.com/user-attachments/files/15927118/Postman-Sandbox.postman_collection.json)

### Screenshots/Live demo link

Postman after import:
![image](https://github.com/usebruno/bruno/assets/157024608/a2fdff4e-4ce6-410c-8c5b-8989a6b7c67b)
![image](https://github.com/usebruno/bruno/assets/157024608/21ef43ce-d24b-493f-bc05-333dbbfdcd8b)
![image](https://github.com/usebruno/bruno/assets/157024608/6ae07903-460e-4a3e-b9e8-c3c89f633d9e)
What I have exported from Bruno
![image](https://github.com/usebruno/bruno/assets/157024608/4dfa9834-0da2-4c7c-a8c9-0e5f5361f907)
![image](https://github.com/usebruno/bruno/assets/157024608/7622f2ac-596d-4054-b792-cc72205123b3)

**Comment by akhot09** [comment]
Even I have faced same issue and noticed all of above issues noted in screen shot by @thannebauer. Eagerly looking for this option as it's creating an additional manual work before importing into Postman API client and also impacts collection run when performed from Newman CLI.

Along with above noted issues even below parameter is missing for each of API request. 
"response": []

**Comment by helloanoop** [comment]
I have merged the PR that fixes this issue, it will be available in the the upcoming release `v1.30.0` that is scheduled to go out in the next couple of days.
