### ISSUE TITLE
Cannot Run Collection with Token saved as setEnvVar

### ISSUE THREAD

**Issue by hananthrao** [usebruno/bruno#2512]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am a non technical tester using Bruno for the first time.  

I want to Run a collection of APIs.   I have a Seperate GetToken call using which I generate Token, save the Token jwt value as a EnvVar using Post Response Script.

If I run the individual APIs in the Collection folder,  everything works fine.   But if I run a Collection, only the first API from collections Passes the token, second API onwards it calls Null Token value and I get 403.

### Screenshots/Live demo link

First API - 200 Response
![Uploading image.png…]()

Second API onwards - 403
![Uploading image.png…]()

**Comment by helloanoop** [comment]
@hananthrao Closing this issues as it is closely related to #2160

Can you add any additional comments you have at #2160

Thanks,
Anoop

**Comment by hananthrao** [comment]
Hi @helloanoop  -- Guess you did not understand the ask.

#2160  is about Env Variables.   

My query is about running collections of 40 APIs with same Token generated before the Run
