### ISSUE TITLE
Double scrollbar tests section

### ISSUE THREAD

**Issue by tester-at-bmi** [usebruno/bruno#2517]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

There is a double scrollbar within the test section

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/100684771/578006d8-ca39-4c03-a18e-7b3e3bfd17d5)

**Comment by vayalildanie** [comment]
This has certainly been fixed in most updated version (now v1.25)

**Comment by sanjai0py** [comment]
This issue has been resolved in the [v1.25.0](https://github.com/usebruno/bruno/releases/tag/v1.25.0) version of Bruno. Closing this as completed.
