### ISSUE TITLE
Collection Runner doesnt show up test status for previous data sets, when collection is run for multiple data sets via scripts

### ISSUE THREAD

**Issue by akhot09** [usebruno/bruno#2522]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am using Bruno Desktop Version : v1.19.0
When i am running collection having set of API requests using Collection Runner feature with data file by writing js scripts feature in Pre/Post request script tabs (as suggested by Aliaic in discussions : https://github.com/usebruno/bruno/discussions/2313) having multiple sets of data (like iteration run), the collection runner doesnt show up test status for previous data sets where as it shows test status against each of API call only for 'nth' data set (last data set) in data file. 

Please find below screen shot for the same: 
![image](https://github.com/usebruno/bruno/assets/168065372/9314337c-a641-4c25-b16e-4584cafdc2ee)

Please let me know if any more information is needed. 
Thanks!

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/168065372/ac4776e7-f6c9-4e1b-986f-176d5f73cef4)

**Comment by BruAlcaraz** [comment]
I am facing the same issue on my end:
![image](https://github.com/usebruno/bruno/assets/20819845/18159c3f-afb8-4a52-a39e-dab05786f252)
![image](https://github.com/usebruno/bruno/assets/20819845/8d5564e0-cfd3-42c1-aee4-0074db107db3)

I have also noticed that if I use the 'bru.setNextRequest("re-queue tests");' in the test script it will not work it only work if it is in the  Post Response script even though the documentation says that it would work on either test or post response scripts:
![image](https://github.com/usebruno/bruno/assets/20819845/28cff82d-16d7-46a8-aa62-17b7c4619800)

**Comment by BruAlcaraz** [comment]
#2551

**Comment by BruAlcaraz** [comment]
@akhot09 I have created a PR #2551 with a fix for this issue. Lets hope that it gets approved by the maintainers.

**Comment by sanjai0py** [comment]
Closing this issue because the [PR](https://github.com/usebruno/bruno/pull/2551) fixing it has already been merged, and the next outgoing release will contain this fix!
