### ISSUE TITLE
Error when click 'generate code' button

### ISSUE THREAD

**Issue by yezhoujie** [usebruno/bruno#2523]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Error page shows when click 'generate code' button

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/25244187/a86bf6cd-830a-418b-8dee-adefa786e9ba)

**Comment by jwetzell** [comment]
duplicate of #2444 that was resolved by #2501

**Comment by jwetzell** [comment]
this is resolved as of v1.20.0 @sanjai0py

**Comment by sanjai0py** [comment]
Closing this as the issue has been fixed in [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0).
