### ISSUE TITLE
Typo on the Github Bug Report Page

### ISSUE THREAD

**Issue by derjohn** [usebruno/bruno#2527]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

One the bug report page:

======8<=====
.bru file to reproduce the bug
Attach your .bru file here that can reqroduce the problem.
==== SNIP ====

s/reqroduce/reproduce/

### Screenshots/Live demo link

.

**Comment by vayalildanie** [comment]
helpful maybe, but not a bug, should be closed

**Comment by derjohn** [comment]
It has been corrected.
