### ISSUE TITLE
[Issue] Path parameters are added as URL search parameters (v1.19.0)

### ISSUE THREAD

**Issue by ThenTech** [usebruno/bruno#2528]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

In `v1.19.0`, using the new path params feature introduced in #484, I'm getting an issue where Bruno is adding the `req.params` object as query parameter, e.g.:

URL (in UI): `{{baseURL}}/some/route/:pk/`
Path param: `pk` with value `test`

If I look in Timeline or `console.log(req)` in post response, the URL I see is:

`http://127.0.0.1:8000/v1/app/some/route/test`

Which should be correct, however, my API endpoint is being called with:

`/v1/app/some/route/test/?0[name]=pk&0[value]=test&0[enabled]=true&0[type]=path&0[uid]=1gTYMy1cJaQsEkW93yRGP`

It seems somewhere during the URL interpolation, the URL search params are updated with the data in `req.params` as shown above.

```javascript
req = {
    ...
    params: [
        {
            "name": "pk",
            "value": "test",
            "enabled": true,
            "type": "path",
            "uid": "1gTYMy1cJaQsEkW93yRGP"
        }
    ],
    ...
}
```

Additionally, the trailing slash is also not kept any more.

Possibly related to #2506?

### .bru file to reproduce the bug

```
meta {
  name: Test
  type: http
  seq: 5
}

get {
  url: {{baseURL}}/some/route/:pk/
  body: none
  auth: inherit
}

params:path {
  pk: test
}

script:pre-request {
  console.log("Pre:", req.url);
}

script:post-response {
  console.log("Post:", req.url);
}
```

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/11493646/de0d161c-c09d-4ea6-b2eb-02dce00c9d92)

**Comment by sanjai0py** [comment]
Hey @ThenTech can you please share a minimal `.bru` or json export?

**Comment by ThenTech** [comment]
> Hey @ThenTech can you please share a minimal `.bru` or json export?

I edited the original post to add the `.bru` file of the request shown, though there's not much to see.

**Comment by Lixfeld** [comment]
@ThenTech I had the same issue in version 1.19.0 but in the current version (1.20.1) this seems to be fixed.

**Comment by ThenTech** [comment]
> @ThenTech I had the same issue in version 1.19.0 but in the current version (1.20.1) this seems to be fixed.

Oh I'll check it again later then. And close the issue if it is indeed fixed.

**Comment by ThenTech** [comment]
@Lixfeld It is indeed fixed now. Thank for letting me know.
