### ISSUE TITLE
CMD+H to hide application not working on Mac

### ISSUE THREAD

**Issue by chriscasola** [usebruno/bruno#253]
It seems like the very commonly used `CMD+H` shortcut to hide an app is overridden to show the help menu. Could this shortcut be reconsidered?

**Comment by helloanoop** [comment]
Sure.

I think a lot of mac users use `Cmd+H` and overriding it to show the help menu (an action that is performed rarely) does not justify it.

Will remove this shortcut so that `Cmd+H` will work like expected

**Comment by helloanoop** [comment]
The cmd+h hotkey has been freed in `v0.17.0`

**Comment by l0new4nder3r** [comment]
The hotkey has indeed been freed, unfortunately cmd+h does not hide the app (tested with v0.17.0)

The option in not available in the menu
<img width="392" alt="Capture d’écran 2023-10-03 à 00 35 02" src="https://github.com/usebruno/bruno/assets/27144372/5099a6e8-9206-47ae-b4c7-9e91abaf9cf4">

As a comparison, a working example with [pulsar](https://github.com/pulsar-edit/pulsar/)
<img width="299" alt="Capture d’écran 2023-10-03 à 00 36 45" src="https://github.com/usebruno/bruno/assets/27144372/fcb747ad-e585-4c41-8aad-e1e67d955830">

**Comment by l0new4nder3r** [comment]
Tested again today, version 0.24.0

Nothing in the menu, BUG cmd+h properly hides the app 😄 

I guess the issue can now be closed - do you confirm @chriscasola?

**Comment by helloanoop** [comment]
Thanks Everyone!
