### ISSUE TITLE
Left down icons overlay on the request names when chrome console opened

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#2538]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

when Chrome console is opened the left side quick access icons overlay on the request names, making it hard to select the request names

### Screenshots/Live demo link

![envDeletePopup](https://github.com/usebruno/bruno/assets/44080743/bde93cd3-6574-4135-803f-85b66f537067)

**Comment by Its-treason** [comment]
I think you attached the wrong image

**Comment by sseenivasan89** [comment]
![iconOverlay](https://github.com/usebruno/bruno/assets/44080743/4cc3e396-fa01-46f9-9fca-33f7926ba291)

**Comment by vayalildanie** [comment]
This is resolved as of (v1.25.0) the footer container is now opaque. 
proof:
![image](https://github.com/user-attachments/assets/11474bd5-c231-4847-96a7-506427df513f)
->
![image](https://github.com/user-attachments/assets/d3f50ac0-1bea-4833-ad93-6bba6d0fa648)

**Comment by sanjai0py** [comment]
Closing this as completed/not reproducible. Thank you, @sseenivasan89, for taking the time to create these valuable bug reports.
