### ISSUE TITLE
About Bruno Dialog is missing "App icon" image

### ISSUE THREAD

**Issue by Shoozza** [usebruno/bruno#254]
How to reproduce:
1. open bruno
2. in the menu click on help -> about bruno

Result:
* dialog opens but is missing app icon (see image below)

Expected:
* icon is visible

System:
* OS: Windows 8.1

![image](https://github.com/usebruno/bruno/assets/276143/e9d4546f-e667-42b7-b24f-7218eb909deb)

**Comment by helloanoop** [comment]
This has been fixed in `v0.16.5`. Thanks to @mirkogolze !

![image](https://github.com/usebruno/bruno/assets/9350733/cc1e98a7-64c4-4de0-892d-61cacd47c31a)
