### ISSUE TITLE
Request level vars don't update it's value after set first value while read from .bru file on app load

### ISSUE THREAD

**Issue by SPIRIT-00** [usebruno/bruno#2547]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I use template for many requests (~ 2.6k) and setting up each request, if it have specific settings. But majority setting work automatically via JS.

Settings like endpoint url. On screenshots example how i change url by change "findOneId" var. After update on 1.20 version, request level var's stop updating it's value when change values in 'vars' tab.

On screenshot 1 have see that initial var's value work correctly.
Then i change value by adding query params. (No difference how change the var, result is same) And request sends with old initial value. Also sent var's value into console.

Also, at now no way to change request level vars, like bru.setRequestVar('name', value).

### Screenshots/Live demo link

![initialValue](https://github.com/usebruno/bruno/assets/128896119/7c8b373f-fdd9-4057-a435-499d4638c839)
![afterChangeVal](https://github.com/usebruno/bruno/assets/128896119/39e340bc-b49f-4704-a382-283be8bda456)

**Comment by chrisnagel** [comment]
This new behavior is indeed very irritating: Newly created variables can be changed and the current value is always used. However, as soon as the configuration is saved, only the content of the bru file is decisive and changes in the GUI are no longer taken into account.

![240705_vars](https://github.com/usebruno/bruno/assets/5313051/2a64d2d2-0a29-48cd-a140-d472ca190628)

**Comment by SPIRIT-00** [comment]
Yep, have many saved request and not want change it. But sometimes need quick check something based on already exist request. Before 1.20 version i "broke" existing request, check what i need and close request without saving. It was quite convenient.

**Comment by SPIRIT-00** [comment]
1.26 now works fine
