### ISSUE TITLE
[v1.20] unable to close collection - an error occurred while closing collection

### ISSUE THREAD

**Issue by darylteo** [usebruno/bruno#2553]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Try to delete a collection

 - an error occurred
 - no console errors
 
electron | : 21.1.1
chrome | : 106.0.5249.103
node | : 16.16.0
v8 | : 10.6.194.17-electron.0

os x: 12.2.1 
macbook air m1 2020, macbook pro m1 2021

### Screenshots/Live demo link

Best I can do as there's no other debugging information. This also happens with fresh collections.

https://github.com/usebruno/bruno/assets/1226920/ede96772-3a8f-4284-a0a4-b168577111f6
https://github.com/usebruno/bruno/assets/1226920/798920ae-08cb-4ea2-8ca4-251c52f06689

**Comment by darylteo** [comment]
I just tested this by cloning Bruno and worked fine so maybe issue was fixed in a recent commit.

**Comment by Its-treason** [comment]
> I just tested this by cloning Bruno and worked fine so maybe issue was fixed in a recent commit.

The released version of Bruno includes the proprietary "Golden Edition" code and is not the same as the publicly available source code. Previous versions also had some bugs that were not present in the public source, [like the code generator not working](https://github.com/usebruno/bruno/issues/2454).

**Comment by sanjai0py** [comment]
Thank you for taking the time to report the issue, @darylteo. We merge the open-source Bruno with the proprietary closed-source code. Changes in the closed-source code caused the bug, but it has been fixed. You can expect the fix in the next patch release.

**Comment by darylteo** [comment]
I'll keep that in mind in the future, thank you.
