### ISSUE TITLE
Bump Electron version

### ISSUE THREAD

**Issue by gepbird** [usebruno/bruno#2558]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Current Electron version 21.1.1 is EOL and shouldn't be used, please update to a [supported version](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

I'm maintaining bruno for nixpkgs, and we've been running it with Electron 30 for a while with only a [minor issue](https://github.com/NixOS/nixpkgs/issues/324176), updating it shouldn't be a big hassle.

Related PR: https://github.com/usebruno/bruno/pull/2258

### Mockups or Images of the feature

-

**Comment by sanjai0py** [comment]
Hey @gepbird, we are currently updating the Electron version. We plan to release a nightly build that the community can use to report any bugs or issues. The nightly build with the updated Electron version is expected to be released next week!

**Comment by gepbird** [comment]
Thanks! I'll check out whether our issue is fixed with this update soon.

Closed by https://github.com/usebruno/bruno/pull/2668. :heart:

**Comment by gepbird** [comment]
Works well, thanks for your work!
