### ISSUE TITLE
Generate code is not working in Macbook M3

### ISSUE THREAD

**Issue by irfansofyana** [usebruno/bruno#2567]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I cannot use "Generate Code" feature in my device.

<img width="1151" alt="image" src="https://github.com/usebruno/bruno/assets/33191443/54ba2d62-8f42-4989-b51f-b9f683ded85e">

I use v1.19.0 installed via brew and my device is Macbook Pro M3

### .bru file to reproduce the bug

simple request like request to https://google.com is not working

_No response_

### Screenshots/Live demo link

<img width="1151" alt="image" src="https://github.com/usebruno/bruno/assets/33191443/54ba2d62-8f42-4989-b51f-b9f683ded85e">

**Comment by Ankit3794** [comment]
Same is happening for Ubuntu (Linux build)

**Comment by sanjai0py** [comment]
Hey @Ankit3794 and @irfansofyana, can you please try the latest version [v1.20.1](https://github.com/usebruno/bruno/releases/tag/v1.20.1) of Bruno in which the bug has been fixed?

**Comment by Ankit3794** [comment]
Hi @sanjai0py , yes for Ubuntu on latest version it's fixed. Thanks!

**Comment by tkbstudios** [comment]
Friendly bump, doesn't work on Windows 11.

**Comment by tkbstudios** [comment]
After updating it seems to be working :)

**Comment by sanjai0py** [comment]
Closing this as the issue has been fixed. Thanks, y'all for taking the time to report it here! ❤️
