### ISSUE TITLE
Crash when trying to load a PDF response

### ISSUE THREAD

**Issue by strongville** [usebruno/bruno#2571]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

- Create a GET request to a web service that returns a PDF file (Content-Type: application/pdf).
- Run request.
- The app crashes and it does not let return to app.

Previously the app showed the text response for PDF file but after clicking on a response tab it also crashed. Right now it consistently crashes when trying to run the request.

Running Bruno v1.20.1 GE on Windows 11 Pro 23H2 (22631.3810) x64.

### .bru file to reproduce the bug

meta {
  name: CF Constancia
  type: http
  seq: 1
}

get {
  url: http://127.0.0.1:5001/pruebas-fisa/us-central1/dbSocioConstancia/file
  body: none
  auth: none
}

### Screenshots/Live demo link

https://github.com/usebruno/bruno/assets/1476503/54c55eef-296f-4724-ab74-09a591a8ddd7

**Comment by Its-treason** [comment]
Could you open the chrome devtools (`Ctrl` + `I`) and share the error message you get? Could you also share some info about the PDF, like size and if other programs can open it.

**Comment by hanneswidrig** [comment]
This is also impacting Mac, issue was introduced in v1.20.x. I had to revert to v1.19 to resolve PDF responses.

**Comment by strongville** [comment]
Great, @Its-treason , so this will be solved as soon as Bruno stable version is updated including the platform change, right?

**Comment by Its-treason** [comment]
> Great, @Its-treason , so this will be solved as soon as Bruno stable version is updated including the platform change, right?

Yes, but not sure, when the electron of Bruno wil be updated. The last update was like +2 years ago. And there are some breaking changes. I guess it will take some time.

**Comment by hanneswidrig** [comment]
This is a serious issue, you straight up can't resolve PDF responses in v1.20 and later.

**Comment by helloanoop** [comment]
@Its-treason I am thinking of doing a electron bump to the latest version. Do you happen to remember anything breaking when you did the electron bumo.

@sanjai0py please prioritise this issue. We need to have this resolved asap.

**Comment by pietrygamat** [comment]
@helloanoop 
 
> Do you happen to remember anything breaking when you did the electron bumo.

 #2304 for sure

**Comment by Its-treason** [comment]
> @Its-treason I am thinking of doing a electron bump to the latest version. Do you happen to remember anything breaking when you did the electron bumo.
> 
> @sanjai0py please prioritise this issue. We need to have this resolved asap.

Be sure to also watch out for: https://github.com/electron-userland/electron-builder/issues/5371 I hacked a fix together using: https://github.com/jitsi/jitsi-meet-electron/commit/4cc851dc75ec15fdb054aa46e4132d8fbfa3a9e5

**Comment by hanneswidrig** [comment]
It looks like something was fixed in Bruno v1.21 and I can now load PDF responses.

**Comment by Its-treason** [comment]
> It looks like something was fixed in Bruno v1.21 and I can now load PDF responses.

Yes, it's fixed. I guess the version of the PDF-Viewer got downgraded to fix this. This issue can be closed. CC: @sanjai0py

**Comment by sanjai0py** [comment]
Closing this issue as the PDF viewer version has been downgraded as a quick fix. Thank you for taking the time to report the bug!
