### ISSUE TITLE
Can not resize vertically 

### ISSUE THREAD

**Issue by IvanMoscovic** [usebruno/bruno#2577]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I can't resize the query window vertically, is there any option for that? Previously I could see the query without scrolling, but now there is an empty space instead

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/22474007/74471c04-9179-4128-9a98-f4d03b43f93b)

**Comment by vayalildanie** [comment]
Now resolved as of latest version(v1.25.0), textbox resizes to fit fill QueryPane correctly: 
![image](https://github.com/user-attachments/assets/5d145aa2-713a-4c0a-b953-c0d730fb49cf)
proper scroll bars, and resizes to fit window

**Comment by sanjai0py** [comment]
Closing this issue is completed. Thank you, @IvanMoscovic, for taking the time to report this bug and for providing the helpful attached images. Also, thank you, @vayalildanie, for confirming this and all the other issues.
