### ISSUE TITLE
Collapse Json not work and find box not show

### ISSUE THREAD

**Issue by fernandomacho** [usebruno/bruno#2580]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When you click on a json node, the json element does not collapse.
When you search on an answer, the search box is hidden.

### Screenshots/Live demo link

Search box
![imagen](https://github.com/usebruno/bruno/assets/62182142/1c45fcec-1c43-43f8-8376-905a7d0a8fd8)

**Comment by dev-abir** [comment]
I can't reproduce the issue, please specify your OS and post a screenshot.

**Comment by dev-abir** [comment]
Not sure then, that might be a mac-specific issue. You may check errors in the console, or try launching it from terminal - it might show you some errors.

I am using ubuntu, bruno version 1.18.0

**Comment by fernandomacho** [comment]
I confirm that with version 1.20.0 both the collapsing of the elements and the search work correctly
![imagen](https://github.com/usebruno/bruno/assets/62182142/b9b6f307-c1e6-4fc3-b158-dd5a59f10449)
The error appears from version 1.20.1

**Comment by Its-treason** [comment]
Works fine with the OpenSource version of 1.20.2, but does not work with the propriotary version.

So one from the Bruno Team has to fix this: @sanjai0py @lohit-1

**Comment by exotexot** [comment]
Also happens for me.
MacOS; M3 CPU, v1.20.2

**Comment by Moghul** [comment]
Happens to me as well on Kubuntu 22.04

**Comment by danielfiniki** [comment]
Same behavior with Bruno v1.20.1 on Arch (6.9.8-arch1-1 with Plasma 6.1.2).

The only error I see if I start it from the console is "ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!", but that's probably not related and just a Electron+Wayland topic as reported [here](https://github.com/electron/electron/issues/32760).

**Comment by sfreeman422** [comment]
Also happening to me on 1.20.2, snap install for Ubuntu 22.04

**Comment by sfreeman422** [comment]
> Works fine with the OpenSource version of 1.20.2, but does not work with the released version.
> 
> So one from the Bruno Team has to fix this: @sanjai0py @lohit-1

Can confirm that this is true. When I clone the repo and run locally, all is well but the release does not have this behavior.

**Comment by Drnkmstr** [comment]
I'm on Bruno 1.20.4 and I still have this issue, it was fine until 1.20.1.

MacOS 14.5, M3 Max

**Comment by sanjai0py** [comment]
Sorry for the inconvenience caused by this bug. The bug was caused by the recent changes made in the codemirror editor. We are fixing it, and the community can expect a patch release soon!

**Comment by diegocam** [comment]
In the meantime, for all of us experiencing this error, a temporary way to make it work: 
1. Place the cursor where you want it to fold/unfold
2. Press `CMD+Shift+[` to fold
3. Press `CMD+Shift+]` to unfold

**Comment by kanetik** [comment]
Is this still in the works? Any ETA?

**Comment by anusree-bruno** [comment]
This issue has been resolved. Feel free to reopen it if the problem persists.

**Comment by jmahalingam** [comment]
> This issue has been resolved. Feel free to reopen it if the problem persists.

Its not working for v1.34 Bruno. I am using the MacOS Sonamo 14.*

**Comment by jmahalingam** [comment]
> Sorry for the inconvenience caused by this bug. The bug was caused by the recent changes made in the codemirror editor. We are fixing it, and the community can expect a patch release soon!

What is the patch release for Bruno v1.34.0 to fix the search box in response body panel?

**Comment by jmahalingam** [comment]
> > This issue has been resolved. Feel free to reopen it if the problem persists.
> 
> Its not working for v1.34 Bruno. I am using the MacOS Sonamo 14.*

It got fixed with v1.38.1
