### ISSUE TITLE
Follow system theme option on linux (freedesktop color scheme)

### ISSUE THREAD

**Issue by TomiOhl** [usebruno/bruno#2581]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

The follow system theme option doesn't work on Linux, Bruno stays always in light mode.
Most Linux distros follow this preference: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference

### Screenshots/Live demo link

System in light mode:
![image](https://github.com/usebruno/bruno/assets/6696659/116ee1c2-e77c-4162-ae08-94863a04afe9)
System in dark mode:
![image](https://github.com/usebruno/bruno/assets/6696659/311d8b0f-9481-4c82-b79b-740e3502939b)
Bruno in dark mode:
![image](https://github.com/usebruno/bruno/assets/6696659/56e74187-bb7f-4843-b68b-ccb040247c90)

**Comment by Its-treason** [comment]
Interresting Bruno currently uses the Browser API to determine the correct theme. This works well on windows not sure why it does not on Linux.

But electron offer an API for this: https://www.electronjs.org/docs/latest/api/native-theme maybe it works better with that.

**Comment by TomiOhl** [comment]
System theme detection was fixed in Chromium 114 iirc, so it might be required to update electron version, too.
Another example of an electron app recently fixing theme detection is VS Code.

**Comment by TomiOhl** [comment]
This got fixed with #2668, since electron got updated to v 25+, which has theme changing fixed 🎉
