### ISSUE TITLE
Import Bruno Collection fails - ValidationError: headers are required

### ISSUE THREAD

**Issue by sigiswald** [usebruno/bruno#2583]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bruno v1.20.2 (and also v1.20.1) on Windows.

- Create a new Collection called "test"
- Add a single request called "test" and URL GET "http://localhost:8080/api/test"
- Save the request and export as a Bruno Collection which creates a test.json file.
- Close the collection and delete it from from the file system (to avoid naming conflicts).
- Import the test.json file as a Bruno Collection.
- Error: Import collection failed.

```
ValidationError: headers are required
    at createError (_app-0ccfd746ec8354d9.js:31:76737)
    at _app-0ccfd746ec8354d9.js:31:77063
656-083d4e6188257160.js:1 BrunoError: The Collection file is corrupted
    at 656-083d4e6188257160.js:1:6056
```

test.json
```
{
  "name": "test",
  "version": "1",
  "items": [
    {
      "type": "http",
      "name": "test",
      "seq": 2,
      "request": {
        "url": "http://localhost:8080/api/test",
        "method": "GET",
        "headers": [],
        "params": [],
        "body": {
          "mode": "none",
          "formUrlEncoded": [],
          "multipartForm": []
        },
        "script": {},
        "vars": {},
        "assertions": [],
        "tests": "",
        "auth": {
          "mode": "none"
        }
      }
    }
  ],
  "environments": [],
  "root": {
    "request": {
      "auth": {
        "mode": "none"
      }
    },
    "meta": {
      "name": "test"
    }
  },
  "brunoConfig": {
    "version": "1",
    "name": "test",
    "type": "collection",
    "ignore": [
      "node_modules",
      ".git"
    ]
  }
}
```

Exporting/importing as a Postman collection works fine.

Kind regards,
/Sigiswald

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/8725098/e11c9880-d4e1-4273-8b46-442030c09de8)

**Comment by sfreeman422** [comment]
+1 similar scenario occurring for me on Ubuntu. I have a more complex collection but still see the same error that @sigiswald is seeing as well.

**Comment by mdxs** [comment]
+1 confirmed same scenario / bug; seen both on:

- Linux Mint using Apt download; and also on
- Windows using Windows x64 Portable download

In both cases using Bruno v1.20.2 with:

- electron : 21.1.1
- chrome : 106.0.5249.103
- node : 16.16.0
- v8 : 10.6.194.17-electron.0

**Comment by mdxs** [comment]
I've found a workaround (based on seeing the PR in #2598).

When the bug is seen, would be to manually edit the export JSON before attempting to import again. Such that there is at least an empty array on the `root.request.headers` path, like:

```
  "root": {
    "request": {
      "headers": [],
      "auth": {
        "mode": "none"
      }
    },
    "meta": {
      "name": "test"
    }
  },

```
For the example scenario in this report, this workaround allowed me to import the "test.json" Bruno collection.

**Comment by sfreeman422** [comment]
Nice! That seems like it would satisfy the current `.required` aspect you recognized on my PR (#2598). I would imagine my PR fixes a regression but will wait for others to chime in.

**Comment by sigiswald** [comment]
Thank you @sfreeman422 and @mdxs !!! Your analysis, feedback and certainly the PR is much appreciated!
