### ISSUE TITLE
Bruno CLI tries to execute folder.bru

### ISSUE THREAD

**Issue by fgrande** [usebruno/bruno#2584]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When running all the requests of a directory without recursion flag, bruno consider also folder.bru as a request to execute, but this is a special filename related to test/scrips/vars of the folder.

### Screenshots/Live demo link

<img width="384" alt="image" src="https://github.com/usebruno/bruno/assets/811941/bbce6f53-6447-48ff-9209-3c8b453ab5cb">

**Comment by helloanoop** [comment]
The fix has been released in CLI `v1.20.3` 🎊
