### ISSUE TITLE
CLI doesn't interpolate params on the URL

### ISSUE THREAD

**Issue by fgrande** [usebruno/bruno#2587]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bruno CLI doesn't interpolate params on the URL
[TestParams.bru.zip](https://github.com/user-attachments/files/16134331/TestParams.bru.zip)

### Screenshots/Live demo link

See attached bru

**Comment by helloanoop** [comment]
The fix has been released in CLI `v1.20.3` 🎊
