### ISSUE TITLE
Constructing Url fails if port in url is injected via variable

### ISSUE THREAD

**Issue by Swiftpaws** [usebruno/bruno#2592]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

http://{{hostname}}:9001/ gives no error

When injecting the port via a variable there are constant error popups "Failed to construct url"
http://{{hostname}}:{{port}}/

### Screenshots/Live demo link

![Bruno_LADgeY4jge](https://github.com/usebruno/bruno/assets/18440081/535d8c54-cc20-444e-a247-9434408ce43d)

**Comment by anusree-bruno** [comment]
This does not happen in the later version. I test on v1.35.
![image](https://github.com/user-attachments/assets/7005f61b-f9e0-423d-a9a1-477f098eccbc)
