### ISSUE TITLE
Cloning a folder does not duplicate `folder.bru` file.

### ISSUE THREAD

**Issue by kkevindev** [usebruno/bruno#2593]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When I clone a folder it does not duplicate the `folder.bru` file and thus all my settings (for example, pre-request vars) are not duplicated.

I think https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/ipc/collection.js#L434-L464 needs to be changed to support the `folder.bru` file.

### Screenshots/Live demo link

![afbeelding](https://github.com/usebruno/bruno/assets/34477826/e6388ed4-0e22-4594-983a-cf8e476a95c8)

**Comment by fgrande** [comment]
I was able to replicate the issue, going to submit a PR to solve it.
