### ISSUE TITLE
Execution sequence of 'Script' and 'Tests' blocks at the collection level and request level changed (v1.19.0 vs v1.20.2)

### ISSUE THREAD

**Issue by anubhavhazarika** [usebruno/bruno#2597]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

We have noticed that in the earlier version [v1.19.0](https://github.com/usebruno/bruno/releases/tag/v1.19.0), the collection level 'Scripts' and 'Tests' blocks were executed first, and then followed by the corresponding request level blocks. That is, the sequence would look like: 
    1. COLLECTION level - Pre Request script
    2. REQUEST level - Pre Request script
    3. COLLECTION level - Post Response script
    4. REQUEST level - Post Response script
    5. COLLECTION level - Tests script
    6. REQUEST level - Tests script

However, in version [v1.20.2](https://github.com/usebruno/bruno/releases/tag/v1.20.2), the execution sequence is changed, and looks like this: 
    1. COLLECTION level - Pre Request script
    2. REQUEST level - Pre Request script
    3. REQUEST level - Post Response script
    4. COLLECTION level - Post Response script
    5. REQUEST level - Tests script
    6. COLLECTION level - Tests script

This unfortunately adversely impacts all tests written based on the previous understanding of the execution sequence.

### .bru file to reproduce the bug

Test collection 'Bruno Execution Sequence' to reproduce the above-reported bug (by running in the different versions):

[Bruno Execution Sequence.zip](https://github.com/user-attachments/files/16149322/Bruno.Execution.Sequence.zip)

### Screenshots/Live demo link

Bruno Execution Sequence v1.19.0: 
![Bruno Execution Sequence v1 19 0](https://github.com/usebruno/bruno/assets/30079665/e4e43634-0523-4253-a7ea-37396048da4c)

Bruno Execution Sequence v1.20.2:
![Bruno Execution Sequence v1 20 2](https://github.com/usebruno/bruno/assets/30079665/aecdcd4d-deab-4c1b-a7d2-63bf40a02260)

**Comment by Its-treason** [comment]
Hey @anubhavhazarika, this is a planned change. 

There was a discussion / voting on the Discord: https://discord.com/channels/1036297729606963331/1039636949855645786/1255862244605034558

![image](https://github.com/usebruno/bruno/assets/39559178/3d838fad-d1ec-42c9-b642-f7d980a2e3a0)

And as you noticed the new "Sandwich Flow" won.

**Comment by anubhavhazarika** [comment]
Hi, @Its-treason, 

Thank you for your response and the information provided. 
We were not aware of the discussion/voting on Discord. 
Although it would have been nice to have the 'choice/setting' as suggested/discussed in that thread, I don't believe we have that feature implemented (please correct if wrong). Meanwhile, we have no other option but to adapt our scripts. 

I will close this issue. Thank you again.
