### ISSUE TITLE
Error when saving Multipart request with empty file input

### ISSUE THREAD

**Issue by maxdestors** [usebruno/bruno#2608]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Current behavior
---

Error when saving a request right after clearing a file input in body multipart requests.
Error when saving a request right after adding a file input in body multipart requests.

Expected behavior
---

Question should be saved.

### .bru file to reproduce the bug

```
meta {
  name: addfile
  type: http
  seq: 1
}

post {
  url: {{base_url}}/addfile
  body: multipartForm
}

headers {
  Accept: application/json
}

body:multipart-form {
  import_file: @file()
}
```

### Screenshots/Live demo link

![buggif](https://github.com/usebruno/bruno/assets/3854597/79eadbf9-5f6a-4540-8715-43fbcc98b6ef)

**Comment by anusree-bruno** [comment]
This issue has been fixed. in #2609, I am closing this ticket
