### ISSUE TITLE
CLI version 1.20.1 and above - bru.setVar() does not set the variable in the collection variables

### ISSUE THREAD

**Issue by hbrahi1** [usebruno/bruno#2611]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

We (@anubhavhazarika) have observed starting from CLI version 1.20.1 and above that when we call bru.setVar() from one request, the variable does not set the variable in the collection variables and consequently, this variable is not available for any following request. However this works correctly when using the Bruno app. Please check the screenshots and attachments.

### .bru file to reproduce the bug

[BrunoCollectionVariables.zip](https://github.com/user-attachments/files/16163577/BrunoCollectionVariables.zip)

### Screenshots/Live demo link

Collection variables using Bruno app v1.20.4:
![image](https://github.com/usebruno/bruno/assets/563034/e77f9c63-1afc-4f02-a071-567991ec9655)

Collection variables using Bruno CLI v1.20.3:
![image](https://github.com/usebruno/bruno/assets/563034/11877d00-9eb1-4438-947d-2db1d8a32bfa)

**Comment by joao-proenca-ada** [comment]
We bumped into this same problem as well. We've had to pin the Bruno CLI version that we're using to 1.20.0 as a workaround, since this broke most of our collections.

**Comment by helloanoop** [comment]
@joao-proenca-ada @hbrahi1 This issue has been fixed in CLI - `v1.20.4`
Can you check if this resolves your issue in CLI ?

**Comment by joao-proenca-ada** [comment]
Hey @helloanoop , just ran a few tests here with `v1.20.4` and it seems to be ok now. Thanks.

**Comment by hbrahi1** [comment]
Hi @helloanoop , tested ok. Thanks for the fix. Closing the bug.
