### ISSUE TITLE
[UI] Code hints invisible on Dark mode

### ISSUE THREAD

**Issue by SPIRIT-00** [usebruno/bruno#2614]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

On screenshot.

### Screenshots/Live demo link

![изображение](https://github.com/usebruno/bruno/assets/128896119/31cc8553-5110-4ddc-91f1-d838ba77271a)

**Comment by drchiodo** [comment]
me too

**Comment by SPIRIT-00** [comment]
@helloanoop it issues was solved on one of updates, Bruno 1.23.1:

![изображение](https://github.com/user-attachments/assets/0a1fdbad-dda0-485f-859c-dcc5557a7878)
