### ISSUE TITLE
Folding of blocks in response doesn't work

### ISSUE THREAD

**Issue by rsau** [usebruno/bruno#2618]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Version: v1.20.4
Folding of blocks in response doesn't work. 
There is no error in console as well. 

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/29110027/d509fa3c-e03f-4de3-a326-448c1f19d4b2)

**Comment by sanjai0py** [comment]
Duplicate of https://github.com/usebruno/bruno/issues/2580
