### ISSUE TITLE
Pre Request vars aren't updating until the request is saved

### ISSUE THREAD

**Issue by nicco09** [usebruno/bruno#2627]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

One of the recent releases made it so my pre request vars aren't being updated when I send the request unless I save it first.

### Screenshots/Live demo link

![Screenshot 2024-07-11 at 4 23 18 PM](https://github.com/user-attachments/assets/6a86c0a9-135a-4892-a3c8-75ec5cdfbb08)
![Screenshot 2024-07-11 at 4 23 28 PM](https://github.com/user-attachments/assets/9ba160ef-50f3-4744-85c2-9b491e9004d0)

**Comment by Moghul** [comment]
Having the same issue with Bruno v1.20.2 on Kubuntu 22.04. This bug has caused me some grief...

**Comment by sanjai0py** [comment]
Hey @nicco09, thank you for taking the time to report the bug. 
Unfortunately, I wasn't able to reproduce it in the latest version [v1.20.4](https://github.com/usebruno/bruno/releases/tag/v1.20.4) of Bruno

https://github.com/user-attachments/assets/37c356e7-0a86-4404-8d5d-5cf5f05cc10b

**Comment by Moghul** [comment]
I can

https://github.com/user-attachments/assets/4d228772-2b74-44ca-8ae1-e254a92040fb

**Comment by sanjai0py** [comment]
Yeah @Moghul, I was also able to reproduce the issue. I notified the team, and we are working on a fix!

**Comment by Moghul** [comment]
Thanks for taking care of this @sanjai0py , I appreciate it!
