### ISSUE TITLE
 Missing "Visualize" Tab in Bruno 1.20.4

### ISSUE THREAD

**Issue by drchiodo** [usebruno/bruno#2633]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

**Description**:
In past version of Bruno , I used a script to generate previews of images received via API. This script was displayed in the "Visualize" tab. However, after updating to Bruno 1.20.4, the "Visualize" tab has disappeared, and I can no longer see the image previews.

**Steps to Reproduce:**

- Use the script provided below to generate image previews.
- Check for the "Visualize" tab in Bruno 1.16 (it should be visible).
- Update to Bruno 1.20.4.
- Notice that the "Visualize" tab is no longer available.

**Expected Behavior:**
The "Visualize" tab should be present in Bruno 1.20.4, allowing users to see visual previews.

**Actual Behavior**:
The "Visualize" tab is missing in Bruno 1.20.4, preventing the display of previews.

**Screenshots**:
![image](https://github.com/user-attachments/assets/8355e53c-fe58-4e07-a002-8b78d93f5d93)

**Script Used**:
```js
let items = "";
try {
  items = res.body;
  let page = `
    <table style="background-color: #DFDFDF; border-spacing: 15px;">
      <tr><td><strong>Image</strong></td><td><strong>Details</strong></td></tr>
    `;

  items.forEach(item => {
    page += `
        <tr>
          <td rowspan="3">
            <img src="${item.mediaUrl}?width=120" alt="Media Image"><br>
          </td>
          <td>Name</td>
          <td><strong>${item.name}</strong><br></td>
        </tr>
        <tr>
          <td>MediaID</td>
          <td><strong>${item.mediaId}</strong><br>
          </td>
        </tr>
        <tr>
          <td>MediaUrl</td>
          <td><strong>${item.mediaUrl}</strong><br>
          </td>
        </tr>
    `;
  });

  page += '</table>';
  bru.visualize(page);
} catch (e) {
  bru.visualize(html)
}
```

**Environment**:
- Bruno version: 1.20.4 Ultimate
- Operating System: Windows 11 - 23H2 - build 22631.3880

### .bru file to reproduce the bug

```bru
meta {
  name: ***
  type: http
  seq: 1
}

get {
  url: {{baseUrl}}/medias?q=***&businessUnit=***&status=Available&page=0&size=20
  body: none
  auth: none
}

params:query {
  q: ***
  businessUnit: ***
  status: Available
  page: 0
  size: 20
  ~references: 
  ~ean: 
  ~adeocode: 
  ~localcode: 
  ~adeotype: 
  ~mediaType: 
  ~category: 
  ~subcategory: 
  ~startCreationDate: 
  ~endCreationDate: 
  ~state: 
}

headers {
  X-Gateway-APIKey: {{$secrets.default.X-Gateway-APIKey}}
}

script:post-response {
  let items = "";
  try {
    items = res.body;
    let page = `
      <table style="background-color: #DFDFDF; border-spacing: 15px;">
        <tr><td><strong>Image</strong></td><td><strong>Details</strong></td></tr>
      `;
  
    items.forEach(item => {
      page += `
          <tr>
            <td rowspan="3">
              <img src="${item.mediaUrl}?width=120" alt="Media Image"><br>
            </td>
            <td>Name</td>
            <td><strong>${item.name}</strong><br></td>
          </tr>
          <tr>
            <td>MediaID</td>
            <td><strong>${item.mediaId}</strong><br>
            </td>
          </tr>
          <tr>
            <td>MediaUrl</td>
            <td><strong>${item.mediaUrl}</strong><br>
            </td>
          </tr>
      `;
    });
  
    page += '</table>';
    bru.visualize(page);
  } catch (e) {
    bru.visualize(html)
  }
}

```

### Screenshots/Live demo link

in Bruno 1.16 i had this 

![image](https://github.com/user-attachments/assets/09083735-0b04-4d13-b1d8-0995335f90ec)

![image](https://github.com/user-attachments/assets/c40d2a71-ef43-4a9f-98d7-0a56b7498537)

this tab is disappeared from Bruno 1.20.4

**Comment by drchiodo** [comment]
Thanks a lot! Works perfectly.

do you know where i can find docs about bru.visualize?

**Comment by itarci** [comment]
When I do an example like lohxt1, the Bruno program stops working and displays the message “Oops! Something went wrong”.
I have no experience in these scripts, can anyone tell me what I'm probably doing wrong?
Is there a “require” missing?

**Comment by helloanoop** [comment]
@itarci The Visualize feature is a part of our paid offering. You should have the Golden Edition for this feature to be enabled.

The issues related to visualisation has been fixed in the latest releases. Please reopen this ticket if the issue persists.

**Comment by nosher150** [comment]
@helloanoop - I've got the Golden Edition (well worth buying it) but can't find any documentation for bru.visualize.

Where can I find documentation about it?

**Comment by helloanoop** [comment]
Hey @nosher150 !
Here are the docs: https://docs.usebruno.com/advanced-guides/visualize
