### ISSUE TITLE
Show indicator whether a script is present

### ISSUE THREAD

**Issue by ihgitigit** [usebruno/bruno#2636]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

When editing a request, the tabs _Query_, _Headers_, _Vars_ and _Asserts_ show an indicator when any values are set.
The Tabs _Body_, _Auth_, _**Script**_ and _Docs_ don't show an indicator.

Especially for scripts, this is kind of dangerous when the collections is used by a colleague that was not the author of that request - he might expect that the shown response is the 1:1 plain answer from the webserver and is not aware, that a "Post response" script did modifications.

So I would suggest to show an asterisk in case values have been applied to the mentioned tabs.

THANK YOU!

### Mockups or Images of the feature

![feature](https://github.com/user-attachments/assets/e72cb381-afa9-4ae9-b4a8-a87cad026d12)

**Comment by helloanoop** [comment]
This is now supported in Bruno

<img width="659" alt="image" src="https://github.com/user-attachments/assets/dee0ee4b-a75a-423c-b08d-4dfb25033e43">
