### ISSUE TITLE
Multiple scroll bars appear in the sidebar in windows production environment

### ISSUE THREAD

**Issue by yaodada123** [usebruno/bruno#2637]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

My computer environment is win10, node version 20, when running the project locally found the situation described in the title
![image](https://github.com/user-attachments/assets/33c04c91-bf5a-47aa-9712-6c169d69a70d)
However, a check of developer options revealed that the css property scrollbar-width was the cause
![image](https://github.com/user-attachments/assets/71be1148-6b29-4a6f-a8a2-684ef1ec137b)
![image](https://github.com/user-attachments/assets/394e391e-a7e7-4461-967e-f3ee1f6e8c39)
By the way, the screenshot of my app is in full screen mode

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/f166c0f6-33e4-48bd-b59e-cd0d553d84d2)

**Comment by pietrygamat** [comment]
This is known issue for builds with updated electron version discussed in  #2293 #2304

**Comment by sanjai0py** [comment]
Closing this issue as resolved. Please use the [v1.26.2](https://github.com/usebruno/bruno/releases/tag/v1.26.2) version of bruno which contains the fix.
