### ISSUE TITLE
Sequential Flow in Script Execution

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#2639]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

## Background
By default Bruno uses sandwich flow while executing collection-folder-request scripts

## Feature Request
Allow UI and CLI Toggles to use sequential flow for script order execution.

If you feel this feature is needed, please upvote and share your use case that will better help us prioritise and implement this feature.

### Mockups or Images of the feature

<img width="880" alt="image" src="https://github.com/user-attachments/assets/10cae459-2e31-4fe7-9321-703b4f194170">

**Comment by tho-gru-38** [comment]
Hi,

My reason for up voting is that I am on the way to import a huge Postman collection into bruno. At collection and folder level some functions are defined to be used in many requests.

Kind Regards
Thomas

**Comment by bkir** [comment]
👋 @helloanoop 

Can you clarify how this should work within the "Tests" context?   Looks like our collection broke after 1.20, we had used the following line at the collection level:

`const scripts = require('./scripts')`

^ We had this at the top of our collection level scripts (pre-request and post-response) and Tests.  Now seeing this when we run our requests: 

> Error invoking remote method 'send-http-request': SyntaxError: Identifier 'scripts' has already been declared

Wasn't this working in a sequential manner before?  What is the solution here?

**Comment by sanjai0py** [comment]
The feature addition pull request [PR](https://github.com/usebruno/bruno/pull/2704) has already been merged, so we are closing this issue.
