### ISSUE TITLE
JavaScript API changed, unable to set variables, 

### ISSUE THREAD

**Issue by joe-gre** [usebruno/bruno#2645]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I recently updated Bruno to the latest version and noticed my pre request scripts were failing because `bru.getProcessEnv()` and `bru.getVar()` were null. I see now that the bru object no longer has these functions and instead has `processEnvVars` and `requestVariables` properties. [The documentation](https://docs.usebruno.com/scripting/javascript-reference) only mentions the functions that are no longer present.

The issue I have is though I can retrieve variables using the properties mentioned above, I can't set them there. The `bru.setVar()` function was removed. If I assign values to them, they aren't actually saved. I need to be able to save variables for my login flow.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/bf536969-084f-40ec-9d85-cd72bc9adea0)

![image](https://github.com/user-attachments/assets/c5c950eb-7346-4656-93c9-3ae428001439)

**Comment by joe-gre** [comment]
I have reproduced this issue with bruno versions 1.20.4, 1.20.1, 1.19.0 and 1.17.0

**Comment by bpoulaindev** [comment]
I'm not sure i understand your issue correctly, you can't log "bru.getVar" but you can still use the method : 
<img width="560" alt="image" src="https://github.com/user-attachments/assets/394a69dc-ce16-486e-8d26-9efaf1ac94ed">
Logs will look like that : 
<img width="383" alt="image" src="https://github.com/user-attachments/assets/ba97a28d-c83a-4f42-999a-e2044f8c0fb6">

**Comment by equiman** [comment]
Indeed, something is wrong. `bru.getVar` is not working. Version: 1.22.0


![Screenshot 2024-07-26 at 12 23 33](https://github.com/user-attachments/assets/9ca124b4-8cdb-42eb-ba92-947555468f6c)

<img width="814" alt="Screenshot 2024-07-26 at 12 21 37" src="https://github.com/user-attachments/assets/75a7a3ee-19e3-4a9a-8760-dcdcdb232a8c">

**Comment by equiman** [comment]
I found the solution in other issue, use `bru.getRequestVar()` instead of `bru.getVar()`

https://github.com/usebruno/bruno/issues/2556#issuecomment-2228163546

**Comment by anusree-bruno** [comment]
I've tested both of these APIs in the latest version, and they're working fine. I'm closing this issue, but feel free to reopen it if the problem persists.

![image](https://github.com/user-attachments/assets/e15e3579-c1fa-4345-bdb4-f8c57541bd5f)
