### ISSUE TITLE
Variables (libs) defined in the Collection-level Post Response cannot be used anymore in the Request-level Post Response since v1.20

### ISSUE THREAD

**Issue by dwiyatci** [usebruno/bruno#2648]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

As the title says - not sure if this is by design.

Before v1.20, I could (re-)use the variables/libs that I defined in the Collection-level, but since v1.20 I got `Error invoking remote method 'send-http-request': ReferenceError: Cannot access 'atob' before initialization` (see the attached screenshots).

### 🟢 Before v1.20
![_Applications_Bruno app_Contents_Resources_app asar_web_index html3](https://github.com/user-attachments/assets/f653c3c1-dcd0-4b9b-b398-acf644f0cad5)
![_Applications_Bruno app_Contents_Resources_app asar_web_index html4](https://github.com/user-attachments/assets/5ecc8fd1-a5e3-423e-89d3-2868cc654f64)

### 🔴 Since v1.20
![_Applications_Bruno app_Contents_Resources_app asar_web_index html](https://github.com/user-attachments/assets/0353adf8-de21-4d35-9a31-329884401627)
![_Applications_Bruno app_Contents_Resources_app asar_web_index html2](https://github.com/user-attachments/assets/4e01a9b9-20ac-47b9-9d67-31a55513e0de)

**Comment by Its-treason** [comment]
Yes, this is kinda by design. It was changed for Folder level scripts. See: https://github.com/usebruno/bruno/issues/2639

**Comment by dwiyatci** [comment]
"kinda"? 😅 

@Its-treason Okay then, perhaps just to confirm so that I can close this issue: is the following where it all started?
- https://github.com/usebruno/bruno/pull/2529
- https://github.com/usebruno/bruno/pull/2530
- https://github.com/usebruno/bruno/commit/45ff36d394518b5c8042a626f9ce2505084653f3

**Comment by Its-treason** [comment]
> "kinda"? 😅 
> 
> @Its-treason Okay then, perhaps just to confirm so that I can close this issue: is the following where it all started?
> - https://github.com/usebruno/bruno/pull/2529
> - https://github.com/usebruno/bruno/pull/2530
> - https://github.com/usebruno/bruno/commit/45ff36d394518b5c8042a626f9ce2505084653f3
> 

Yes, this is where it all started. 

The reason I wrote "kinda" is because breaking your script was not the design goal.

**Comment by dwiyatci** [comment]
But wait, this is weird. If I now put the same declarations in the Folder-level script, I got: `Error invoking remote method 'send-http-request': SyntaxError: Identifier 'atob' has already been declared`.
![_Applications_Bruno app_Contents_Resources_app asar_web_index html5](https://github.com/user-attachments/assets/b19090f6-1056-4db1-b73f-ddfb09c9e2d0)

I thought Collection-level and Folder-level scripts work in their own isolated "boxes". So are they still sharing the same scope somehow? Is this how it's supposed to work? 🤔

**Comment by Its-treason** [comment]
Internally for executing the for example the Pre-Request script. The scripts from Collection, Folders and requests are concatenated. So the Collection and Request Pre-Request script are executed in the same context. The Post-Script is then concatenated, executed in another context.

I hope this explanation made sense. If not, peeking into the source code could help:

Pre-Request-Script: https://github.com/usebruno/bruno/blob/81497d8397082f8600d348f87dfcdded05660d65/packages/bruno-electron/src/ipc/network/index.js#L329-L343

Post-Request-Script: https://github.com/usebruno/bruno/blob/81497d8397082f8600d348f87dfcdded05660d65/packages/bruno-electron/src/ipc/network/index.js#L410-L427

**Comment by dwiyatci** [comment]
Thanks - if the scripts are concatenated, it does make sense for the second error:
`Error invoking remote method 'send-http-request': SyntaxError: Identifier 'atob' has already been declared`

But I still cannot make sense of the first one that I originally reported:
`Error invoking remote method 'send-http-request': ReferenceError: Cannot access 'atob' before initialization`

I mean, if they're concatenated, shouldn't the Folder-level script also get the declarations from the Collection-level script?

**Comment by Its-treason** [comment]
> I mean, if they're concatenated, shouldn't the Folder-level script also get the declarations from the Collection-level script?

No, because Bruno uses "Sandwich" order, the Post-Request scripts are concatenated in reverse order. 

<img width="880" alt="348624235-10cae459-2e31-4fe7-9321-703b4f194170" src="https://github.com/user-attachments/assets/27fbca78-71f7-4b09-9e97-6cb595a772b8">


So the final Post-Request-Script will look like this:

```
const result = atob("Something");

const atob = require("atob");
```

**Comment by dwiyatci** [comment]
Aah, gotcha! It's all clear now. Thanks again, very much, for the clarification! 🙇🏻

**Comment by bkir** [comment]
How does this work for scripts within the Tests tab?  We have a custom scripts.js file sitting at the root of the collection that we were requiring at the collection level in 3 places:  Pre-Request,Post-Response, and Tests:

`const scripts = require('./scripts')`

If we want these scripts available to each request (we're ignoring folder scripting, for now), how should we set this up?  Seems like the sandwich flow won't allow for this any more?

**Comment by Its-treason** [comment]
> If we want these scripts available to each request (we're ignoring folder scripting, for now), how should we set this up? Seems like the sandwich flow won't allow for this any more?

Yes, you are right, with the current "Sandwich" flow this does not work.
