### ISSUE TITLE
CLI Summary output at the end of a run

### ISSUE THREAD

**Issue by MarcHagen** [usebruno/bruno#2649]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

At the moment I've 1381 total requests with 2196 total assertions.
If one or two of these are failing, good luck finding them in the cli output (commandline or GitHub actions).

### Mockups or Images of the feature

_Similar to the newman output_

```
Requests:    1381 passed, 1381 total
Tests:       106 passed, 106 total
Assertions:  2195 passed, 1 failed, 2196 total

 #   failure         detail
 1.  AssertionError  check output of healthcheck
                     expected 'something' to equal 'something'
                     at assertion:0 in test-script
                     inside "healthcheck specific check should pass"
```

_Edit:_
_My javascript is not very on par but could create a PR as jumpstart if desired_

**Comment by anusree-bruno** [comment]
This has been added—thanks for the suggestion! Please check out the latest versions. I'll go ahead and close this ticket.
