### ISSUE TITLE
Snap Releases Are Not Being Updated to Latest Release

### ISSUE THREAD

**Issue by sfreeman422** [usebruno/bruno#2659]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

It looks like the latest version of Bruno has not been released on Snap. I am using the snap package on Ubuntu 22.04 and I do not receive notifications that this app has an update available. I have also manually ran snap refresh per screenshot. At the time of writing this post the latest release per Github is `v1.21.0` however, I can see that my version is `v1.20.2`

![image](https://github.com/user-attachments/assets/9b0e51e8-b533-4695-a9a4-ae041e24e879)
![image](https://github.com/user-attachments/assets/84ef4b8c-ced4-4041-a993-f9b54dc7f736)

### .bru file to reproduce the bug

N/A

### Screenshots/Live demo link
See above

**Comment by sanjai0py** [comment]
Hey @sfreeman422, thank you for taking the time to report this. The Bruno app update in the Snapstore will be visible in a few hours.

**Comment by sanjai0py** [comment]
Hey @sfreeman422 the snap builds are up to date. Please verify!

**Comment by sfreeman422** [comment]
Update received! Thank you!! Is this an automated process or is this something that the team is doing manually upon each release? Curious why this may have been missed for a few versions

**Comment by pietrygamat** [comment]
@sanjai0py the flatpak builds are not part of the build, are they?

**Comment by sfreeman422** [comment]
To build off of this as well, it seems per [this comment](https://github.com/usebruno/bruno/issues/2667#issuecomment-2242211965) that there is the possibility for snap releases to be out of sync with the latest release artifact per the Github repo. Is it possible to firm up this process to ensure that the latest version, regardless of package manager/distribution method will always be on the same release version and that that version is always the version shown in Github? Curious what can be done to help here/if anything from an outside contributor?

**Comment by sanjai0py** [comment]
Hey @sfreeman422, thanks for your interest in this. Currently, our snap releases require manual interaction for build pushes. Due to the involvement of various credentials, we can't delegate this process to an outside contributor. We have a checklist for each release, but occasionally urgent releases cause us to overlook it. We're working on improving this, and we appreciate your interest in contributing to the project. Thank you!
