### ISSUE TITLE
Client Certificates by Environment

### ISSUE THREAD

**Issue by ggiambo** [usebruno/bruno#267]
Four our team I'm looking for a valid alternative to PostMan.
Bruno looks very clean, reactive and easy to use, thank you!
What I'm missing is the possibility to define client-certificates depending on the environment.
Would it be available in the near future?

**Comment by dengnao-tw** [comment]
Any plans to add support for client certificate functionality?

**Comment by tibeer** [comment]
This looks like a promising approach: https://stackoverflow.com/a/52065387
Unfortunately I'm unable to contribute here since I don't know much about the underlaying programing language :(

**Comment by max-wittig** [comment]
HTTP client certificates would be cool to have indeed.

**Comment by panda7789** [comment]
There is PR adding it:
#275

**Comment by tibeer** [comment]
@helloanoop #275 has been merged, so I guess this can be closed :)

**Comment by ggiambo** [comment]
Awesome, thank you!
