### ISSUE TITLE
How to pass multiple environment variable value via CLI

### ISSUE THREAD

**Issue by vaibhav0461** [usebruno/bruno#2671]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Hi Bruno Team,

I want to pass multiple environment variables via CLI like bru run --env Environment_name --env-var client-id='XXX' client-secret='XXX' but it seems only one variable is supported

### Screenshots/Live demo link

<img width="1823" alt="Screenshot 2024-07-19 at 7 16 56 PM" src="https://github.com/user-attachments/assets/1b25d0b1-1e37-4049-bef6-ca0064bf9cbd">

**Comment by DominicRacine** [comment]
You have to do it similarly to docker by repeating the flag every time.

```sh
bru run --env Environment_name  \
    --env-var client-id='XXX' \
    --env-var client-secret='XXX'
```

Cheers

**Comment by vaibhav0461** [comment]
Thanks for the revert @DominicRacine.

This is working.
