### ISSUE TITLE
Axios is null in pre-script

### ISSUE THREAD

**Issue by garposmack** [usebruno/bruno#2674]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I have the following script in the pre-script of my collection (and also tried in only 1 request)
`const axios = require('axios');
console.log(axios);`
on the console i get null as a result.

I was trying to create a pre-script to fetch a token from an url, and i was not able... and it seems that the reason is because axios is null

I have also tried the same with moment, and got the same result.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/6af563f8-5fbf-47c1-8c54-025d50dd58ed)

**Comment by Its-treason** [comment]
Try to log `typeof axios` it will be a function. Because functions cannot be serialised Bruno logs null.

**Comment by helloanoop** [comment]
@garposmack Here is a sample axios code

```javascript
const axios = require("axios");
const response = await axios.get("https://api.github.com/users/usebruno");
console.logresponse.data.avatar_url);
```

Closing this issue. @garposmack please re-open the issue if you are still struggling to make axios work.
