### ISSUE TITLE
Add Command to Run CLI Locally for Development Purposes

### ISSUE THREAD

**Issue by sfreeman422** [usebruno/bruno#2678]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Trying to take a look at some issues that have been opened in this repo, one of which is regarding a modification to the CLI however, I am not sure how to run the CLI locally. 

### Mockups or Images of the feature

N/A - Documentation update

**Comment by Its-treason** [comment]
Try to executing `node packages/bruno-cli/bin/bru.js` from the project root

**Comment by anusree-bruno** [comment]
Hi @sfreeman422 

You can refer to the documentation to run the CLI locally—hope that helps!

[bru-cli Overview](https://docs.usebruno.com/bru-cli/overview)

If you run into any issues, feel free to let us know. Closing this issue.
