### ISSUE TITLE
New Feat: Copy & Paste / Import & Export Button For Headers and Params

### ISSUE THREAD

**Issue by Bervenia** [usebruno/bruno#2684]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

A nice quality of life feature be a copy and past button for request headers and params. Currently for each request if it has the same fields of another you need to individually copy and past the name value pairs separately. Having a simple copy and past button would be just a quality of life feature reducing the number of clicks and button presses needed when making new but similar request files. 

### Mockups or Images of the feature

<img width="465" alt="Screenshot 2024-07-22 at 12 35 00 PM" src="https://github.com/user-attachments/assets/3ee91aff-45bd-4df1-895c-d1700655713f">

**Comment by Its-treason** [comment]
I feel like this adding more button here would clutter up the UI. I feel like adding a Bulk edit more would better because it only adds one button and adds new functionality: https://github.com/usebruno/bruno/pull/706

**Comment by Bervenia** [comment]
Yeah I would agree if they were to go with a copy button per each it should be like a on hover button to show. though I think I like the bulk more. 


honestly it just drives me crazy when there's a good handful of headers that need to be used for every request with no good way of bringing them over.

**Comment by Bervenia** [comment]
Closed as duplicate of #706
