### ISSUE TITLE
Don't require save before sending

### ISSUE THREAD

**Issue by pingiun** [usebruno/bruno#2689]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I would like to use the latest variable data when sending a request, instead of having to save before it uses the new variable.

### Mockups or Images of the feature

N/A

**Comment by Its-treason** [comment]
Duplicate of: #2627. There is already open for this problem: https://github.com/usebruno/bruno/pull/2651 so the problem is hopefully fixed soon.

**Comment by pingiun** [comment]
Thanks, i'll close this one
