### ISSUE TITLE
Mouseover for pre request variables

### ISSUE THREAD

**Issue by Philipp3211** [usebruno/bruno#2692]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I would like to see the value of a referenced pre request variable in the URL if I hover it. Probably there are also other places where the mouseover should appear like if it is used in params or body.

In my example image below the environment variable `url` gets a mouseover but `a` does not. In order to get the mouseover you would have to evaluate the pre request variable before the request is sent and then save the result for when the request will be sent.

I would be down to do PR if this feature is something that you want to have.

### Mock
![abcdefg](https://github.com/user-attachments/assets/19092b44-1ef8-468e-9f56-3e12817d17e1)

**Comment by Its-treason** [comment]
This feature was implemented in 1.21.0 are you on the newest version?

**Comment by Philipp3211** [comment]
You are right. It was implemented. That is awkward 😅
