### ISSUE TITLE
Assert still tested even if deleted before unchecked

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#270]
When an assert is delete, the tests are still ran.

To reproduce:
- Create an assert and run 
<img width="1106" alt="image" src="https://github.com/usebruno/bruno/assets/56150873/34fd2182-f4db-4be4-ab48-368560641ad7">

- Delete the assert using the "bin" icon and run again
<img width="1106" alt="image" src="https://github.com/usebruno/bruno/assets/56150873/0be838f5-da65-403b-ba8a-4e143e054a10">

The assertions is failing the same.

To workaround:
- recreate an assert
- uncheck the newly created assert
- only then, delete the assert using the icon

Version: Bruno v0.16.5
OS: MacOS Sonoma 14.0

**Comment by helloanoop** [comment]
This has been fixed by @Its-treason and is now available in `v0.18.0`
