### ISSUE TITLE
Experiencing "Error invoking remote method 'send-http-request`: TypeError: Invalid URL" in Bruno UI on Windows but not Mac.

### ISSUE THREAD

**Issue by dave-stone-bah** [usebruno/bruno#2702]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

**Note:** Our remote services require access via proxy. These have been set up globally in the Bruno settings for Proxy.

When attempting to send requests with the same collection and same proxy tunnel, our Windows users are experiencing the following error response, while requests are successful on Macs:
```
Error invoking remote method 'send-http-request`: TypeError: Invalid URL
```

**Bruno UI Version:** 1.22.0

**Steps to Reproduce:**
1. Set up global Proxy in **Bruno > Settings > Proxy**.
    - Enabled: ✅ 
    - Protocol: HTTP
    - Hostname: 127.0.0.1
    - Port: 9443
    - Auth: ✅ 
    - Username/Password: confirmed correct
    - Proxy Bypass: set according to our tunnel recommendations
1. Start our local AWS proxy tunnel.
1. Open request and choose environment that contains variable values for path/request parameters.
    - An example of a URL in our collection that fails: `{{base.url}}/v2/job-review/:jobId`
1. Execute request.

**Expected Result:** A JSON response with proper HTTP status.
**Actual Result:** Error invoking remote method 'send-http-request`: TypeError: Invalid URL

I'm not sure if the issue is with the Windows client or a proxy issue. I was hoping someone could tell me if there's a way to get more Bruno internal error logging via the UI in order to troubleshoot these types of errors? I tried opening the Developer Tools, but didn't see anything there related to this error.

I'm wondering if this has anything to do with path parameter resolution that was an issue before 1.20.4? 
Reference: #2439, Fixed by #2465

Thanks for any help you all can provide in figuring this out!

### Screenshots/Live demo link

This screenshot is from a huddle with a team member on Windows that is experiencing this issue.
![image](https://github.com/user-attachments/assets/a25a61e0-f13d-4eb2-a1f9-43db2f6b6201)

I know this doesn't really look or seem helpful, but this is all that we're getting in response and I'm unsure how to troubleshoot.

Also note that we attempted to use a fully-resolved URL instead of one with variable placeholders and still received the same error. No indication in the Developer Tools > Network tab that any request was even sent.

**Comment by dave-stone-bah** [comment]
This appears to have been a configuration error on the user's machine. The resolution is unknown -- it seems to have been resolved as a result of trying multiple things related to the user's proxy settings. I apologize for the false alarm... I'll be more diligent in troubleshooting before posting another issue. Thanks anyway!

**Comment by ahmadawais** [comment]
Just downloaded, ran for the first time, and this is the error on the first simple get request.

```
Error invoking remote method 'send-http-request': TypeError: Invalid URL
```
