### ISSUE TITLE
OAuth 2.0  ReferenceError: getExternalCollectionSecretsForActiveEnvironment is not defined

### ISSUE THREAD

**Issue by jfpedroza** [usebruno/bruno#2706]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When I try to generate an access token using client credentials from the collection auth tab, I get the following error:

```
Uncaught (in promise) ReferenceError: getExternalCollectionSecretsForActiveEnvironment is not defined
    at _app-5ddd16132c496b1d.js:1:854329
    at new Promise (<anonymous>)
    at _app-5ddd16132c496b1d.js:1:854200
    at _app-5ddd16132c496b1d.js:1:10400
    at 626-4d2102350b3d9e2d.js:1:210544
    at s (main-ad5649da2d8f61d3.js:1:87145)
    at Generator._invoke (main-ad5649da2d8f61d3.js:1:86933)
    at P.forEach.e.<computed> [as next] (main-ad5649da2d8f61d3.js:1:87568)
    at n (_app-5ddd16132c496b1d.js:1:1536412)
    at s (_app-5ddd16132c496b1d.js:1:1536615)
```

It has been broken since at least v1.20.4.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/0bea00e6-4525-4638-82ff-032dc599e6a4)

**Comment by sanjai0py** [comment]
Hey @jfpedroza, are you using the latest version of Bruno? The issue you reported has already been fixed and released in version [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0). Please try the latest version [v1.22.0](https://github.com/usebruno/bruno/releases/tag/v1.22.0).

**Comment by LRoss16** [comment]
I've noticed this as well, cloned the repo and I get this error as well

**Comment by sanjai0py** [comment]
Hey @jfpedroza, we weren't able to reproduce the issue. Can you please confirm that you are on version [v1.22.0](https://github.com/usebruno/bruno/releases/tag/v1.22.0) of Bruno once again?

**Comment by pietrygamat** [comment]
@sanjai0py this is specific to FOSS build. The referenced methods are nowhere to be found in this repository.

**Comment by jfpedroza** [comment]
@sanjai0py Yes, it's 1.22.0.

![image](https://github.com/user-attachments/assets/646f1396-74ab-4493-a0db-b8cee0df4832)

**Comment by anusree-bruno** [comment]
The issue has been fixed. I am Closing this.
