### ISSUE TITLE
@usebruno/cli is not being released

### ISSUE THREAD

**Issue by LaSylv** [usebruno/bruno#2707]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I want to upgrade usebruno/cli to 1.22 but the package is not available

### Screenshots/Live demo link

https://www.npmjs.com/package/@usebruno/cli

**Comment by fgrande** [comment]
Hi @LaSylv 

I've just issued 

npm update -g @usebruno/cli

and launching "bru" I see the correct release : 

Bru CLI 1.22.0

FYI I'm on a Mac using Node v.18.12.0

**Comment by sanjai0py** [comment]
Hey @LaSylv, thanks for reporting! And thanks @fgrande for taking the time to look into this issue. 

We just released updates for the CLI!

**Comment by sanjai0py** [comment]
Closing this issue as the CLI has been updated!
