### ISSUE TITLE
Scroll on details click in Runner

### ISSUE THREAD

**Issue by panda7789** [usebruno/bruno#2718]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

In runner, auto scroll feature was recently added which is great.
But it is not very user friendly that **it scrolls on end if user clicks on request** to view more info.
Because after reading request details you have to scroll all way again.

### Screenshots/Live demo link

https://github.com/user-attachments/assets/36e3e968-a255-49b6-a34a-c60abbc6134d

**Comment by panda7789** [comment]
Hmm when I try to build it from the master, it works like expected. Maybe in master is some commit that fixes it, but i cannot find which one.

**Comment by Its-treason** [comment]
> Hmm when I try to build it from the master, it works like expected. Maybe in master is some commit that fixes it, but i cannot find which one.

The Published version of Bruno is very different from the Current Master, because it includes the proprietary code from the Golden Edition.

This is something Bruno Staff has to fix. CC @sanjai0py

**Comment by nikischin** [comment]
Possibly duplicated by #3005

**Comment by sreelakshmi-bruno** [comment]
Hi, this issue is fixed as per v2.15.0. Please check it out. Thanks!
