### ISSUE TITLE
Can it be installed with docker?

### ISSUE THREAD

**Issue by jearton** [usebruno/bruno#2728]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Docker installation

### Mockups or Images of the feature

Docker installation

**Comment by Its-treason** [comment]
You can run the CLI inside Docker. There is an existing community maintained image: https://github.com/davidkarlsen/bruno-image

**Comment by sanjai0py** [comment]
Closing this issue as a duplicate of #1415. Please react with a 👍 to issue #1415 instead.
