### ISSUE TITLE
Query parameters break if "=" is used as value instead of key, parenthesis ignored

### ISSUE THREAD

**Issue by LivingWithHippos** [usebruno/bruno#2731]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I'm using pocketbase and it supports filtering like this:

`http://example.com?filter=(id='abc' && created>'2022-01-01')`

If I use the  `Add Param` button the second = will be recognized as a key instead of value, giving for example this for `newParam`

`http://example.com?filter=(id=&newParam=...`

instead of 

`http://example.com?filter=(id='abc' && created>'2022-01-01')&newParam=...`

writing it manually works

### Screenshots/Live demo link

![Screenshot_20240731_123140](https://github.com/user-attachments/assets/7f2e2ebd-0b9c-467d-944d-1839645cd935)

![image](https://github.com/user-attachments/assets/35a5d9f7-89d7-4df1-8e85-395a0bda9ab5)

**Comment by pietrygamat** [comment]
Same problem reported in #2124, with fix attempted at #2139, probably stale after introducing path parameters.

**Comment by LivingWithHippos** [comment]
> Same problem reported in #2124, with fix attempted at #2139, probably stale after introducing path parameters.

Oh yeah missed that one. Closing as duplicated
