### ISSUE TITLE
Check for updates tab

### ISSUE THREAD

**Issue by creative-tutorials** [usebruno/bruno#2734]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I always make sure to download the latest version of Bruno. It would be great to have a tab to check for available updates and automatically download them if they are available.

### Mockups or Images of the feature

This is an example of something I found on Notion. This feature could be introduced in Bruno.

![notion-example](https://github.com/user-attachments/assets/19c199ea-b2b1-46fa-b2ca-2546be44a5b2)

Here's another example from HTTPie

![httpie-example](https://github.com/user-attachments/assets/22a8b2d0-37a3-4cc3-b8fc-e85090b20fa8)

**Comment by jwetzell** [comment]
This would not be too bad to implement using something like [this](https://www.electron.build/auto-update.html).

**Comment by creative-tutorials** [comment]
> duplicate of #103

Okay, thanks for replying. I'd close the issue right away
