### ISSUE TITLE
Sequence Flow natural not working

### ISSUE THREAD

**Issue by tho-gru-38** [usebruno/bruno#2739]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I just tried the new feature in 1.23.0 regarding the natural flow. Unfortunately I did get it work. Please find attached my collection I did my tests.

This collection finish with the following console messages:
![Sequence-Console](https://github.com/user-attachments/assets/9ec05971-1c91-42c6-b4c5-0b8f4088e0a6)

### .bru file to reproduce the bug

[Sequence-Test-20240801.zip](https://github.com/user-attachments/files/16455394/Sequence-Test-20240801.zip)

### Screenshots/Live demo link

![Sequence-Console](https://github.com/user-attachments/assets/e544bdca-63d3-4dfd-9895-c772605565a9)

**Comment by Its-treason** [comment]
The flow option has been renamed from `natural` to `sequential` in https://github.com/usebruno/bruno/pull/2717

**Comment by tho-gru-38** [comment]
Hi @Its-treason,

Thanks for your quick response. 

Sorry, I missed this detail. In your video `natural` was still used.

Kind regards
Thomas

**Comment by hinnerkoetting** [comment]
I ran into the same issue yesterday, wondering why the natural flow was not working.
Maybe information about flows could be added to the documentation?
