### ISSUE TITLE
UX: Visualize if request body is provided

### ISSUE THREAD

**Issue by matrixik** [usebruno/bruno#2757]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I would like to have some indicator that request body is filled in request.
Now Params and Headers have counter if they are added, but Body have no indication at all that it's filled.
Even simple dot would be nice.

### Mockups or Images of the feature

![image](https://github.com/user-attachments/assets/ea1d0bf4-419d-4412-a319-7438fdb04853)
![image](https://github.com/user-attachments/assets/05d10ff8-d346-41c1-875f-77466e640f56)

**Comment by SPIRIT-00** [comment]
Confirm. I think it needed for 'Scripts' tab too, if any symbol inside scripts field is exist. Sometimes you need to check a lot of requests and you don’t want to waste time going into the scripts and body tabs.

In my cases some requests define body inside scripts, some inside body tab.

**Comment by N-Ziermann** [comment]
I also like that idea. I've just played around with it a bit and I think this unicode character (&\#9679;) would do the job quite well 

<img width="694" alt="Screenshot 2024-08-11 at 16 29 37" src="https://github.com/user-attachments/assets/9efda5c9-c573-4846-8e69-baa112f3978b">

**Comment by matrixik** [comment]
@N-Ziermann thank you for implementing it.
