### ISSUE TITLE
[Feature Request] Environments accessible by Collection

### ISSUE THREAD

**Issue by mkeefe** [usebruno/bruno#2769]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

## Description
Currently environments are tied to collections, which is good for keeping things together for a project. However a use-case does exist where you want environment data accessible across a variety of collections.

## Reason
In Postman, environments sit outside of collections and there is even a globals (not needed). This allows you to have various collections that use the same environment variables.

## Final Thoughts
I'm not sure if an ability to have it within a collection OR outside makes sense, but perhaps a choice is better? The most amazing solution would be to combine top-level environment data and per-collection, but I realize this could cause conflicts and complexity.

### Mockups or Images of the feature

N/A

**Comment by anusree-bruno** [comment]
Hi @mkeefe 
We've added global environments, so these variables can now be accessed across collections. Does this meet your needs?

**Comment by mkeefe** [comment]
Globals does fit the use-case, thanks for the update!
