### ISSUE TITLE
cURL Import ignores Basic Auth values

### ISSUE THREAD

**Issue by stephencoffey** [usebruno/bruno#2774]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

## Steps
- New request
- Select  'from cURL'
- Enter following as cURL command: `curl -u "sk_live_my_octopus_user:" "https://api.octopus.energy/v1/electricity-meter-points/12345/meters/12345/consumption/"`
- Press Create

### Expected
Created request has Basic Auth configured with user `sk_live_my_octopus_user` and blank password

### Actual
Auth tab says No Auth.  Basic Auth is not configured

### .bru file to reproduce the bug

[curl-import-bug.bru.json](https://github.com/user-attachments/files/16530664/curl-import-bug.bru.json)

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/4c92faf9-73ad-45ab-b85a-5982c5f71cea)

**Comment by jwetzell** [comment]
Looks like an easy fix, I will get a PR implementing this later today!
