### ISSUE TITLE
Module not found: Can't resolve @usebruno/common

### ISSUE THREAD

**Issue by pk3000lc** [usebruno/bruno#2794]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When I try to run
`npm run dev:web`
When executing the command, the following error occurred:
```
error - ./src/utils/url/index.js:7:0
Module not found: Can't resolve '@usebruno/common'
   5 | import find from 'lodash/find';
   6 |
> 7 | import brunoCommon from '@usebruno/common';
   8 | const { interpolate } = brunoCommon;
   9 |
  10 | const hasLength = (str) => {
```

I have tried several times to delete the node_modules directory and re-execute all the compilation commands, but I still get the error here.

### Screenshots/Live demo link

![err1](https://github.com/user-attachments/assets/16a62fd1-cc4a-44f3-81e2-9bc322bcddd0)

**Comment by sanjai0py** [comment]
Hey @pk3000lc `bruno-common` needs to be built before starting the dev server. 

```bash
npm run build:bruno-common
```

**Comment by helloanoop** [comment]
Closing this issue. @pk3000lc please re-open if you are not still facing the issue.
