### ISSUE TITLE
Update @aws-sdk/credential-providers in packages/bruno-electron

### ISSUE THREAD

**Issue by SamSalvatico** [usebruno/bruno#2795]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

The `@aws-sdk/credential-providers` dependency must be updated in `packages/bruno-electron` because the current one exposes the project to high vulnerabilities

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/ee6d1773-07b0-4060-935b-3ff6c0a61727)

**Comment by helloanoop** [comment]
This has been fixed in the latest -`v1.34.0` release
We have now moved to `3.658.1` for `@aws-sdk/credential-providers`

**Comment by sxflynn** [comment]
This issue has cropped up again, in @usebruno/cli https://github.com/usebruno/bruno/issues/7025
