### ISSUE TITLE
[Bug] Script/Test input fields are very small (folder view)

### ISSUE THREAD

**Issue by mnkdev** [usebruno/bruno#2796]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Navigate to the `Script` area in any collection `folder` view. The input fields for `Pre Request` and `Post Response` are very small in this view.

The same occurs in the `Test` view, also in the `folder`. Here the input field is only barely visible and therefore not even usable.

I have attached two screenshots below where you can see the problem.

### Screenshots/Live demo link

![Screenshot 2024-08-09 150023](https://github.com/user-attachments/assets/5e12f0cc-e6f6-4dfc-8c77-6df933f4ea33)
![Screenshot 2024-08-09 150124](https://github.com/user-attachments/assets/d1003ebc-cd2b-4539-94a6-832922f144cb)

**Comment by jwetzell** [comment]
@helloanoop this commit [here](https://github.com/usebruno/bruno/commit/4598bb1bdd5db485fa69a40aa20189a3f5b81c33) caused this regression.

**Comment by SamWooler** [comment]
Hey 👋 I noticed this as well and made a [quick fix](https://github.com/usebruno/bruno/pull/2817)

**Comment by mnkdev** [comment]
[like]  Marvin Küppers reacted to your message:
________________________________
