### ISSUE TITLE
send button hiding

### ISSUE THREAD

**Issue by CPU-IDA** [usebruno/bruno#2802]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

![image](https://github.com/user-attachments/assets/95e8f3f3-128a-4e9d-8bec-05e42c01e4f7)

### .bru file to reproduce the bug

send button

### Screenshots/Live demo link

send button

**Comment by CPU-IDA** [comment]
path too long

**Comment by marcusvcalves** [comment]
i've had this same issue

**Comment by sanjai0py** [comment]
Hey @CPU-IDA thanks for reporting this bug! Will look into it!

**Comment by helloanoop** [comment]
PR Merged. This will be released by Tuesday, 13 Aug 2024
