### ISSUE TITLE
Import a large collection from postman

### ISSUE THREAD

**Issue by PabloRodriguezMontalvo** [usebruno/bruno#2805]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I tried to import a v2.1 postman collection to Bruno, it's not showing any errors but the collection is empty. The folders are created but no files inside

### Screenshots/Live demo link

![brunoerror](https://github.com/user-attachments/assets/fec406ab-cef0-46c3-9b07-a552a55c81cd)
![largecollection](https://github.com/user-attachments/assets/f4683e33-298e-48ba-8fec-5609eb67363b)

**Comment by sanjai0py** [comment]
Hey @PabloRodriguezMontalvo can you please check the console for any errors?

**Comment by PabloRodriguezMontalvo** [comment]
I discovered the issue, "[]" symbols in the name of the collection cause this problem
