### ISSUE TITLE
Cookies in CLI

### ISSUE THREAD

**Issue by matthewdickinson** [usebruno/bruno#2821]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Currently, as far as I've seen, there is no support for cookies when running requests from the CLI. This is unfortunate since I have a use-case to run a folder of requests via CLI as part of a test suite. The first request in the folder would log in via an authentication mechanism that results in a cookie being set, and this cookie would be passed on in subsequent requests. However, short of writing unnecessarily complex pre and post request scripts, this is currently not feasible.

I would like Bruno CLI to support cookies for a single invocation of `bru`. For backwards, compatibility, I would think this would be an additional flag that defaulted to false.

Attached is [my PR](https://github.com/usebruno/bruno/pull/2820) to add this feature.

### Mockups or Images of the feature

I think the call would look like this:
```
bru run --env Local --use-cookies
```

**Comment by alan-suchanek** [comment]
I have the same use case. Without support for cookies, I can't use Bruno effectively in test suites.

**Comment by snoeber** [comment]
+1

**Comment by matthewdickinson** [comment]
This was resolved in https://github.com/usebruno/bruno/releases/tag/v1.35.0
