### ISSUE TITLE
Cant press send button if URL becomes to long

### ISSUE THREAD

**Issue by senseiBas** [usebruno/bruno#2826]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When the URL becomes to long, because for example there are to many params in a get call. Then the send button gets pushed out of the application

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/f9d9f1b5-0019-4677-a5ba-08af88bc596f)

**Comment by vayalildanie** [comment]
this issue has already been resolved, as per #2804, just not provided in v 1.24 currently

**Comment by senseiBas** [comment]
Epic!
Thanks!🤘

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/2804) resolving the issue has been merged. The build with the fix will be released today.
