### ISSUE TITLE
Logs are not logged

### ISSUE THREAD

**Issue by krishnakumar-ng** [usebruno/bruno#2827]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

console.log() is not printing any log statements.

### Screenshots/Live demo link

<img width="1372" alt="Screenshot 2024-08-13 at 21 20 16" src="https://github.com/user-attachments/assets/04cd17ac-d3ee-44aa-a24f-5072d74c3873">

**Comment by Its-treason** [comment]
Its printed to the browser console of electron. You can open it with `ctrl`+`shift`+`i`

**Comment by krishnakumar-ng** [comment]
Thanks for the information @Its-treason

**Comment by krishnakumar-ng** [comment]
test("All objects have the 'ID' field", function () {
    var jsonData = res.getBody();

    jsonData.data.forEach( function (item) {
        console.log("ID is: "+item.id);
    });
    console.log("Success");
});

The log statements within the forEach is not printed in the console but the log statement outside the forEach is printed.

**Comment by sanjai0py** [comment]
Hey @krishnakumar-ng, could you please double-check the issue? I couldn't replicate it on my end. Am I missing something?

Also, I've attached a video for reference:

https://github.com/user-attachments/assets/9d7747af-e08c-4afa-9d2e-1fa5642d1f36

Close this issue. Please reopen it if you are still facing the problem.
