### ISSUE TITLE
The NPM run Dev does not work

### ISSUE THREAD

**Issue by jyotipravatiitm** [usebruno/bruno#2836]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

While running the project for first time. I encountered this error

![image](https://github.com/user-attachments/assets/59d2732d-6c8d-4662-8f72-9e48806950fe)

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/e1b77eec-38bd-44bf-b55f-955d1e37bcd4)

**Comment by vanamraghu** [comment]
I faced same issues, you can try installing following below steps (Which should work)
![CleanShot 2024-08-15 at 23 22 11](https://github.com/user-attachments/assets/b802ec4b-3a5f-42dc-974c-23440c8854db)

**Comment by helloanoop** [comment]
Please refer to [docs](https://github.com/usebruno/bruno/blob/main/contributing.md) here for the steps to run bruno locally

```bash
# use nodejs 18 version
nvm use

# install deps
npm i --legacy-peer-deps

# build packages
npm run build:graphql-docs
npm run build:bruno-query
npm run build:bruno-common

# bundle js sandbox libraries
npm run sandbox:bundle-libraries --workspace=packages/bruno-js

# run next app (terminal 1)
npm run dev:web

# run electron app (terminal 2)
npm run dev:electron
```
