### ISSUE TITLE
bruno SBOM

### ISSUE THREAD

**Issue by Lakshmi7705** [usebruno/bruno#2838]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I would like to get SBOM file for Bruno opensource

### Mockups or Images of the feature

I would like to get SBOM file for Bruno opensource

**Comment by jwetzell** [comment]
All the dependencies for the open source components of Bruno are listed in the `package.json` of those components here in this repo. The distributed builds of Bruno on the release page of this repo come from a closed source repo so you would need to reach out to the team to get details on the dependencies there.

**Comment by helloanoop** [comment]
Hey @Lakshmi7705 If you still need the SBOM for the production builds, please reach out to us at support@usebruno.com
