### ISSUE TITLE
Bruno CLI: Assertions if certificate is expired it doesn't count as test failed

### ISSUE THREAD

**Issue by FleaFieldy** [usebruno/bruno#285]
Your aplication y awesome! Very good work.

In Bruno CLI running on Win11 if I run 'bru run' on a folder it runs every test very well. Nevertheless if a request failed because the certificate is expired, This request doesn't count as failed within the total of all tests.

I had two cert expiration in my run. This is the message I've got
![image](https://github.com/usebruno/bruno/assets/11560460/5eaf286b-c0cf-4cad-8b2b-63201ccaa27f)

It has to say:
`Tests: 0 passed, 0 total
Assertions: 20 passed, 2 failed, 22 total`

Otherwise, please, could you please tell me how to assert a valid certificate?

**Comment by helloanoop** [comment]
This issue has been resolved in the latest CLI version.
Please re-open if the problem persists.
