### ISSUE TITLE
Shell-Curl doesn't add Content-Type header

### ISSUE THREAD

**Issue by jtara1** [usebruno/bruno#2853]
### I have checked the following:

- [ ] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

The code generated from a request is not equivalent to that sent from bruno.

To reproduce:
1. run an http server
```python
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/', methods=['POST'])
def handle_post_request():
    data = request.get_json()
    
    response = {
        "data": data
    }
    
    return jsonify(response), 200

if __name__ == '__main__':
    app.run(debug=True)
```
2. send a request through bruno (temp.bru), (returns 200)
3. send the request generated for shell using curl, (returns 415)
```
curl --request POST \
  --url http://localhost:5000/ \
  --data '"test request body"'
```

### .bru file to reproduce the bug

meta {
  name: temp
  type: http
  seq: 2
}

post {
  url: http://localhost:5000
  body: json
  auth: none
}

body:json {
  "test request body"
}

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/efc5abf6-f6c4-446f-af36-1f2ce43cd82d)

**Comment by jwetzell** [comment]
What version of bruno are you using? This use to be the behavior but was resolved in v1.24.0.

**Comment by jtara1** [comment]
1.22.0

Sorry, didn't notice recent updates. I'll pull from nixpkgs unstable instead of 24.05.

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=bruno

**Comment by jwetzell** [comment]
Looks like the unstable is still behind but not as much.
