### ISSUE TITLE
Import POSTMAN collection with inconsistent request.method capitalization

### ISSUE THREAD

**Issue by davidweterings** [usebruno/bruno#2859]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Try importing https://github.com/commercetools/commercetools-postman-collection/blob/master/api/collection.json on Bruno 1.25.0

This gives a validation error:

`ValidationError
    at Object.createError (_app-7d2ec193079a61ca.js:31:76737)
    at Object.test (_app-7d2ec193079a61ca.js:34:3550)
    at validate (_app-7d2ec193079a61ca.js:31:76989)
    at runTests (_app-7d2ec193079a61ca.js:31:74506)
    at _app-7d2ec193079a61ca.js:34:740
    at _app-7d2ec193079a61ca.js:31:74249
    at _app-7d2ec193079a61ca.js:31:74751`

If you dive deeper, the inner error is:

`
items[1].items[11].request.method must be one of the following values: GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS, TRACE
`
Inspecting the postman collection, the request.method is inconsistent. Sometimes it's lower case get/post/delete etc.

Would it make sense to allow lower case values for request.method? Or uppercase and validate them?

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/e4fdb63a-2f87-45f2-962a-40bc2744adb6)
![image](https://github.com/user-attachments/assets/35d1638b-f747-4829-a134-1054f0656d2b)

**Comment by NiklasBr** [comment]
It ought to validate as upper case:

https://datatracker.ietf.org/doc/html/rfc9110#section-9

> The method token is case-sensitive because it might be used as a gateway to object-based systems with case-sensitive method names. By convention, standardized methods are defined in all-uppercase US-ASCII letters.

**Comment by davidweterings** [comment]
I will instead ask for the collection to be fixed, thanks!
