### ISSUE TITLE
Saving a response to a file results in the file being base64 encoded

### ISSUE THREAD

**Issue by RohanTalip** [usebruno/bruno#2872]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

After making a successful request that returns JSON data in the response:
![Screenshot 2024-08-20 at 1 03 23 PM](https://github.com/user-attachments/assets/b8de4306-5525-42ad-86bc-77a0dfc8de91)
![Screenshot 2024-08-20 at 1 03 36 PM](https://github.com/user-attachments/assets/4b673dbd-24cd-41c2-9a3f-dfbfc12aa793)

... clicking on the `Save response to file` button:
![Screenshot 2024-08-20 at 1 10 37 PM](https://github.com/user-attachments/assets/08599076-156c-49a5-9ba2-0f69bb883162)

... and saving it to a file in my local file system results in it being `base64` encoded.

```
$ cat httpbin-get-response.json 
ewogICJhcmdzIjoge30sIAogICJoZWFkZXJzIjogewogICAgIkFjY2VwdCI6ICJhcHBsaWNhdGlvbi9qc29uIiwgCiAgICAiQWNjZXB0LUVuY29kaW5nIjogImd6aXAsIGNvbXByZXNzLCBkZWZsYXRlLCBiciIsIAogICAgIkhvc3QiOiAiaHR0cGJpbi5vcmciLCAKICAgICJSZXF1ZXN0LVN0YXJ0LVRpbWUiOiAiMTcyNDE4NDEzMzQ0MiIsIAogICAgIlVzZXItQWdlbnQiOiAiYXhpb3MvMS43LjIiLCAKICAgICJYLUFtem4tVHJhY2UtSWQiOiAiUm9vdD0xLTY2YzRmNjQ3LTEyNTg3YWMyMmEyMmZhYzg0MDM0MWQ5MyIKICB9LCAKICAib3JpZ2luIjogIjEwNy4xMzMuMTQ0LjIzMiIsIAogICJ1cmwiOiAiaHR0cHM6Ly9odHRwYmluLm9yZy9nZXQiCn0K 
```

```
$ base64 -d < httpbin-get-response.json 
{
  "args": {}, 
  "headers": {
    "Accept": "application/json", 
    "Accept-Encoding": "gzip, compress, deflate, br", 
    "Host": "httpbin.org", 
    "Request-Start-Time": "1724184133442", 
    "User-Agent": "axios/1.7.2", 
    "X-Amzn-Trace-Id": "Root=1-66c4f647-12587ac22a22fac840341d93"
  }, 
  "origin": "107.133.144.232", 
  "url": "https://httpbin.org/get"
}
```

This is just a sanitized example.  This also happened with some other queries too.

It is probably due to this line in PR #766 that added the ability to save a response to a file:
https://github.com/usebruno/bruno/pull/766/files#diff-eaeb1da31271859ebecb449a3291ab31d513dbee71aff0df896001827f94cc90R883

This is the current canonical URL of the same line: https://github.com/martinsefcik/bruno/blob/bcdbc0ebede4ecd60f5e0a750c7634e106400a6b/packages/bruno-electron/src/ipc/network/index.js#L1146

### .bru file to reproduce the bug

```
meta {
  name: get
  type: http
  seq: 2
}

get {
  url: https://httpbin.org/get
  body: none
  auth: none
}

headers {
  accept: application/json
}
```

### Screenshots/Live demo link

See above.

**Comment by datatraveller1** [comment]
Thank you very much! Please publish a new version with the fix soon. I can't save XML files since version 1.25 properly anymore. Version 1.24 is the last version which works as expected when using save response to file.
