### ISSUE TITLE
Request brokes sandbox vm in Safe mode

### ISSUE THREAD

**Issue by SPIRIT-00** [usebruno/bruno#2881]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

If use safe mode and **have body with boolean field** inside request And any **getRequestVar** / **getVar** method of _bru_ object inside any script field vm machine will down with: Error invoking remote method 'send-http-request': Error: TypeError: vm.newBoolean is not a function.

### .bru file to reproduce the bug

meta {
  name: BruTestVMDown
  type: http
  seq: 1
}

post {
  url: {{TestServerApi}}
  body: json
  auth: none
}

headers {
  x-access-token: {{CurToken}}
}

auth:basic {
  username: 
  password: 
}

auth:bearer {
  token: 
}

body:json {
  {
    "name": "Тестовый тип вложений",
    "fileExtension": [],
    "bucket": "TestBucket",
    "icon": "mdi-border-none-variant",
    "reqModels": ["Labels"],
    "reqLoadName": false
  }
}

vars:pre-request {
  table: {{ftable}}
  testField: name
  testFieldDataType: 
  errMessage: 
  expectedStatus: 201
  notExistId: 5000000
  tooLongId: 9223372036854775808
  isLink: false
  id1: 
  id2: 
  linkWith: 
  findOneId: 
  propName: 
  propValue: 
}

script:pre-request {
  const isLink = bru.getRequestVar('isLink')
}

### Screenshots/Live demo link

![изображение](https://github.com/user-attachments/assets/3336bf13-b3d8-41e4-9c0b-4773d7e97fdd)

**Comment by helloanoop** [comment]
The fix is now available in `v1.26.1` release
