### ISSUE TITLE
[Feature] Double click to rename a request

### ISSUE THREAD

**Issue by thelazyoxymoron** [usebruno/bruno#291]

**Comment by ilumin** [comment]
Should it render input in the request or render the modal to rename the request (right now when I click the rename in the option menu, it renders the modal to rename the request)

**Comment by thelazyoxymoron** [comment]
Ideally, it should enable renaming in-place rather than a modal, but for the sake of consistency, a modal would also work.

**Comment by helloanoop** [comment]
This was delivered by @ilumin and is now available in `v0.18.0`
