### ISSUE TITLE
Test cases failing when using forEach with nested tests

### ISSUE THREAD

**Issue by z0r3f** [usebruno/bruno#2921]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

**Description:**
I've just updated the app (1.23.0 -> 1.26.2), and now my test cases are failing. The issue occurs when I try to use a `forEach` loop to iterate over test cases and create individual tests. Here's a simplified example of the code that is causing the problem:

```javascript
const testCases = [
  {
    description: "first message",
    expectedMessage: "first message",
  },
  {
    description: "second message",
    expectedMessage: "second message",
  }
];

testCases.forEach(({ description, expectedMessage }) => {
  test("my inner test", () => {})
});

test("my outer test", () => {})
```

*Problem*: When I comment out the line test("my inner test", () => {}), the tests run fine. However, with the line uncommented, the tests fail ( `SyntaxError: Unexpected identifier` ). My tests are structured this way and I need to retain this format.

*Expected Behavior*: The tests should generate individual test cases successfully.

*Actual Behavior*: Tests fail when using a forEach loop to generate nested test cases.

### Screenshots/Live demo link

# Fail
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/5dc77803-a9be-451f-b3ba-5a543adb384a">

# Success
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/e2a1e853-9237-4890-a416-683d54238e19">

**Comment by helloanoop** [comment]
@z0r3f You can use @lohxt1 fix above in the interim.
We will be releasing a patch in the next few days that will revert to the old behaviour.

**Comment by z0r3f** [comment]
Perfect. Staying tuned for the fix.
Thank you all

**Comment by anusree-bruno** [comment]
This has been fixed.
![image](https://github.com/user-attachments/assets/41d3b15c-9ac1-4c9a-892a-8ab8383218d4)


I am closing this issue.
