### ISSUE TITLE
Version Typo

### ISSUE THREAD

**Issue by menjilx** [usebruno/bruno#2929]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

There's a typo maybe on the version showing on the Bruno app it should be 1.26.2

### Screenshots/Live demo link

<img width="518" alt="image" src="https://github.com/user-attachments/assets/2cc88715-6c31-447b-b7f6-c23155c3ea68">

**Comment by bengeois** [comment]
It seems to be fixed with v1.27.0
<img src="https://github.com/user-attachments/assets/c40f7d22-af68-425c-96b0-f040e5a1fcf5" width="500">
