### ISSUE TITLE
Unable to update or install 1.26.2 using Homebrew

### ISSUE THREAD

**Issue by Mo0rBy** [usebruno/bruno#2948]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Hello! I'm not sure if I should be reporting this on Bruno Github or Homebrew's but my guess is that something may have gone wrong in the release process for 1.26.2 so I'm reporting it here, however, from other issues it looks like others have been able to install 1.26.2 just fine (but I can't see how they have installed it).

When attempting to upgrade Bruno or install Bruno version 1.26.2 using Homebrew, I get a SHA256 mismatch error:
```
❯ brew install --cask bruno
==> Downloading https://github.com/usebruno/bruno/releases/download/v1.26.2/bruno_1.26.2_arm64_mac.dmg
Already downloaded: /Users/wmoorby/Library/Caches/Homebrew/downloads/9208a792d118d96fcb3f63fa9e2117d0cc4870db8cb9f5dca43565e1972da7a2--bruno_1.26.2_arm64_mac.dmg
Error: SHA256 mismatch
Expected: 0ef878baadbc6298fbb96bb2214b7017507d5001137f5c2e088c4b1816ee0d76
  Actual: 5ba1574ed5a2eb48b75ec783c83948940f35933e6e1fbd1667fcfb3a53513efa
    File: /Users/wmoorby/Library/Caches/Homebrew/downloads/9208a792d118d96fcb3f63fa9e2117d0cc4870db8cb9f5dca43565e1972da7a2--bruno_1.26.2_arm64_mac.dmg
To retry an incomplete download, remove the file above.
```

I've attempted removing the file as instructed and re-running the command and I get the same result with the same SHA's presented.

Here is the output of `brew doctor` (no issues):
```
❯ brew doctor
Your system is ready to brew.
```

I am using an M1 Pro with MacOS Sonoma 14.6.1

### .bru file to reproduce the bug

N/A

### Screenshots/Live demo link

N/A

**Comment by Mo0rBy** [comment]
I just tried downloading the package directly from the Homebrew site and can install this way:
![Screenshot 2024-08-28 at 09 22 28](https://github.com/user-attachments/assets/da43f987-981f-41bf-bdcc-1f83e629a13a)

**Comment by fenneclabs** [comment]
I have the same problem with the x86 build:
`==> Downloading https://github.com/usebruno/bruno/releases/download/v1.26.2/bruno_1.26.2_x64_mac.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/542284380/154e6040-db27-4fbe-9649-c06ce4ef1aed?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240828%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240
######################################################################################################################################################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: 20bc7a105b5fc9037c70b2f00732b7becf4239beb48161b7e18c4eea51f1bc9f
  Actual: bfcca3cb7b13dcf1f0b3c71d96f520d766bb1fc42ae83158c1eadc0add095c82
    File: /Users/<user>/Library/Caches/Homebrew/downloads/0e2ed166db3654a583098f261d30e4a6f986dde41157024c57a872d7a1b201ac--bruno_1.26.2_x64_mac.dmg`

**Comment by helloanoop** [comment]
Apologies for the homebrew issue around `1.26.2` release.
We had to update our mac builds a few hours ago due to a step that got missed while creating the build.

We will be releasing `v1.27.0` within the next few hours.

Current workaround is to use `brew install bruno@1.26.1` or install the binary manually
We'll also be raising a PR soon to patch the homebrew SHA mismatch for v1.26.2

**Comment by Mo0rBy** [comment]
Oh, you don't need the `--cask` flag? Does the HomeBrew Bruno page need updating (you can see the command shown in my screenshot)? 
Using this flag works btw, but I don't think it's possible to define a specific version of a cask without doing some annoying stuff, or am I completely wrong?

**Comment by Mo0rBy** [comment]
And @helloanoop what release process do you have? You said 
> We had to update our mac builds a few hours ago due to a step that got missed while creating the build

which indicates that you have some manual processes. I'm a DevOps Engineer and would be happy to contribute to some automated release workflows if you think this will benefit the project.

**Comment by helloanoop** [comment]
Hey @Mo0rBy 

Yes, currently we have a manual process for the builds. We are working on the automation the builds.

> Using this flag works btw, but I don't think it's possible to define a specific version of a cask without doing some [annoying stuff](https://stackoverflow.com/questions/58373704/how-do-you-specify-a-version-using-brew-cask), or am I completely wrong?

You are right. I have deleted the note on installing a custom version

**Comment by helloanoop** [comment]
We just released `v1.27.0` 

You can download the binaries at https://www.usebruno.com/downloads

Brew Cask should get updated within the next few hours.
https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+bruno+

**Comment by Mo0rBy** [comment]
> Hey @Mo0rBy
> 
> Yes, currently we have a manual process for the builds. We are working on the automation of the builds.
> 
> > Using this flag works btw, but I don't think it's possible to define a specific version of a cask without doing some [annoying stuff](https://stackoverflow.com/questions/58373704/how-do-you-specify-a-version-using-brew-cask), or am I completely wrong?
> 
> You are right. I have deleted the note on installing a custom version

Using `brew install bruno` works, so you weren't wrong to state using `bruno@X.X.X`, I was just highlighting that the HomeBrew website states to use the `--cask` flag which you cannot define a specific version. So I think the HomeBrew website Bruno page needs to be updated to remove the `--cask` flag, as it is not needed and does not enable defining a specific version.

![Screenshot 2024-08-28 at 11 53 20](https://github.com/user-attachments/assets/9148a58e-8cfd-4890-840c-d3db8163252c)

Here you can see it works without the `--cask` flag (which is better than with it):
```
❯ brew install bruno
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################################################################ 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
############################################################################################################################################################################################################ 100.0%
==> Downloading https://github.com/usebruno/bruno/releases/download/v1.26.2/bruno_1.26.2_arm64_mac.dmg
Already downloaded: /Users/wmoorby/Library/Caches/Homebrew/downloads/9208a792d118d96fcb3f63fa9e2117d0cc4870db8cb9f5dca43565e1972da7a2--bruno_1.26.2_arm64_mac.dmg
Error: SHA256 mismatch
Expected: 0ef878baadbc6298fbb96bb2214b7017507d5001137f5c2e088c4b1816ee0d76
  Actual: 5ba1574ed5a2eb48b75ec783c83948940f35933e6e1fbd1667fcfb3a53513efa
    File: /Users/wmoorby/Library/Caches/Homebrew/downloads/9208a792d118d96fcb3f63fa9e2117d0cc4870db8cb9f5dca43565e1972da7a2--bruno_1.26.2_arm64_mac.dmg
To retry an incomplete download, remove the file above.
```

**Comment by fenneclabs** [comment]
1.27 fixed the issue for me, thank you @helloanoop

**Comment by helloanoop** [comment]
Homebrew cask of Bruno has been updated.
Thanks everyone!
Closing this issue.

**Comment by james-s-w-clark** [comment]
RE `--cask`, for `brew bundle install` I get:

```
# ~/Brewfile
brew "bruno"

# Warning: 'bruno' formula is unreadable: No available formula with the name "bruno". Did you mean run?


cask "bruno"
# OK
```

Maybe it's best to keep stating it as a cask install, if that gives the most reliable installs.
