### ISSUE TITLE
Setting value of undeclared env variables from pre-request scripts has no effect

### ISSUE THREAD

**Issue by lared** [usebruno/bruno#295]
Affected: Bruno v0.17.0, electron

Steps to reproduce:

1. Create an empty environment and make it active
2. Create an empty GET request with url `{{calculatedUrl}}`
3. Have pre-request script set the variable to some valid url:

```js
bru.setEnvVar("calculatedUrl", "https://petstore.swagger.io/v2/pet/findByStatus?status=available");

console.error(bru.getEnvVar("calculatedUrl"))
```

Expected (version 1):

- dev tools logs contain the log with url
- environment variable gets created
- request succeeds

Expected (version 2):

- code which sets the variable raises an exception

Actual:

- dev tools contain "null" error message
- environment is still empty
- I get error ECONNREFUSED 127.0.0.1:80

It works just fine when I pre-create the variable.

It seems like it would be a good idea to dynamically create those variables as they can be quite useful, as they were in postman (you don't need to create placeholders ahead of time), however the API of setEnvVar should take into account whether they are secret or not (in this particular case I use it for intermediate tokens in a non-standard auth flow).

I'd see it working like that:

- if there is no active environment - throw an exception
- if there is an active environment and the variable already exists
  - if the type (secret/non-secret) doesn't match - throw an exception
  - otherwise, overwrite the value
- if there is an active environment and the variable doesn't exist yet, create it

Also defaulting to localhost when no url is given seems kind of weird.

**Comment by helloanoop** [comment]
This has been fixed in v1.3.0

Please re-open if the issue still exists
