### ISSUE TITLE
Multiple requests in a single .bru CLI file

### ISSUE THREAD

**Issue by ketilyv** [usebruno/bruno#2952]
Hello - is it possible to run multiple requests in a single .bru file? Example could be a POST request followed by a get request in the same file.

**Comment by berlingoqc** [comment]
If you arrange your request in a single folder , you can execute the folder. It will do all request inside

**Comment by ketilyv** [comment]
OK, thanks! I implicitly take the answer to be "No - you can only run 1 request per file." But as you point out - yes, you can run all requests in a folder, but no - not more than one request per .bru file!

**Comment by berlingoqc** [comment]
Yeah sorry, i'm a new user too of Bruno. But my guess is that is designed that way. And it makes sense. a single bru file is a request.

Do you think we could close this issue?
