### ISSUE TITLE
bug: userAgent in request header shows `axios`

### ISSUE THREAD

**Issue by shravan20** [usebruno/bruno#2972]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Current Behaviour

Currently, if you check the request header, you see that we are previewing it as axios; since `axios` is used under the hood.

### Expected Behaviour

Set `userAgent` to bruno-runtime/version_noSet `userAgent` to `bruno-runtime/version_no`, so that we can differentiate these request agents.

Example:
```
{ "level": "info", "message": "{ "timestamp ": "2024 -08 - 29T21: 37:06.281Z ", "method ": "GET ", "url ": " / health - check ", "status ": "404 ", "responseTime ": "0.420 ", "remoteAddr ": ":: 1 ", "userAgent ": "axios / 1.7.2 "}", "timestamp": "2024-08-29T21:37:06.282Z" }
```

### Screenshots/Live demo link

Attaching sample screenshot for reference:

![Screenshot 2024-08-30 at 3 11 55 AM](https://github.com/user-attachments/assets/bf58589b-f71c-44aa-8450-3a5599f866b5)

**Comment by helloanoop** [comment]
This will be available in `v1.29.0`
