### ISSUE TITLE
Support more languages in Generate Code

### ISSUE THREAD

**Issue by HSGamer** [usebruno/bruno#2990]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Since I usually work on Java projects, I want to generate Java code from the collections.
Then I checked `httpsnippet`, the library Bruno is using to generate code snippets, and saw that it supports more languages than the current ones.
Perhaps there should be a way to show all languages from `httpsnippet` in Bruno so that I can generate code snippets in any language `httpsnippet` supports.

### Mockups or Images of the feature

![Screenshot_20240902_110210](https://github.com/user-attachments/assets/9301a8f0-f905-4351-ba01-8053180b9729)

**Comment by helloanoop** [comment]
This will be available in `v1.29.0`
