### ISSUE TITLE
BUG1 - Collection Runner with parameters shouldn’t throw a error if you bail on the file selector dialog without picking a file. 

### ISSUE THREAD

**Issue by i-usebruno** [usebruno/bruno#2994]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

> Collection Runner with parameters shouldn’t throw a error if you bail on the file selector dialog without picking a file

### .bru file to reproduce the bug

None

### Screenshots/Live demo link

<img width="1228" alt="Screenshot 2024-09-02 at 1 00 41 PM" src="https://github.com/user-attachments/assets/0e920c02-ce5c-4575-9ee1-7e731858ddc6">

**Comment by anusree-bruno** [comment]
This issue has been fixed (see the screen recording). I am closing this issue.

https://github.com/user-attachments/assets/cda11700-8ef2-4763-b5a7-ac843281dc50
