### ISSUE TITLE
Chaning only uppercase/lowercase in a file results in an error.

### ISSUE THREAD

**Issue by Placeprom** [usebruno/bruno#2995]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Problem
Renaming a request fails if you only change uppercase/lowercase since a request with the same name already exists. This makes sence since we can not have the same file name twice inside the folder. As a user I would however expect the programm to be able to rename the file if I made a typo (f.ex if I want to rename myREquest to myRequest)

### Current Solution
When making a Caps typo the only solution is to rename it to another name and rename it again which is anoying. (myREQuest -> myRequest1 -> myRequest)

### Proposed Solution
When editing a file if the file exists but is the same file renaming it to the same file name (with different upper and lower cases) should be fine. 

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/438b7df4-86ca-46d4-98c5-65ea1bfceace)

**Comment by helloanoop** [comment]
This has been addressed in PR #3171 and will be released in the upcoming `v1.32.0` release next week.
