### ISSUE TITLE
Can't create a new collection in wsl

### ISSUE THREAD

**Issue by tiagosimoesdev** [usebruno/bruno#3010]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When trying to creating a new collection in wsl it gives 
![image](https://github.com/user-attachments/assets/f8fe5656-5edd-4c96-a64e-ea0526bac42a)

The path I'm trying to create:
\\wsl$\Ubuntu\home\tiago\blablabla

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/f8fe5656-5edd-4c96-a64e-ea0526bac42a)

**Comment by sanjai0py** [comment]
Hey @tiagosimoesdev, thank you for taking the time to report this issue! Could you please check the console tab for any error messages and share them here? It will help us with debugging.

**Comment by Pragadesh-45** [comment]
Hey @tiagosimoesdev!

I'm able to create a Collection in WSL, e.g., path: `\\wsl.localhost\Ubuntu\home\codex_wsl\wsl-testing`. If you're able to reproduce the bug, please send the logs from the dev tools.


https://github.com/user-attachments/assets/9b93cdc2-0396-4f0c-83ad-7efe117216cb

**Comment by tiagosimoesdev** [comment]
Hi , thanks for replying . 
I tested with \\wsl.localhost and it works ! 

but with \wsl$\Ubuntu\ ( what i usually use it doesn't ) 

There is no error in console or network, just the message in the UI.

**Comment by Pragadesh-45** [comment]
Hey @tiagosimoesdev!

I'm not able to traverse this path: `\wsl$\Ubuntu\`. Since it comes from the network, we can use `\\wsl$\Ubuntu\` to access it.
We'll release a fix for this soon.

For the WSL network path, please use `\\`.

![image](https://github.com/user-attachments/assets/899bc312-ce41-426e-8c52-eea73b578f77)
