### ISSUE TITLE
Search on response body breaking with special symbol

### ISSUE THREAD

**Issue by augustotimm** [usebruno/bruno#3016]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am using Bruno v 1.27.0 on MacOS. When I try to search (cmd+F) on a response body as soon as I type a special symbol, as "[" for example, the app breaks and send me to the issue report page, but clicking on going back to the app it restores correctly.

### Screenshots/Live demo link

<img width="1296" alt="image" src="https://github.com/user-attachments/assets/c8cb9c06-b123-477f-bc57-dc5bf950a60c">

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/3057) fixing the issue has been merged and is expected to be released soon. Thank you for taking the time to report the issue!
