### ISSUE TITLE
PostHog ApiKey is hardcoded

### ISSUE THREAD

**Issue by zioalex** [usebruno/bruno#3023]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Looking in the code I found that you store PostHog ApiKey in code in the files:
[packages/bruno-app/src/providers/App/useTelemetry.js](https://github.com/usebruno/bruno/blob/46017a6c505642643a623a7d5bb666c6b38a893e/packages/bruno-app/src/providers/App/useTelemetry.js#L11)
[packages/bruno-app/src/components/Sidebar/GoldenEdition/index.js](https://github.com/usebruno/bruno/blob/46017a6c505642643a623a7d5bb666c6b38a893e/packages/bruno-app/src/components/Sidebar/GoldenEdition/index.js#L12)

Not sure if such key is still valid but surely it shouldn't be there in clear text

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/11ac2f87-65d6-4850-9788-81cb16bb1bd4)

**Comment by sanjai0py** [comment]
Hey @zioalex, thank you for being security conscious and creating this issue. However, the `posthogApiKey` is a public key, which means keeping the key open in the codebase is fine.

**Comment by zioalex** [comment]
Hi Sanjai, what do you mean that it is a public key?.
Can you please explain it?
It is used to send the Telemetrics to Posthog

**Comment by berlingoqc** [comment]
even if it's a public api key , should be injected from secret in your build process ? Anyone could send you fake metrics with this right ?

Why was the response deleted ?

**Comment by gepbird** [comment]
Fixed in https://github.com/usebruno/bruno/pull/3490
