### ISSUE TITLE
Color in json response folded

### ISSUE THREAD

**Issue by leandrohago** [usebruno/bruno#3026]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Possibility to change color of folded response or remove shadow to improve visualization.

### Mockups or Images of the feature

![image](https://github.com/user-attachments/assets/47d53d3b-7d2f-47e6-b7a5-09d437aa95e6)

**Comment by helloanoop** [comment]
This has been fixed in the latest version of Bruno (v1.33.0 onwards)

**Comment by leandrohago** [comment]
It's pretty good now.

![image](https://github.com/user-attachments/assets/0f305c9b-7ffa-4c71-bd22-7e32bc30922b)
