### ISSUE TITLE
Error message when creating a request collection with a folder name that already exists

### ISSUE THREAD

**Issue by dharsanb** [usebruno/bruno#3040]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Error message when creating a request collection with a folder name that already exists returning error while creating collection but it'd be helpful if it returns that the folder name already exists

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/b7226d06-80ae-431e-b501-787188478df6)

**Comment by zachary-berdell-elliott** [comment]
I created a PR at #3046 to log the exception to give more information. I'll see if the maintainers are fine with the way I implemented it or if I need to simplify the message.
