### ISSUE TITLE
Not exist hint of 'bru' object for 'getFolderVar' and 'getCollectionVar' methods

### ISSUE THREAD

**Issue by SPIRIT-00** [usebruno/bruno#3043]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Also not exist information inside documentation.

### Screenshots/Live demo link

![изображение](https://github.com/user-attachments/assets/91170284-ac97-4cd8-90e0-4ce76cf45179)

**Comment by chrisnagel** [comment]
https://github.com/usebruno/bruno/pull/3062

**Comment by chrisnagel** [comment]
Should be solved with https://github.com/usebruno/bruno/pull/3062

**Comment by helloanoop** [comment]
Fixed in #3062 
This will be released in the upcoming patch release `v1.28.1`
