### ISSUE TITLE
typing `\` in the search bar crash Bruno

### ISSUE THREAD

**Issue by Aviortheking** [usebruno/bruno#3051]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When searching for informations in a request's response I typed `\` as the first character and the application crashed

I also fetched the erorr in the console:
```
779-f67e1698eec5c86a.js:1 Uncaught SyntaxError: Invalid regular expression: /\/gi: \ at end of pattern
    at RegExp (<anonymous>)
    at HTMLInputElement.<anonymous> (779-f67e1698eec5c86a.js:1:152742)
```

### .bru file to reproduce the bug

_doesn't matter but I include one just in case_
```
meta {
  name: Get one card
  type: http
  seq: 2
}

get {
  url: https://api.tcgdex.net/v2/en/cards/swsh3-136
  body: none
  auth: none
}

assert {
  res.status: eq 200
  res.body.id: eq swsh3-136
}
```

### Screenshots/Live demo link

before typing `\` in the search bar
![image](https://github.com/user-attachments/assets/114e69fb-05c1-4659-8811-f70e9dec3e9f)

after :
![image](https://github.com/user-attachments/assets/48ad7333-ed97-4b05-8634-d1c7b8857317)

**Comment by sanjai0py** [comment]
Hey @Aviortheking, thanks for taking the time to report this! A [PR](https://github.com/usebruno/bruno/pull/3057) fixing the issue has been merged and will be available in the next patch release!

**Comment by Aviortheking** [comment]
Awesome thanks !
