### ISSUE TITLE
 Links for Documentation, Report Issues, and GitHub Not Redirecting to Intended Destination

### ISSUE THREAD

**Issue by jeevankumarj25** [usebruno/bruno#3055]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When clicking on any links like documentation ,report issues,github does not redirect to the intended destination.

### Screenshots/Live demo link

<img width="960" alt="1" src="https://github.com/user-attachments/assets/cdc8f2d0-dd44-4338-bea0-8248edd3df80">
<img width="960" alt="2" src="https://github.com/user-attachments/assets/8a76a2dd-de63-43fd-870f-b29606d4d811">

**Comment by TheRealRyanReynolds** [comment]
Hi @jeevankumarj25 - I've also just checked on both Windows and Mac and it seems to be behaving as expected. Have you tried this on the latest version(1.34)? I'm going to close this ticket as this issue does not exist on later versions of Bruno. Please reopen if you feel this was an issue.
