### ISSUE TITLE
When importing Postman collection, pm.collectionVariables methods in scripts are not converted to .bru equivalents

### ISSUE THREAD

**Issue by That-1-QA** [usebruno/bruno#3061]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When importing postman collection with scripts that include pm.collectionVariables.unset(), or pm.collectionVariables.has() Bruno will provide an error dialog after importing the collection. "Warning: Some commands were not translated." Details point to the collections and lines, affected.

From what I understand the bru.deleteVar(), and bru.hasVar() are the equivalents, and they are a recent addition. They are not within the Bru DSL documentation currently, and are not used for translating the postman scripts.

### .bru file to reproduce the bug

[BrunoTest.postman_collection.json](https://github.com/user-attachments/files/16949450/BrunoTest.postman_collection.json)

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/a509ace4-b729-4c63-ad1a-8ddb050f05fd)

**Comment by helloanoop** [comment]
PR merged that added the below translations
```javascript
'pm\\.collectionVariables\\.has\\(': 'bru.hasVar(',
'pm\\.collectionVariables\\.unset\\(': 'bru.deleteVar(',
```

This will be available in the upcoming release `v1.34.0`
