### ISSUE TITLE
how to set content type for"multipart form" in body??

### ISSUE THREAD

**Issue by KianaMei** [usebruno/bruno#3063]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

how to set content type for"multipart form" in body??
i want to include both a multipart file and a json data in one request, but it will say"Content type 'application/octet-stream' not supported"
From what i saw on the Internet,this error may be sovled by setting the content type of json data as"application/problem+json",but I cannot find this option in Bruno.

### Mockups or Images of the feature

![image](https://github.com/user-attachments/assets/15b8d3b9-88ba-4c31-8050-1947cdfb1632)
![image](https://github.com/user-attachments/assets/21783370-c9f1-422e-bee6-ddd82ad7e1bf)

**Comment by jfslin** [comment]
There's a PR in the works that will take care of this: https://github.com/usebruno/bruno/pull/2121

**Comment by anusree-bruno** [comment]
We've introduced the ability to set the content type for multipart forms!
Check out the latest release, v1.37.0: [Download here](https://www.usebruno.com/downloads).
