### ISSUE TITLE
Crash on json search

### ISSUE THREAD

**Issue by fernandomacho** [usebruno/bruno#3084]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

You make a request that returns a json
![image](https://github.com/user-attachments/assets/b0b8fed5-b495-4f74-8bdf-bc6f24110787)
when write + character on search box get a crash

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/b87eb88c-ffab-4b18-9a96-706d4edb7498)

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/3057) fixing the issue has been merged and is expected to be released soon. Thank you for taking the time to report the issue!
