### ISSUE TITLE
can't get bruno variables from collection

### ISSUE THREAD

**Issue by equiman** [usebruno/bruno#3097]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I have created an example collection and I'm defined a variable inside the collection.

![Screenshot 2024-09-13 at 15 16 44](https://github.com/user-attachments/assets/b9d3c83e-29a9-4fa2-ab3e-009c129b49e8)

And I can use it directly from a request:
![Screenshot 2024-09-13 at 15 17 07](https://github.com/user-attachments/assets/a9dd3359-b3b9-47dc-ad77-11ab8583af38)

But when I want to get his value from pre-script on collection or even on request, it can be possible to get the value.

![Screenshot 2024-09-13 at 15 13 18](https://github.com/user-attachments/assets/4519dcaf-7a13-45e3-a931-7a2b85a1e5d8)

I've been following the [JavaScript Reference](https://docs.usebruno.com/scripting/javascript-reference) documentation. But nothing seems to be working. What I'm missing?

### .bru file to reproduce the bug

bruno.json:

```
{
  "version": "1",
  "name": "bruno-test",
  "type": "collection",
  "ignore": [
    "node_modules",
    ".git"
  ]
}
```

collection.bru

```
vars:pre-request {
  name: ditto
}

script:pre-request {
  const name_var = bru.getVar('name')
  const name_req = bru.getRequestVar('name')
  const name_sec = bru.getSecretVar('name')
  
  console.log({
    'var': name_var ?? '',
    'req': name_req ?? '',
    'sec': name_sec ?? ''
  })
}
```

get-pokemon.bru:

```
meta {
  name: get-pokemon
  type: http
  seq: 2
}

get {
  url: https://pokeapi.co/api/v2/pokemon/:name
  body: none
  auth: none
}

params:path {
  name: {{name}}
}
```

### Screenshots/Live demo link

![Screenshot 2024-09-13 at 15 13 18](https://github.com/user-attachments/assets/91dee0b1-d1a2-47f9-ae8b-d3753d274032)
![Screenshot 2024-09-13 at 15 16 44](https://github.com/user-attachments/assets/07f5a2c5-ee4b-4ae0-abf2-d1ac606a9666)
![Screenshot 2024-09-13 at 15 17 07](https://github.com/user-attachments/assets/c0ec0e6d-e7af-4343-b1a4-8ff46fc69db5)

**Comment by apoorvyadav1111** [comment]
Hi @equiman , I tried recreating the bug and believe that the variable you are trying to access can be accessed using another method of the bru object and not the ones you used. The var you have created belongs to the collection and so you can access it using the `getCollectionVar `method of the bru class. Please find the screenshot below:
Collection Vars:
![image](https://github.com/user-attachments/assets/0a38c43d-5454-445e-8187-8ab4ea221eba)
Env Vars:
![image](https://github.com/user-attachments/assets/c3d172b1-80b2-4f08-bf08-7afe18fcc82b)
Script:
![image](https://github.com/user-attachments/assets/e007454c-0b5d-4c1e-9601-e94d952f6e31)

Console:
![image](https://github.com/user-attachments/assets/b33e3a75-a0f4-418f-8e18-c27adcad2a99)

Summary (from what I understood):
Available vars in bru object and where to set them:
1. getEnvVar(key) : set in env
2. getCollectionVar(key): set in vars tab in collection pane
3. getRequestVar(key) : set in pre-request vars in request pane

**Comment by equiman** [comment]
@apoorvyadav1111 `getCollectionVar` solve it. Thanks!

It will be good to have tose methods updated on autocomplete options and also in documentation.
