### ISSUE TITLE
Detection for runner in script

### ISSUE THREAD

**Issue by nikischin** [usebruno/bruno#3104]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

As mentioned in #2397 I would like to have a possibility to determine wether the current request is triggered by a runner or as a single request. This will be beneficial especially when using with #2116 and a skip request function.

Usage is like this
`bru.isRunner()`

Returns either **true** or **false** 

### Mockups or Images of the feature

<img width="656" alt="image" src="https://github.com/user-attachments/assets/b72dad53-f2c8-453a-bad1-860ac2841b88">

**Comment by helloanoop** [comment]
Just merged the PR #3200

New api is `bru.getExecutionMode()`
This will return 
* standalone - when single request is being run
* runner - during collection runner is in progress

**Comment by nikischin** [comment]
> Just merged the PR #3200
> 
> New api is `bru.getExecutionMode()` This will return
> 
> * standalone - when single request is being run
> * runner - during collection runner is in progress

Thank you so much @helloanoop! 

Just one remark, it's `req.getExecutionMode()` not `bru.getExecutionMode()`. This does totally make sense, just not to confuse anyone passing by this ticket.
