### ISSUE TITLE
Importing a postman collection for commercetools fails

### ISSUE THREAD

**Issue by jonashilmersson** [usebruno/bruno#3113]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When importing the postman collection from commercetools (https://github.com/commercetools/commercetools-postman-collection/blob/master/api/collection.json), I only get the message "Import collection failed". It doesn't matter if I uncheck the "Auto translate postman scripts".

I'm using Bruno v1.28.0. 

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/3cc6750f-58b4-4299-a0f7-f55bfc007a38)

**Comment by sanjai0py** [comment]
Hey @jonashilmersson, thanks for reporting the issue. I'm looking into the problem you are facing.

**Comment by sanjai0py** [comment]
The Postman collection you shared contains lowercase values for the property `method`, but in Bruno, we are [expecting](https://github.com/usebruno/bruno/blob/4c3fe2f7195d235e152e9b885329238859227228/packages/bruno-schema/src/collections/index.js#L51) it to be in uppercase. I have updated an existing [PR](https://github.com/usebruno/bruno/pull/2445) with a fix for this, which should resolve your issue.

**Comment by jonashilmersson** [comment]
> The Postman collection you shared contains lowercase values for the property `method`, but in Bruno, we are [expecting](https://github.com/usebruno/bruno/blob/4c3fe2f7195d235e152e9b885329238859227228/packages/bruno-schema/src/collections/index.js#L51) it to be in uppercase. I have updated an existing [PR](https://github.com/usebruno/bruno/pull/2445) with a fix for this, which should resolve your issue.

Thanks for the quick response!

**Comment by helloanoop** [comment]
I have merged the PR. The fix will be available in the upcoming `v1.31.0` release.
