### ISSUE TITLE
GraphQL 

### ISSUE THREAD

**Issue by vidi42** [usebruno/bruno#3115]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Environment variables are not replaced in the GraphQL variables JSON.

I'm attaching a simple example using a public GraphQL API.

### .bru file to reproduce the bug

Attached is the collection to reproduce the issue.
It has an environment called `default` so make sure to select it before running the `Get Country Details` request.
[Bruno.zip](https://github.com/user-attachments/files/17028213/Bruno.zip)

### Screenshots/Live demo link

Working example with no environment variable used:
![image](https://github.com/user-attachments/assets/b1cc125e-1943-48a4-b970-c32a397566ca)

Non working example with environment variable used:
![image](https://github.com/user-attachments/assets/b1f9c9d9-27ff-48d5-8b24-e27f88856844)
![image](https://github.com/user-attachments/assets/10a7a649-6217-464e-88dd-81690f4231ab)

**Comment by That-1-QA** [comment]
Looks like a duplicate of this, I've got a workaround using the latest version of Bruno, and other users report using earlier builds also works:

https://github.com/usebruno/bruno/issues/2960

**Comment by vidi42** [comment]
@That-1-QA I missed the other ticket. Thank you. Will close this one
