### ISSUE TITLE
Bruno crashes when parsing non-JSON success response

### ISSUE THREAD

**Issue by TheoD02** [usebruno/bruno#3119]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bruno crashes when handling a server response that returns `"true"` with the `application/json` content type. This occurs when sending a request to the Dokploy API in my case (`/api/application.update`). The issue seems related to Bruno attempting to parse the `"true"` response, which is not valid JSON, leading to a crash.

**Steps to Reproduce:**
1. Send a request to an endpoint that responds with `"true"` and sets the `Content-Type` header to `application/json`.
2. Observe that Bruno crashes after receiving this response.
3. Confirm that Bruno handles responses properly when valid JSON (e.g., a 400 Bad Request response) is returned from the server.

**Expected Behavior:**
Bruno should be able to handle and display non-JSON responses like `"true"` without crashing, especially when the content type is `application/json`.

**Actual Behavior:**
- When the response is `"true"`, Bruno crashes due to invalid JSON parsing.
- If the server returns valid JSON (e.g., an error response), Bruno displays the response without issues.

**Additional Context:**
- The response `"true"` is sent with the `application/json` content type, which is technically incorrect, but Bruno should still handle this gracefully.

e.g.:
Returning this in Symfony Controller will make bruno crash

```php
public function __invoke(): JsonResponse
{
    return $this->json(true);
}
```

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/c4464831-3fbd-4af2-8dca-0d55ab311d25)

**Comment by helloanoop** [comment]
I have merged the PR that fixes this issue.
We will release a patch in the next couple of hours.
