### ISSUE TITLE
Tab Navigation in Fields Inconsistent

### ISSUE THREAD

**Issue by hardeaux** [usebruno/bruno#312]
When moving between data fields in key/val type cells (Query/Headers/Vars, etc) Tab key should move to next column, preferably to next row after last column. 

Shift+Tab should work similarly but in reverse.

Running on MacOS, not sure this is the same on other platforms.

**Comment by lared** [comment]
It annoys me too, I'll take it. It seems fairly simple other than fiddling with codemirror.

**Comment by helloanoop** [comment]
This has been fixed by @lared and has been released in `v0.18.0`
