### ISSUE TITLE
Error message when using OAuth 2.0 Authentication since 1.29

### ISSUE THREAD

**Issue by utrotzek** [usebruno/bruno#3124]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Since version 1.29 I'm getting the error message

`Error invoking remote method 'send-http-request': TypeError: Cannot read properties of undefined (reading 'formSerializer')`

when trying to authenticate using the `OAuth 2.0` with Grant Type `Authorization Code`. 

The exact same requests was working fine with an older version. I'm sorry, that I have no further infos.

e.g. I'm also not able to downgrade `bruno` 

I'm using this debian repo http://debian.usebruno.com/

Command to reproduce:
`apt update && apt-cache madison bruno`

### Screenshots/Live demo link

![bruno_error](https://github.com/user-attachments/assets/ab840c67-4579-40a1-a22d-1fe86a39fc78)

**Comment by helloanoop** [comment]
Just merged the fix for this issue. We will release a patch version in the next couple of hours.
