### ISSUE TITLE
BUG: Postman collection exported by bruno failed to be imported in postman 

### ISSUE THREAD

**Issue by alessandrofaccio-ors** [usebruno/bruno#3125]
### I have checked the following:

- [X] I use the newest version of bruno.
### Describe the bug

I've tried to export a bruno collection in "postman collection" format, but when i've tried to import this file on postman, the requests in the collection hasn't take the path, the situation is like this: 

Pls can someone give me a solution for this bug?

### .bru file to reproduce the bug

[Test Api Fittizie.json](https://github.com/user-attachments/files/17041060/Test.Api.Fittizie.json)

### Screenshots/Live demo link

![Screenshot 2024-09-18 103158](https://github.com/user-attachments/assets/3cf89fc1-65d5-415d-bce4-2bb721a2cf1a)

**Comment by sanjai0py** [comment]
Hey @alessandrofaccio-ors, thank you for taking the time to report this bug. Your issue seems similar to the one at https://github.com/usebruno/bruno/issues/2496. Can you please confirm it?

**Comment by alessandrofaccio-ors** [comment]
Hey @sanjai0py, yeah it's similar, i have the problem connected to host and path, because bruno export empty arrays, do you know how can i fix it?

Bruno to Postman Collection:
![Screenshot 2024-09-18 101221](https://github.com/user-attachments/assets/d82c6e79-3e4b-4f77-a20f-f06436caf388)

Collection exported by postman
![Screenshot 2024-09-18 101317](https://github.com/user-attachments/assets/e75bbf56-1b89-421c-8997-43a6d1203773)

**Comment by sanjai0py** [comment]
A [PR](https://github.com/usebruno/bruno/pull/3025) is available to fix this issue, which has not been merged yet. If possible test the PR against your collection to provide feedback or give it a ping!

**Comment by alessandrofaccio-ors** [comment]
IT WORKS !!! Do you want to realease this bugfix in the official version in the next few days?

**Comment by sanjai0py** [comment]
The pull request fixing this bug has been merged and is expected to go out in the next release, which is later this week. Thanks to @alessandrofaccio-ors for reporting this issue and testing it!

**Comment by helloanoop** [comment]
I have merged the PR that fixes this issue, it will be available in the the upcoming release `v1.30.0` that is scheduled to go out in the next couple of days.
