### ISSUE TITLE
Proxy Bypass works but doesn't send client certificates along since v1.28

### ISSUE THREAD

**Issue by dwiyatci** [usebruno/bruno#3128]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When I upgraded to v1.28, I thought it would be fixed in v1.29, but it's still broken somehow. 😞 I downgraded back to v1.27 and it worked there. Note that I didn't change anything except upgrading (and downgrading) Bruno version - so something must have changed between these versions that breaks the behavior. See screenshots for v1.29.0 vs. v1.27.0.

Actually, is there a way to check/inspect whether the client cert is really appended in the request?

### Screenshots/Live demo link

❌ **v1.29.0**
![_Applications_Bruno app_Contents_Resources_app asar_web_index_Page_1](https://github.com/user-attachments/assets/b3b8e116-aa46-4de1-ae40-80617594bfed)

---

✅ **v1.27.0**
![_Applications_Bruno app_Contents_Resources_app asar_web_index_Page_2](https://github.com/user-attachments/assets/45f44a21-744f-4991-a411-b9fa71eeb7cb)

**Comment by mjhcorporate** [comment]
This is strange. Client certificates still work for me on 1.28 and 1.29 (I am on MacOS). What kind of certificates are you using? What is your bruno.json?


For me, I am using X509 certificates in the PEM format. This is how I configured them:

![image](https://github.com/user-attachments/assets/c595e9eb-80b2-47b0-8bf5-e536a1df3532)

The relevant section in my `bruno.json` is
```json
  "clientCertificates": {
    "enabled": true,
    "certs": [
      {
        "domain": "localhost",
        "certFilePath": "{{certBasePath}}/.my-awesome-enterprise-service-client.crt",
        "keyFilePath":  "{{certBasePath}}/.my-awesome-enterprise-service-client.key",
        "passphrase": ""
      }
    ]
  }
```

**Comment by dwiyatci** [comment]
My certs are also in the PEM format and I'm also on macOS. I've checked my `bruno.json` - nothing changed there, and I've verified the cert paths are valid - if they weren't, I believe they wouldn't work when I downgraded to v1.27.0 without changing anything 😬 
```json
"clientCertificates": {
  "enabled": true,
  "certs": [
    {
      "domain": "apiGatewayUrl1.com",
      "type": "cert",
      "certFilePath": "../../../../../domain1/crt.pem",
      "keyFilePath": "../../../../../domain1/key.pem",
      "passphrase": ""
    },
    {
      "domain": "apiGatewayUrl2.com",
      "type": "cert",
      "certFilePath": "../../../../../domain2/crt.pem",
      "keyFilePath": "../../../../../domain2/key.pem",
      "passphrase": ""
    }
  ]
},
```

> Actually, is there a way to check/inspect whether the client cert is really appended in the request?

Quoting myself above, is there a way to debug it?

**Comment by mjhcorporate** [comment]
After some digging we found that it was the following issue:
- global proxy configured to `localhost:3128`
- bypass configured for `the-domain.com`
  - this worked successfully, the proxy was not called for the request to `the-domain.com`
- client-cert configured for `the-domain.com`
  - **bug**: the client cert is not sent!

Removing the proxy configuration allowed the user to continue. However, the fact that the client certificate is not picked up correctly is a bug, in my opinion.

**Comment by dwiyatci** [comment]
Yep, the proxy bypass works but doesn't seem to send the client cert along. And I can confirm my request works after turning off my global proxy settings in v1.29.0.
![_Applications_Bruno app_Contents_Resources_app asar_web_index-preferences html](https://github.com/user-attachments/assets/0b04953c-d957-4af2-b6db-47b7d509d0f6)

**Comment by Pragadesh44-Bruno** [comment]
Hey @dwiyatci,

Thanks for reporting this bug. I tried to replicate it on my machine (Windows 11 with Squid proxy). I blocked access to google.com through the `hosts` file in Windows, so the only way to access the domain was via the proxy. For testing purposes, I added invalid certificates to trigger the mismatch certificate error. As expected, I encountered the same error.

However, when I ran the test with the proxy configuration and the correct SSL certificates, it worked for me in the latest version (`v.1.34.2`).

And, We are working on the Logging the info about Client certificates in DevTools




Demo Working video:

https://github.com/user-attachments/assets/92127d1d-0743-4035-96b8-94ba61859127

**Comment by dwiyatci** [comment]
Thanks @Pragadesh44-Bruno for the effort! I can confirm that the Proxy Bypass works again on v1.34.2. And yes, the info logging would be a very nice addition :)

**Comment by sreelakshmi-bruno** [comment]
Hi @dwiyatci , can you confirm if you are able to send the client certificated successfully?

**Comment by dwiyatci** [comment]
Sorry, I mean "the proxy bypass and client certs sending" in my previous comment (edited)

**Comment by sreelakshmi-bruno** [comment]
Thanks for confirming!
