### ISSUE TITLE
Exception when using OAuth 2.0 (client credentials) to authorise after updating to v1.29.0 from v1.28.0

### ISSUE THREAD

**Issue by Reece-Carruthers** [usebruno/bruno#3135]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Hi, I am facing issues with the latest version of Bruno. 
My Bruno scripts make use of the OAuth 2.0 authentication tab utilising the client credentials drop-down option.
After the update when pressing get access token I receive an error pop-up with the below exception:

`Error invoking remote method 'send-collection-oauth2-request': TypeError: Cannot read properties of undefined (reading 'formSerializer')`

Downgrading to the older version of Bruno fixes the issue, I was wondering if something has changed in the way we need to use the OAuth 2.0 authentication, or if this is a bug?

### .bru file to reproduce the bug

https://github.com/hmrc/uknw-auth-checker-api/tree/main/.bruno/dev-staging-et

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/f2f95b44-1e60-45eb-a987-f90e6eca2926)
[Screencast from 18-09-24 15:56:02.webm](https://github.com/user-attachments/assets/2626cced-dac4-4237-8fca-ae5165ff719c)

**Comment by enricojonas** [comment]
Guess it's the same bug as https://github.com/usebruno/bruno/issues/3129

**Comment by Reece-Carruthers** [comment]
@enricojonas Yep, looks to be the same issue just a different method. That'll be why it didn't pop up when I searched the exception! I'll leave this open encase it proves useful to the developers.

**Comment by mjhcorporate** [comment]
I just ran into the same bug in one of my collections 🤦 
@helloanoop : This is something worth fixing. The `Content-Type` header is present in a lot of collections that were migrated from Postman or Insomnia.

**Comment by helloanoop** [comment]
We just released a patch fix `v1.29.1` that should have fixed this issue. Can you please test.

**Comment by weretac0** [comment]
I updated to resolve this issue and while I am getting a token correctly now, when I invoke the POST URL it's actually calling the OAUTH endpoint and just giving me the JSON response with the access_token and not the URL configured for the request.

**Comment by Reece-Carruthers** [comment]
@helloanoop The patch has fixed the issue, thank you for resolving it so soon.
