### ISSUE TITLE
After cloning a request it should open newly created request tab instead of staying on old one

### ISSUE THREAD

**Issue by abdulmahamaliyev** [usebruno/bruno#3149]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

It can be matter of preference but I think opening new tab after duplicating should be default action. 

So many times I cloned a request, renamed it for something new, worked on it, then later came back to see it's mixed up: new cloned request has old inputs, old request has new inputs because I didn't realize after cloning window still shows old request.

I'm used to it now, but every once in a while I see a request tab with named staging but url is localhost etc.

### Mockups or Images of the feature

N/A

**Comment by sanjai0py** [comment]
Isn't your feature request similar to this https://github.com/usebruno/bruno/issues/1624?

**Comment by abdulmahamaliyev** [comment]
Oh, my bad. Searched in issues but nothing came up. 
Closing this one because it's duplicate of #1624

**Comment by sanjai0py** [comment]
The feature is already available in the recent builds!
