### ISSUE TITLE
[Feature] Add capability to view JSON/XML responses in tree view

### ISSUE THREAD

**Issue by n00o** [usebruno/bruno#315]
When looking at the API responses, I often want to look at the response structure quickly without having to scroll down for a long time to see the entire response. Currently I copy the response into Notepadd++ and use the plugins [JSTool](https://github.com/sunjw/jstoolnpp) and [XML TreeView](https://github.com/joaoasrosa/nppxmltreeview) (which is a bit more rudimentary) to do this but it would be convenient and helpful if Bruno could support this inside the app. 

Postman offers you the ability to pick the response format from either being Pretty, Raw, Preview and Visualize (which is a bit excessive). Bruno could have a similar set of options inside the response section that could default to the Pretty (colorized) format but could also do tree view.

**Comment by haagtobias** [comment]
I second that. I think this is an important feature, especially if you are used to postman.
