### ISSUE TITLE
Trailing slash is removed when using path variables

### ISSUE THREAD

**Issue by Drew-Chase** [usebruno/bruno#3159]
### I have checked the following:

- [x] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When sending a request using a path variable, the end slash ('/') is removed.

### .bru file to reproduce the bug

```bru
meta {
  name: Get server by Id
  type: http
  seq: 3
}

get {
  url: http://127.0.0.1:1420/api/server/:id/
  body: none
  auth: none
}

params:path {
  id: y7dALql02apYGBkN
}
```

### Screenshots/Live demo link

https://github.com/user-attachments/assets/ae7d5b1b-b0bd-4a8e-a287-003daea4ef34

**Comment by sreelakshmi-bruno** [comment]
Hi, this issue has been fixed on our latest version 1.34.2. Please check it out!
