### ISSUE TITLE
Flatpak update error (Invalid checksum for extra data)

### ISSUE THREAD

**Issue by TickDracy** [usebruno/bruno#3167]
### I have checked the following:

- [ ] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Hello, I've installed Bruno from the Pop!_Shop of Pop_Os distro. Whenever I try to update it through the store or through the terminal, I get the following error: Error: Invalid checksum for extra data https://github.com/usebruno/bruno/releases/download/v1.30.0/bruno_1.30.0_x86_64_linux.AppImage

I think it might be related to the latest image being 1.30.1 and not 1.30.0. Either way, is there any way to upgrade it, without manually installing the .AppImage?

Thanks!

### Screenshots/Live demo link

![brunoapp@pop-os:~_001](https://github.com/user-attachments/assets/aab3020e-be8d-4d6f-b26f-b0818a09c714)

**Comment by peteruithoven** [comment]
To clarify the issue, you're also trying to update Bruno through flatpak.

Seeing Bruno is marked as unverified in Flathub, I've opened an issue here: 
https://github.com/flathub/com.usebruno.Bruno/issues/51

**Comment by TickDracy** [comment]
> Seeing Bruno is marked as unverified in Flathub, I've opened an issue here as well: [flathub/com.usebruno.Bruno#51](https://github.com/flathub/com.usebruno.Bruno/issues/51)

Thank you, @peteruithoven. I noticed that a new update showed up on the Pop!_Shop for the runtime locale and also for the AppImage 1.30.1. I tried to update, and it worked as expected now.

**Comment by peteruithoven** [comment]
Ah yeah, indeed it seems fixed :+1: 
I'll close my issue.
