### ISSUE TITLE
Toggle / hide titlebar visibilty

### ISSUE THREAD

**Issue by darcyrush** [usebruno/bruno#3177]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

The electron titlebar not only takes up valuable screen real-estate, but the grey colour contrasting against the dark theme is pretty off putting. The lost space is exacerbated when using a tiling window manager.

Adding the option to toggle / hide the titlebar in preferences would be great, and would not be inaccessible once the titlebar is hidden, since the preferences icon is still visible in the GUI in the bottom left.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/f4aaed95-0fed-413c-9ca2-115d10d83d68)

**Comment by AshkanArabim** [comment]
This might be a duplicate of this issue: https://github.com/usebruno/bruno/issues/1315

**Comment by darcyrush** [comment]
I did search, but apparently not effectively. Closing as duplicate
