### ISSUE TITLE
Cursor jumps to the end when editing parameter name in Query Params menu

### ISSUE THREAD

**Issue by TheoD02** [usebruno/bruno#3191]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

**Description:**  
When editing a parameter name in the *Query Params* menu, the cursor behaves unexpectedly. If you make a mistake and attempt to go back to edit part of the parameter name, the cursor jumps to the end after typing the first corrected character. This makes it difficult to fix mistakes, as the cursor always returns to the end after each character input.

**Steps to Reproduce:**
1. Open the Query Params menu.
2. Start typing a parameter name.
3. Make a mistake in the middle of the name.
4. Use the cursor or arrow keys to go back and fix the mistake.
5. Start typing the correction.

**Expected Behavior:**  
The cursor should remain in place after typing the first corrected character, allowing the user to continue editing.

**Actual Behavior:**  
The cursor jumps to the end of the parameter name after typing the first corrected character, requiring the user to manually move the cursor back to the desired position after every input.

**Environment:**
- Affected Version: 1.30.1

### .bru file to reproduce the bug

Any file with Query Params

### Screenshots/Live demo link

https://github.com/user-attachments/assets/d0782abe-9d8c-49fc-a188-03c960e4e985

**Comment by Ved504** [comment]
Hey @TheoD02 Thanks for bringing this issue to our attention. We are working on a solution and will include the fix in the upcoming release.
