### ISSUE TITLE
[BUG] Broken json to yaml functionality (golden)

### ISSUE THREAD

**Issue by fabrem** [usebruno/bruno#3193]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Makes the app crash when using json to yaml (golden edition)

**Comment by Ved504** [comment]
Hey @fabrem! Thank you for highlighting this issue. We are addressing it and will have the fix included in the immediate release.

**Comment by fabrem** [comment]
Will I be notified if a new version is released directly on the app? Thank

**Comment by Rreyn-Bruno** [comment]
HI @fabrem - confirming we've resolved this issue in the latest release. Let us know if you have any other issues.
