### ISSUE TITLE
Unable to rename uppercase environment to lowercase environment

### ISSUE THREAD

**Issue by Pragadesh-45** [usebruno/bruno#3198]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When attempting to update an environment name with only a case difference (e.g., `ProD` to `Prod`), an error is thrown stating that the `Error while renaming the environment`. As a workaround, the renaming currently has to be done in steps: `ProD` -> `ProD1` -> `Prod`.

### Screenshots/Live demo link

https://github.com/user-attachments/assets/f9e439b9-cefd-49d2-bcbb-0c2a1cb3b129

**Comment by helloanoop** [comment]
PR #3199 has been merged and this fix will be available in `v1.32.0` that is scheduled to go out next week.
