### ISSUE TITLE
Arm64 build failure 

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#32]
arm64 version is not working on my MacBook 14 M1 Pro. It's damaged.

Reported by @jozefrebjak on twitter

https://twitter.com/jozefrebjak/status/1582467505125486592?t=fLWOWQmzZ-XjS0W892U9DQ&s=19

**Comment by helloanoop** [comment]
Thanks @Butochnikov !

I use electron-builder to package the app.
Found this thread around the same issue. I am yet to take a deeper look on all the comments and solutions.

I need to check the code signing process that happens during build, and see if that is causing this issue?

Do you happen to know the solution to resolve this problem in the arm64 build artifact (in case you have resolved this before) ?

**Comment by Butochnikov** [comment]
@helloanoop unfortunately, no, I only know how to avoid this using the command in the console

**Comment by helpermethod** [comment]
Hi!

Probably related: I've tried to submit Bruno as an official Homebrew Cask, in order to simplify the installation process, *but* it requires the ARM64 build to be signed 😢 .

See https://github.com/Homebrew/homebrew-cask/pull/141287#issuecomment-1427497252

**Comment by helloanoop** [comment]
Thanks @helpermethod 

Just enrolled with the apple developer program.
I am working on getting a arm64 signed build up. Once complete, I will submit it to Homebrew Cask.

**Comment by helloanoop** [comment]
I recently completed Code Signing, as well as Notarization for the Mac builds.
Here is the Arm64 Download for v0.10.0: https://github.com/usebruno/bruno/releases/download/v0.10.0/bruno_0.10.0_arm64_mac.dmg

@helpermethod @jozefrebjak @Butochnikov 
Can you help me test if you are able to successfully install Bruno on your Arm64 Mac ?

I will be submitting it to the official Homebrew Cask shortly

**Comment by Butochnikov** [comment]
@helpermethod The new version installed without any problems

**Comment by helloanoop** [comment]
Awesome. Thanks @Butochnikov 👍

**Comment by helpermethod** [comment]
Hi @helloanoop!

I was able to install the lastest version without any problems, so I've re-submitted the Homebrew Cask PR for the current version. I hope I've got the checksums right 😆. If this gets accepted, we can think about automating that stuff.

https://github.com/Homebrew/homebrew-cask/pull/141699

**Comment by helpermethod** [comment]
And it has just been accepted as an official Homebrew cask!

**Comment by helloanoop** [comment]
Awesome. Thanks @helpermethod !!

**Comment by helloanoop** [comment]
@helpermethod I see that brew is now automatically picking up the latest release in github release.
The PR you submitted had v0.10.0
I had released a patch version v0.10.1

I just attempted a brew install and it installed v0.10.1 
![brew](https://user-images.githubusercontent.com/9350733/221283977-d1d5c6f6-9086-4f02-947c-8d5f39edb3a5.png)

**Comment by helpermethod** [comment]
> @helpermethod I see that brew is now automatically picking up the latest release in github release.
> The PR you submitted had v0.10.0
> I had released a patch version v0.10.1
> 
> I just attempted a brew install and it installed v0.10.1 
> ![brew](https://user-images.githubusercontent.com/9350733/221283977-d1d5c6f6-9086-4f02-947c-8d5f39edb3a5.png)
> 

I think that is bc one of the Homebrew maintainers updated the PR to reflect the latest release.

**Comment by helloanoop** [comment]
Closing this.
Have created #105 to investigate the possibility of automating homebrew updates.

**Comment by GhostLyrics** [comment]
@helloanoop Maybe you could remove the warning note on the homepage now that the issue is resolved, please?
<img width="1064" alt="Screenshot 2023-03-06 at 13 11 38" src="https://user-images.githubusercontent.com/259911/223107069-0d01f461-62a0-4cc2-9398-41d5066c427f.png">

**Comment by helloanoop** [comment]
Done and Deployed!
Thanks for letting me know 🙏 @GhostLyrics
