### ISSUE TITLE
Proxy Configuration Issue in Bruno v1.28+

### ISSUE THREAD

**Issue by giuseppemilicia** [usebruno/bruno#3233]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Since version 1.28 of Bruno, when configuring "proxy enabled" and "proxy pass" for a specific domain within a collection, requests that bypass the proxy return the following error:
`Error invoking remote method 'send-http-request': Error: unable to verify the first certificate.`

If the proxy is disabled or when using version 1.27, everything works as expected.

### Screenshots/Live demo link

v1.31:
![image](https://github.com/user-attachments/assets/11e5acde-0c2d-49bc-b05e-9582d4da45f5)

**Comment by christiangierschner** [comment]
![grafik](https://github.com/user-attachments/assets/998bc5a8-16e4-4984-addf-cdd341669a15)
same issue, but different error msg 1.28+
SSL is disabled -> not working

**Comment by helloanoop** [comment]
I have merged the PR for this fix.

@Ved_Sharma please test the resolution once `v1.34.0` is live

**Comment by helloanoop** [comment]
@giuseppemilicia, could you please check if the issue is resolved in version v1.34.0?

**Comment by giuseppemilicia** [comment]
@helloanoop the issue has been fixed in version v1.34.0
