### ISSUE TITLE
Improve Folder Rename/Move Handling to Address `EPERM` Errors

### ISSUE THREAD

**Issue by Pragadesh-45** [usebruno/bruno#3235]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add:

Existing issues: #678 

#### **Problem:**

When attempting to rename/move a parent folder that contains subfolders on Windows, the operation often fails with an `EPERM` (Error: Permission Denied) error. This issue arises due to Windows’ strict permissions, file locking, and background processes keeping file handles open. Applications such as Visual Studio Code also face this issue when using the Node.js `fs.promises.rename` function, as documented in the following issues:
- [Issue #152633](https://github.com/microsoft/vscode/issues/152633)
- [Issue #197157](https://github.com/microsoft/vscode/issues/197157)
- [Issue #194845](https://github.com/microsoft/vscode/issues/194845)

This behavior disrupts the user experience, making it difficult to consistently rename folders that contain subfolders, especially when some files are in use by the system or other processes.

### Mockups or Images of the feature

https://github.com/user-attachments/assets/5002dc78-800a-4d8e-8b51-0bef419a4078

**Comment by helloanoop** [comment]
@Pragadesh-45, let's make some time this week to review and merge this PR.

**Comment by yuniet87** [comment]
Any news on this?? Still have this problem.

**Comment by sreelakshmi-bruno** [comment]
Hi @yuniet87, we're working on it and it's set to go out in the next release.

**Comment by helloanoop** [comment]
I have merged the PR https://github.com/usebruno/bruno/pull/3236 that fixes this.
This will go out in the upcoming v1.36.0 release scheduled to be released on 4 Dec 2024
