### ISSUE TITLE
Thanks for this awesome improvement

### ISSUE THREAD

**Issue by robs-nice99** [usebruno/bruno#3240]
Hello,

I've been looking for a git-friendly alternative to Postman since the first time I needed to export/import a collection.

Congratulations for bringing API manual/auto testing to the dev iteration process.

I just left some suggestions for new features and a bug?/improvement? (not sure), but didn't want to leave without thanking you for this great improvement!

Thanks

**Comment by Rreyn-Bruno** [comment]
Thanks so much @robs-nice99! Appreciate the feedback as well as your suggestions.
