### ISSUE TITLE
Unable to select No environment after selecting an environment

### ISSUE THREAD

**Issue by codewell-learning** [usebruno/bruno#3245]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bruno 1.32.0. Steps to reproduce:
Create a collection
Create a request
In the request click the environments dropdown and click the gear
Create a new environment and click Save
Pick the new environment in the  environments dropdown
Now you can't pick No environment option no matter what you do. Deleting the new environment helps but only until you create a new one with the same name, then Bruno automatically switches to this new environment

### .bru file to reproduce the bug

i don't have one

### Screenshots/Live demo link

https://github.com/user-attachments/assets/c105466f-4adc-4266-9a41-730465b18621

**Comment by helloanoop** [comment]
The fix for this will be available in the upcoming `v1.32.1` release scheduled to go out today.
