### ISSUE TITLE
Cannot create collection in exists empty directory

### ISSUE THREAD

**Issue by toby3d** [usebruno/bruno#3250]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I created an empty folder in my home directory, but bruno can't use it when creating a collection. I expected bruno to skip the step of creating a directory with the specified name and just use the existing one.

### Screenshots/Live demo link

![2024-10-03_15-40](https://github.com/user-attachments/assets/6e7984fb-71f2-490e-ad9e-58bba4c055c9)

**Comment by MWDidata** [comment]
Could it be the Cyrillic chars in the folder name?
I spotted this issue might be related:
[https://github.com/usebruno/bruno/issues/3288](url)

**Comment by toby3d** [comment]
> Could it be the Cyrillic chars in the folder name?

![image](https://github.com/user-attachments/assets/9bcb035b-f3b5-4136-9bf7-8704b1934173)

No, it doesn't depend on the language in the directory path. The error text makes it clear that the problem is “creating a folder that already exists”.

**Comment by helloanoop** [comment]
I have merged PR #3256 
This will be available in the upcoming release `v1.34.1`
