### ISSUE TITLE
I lost Vault Integration in Ultimate Edition

### ISSUE THREAD

**Issue by drchiodo** [usebruno/bruno#3263]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I updated to 1.32.1 and i lost Integration of Hashicorp Vault. I reverted to 1.32.0 and the integration is back.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/2155ad8e-30a5-4e6c-b5d8-11be06e30da1)
![image](https://github.com/user-attachments/assets/2393b0b4-b8ab-4a84-ab98-d6c32094a010)

on version 1.32.1
![image](https://github.com/user-attachments/assets/81ac9965-6431-41f5-a254-9466ee1b6685)

on version 1.32.0
![image](https://github.com/user-attachments/assets/8985fc13-9611-44aa-aaa3-84361fc0ff13)

**Comment by drchiodo** [comment]
on versione 1.32.0
![image](https://github.com/user-attachments/assets/f1f94212-4d3c-43fe-afa8-a4ac7270fb8b)

**Comment by helloanoop** [comment]
We are fixing this. We will release a new version with the fix in the next few hours.

As a temporary workaround, please revert to 1.32.0

**Comment by ClementValot** [comment]
For reference, the "Download Report" button is for a Collection Run also gives me the "Ultimate Edition" popup even though my license is active

Thanks for the quick release 🙏

**Comment by helloanoop** [comment]
Hey @drchiodo @ClementValot 

This has now been fixed in `v1.33.0`
