### ISSUE TITLE
Secret Variables Exposed on Hover Over Request Components

### ISSUE THREAD

**Issue by Pragadesh-45** [usebruno/bruno#3265]
When hovering over a {{variable}} that is set as a secret value, the secret is currently displayed in the editor component. It would be better to show asterisks (***) in the hover text instead of revealing the secret value.

![image](https://github.com/usebruno/bruno/assets/1887439/d6557ed0-3114-42a7-8296-fb4f1676c20a)

_Originally posted by @JaceyPenny in https://github.com/usebruno/bruno/issues/1646#issuecomment-1989065065_

**Comment by helloanoop** [comment]
@Pragadesh-45 Lets get this PR reviewed and closed this week.
