### ISSUE TITLE
Windows: can't use forward or backward slashes in request names

### ISSUE THREAD

**Issue by drauch** [usebruno/bruno#3266]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

If you use a forward slash, you get an error.
If you use a backslash, you get an error + the request is deleted (ouch, did hurt me today to lose the whole request)

### Screenshots/Live demo link
![image](https://github.com/user-attachments/assets/7e9e1e89-0710-4dc4-8290-63640e901ab3)

**Comment by Broutard** [comment]
Same on linux

**Comment by Pragadesh-45** [comment]
Hey @drauch, @Broutard!

Thanks for reporting this bug. We are actively looking into it. I've made a fix in my branch, but it is still under review.

**Comment by helloanoop** [comment]
I have merged the PR #3274 that will now throw warnings and prevent file deletion.
This will go out in the upcoming `v1.36.0` release scheduled to be released on 4 Dec 2024

We are also working on supporting backward and forward slashes in request names. Please track #2996 for updates regarding that.
