### ISSUE TITLE
Bruno CLI Headers don't support variables

### ISSUE THREAD

**Issue by MWDidata** [usebruno/bruno#3276]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When using variables in the header for Version and Content-type the CLI request does not work, ResonseCode 400 bad request.

Our API requires the api version to be send in the header.
After hardcoding Content-type to application/json and the Version to 1.17 all works well

### .bru file to reproduce the bug

meta {
  name: api-Account-Token
  type: http
  seq: 1
}

post {
  url: {{BaseURL}}/api/Account/Token
  body: json
  auth: none
}

headers {
  Version: {{Version}}
  Content-Type: {{Content-Type}}
  ~Accept-Encoding: gzip, deflate, br
}

body:json {
  {
    "userName" : "{{Token_Username}}",
    "password" : "{{Token_Password}}"
  }
}

body:text {
  {
    "userName" : "USER",
    "password" : "PASSWORD"
  }
}

tests {
  // Store the token from the response in the "Token" variable of Breur Lokaal
  var responseBody = res.getBody();
  var token = responseBody.token;
  bru.setEnvVar("Token", token);
  //_________________________________________________________________
  
  
  // Test to check if the response status code is 200
  test("Response status code is 200", function() {
    expect(res.getStatus()).to.equal(200);
  });
}

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/ff18ba0b-f947-4770-ba8b-04a40a3a4636)

**Comment by bstupid** [comment]
the collection or request headers can be set to variables in env. I then use cli to load env before execution and that seemed to work. where there are things like cred you can set local --env-var for things like tokens. was able to get headers to load correctly via cli with this setup

**Comment by MWDidata** [comment]
The Token does work from variables. After creating the Content-type and Version vars in the env variables this also works.

I guess thats a fix but I still think it sould also work from the collection vars.

**Comment by MWDidata** [comment]
Since env variables do work I'll close this issue.
