### ISSUE TITLE
Tooltips hided by tabs

### ISSUE THREAD

**Issue by LileFab** [usebruno/bruno#3278]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When I have too many tabs open the tooltips of the buttons are hided by the "+" button

### .bru file to reproduce the bug

headers {
  ApiKey: {{ApiKey}}
}

auth {
  mode: none
}

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/6d1a8ad2-178d-475e-9211-b7bb9778642a)
![image](https://github.com/user-attachments/assets/bc3a89c7-2246-4d9f-8f08-2296029b9f1e)
![image](https://github.com/user-attachments/assets/014cd25c-64ab-47f4-8e96-7acfd269e79c)

**Comment by helloanoop** [comment]
I have merged the PR for this fix and it will be available in the upcoming `v1.34.0` release
