### ISSUE TITLE
res.setBody() - Enable custom final responses.

### ISSUE THREAD

**Issue by russeree** [usebruno/bruno#3287]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

I am doing some preliminary research into the ability to decode and/or modify the response object before writing it to the report.

This pull here seems  to add the functionality somewhere, this is not accessible from the GUI on v1.33.0
https://github.com/usebruno/bruno/commit/81d8c30d8484678dc627b2a76d790c6c95faa1ea

Currently I have a test that iterates the same request 1000s of times to detect and or stimulate errors form an endpoint. The responses returned are on the order of 10s of MB each. Logging each successful attempt only seems to result in higher ram usage. 

My goal would be to clear the response to null if all tests pass and if an exception occurs then log the failed response to the report.

Thanks,
Russeree

### Mockups or Images of the feature

None

**Comment by helloanoop** [comment]
Thanks for reporting this @russeree !

@lohxt1 looks like the `setBody()` function does not have shims in the vm. Can you look into this?
