### ISSUE TITLE
Lost access to Run Reports in Golden Edition

### ISSUE THREAD

**Issue by russeree** [usebruno/bruno#3289]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

In the latest version of Bruno 1.33.0 I have lost access to create run reports. On the previous version 1.32.0 I was able to create reports. My current license in Golden Edition. Reports are also not listed as a feature of the Enterprise editions.

![image](https://github.com/user-attachments/assets/c80f2d39-ce0a-46a3-82a2-2c17ab7ba82d)

### .bru file to reproduce the bug

None

### Screenshots/Live demo link

None

**Comment by russeree** [comment]
An example of a previous run I did with a report downloaded

![image](https://github.com/user-attachments/assets/404b3575-4a27-4ff6-974d-3a6399a538c4)

**Comment by Rreyn-Bruno** [comment]
@russeree - apologies for any confusion or frustration. We're going to push an update likely in the next week that will restore this for you.  This was inadvertently put into Golden Edition but was always on our pricing page under Ultimate Edition. Rest assured though that we're going to do the right thing here and grandfather it into any Golden Editions to which it was released.

**Comment by helloanoop** [comment]
Update: This will be fixed in the upcoming `v1.34.1` release that is set to go out in the next 4-5 days

**Comment by anusree-bruno** [comment]
This has been fixed. I am closing this issue
