### ISSUE TITLE
Basic Auth header not sent

### ISSUE THREAD

**Issue by nico-m-64** [usebruno/bruno#329]
Hi,
Just say that you made a very very great tool, hope this open source project will be 🚀 all around the solar system ! Thank you so much for your work.

It seems that the header "Authorization: Basic *****" is not sent when configuring the Auth tab with this type.

Have a nice day

**Comment by l0new4nder3r** [comment]
It works fine for me with version 0.18.0: I just replaced a manually generated "Authorization" (Basic) header with the needed username and password in the "Auth" tab, and I can successfully access a restricted API in one of my apps.

Could you try again, or check if you do not have anything else interfering your test, @nico-m-64 ?

One other thing, though: when using "Generate code" on this new request, the "Authorization: Basic xxx" header is not included in the "curls". Should I create another issue, @helloanoop ?

**Comment by helloanoop** [comment]
Yes, it worked for me too in my local tests. But we need to use headers. The current code uses axios inbuilt auth which is resulting in the header not being populated.

Here is the part we need to make changes: https://github.com/usebruno/bruno/blob/main/packages/bruno-electron/src/ipc/network/prepare-request.js#L22-L33

I will send out a patch fix for this later tonight.

**Comment by francocm** [comment]
I'm playing with Basic Auth on `v0.18.0` and observed that Basic Auth works fine if I put hardcoded values. However it breaks if I use variables.

# Example

## Works

* Username: `foo`
* Password: `foo`

## Does not work

* Username: `{{my-username}}`
* Password: `{{my-password}}`

**Comment by lared** [comment]
@helloanoop should it be done there, or in dedicated step where we interpolate everything afterwards?

I don't think this is going to help interpolating generated code, as there the only piece of code that's actually being interpolated is the url.

**Comment by helloanoop** [comment]
This has been fixed and released in `v0.19.0`
CLI support has also been released in `v0.11.0`

**Comment by nico-m-64** [comment]
Thanks a lot for the quick fix ! Everything work perfectly 👍
I wish you the best for the future
