### ISSUE TITLE
Runner Parallel execution creates OOM when executed with large number of csv rows 

### ISSUE THREAD

**Issue by bstupid** [usebruno/bruno#3296]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I have several 1000 row csv with 5 columns 
In my collection I have 3 requests

Each request is executed 1000 times 

When runner executes it allocates memory and ports for all 3000 requests all at once and pretty much creates a dos on bruno and my computer until it falls over when allocating over 5GB of memory and 3000 ports. 

can you please enable the option to run serially.. its usual to offer a api app the option to only always run in parallel 

### Screenshots/Live demo link

https://discord.com/channels/1036297729606963331/1036367269804130314/1284753638857904251
https://discord.com/channels/1036297729606963331/1036367269804130314/1284749828085121024

**Comment by bstupid** [comment]
I am able to work around this by using the cli which does execute serially.

**Comment by Rreyn-Bruno** [comment]
Thanks for submitting this @bstupid, we've logged it as a feature request as we do not currently support serial execution of .csv via the CLI.

**Comment by bstupid** [comment]
@Rreyn-Bruno your miss reading the issue. with Runner via the GUI if you have an csv driving execution anything more than 300 rows creates a massive issue and OOM error for Bruno and makes runner pretty much useless. 

With CLI which DOES NOT REQUIRE a fix is the work around because it only run's serially and does not create this issue. This is how Runner should work but does not offer this option. 

Runner only runs in parallel which is the problem. 

Anyone coming from PM will expect runner to work serially, It doesnt make sense for runner to only run in parallel where it directly impacts Bruno.. it basically locks up or crash's before allowing users access to the Bruno gui. usually after many hours.

**Comment by helloanoop** [comment]
Support for Serial execution will be available in the upcoming `v1.35.0` release which is set to be released tomorrow.
