### ISSUE TITLE
Bruno constantly freezes on Apple Silicon

### ISSUE THREAD

**Issue by dev-inside** [usebruno/bruno#3302]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Whenever I start Bruno and work with the Collections-Tab, Bruno instantly freezes. Doesn't matter if I create a new Environment or edit an available one - it freezes constantly. 

My machine asks if Bruno should be allowed to get permissions to access other app. I gave already that permission on every start. It happens with the installed and the portable version.

I use a Macbook Pro on Sonoma.

### Screenshots/Live demo link

![bruno_issue](https://github.com/user-attachments/assets/1cf46a34-c584-4685-b1c4-092b88b9aa45)
![image](https://github.com/user-attachments/assets/7c9cf060-6d52-4728-a905-41e0562dd7ee)

**Comment by ManuelW77** [comment]
Maybe it is related to this https://github.com/usebruno/bruno/issues/2993

**Comment by helloanoop** [comment]
Closing this issue as it's a duplicate of [issue #2993](https://github.com/usebruno/bruno/issues/2993), which we are actively tracking.

We’ve noticed a recurring pattern: these performance issues are primarily affecting macOS Sonoma, while other macOS versions remain unaffected.
