### ISSUE TITLE
Windows is missing on latest build

### ISSUE THREAD

**Issue by Nolway** [usebruno/bruno#3308]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Hello, Windows isn't available on the latest build.

### Screenshots/Live demo link

Just look the latest release.

**Comment by Vikaseneco** [comment]
![image](https://github.com/user-attachments/assets/50be0bcf-6967-4cf4-be94-dbd7e712481a)

**Comment by Ved504** [comment]
Hey @Nolway, Thank you for bringing this issue to our attention. We have now added the Windows build, which is available for download.
