### ISSUE TITLE
Move an endpoint between 2 collections

### ISSUE THREAD

**Issue by asirota** [usebruno/bruno#3314]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Add ability to drag and drop end point between 2 open collections. This would make it easier to build collections especially since you cannot import a collection into an existing collection.

### Mockups or Images of the feature

![2024-10-15_10-14-01](https://github.com/user-attachments/assets/880a2345-6199-49ea-a253-109f97c29ec1)

**Comment by ykburda** [comment]
+1

**Comment by ykburda** [comment]
https://github.com/usebruno/bruno/issues/290

**Comment by asirota** [comment]
I'll close this as dupe of #290
