### ISSUE TITLE
Graphql Curl Import and Export not working

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#3333]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bruno doesn't detect graphql request when I do cURL command import
Couldn’t find a way to generate cURL command from Graphql request in Bruno (like we do for rest api)

### Screenshots/Live demo link

NA

**Comment by sanjai0py** [comment]
I'm working on fixing this issue!

**Comment by Infinitay** [comment]
Some additional info on this is neither a Curl (CMD) nor a Curl (Bash) commands import properly - especially the CMD version. Oddly, it accepts the CMD version of the Curl command when importing, but the URL and headers are not corrected.

**Comment by helloanoop** [comment]
This will be available in the upcoming `v1.35.0` release
