### ISSUE TITLE
[Bug] Runner: Download report not working any more

### ISSUE THREAD

**Issue by tho-gru-38** [usebruno/bruno#3351]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I like the Download Report function and used it quite often:
![Bruno-Download-Report](https://github.com/user-attachments/assets/a6c389a4-0aea-484a-a3d9-35e9187a6316)

For some reason this function was moved to the ultimate edition.

I am upset because a "free" function was changed to a payed function. This behavior will hinder me to promote Bruno as I did in former days.

### .bru file to reproduce the bug

By clicking the above marked button you will see:
![image](https://github.com/user-attachments/assets/48d28c22-2a61-4d8d-b8a0-6aa8737a99f6)

### Screenshots/Live demo link

nothing to show here

**Comment by helloanoop** [comment]
Hey @tho-gru-38!

Sorry for the mix-up! Test Reports were originally intended to be part of the Ultimate Edition, but they were mistakenly included in the Golden Edition. We're in the process of fixing this, and in the upcoming release next week, this feature will be available to all Golden Edition customers.

Thanks,
Anoop

**Comment by helloanoop** [comment]
Closing this as this we are tracking this issue here: #3289
