### ISSUE TITLE
[1.34.0] Command-F to search items in responses no longer works

### ISSUE THREAD

**Issue by fantpmas** [usebruno/bruno#3355]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When performing Command-F in a JSON result, the search dialog no longer appears.

### Screenshots/Live demo link

1.33.1
![image](https://github.com/user-attachments/assets/01734b5f-6c82-4ef4-9205-3fa0c1e48191)
1.34.0
![image](https://github.com/user-attachments/assets/4f30c8df-353b-408b-a7ca-31b3ea10cccd)

**Comment by TheRealRyanReynolds** [comment]
Hi @fantpmas - thanks for raising this. We'll have it sorted in the next release (likely next week).

**Comment by rajib-raiyat** [comment]
> Hi @fantpmas - thanks for raising this. We'll have it sorted in the next release (likely next week).

Please fix this asap.

**Comment by anusreesubash** [comment]
This issue has been resolved in v1.34.1, so I'm closing this ticket.

**Comment by pras4917** [comment]
Can anyone tell me how to search the results in postman response? Currently CTRL + F is coming up fine and it shows the count of given text in the response window. But how to navigate inside it?
