### ISSUE TITLE
Collection level script are not imported

### ISSUE THREAD

**Issue by bhecquet** [usebruno/bruno#3356]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Hello

Testing the new import feature (https://github.com/usebruno/bruno/pull/3334), I've seen that import correctly work for folder level script, but not for collection level scripts
You can test this with de attached postman collection

[Test import.postman_collection.json](https://github.com/user-attachments/files/17518143/Test.import.postman_collection.json)

### Screenshots/Live demo link

![postman](https://github.com/user-attachments/assets/cf0ebe23-6269-4d46-8254-2b22c88644b5)
![bruno](https://github.com/user-attachments/assets/05c86156-4e5c-4343-8f9e-f1a73355e301)

**Comment by Pragadesh-45** [comment]
Hey @bhecquet,

Thank you for reporting this bug. We are working on it and will fix it in the upcoming release.

**Comment by anusreesubash** [comment]
Thanks for reporting this issue. This issue has been fixed, I am closing this ticket.
![image](https://github.com/user-attachments/assets/74a0ecc2-9f08-4eef-b717-a5b2ba56caea)
