### ISSUE TITLE
[Feature request]: Clone or extend environments

### ISSUE THREAD

**Issue by VersusF** [usebruno/bruno#336]
Hello,
sorry but I did not find any template for this.

In my use cases I need to test my local API with different users which have different roles. To manage this I use an environment for each user, but many variables are shared among them and maybe the only thing that change is the email or the password. It would be very useful to have the ability to create new environments as copies of existing ones, so that only few changes can be done.

My current workaround is to clone the environment file inside the folder on the file system.

Another options would be environment extension, a sort of inheritance, but this would be more complicated, maybe too much to be worth.

Thanks again for making Bruno

Additional keyword for potential issues-search: copy environment, copy env, clone env, duplicate env

**Comment by helloanoop** [comment]
> My current workaround is to clone the environment file inside the folder on the file system.

Thanks for posting this workaround, many would find this helpful until we improve this in UI

This would be a great feature

Design wise I am imagining a clone icon next to edit button on the right hand top of this screenshot.
Clicking on it opens a modal asking to enter the name for the cloned environment

We can refer the clone request functionality for implementation approach

![image](https://github.com/usebruno/bruno/assets/9350733/ecaa2328-cce3-4736-afc5-2e05cc3c70f8)
