### ISSUE TITLE
⭐️ Golden Edition - Issue with JSON to YAML Converter Paste Input Height

### ISSUE THREAD

**Issue by swagfin** [usebruno/bruno#3367]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

In the DevTools JSON to YAML Converter window, the default height is currently very small, making it difficult to view and edit content comfortably. At present, only one line of text is visible at a time, which limits usability and requires constant scrolling to review content.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/e5eb40ce-6d27-4eae-9fca-be3af26e7de8)

**Comment by helloanoop** [comment]
Thanks for reporting this @swagfin !
We'll have this fixed in the upcoming release.

**Comment by anusreesubash** [comment]
This issue has been resolved in v1.34.1, so I'm closing this ticket.
![image](https://github.com/user-attachments/assets/ea8927b8-6ac6-410f-a105-fe16ee84db01)
