### ISSUE TITLE
Adjust route formatting when importing from OpenAPI v3

### ISSUE THREAD

**Issue by GeisonJr** [usebruno/bruno#3372]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Currently, routes imported from OpenAPI v3 sometimes have a leading slash `/`, leading to duplicate slashes `//` when combined with `{{baseUrl}}`. This requires manual removal of the leading slash in the environment settings. Implementing an automatic check to strip the leading slash from routes during import will prevent this issue and ensure consistent URLs without manual intervention.

### Screenshots/Live demo link

1. Request Route - Initial route setup:
![image](https://github.com/user-attachments/assets/122d614c-df99-41f4-a4d0-d1ab339b3df2)

2. Imported Environment - Verifying `{{baseUrl}}` from the environment file:
![image](https://github.com/user-attachments/assets/f266f6ab-c468-43ef-8e43-a1d75604aaea)

3. Slash Example - Showing the trailing slash in `{{baseUrl}}`:
![image](https://github.com/user-attachments/assets/5fd25900-667a-4450-aa64-7379c46eb077)

4. Final Problem - Resulting in URLs with a duplicate `//`:
![image](https://github.com/user-attachments/assets/8c3a95cf-a0fc-4350-abb4-3b6a4539ebb3)

**Comment by anusree-bruno** [comment]
Hi @GeisonJr!

Thanks for reporting this. We will get this fixed soon.

**Comment by anusree-bruno** [comment]
This has been fixed in the latest release v1.35.

Closing this issue, feel free to reopen if the issue persists
