### ISSUE TITLE
Convert curl commands to request.

### ISSUE THREAD

**Issue by sanskar-mk2** [usebruno/bruno#338]
In Insomnia, whenever you post a curl request to the url bar, it autofills the headers/url/parameters/creds accordingly to that curl request. It is very important feature since curl is very universal to http requests. You can copy curl directly from browser.

- [x] Import Curl when creating a new request
- [x] Switch to curl mode automtically when a curl command is pasted in NewRequest modal
- [ ] Allow importing of curl when a curl command is pasted in an already opened tab

**Comment by cvmocanu** [comment]
+1

In addition, an "Import from curl" option on the directory menu (next to "New request") should be added, to make it obvious that Bruno has this feature.

**Comment by davidsr2r** [comment]
If you can't export to curl, that would also be great to have added. Apologies if it's already a feature, I couldn't see any obvious place in the docs that point that out & GOOG simply pointed me here.

**Comment by Olian04** [comment]
@davidsr2r You can export a request as a curl command from the "generate code" menu.
<img width="248" alt="Screenshot 2023-10-13 at 09 01 56" src="https://github.com/usebruno/bruno/assets/5493406/54aa72af-0a50-41af-ac9a-aa404a5e831f">
<img width="848" alt="Screenshot 2023-10-13 at 09 02 11" src="https://github.com/usebruno/bruno/assets/5493406/366e3e38-c4a1-40a1-b993-101d82aceb5f">

**Comment by snippetkid** [comment]
@sanskar-mk2 @helloanoop @cvmocanu I'll start working on this issue.

**Comment by snippetkid** [comment]
A quick update, I'm through with the changes for this and is currently working on a bug while updating headers from the curl command.

**Comment by helloanoop** [comment]
Would love to see a teaser video :)

**Comment by snippetkid** [comment]
https://github.com/usebruno/bruno/assets/16718733/2f1caea9-ffee-4e29-998a-f96d8017109c

@helloanoop Here is what it looks like now. Please pass on review comments.

**Comment by helloanoop** [comment]
Curl Import functionality is now available in `1.1.0` 🎉

**Comment by girishkumar9** [comment]
@helloanoop it would be good to also have a curl script generated on an existing request. Postman has this feature and it is very handy to show the output of an API call

**Comment by cvmocanu** [comment]
@girishkumar9 that is already implemented: hover your mouse cursor over a request in the left-side tree, click the 3 dots, Generate Code, Shell-Curl.

**Comment by tbkahuna48** [comment]
On Apple M1 Pro with Ventura 13.5.2- All attempts to use the create new request with curl error out. Window with error disappears to quickly to copy the error.

**Comment by koljatm-edeka** [comment]
> @girishkumar9 that is already implemented: hover your mouse cursor over a request in the left-side tree, click the 3 dots, Generate Code, Shell-Curl.

Unfortunately it doesn't work properly with variables. I have the base url in an environment variable and the export doesn't recognize the url.

**Comment by hp77-creator** [comment]
@helloanoop I was trying to import a curl but the request url is not properly appearing in the URL field, I tried multiple times, different URLs are coming. is there any debugger or someway that I can see what might be causing it? I tried importing from the collection tab(sidebar) and also in the request window(by clicking on '+').

**Comment by Aeolun** [comment]
I kind of need to re-import from curl on an existing request. Making a new request for every time I want to import curl is really unwieldy.

**Comment by verhovsky** [comment]
Your Bash parser doesn't handle ANSI-C quoted strings, which browsers output when generating curl when some part of the request (namely the body) contains a control character, a non ASCII character or a single quote.

https://github.com/ChromeDevTools/devtools-frontend/blob/c9afdb4745a76866f7486be0e5cdd4e2b270d8af/front_end/panels/network/NetworkLogView.ts#L2090-L2099

You can use https://www.npmjs.com/package/shlex which does

**Comment by mivanov** [comment]
Just found Bruno. Really like it but I wish import from cURL was a little easier for when I need to do it repeatedly. A keyboard shortcut would go a long way. Or a magic textbox that recognizes when the pasted string starts with "curl " and does the right thing. To make this really seamless would be nice if the request name was optional or auto-generated. Thanks for creating this tool!

**Comment by jwetzell** [comment]
It would be nice if it wasn't so many clicks in. In Insomnia pasting a curl command into the url bar would prompt you to import it as a new request. It also had import from curl as an option from under the add menu directly.

**Comment by skoruppa** [comment]
Yeah. When working as QA I need to import a lot of curl request during the day, just to make some minor adjustments and run them. I don't want to create and save a new request in my collection each time I just want to import something from my browser. 

Like stated before, both Insomnia and postman "overwrite" the current request when you paste a curl script right into the URL field. Would love to have the same functionality in Bruno

**Comment by helloanoop** [comment]
Closing this issue since the core functionality for importing Curl has been implemented. Additionally, the Curl importer has seen several updates over the past few months.

If you have suggestions for improvements, please feel free to raise a new issue with specific details.

**Comment by emirozmen07** [comment]
I think there is a problem, for example I put the curl below
`curl --request POST 'localhost:8181/api/generateFile?uid=67176bc0b34ba4009e2a7032'`
But, it did not add the request type (POST) and after I changed it to POST still gave error on request(415) while curl was working.

**Comment by ltouro** [comment]
this was lost at some point, right? there is no curl import anymore since there is no modal when clicking new request.

ps; VSCode extension

<img width="226" height="274" alt="Image" src="https://github.com/user-attachments/assets/0fa8a02d-59d1-44d3-9548-dff4e622da5c" />

<img width="1952" height="356" alt="Image" src="https://github.com/user-attachments/assets/870f555e-5072-4648-8ea2-168ce260e75e" />

**Comment by helloanoop** [comment]
@ltouro 

We need to add it in the context menu in VSCode.
However, you can click on the Code Icon in the URL Bar to access it

<img width="529" height="229" alt="Image" src="https://github.com/user-attachments/assets/59bcbd7b-b7e8-4e57-b9b8-4fe95fb42ea5" />

**Comment by ltouro** [comment]
@helloanoop you are talking about  'exporting to curl', correct? I'm talking about 'import to bruno, from curl', which was the OP ask. 

A common pattern is use the 'copy as curl' in the network tab of the browser developer tool and paste it in the HTTP client.

**Comment by szeltneraptica** [comment]
@ltouro 
I was able to find it here.  From within a Bruno editor (in a request), press cmd + B for new request modal:
<img width="1515" height="571" alt="Image" src="https://github.com/user-attachments/assets/b8048751-a487-42e3-95f1-fc6701e40253" />

but if I click "create", it tells me it was a success but vscode Bruno Output says
`Received message from webview: ipc-invoke
IPC invoke: renderer:new-request
IPC invoke: renderer:new-request
No handler registered for IPC invoke channel: renderer:new-request
IPC invoke response for renderer:new-request: null`

Not sure if that's my environment being weird or if it wasn't "supposed" to be found :)

**Comment by ltouro** [comment]
@szeltneraptica oh, i see now. Thanks!
