### ISSUE TITLE
Search field not visible in Response, Body, Scripts and Tests

### ISSUE THREAD

**Issue by gdekeuster** [usebruno/bruno#3381]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

**Steps:**
I'm using Bruno v1.34.0 on a MacBook Pro with M1 Pro.
Run a GET request
Click in the Response field and tap command+F keys on your keyboard.

**Actual result:**
There is no search field visible. Only the top border of the field is visible at the bottom. 
When you start typing the value you want to search on and tap the Enter key the search does work.

**Expected result:**
The search field should be visible so you can correct possible spelling mistakes in case the search doesn't return any result.

**Additional info:**
The same occurs in Body, Script (Pre Request and Post Response) and Tests.

### Screenshots/Live demo link

<img width="1567" alt="image" src="https://github.com/user-attachments/assets/8bcdc89d-f25a-4ae3-bebf-e8873dc9a0f2">

**Comment by sreelakshmi-bruno** [comment]
Hi @gdekeuster , thanks for reporting, this issue has been resolved and is available on our latest version(1.34.1)!

**Comment by gdekeuster** [comment]
I downloaded version 1.34.1 and the issue is indeed fixed.
Thanks a lot for the quick fix. Keep up the good work, much appreciated.
