### ISSUE TITLE
Cannot run a script file in parent folder

### ISSUE THREAD

**Issue by Nizoryu** [usebruno/bruno#3384]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I have no problem running my script from the root folder of the collection.
```
bruno/
├── demo/
    └── environnements
    └── bruno.json
    └── get demo.bru
    └── script.js
```

When I move the file to the parent folder like this: 
```
bruno/
├── demo/
    └── environnements
    └── bruno.json
    └── get demo.bru
└── script.js
```
i have  this issue: 
Error invoking remote method 'send-http-request': VMError: Cannot find module '../script.js'

### .bru file to reproduce the bug

meta {
  name: get demo
  type: http
  seq: 2
}

get {
  url: http://localhost:3000
  body: none
  auth: none
}

script:pre-request {
  const script = require("../script.js");
  // const moment = require('moment');
  
  
  console.log(bru.getVar('today'));
}

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/f3c1462f-6c53-467b-972a-750eb64c1c54)

**Comment by sreelakshmi-bruno** [comment]
Hi @Nizoryu, access to files outside of the Collection path is not allowed in Bruno. When doing so you'll get an error message saying 'Error: Access to files outside of the collectionPath is not allowed'. I'm not sure why you are getting a 'Cannot find module' message. Can you check again and get back? Thanks! Also from the file structure you've shown, I assume 'demo' as your collection.

**Comment by Nizoryu** [comment]
> Could you share your use case? Are you looking to share a common script file across multiple collections?

[bruno-demo-external-script.zip](https://github.com/user-attachments/files/17829434/bruno-demo-external-script.zip)

**Comment by tlaloc911** [comment]
@Nizoryu , it is possible to do that, with two considerations

1) You have to declare the external path (take a look into #795)
2) It only works in pre-request. There is an unmmerged PR that aims to make it work in post-response: #1397

**Comment by Nizoryu** [comment]
> @Nizoryu , it is possible to do that, with two considerations
> 
> 1. You have to declare the external path (take a look into [[feature] allow multiple script context roots #795](https://github.com/usebruno/bruno/pull/795))
> 2. It only works in pre-request. There is an unmmerged PR that aims to make it work in post-response: [feat(scripting): allow multiple script context roots in response scripts #1397](https://github.com/usebruno/bruno/pull/1397)

Thank you for you help, the external path is perfect for my use case.
