### ISSUE TITLE
[Bug] Hitting 'Home' Key in Scripts Opens Autocomplete

### ISSUE THREAD

**Issue by rreyn-bruno** [usebruno/bruno#3403]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When inside of either pre request or post response scripts, if you press the 'home' key on your keyboard, it opens up the auto-complete library. 

This isn't a blocking bug but can be annoying if that is your workflow. 

### Screenshots/Live demo link

Here is a [video reproducing the issue ](https://app.screencast.com/spOlGQ4mFRMPa)when pressing 'Home' on my keyboard.

**Comment by sreelakshmi-bruno** [comment]
Hi @TheRealRyanReynolds , thanks for pointing this out! Will initiate work on the fix!

**Comment by helloanoop** [comment]
Just merged the PR for this. This will be released in `v1.35.0` that is expected to be go out in a couple of days.
