### ISSUE TITLE
Bruno crash when i try to put an auth bearer token in my collection

### ISSUE THREAD

**Issue by jmischler72** [usebruno/bruno#3409]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When i try to select Bearer token in my collection, bruno crashes
I'm using bruno 1.34.1 on Mac

Let me know if you need any other informations

### Screenshots/Live demo link

<img width="400" alt="image" src="https://github.com/user-attachments/assets/7028b8cc-4b53-4723-b644-23210a0ba48e">
<img width="737" alt="image" src="https://github.com/user-attachments/assets/601f8b9e-200e-4d02-ac7b-a2c004160ef3">

**Comment by gzurowski** [comment]
I am having the same issue on MacOS when trying to add any type of authentication on collection level. It works for individual requests.

**Comment by samislam** [comment]
This happens on Linux Mint 21

**Comment by confuzeus** [comment]
> I am having the same issue on MacOS when trying to add any type of authentication on collection level. It works for individual requests.

+1

The console output when adding authentication for a collection:

```javascript
TypeError: Cannot read properties of undefined (reading 'res')
    at lB (index.js:47:44)
    at ak (react-dom.production.min.js:167:135)
    at up (react-dom.production.min.js:197:256)
    at i (react-dom.production.min.js:292:18)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
    at oP (react-dom.production.min.js:273:286)
    at r8 (react-dom.production.min.js:127:100)
```

**Comment by anusreesubash** [comment]
Thank you for reporting this issue. We're actively working on it and will roll out a fix as a hot release soon.

**Comment by sreelakshmi-bruno** [comment]
Hi @jmischler72, this issue has been resolved in out latest release. Please check it out!

**Comment by gzurowski** [comment]
> Hi @jmischler72, this issue has been resolved in out latest release. Please check it out!

Thanks, I can confirm it's working on MacOS now.

**Comment by jmischler72** [comment]
Thank you, it is fixed !
