### ISSUE TITLE
Bruno crashes when I try to export a collection.

### ISSUE THREAD

**Issue by shw2ypro** [usebruno/bruno#3410]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Bruno crashes whenever I attempt to export a collection. The application displays an error screen with the message "Oops! Something went wrong." (screenshot attached). I am using the official production build.

### Screenshots/Live demo link

<img width="1491" alt="Screenshot 2024-11-01 at 3 24 26 PM" src="https://github.com/user-attachments/assets/37aafb12-1ba8-4866-9fcc-63f7b841e709">

**Comment by sreelakshmi-bruno** [comment]
Hi @shw2ypro, thanks for reporting this issue. We're working on this.

**Comment by sreelakshmi-bruno** [comment]
@shw2ypro , I was able to reproduce the issue while exporting collections as postman collection with empty requests (requests with no url)/ requests with unsaved changes. Did you encounter the error while doing the same or is it something else? Thanks!

**Comment by sreelakshmi-bruno** [comment]
Hi @shw2ypro, this issue has been taken care of in our latest release(1.34.2). Please check it out!

**Comment by shw2ypro** [comment]
Hello @sreelakshmi-bruno I've downloaded the latest version of the app (release 1.34.2), but I'm still encountering the same issue with some collections—not all—when attempting to export as Postman.

**Comment by sreelakshmi-bruno** [comment]
@shw2ypro, can you share more details about the collections which aren't working for you/ how i can reproduce them?

**Comment by helloanoop** [comment]
Just adding here that this has been fixed in `v1.34.2` 🎉
