### ISSUE TITLE
Error while creating vars

### ISSUE THREAD

**Issue by rajdip-b** [usebruno/bruno#3419]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Whenever I try to add a variable to a collection (both pre- and post-request), the app crashes. 

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/a45eb1d8-278f-4694-8c80-40045876ecb9)
![image](https://github.com/user-attachments/assets/25796633-3720-430c-ae03-42b991a62388)

**Comment by ganesh-bruno** [comment]
Hey @rajdip-b,

Thanks for raising this issue.

I was able to reproduce the problem and found that the app crashes when creating variables in a collection (both in pre- and post-requests). Our team is working on it.

**Comment by rajdip-b** [comment]
Hey @ganesh-bruno! I did some digging over the weekends, and have found a fix. If you want, I can open up a PR

**Comment by gasbi** [comment]
Same happens when trying to add vars to folders.

**Comment by rajdip-b** [comment]
Yeah, I noticed that aswell.

**Comment by ganesh-bruno** [comment]
Hey @rajdip-b,

Thank you for suggesting a solution. We’re actively working on it and will release a fix as a hot patch shortly.

**Comment by sreelakshmi-bruno** [comment]
Hi @rajdip-b, this issue has been resolved in our latest release(1.34.2). Please check it out. Thanks!
