### ISSUE TITLE
my API returns a video file, Bruno can detect that this is a video file but cannot display it

### ISSUE THREAD

**Issue by stephane-archer** [usebruno/bruno#3423]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

my API returns a video file, Bruno can detect that this is a video file but cannot display it.
here is the output video file:

https://github.com/user-attachments/assets/420e75a0-adb2-4f8b-b8fe-3960cbadf2e6

### Screenshots/Live demo link

<img width="1440" alt="Screenshot 2024-11-05 at 11 09 28" src="https://github.com/user-attachments/assets/75a80c52-d91d-4575-9159-dee0cfc81354">

**Comment by ganesh-bruno** [comment]
Hi @stephane-archer,

Thanks for raising this issue.

We’re currently looking into it, and the fix will be available soon. You should be able to see the video displayed correctly in the upcoming release.

**Comment by helloanoop** [comment]
This will be available in the upcoming `v1.35.0` release.

**Comment by stephane-archer** [comment]
@helloanoop you are the best!
