### ISSUE TITLE
Error while attempting to retrieve GQL schema in Bruno

### ISSUE THREAD

**Issue by hadidy100** [usebruno/bruno#3432]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When clicking Schema tab and then click Load from Introspection for a valid GraphQL URI, I get the following error: 
" Error invoking remote method 'fetch-gql-schema': TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object" 

### Screenshots/Live demo link

![ErrorLoadingSchema_GQL](https://github.com/user-attachments/assets/600141ef-a76e-47c4-985f-2126da08e216)

**Comment by ganesh-bruno** [comment]
Hi @hadidy100,

I'm using Bruno `1.34.2`, and I was able to reproduce this issue with a valid GraphQL API.

### Here's what I did:
1. Opened the **Schema tab**.
2. Selected the **Load from Introspection** option.

The response I received was: **`GraphQL Schema loaded successfully`**.

I've also attached a video for reference: 

Please let me know if this works on your end or if you're encountering any issues.


https://github.com/user-attachments/assets/2c988d41-850e-47f5-a181-8129f0b2fba5

**Comment by ganesh-bruno** [comment]
Hi @hadidy100,

I'm using Bruno `1.34.2`, and I was able to reproduce this issue with a valid GraphQL API.

### Here's what I did:
1. Opened the **Schema tab**.
2. Selected the **Load from Introspection** option.

The response I received was: **`GraphQL Schema loaded successfully`**.

I've also attached a video for reference: 

Please let me know if this works on your end or if you're encountering any issues.

https://github.com/user-attachments/assets/fff123e3-b108-478a-be5e-0293addbdb32

**Comment by hadidy100** [comment]
Hi @ganesh-bruno, 

Thank you for the GIF! 
This revealed that I do not have the latest version of Bruno, so I downloaded the 1.34.2 version and it is now working as expected. so THANK YOU. 

However this link : https://github.com/usebruno/bruno/issues/562 

Says that we can update manually but that option was not available in the old version, but I am good now. Thanks again.
