### ISSUE TITLE
Global Environment not found

### ISSUE THREAD

**Issue by raimondsL** [usebruno/bruno#3442]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

After I open Bruno and make any request I see Console error.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/426376bd-6e2b-4ffd-8e1f-96a2f242ec5f)

**Comment by sreelakshmi-bruno** [comment]
Hi @raimondsL, sorry to know you're facing this. I'm not able to reproduce this on 1.34.2. Can you share the bru file you are using?

**Comment by sreelakshmi-bruno** [comment]
Hi @raimondsL, thanks for reporting this. We're working on it!

**Comment by raimondsL** [comment]
meta {
  name: test
  type: http
  seq: 1
}

get {
  url: www.example.com
  body: none
  auth: none
}

**Comment by BruAlcaraz** [comment]
Hi, The best solution to the issue is to Create a global Environment even it does not have any variables and select it in the app. Once you do that the error will no longer be logged in the console
![image](https://github.com/user-attachments/assets/278eb8ca-a6b3-4c14-ba66-d098865b64fe)
