### ISSUE TITLE
When renaming a request in bruno client, if we add 'DELETE/' it removes such request

### ISSUE THREAD

**Issue by Drachenfels** [usebruno/bruno#3454]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

It's easy to reproduce.

1. Create a new request say "Hello World"
![selection-20241108143931](https://github.com/user-attachments/assets/b56cec47-a36f-4c10-9c81-0e1b611f8996)

2. Rename the request to say "Hello/DELETE World"
![selection-20241108144105](https://github.com/user-attachments/assets/487b978e-8755-44e8-82e7-74a07ceb441d)

3. Instead of renaming, the file will be removed from the hard drive
![selection-20241108144113](https://github.com/user-attachments/assets/693ace3e-9420-4233-9549-b563f6359cd8)

### Screenshots/Live demo link

![selection-20241108143931](https://github.com/user-attachments/assets/b56cec47-a36f-4c10-9c81-0e1b611f8996)
![selection-20241108144105](https://github.com/user-attachments/assets/487b978e-8755-44e8-82e7-74a07ceb441d)
![selection-20241108144113](https://github.com/user-attachments/assets/693ace3e-9420-4233-9549-b563f6359cd8)

**Comment by ganesh-bruno** [comment]
Hey @Drachenfels 
Thanks for reporting this issue. 

I'm able to reproduce it. 
The error occurs when renaming the request to `req-name/DELETE` and we're working on it.

**Comment by helloanoop** [comment]
I have merged the PR https://github.com/usebruno/bruno/pull/3274 that will now throw warnings and prevent file deletion.
This will go out in the upcoming `v1.36.0` release scheduled to be released on 4 Dec 2024

We are also working on supporting backward and forward slashes in request names. Please track https://github.com/usebruno/bruno/issues/2996 for updates regarding that.
