### ISSUE TITLE
Bruno CLI variable interpolation in the URL is not working

### ISSUE THREAD

**Issue by Agagnier35** [usebruno/bruno#3455]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

The variable interpolation of the URL field is partially working when using the CLI. It always work in the UI though.

Type of variable tested as not working:

- Request Variable
- Folder Variable
- Collection Variable

Type of variable tested as working:
- Environment Variable

Bruno CLI version: 1.34.1, but I noticed the issue was already happening in 1.28.0
Bruno UI version: 1.34.2

### .bru file to reproduce the bug

meta {
  name: A sample request with a variable in the URL
  type: http
  seq: 1
}

get {
  url: {{host}}/resource/{{id}}
  body: none
}

vars:pre-request {
  id: 46345080-3b96-45f0-a3df-d26932233473
}

assert {
  res.status: eq 200
}

### Screenshots/Live demo link

when running with the JSON output you can notice that the "results.request.url" field has the variable template still present.

In the provided bru, if the host is an env variable, and the id a request variable, you would notice that the host would be interpolated properly in the results JSON but the ID would still be the template with the `{{}}`

**Comment by ganesh-bruno** [comment]
Hi @Agagnier35,

Thank you for reporting this issue.

Currently, we support all levels of variables in the GUI app, but only a few are supported in the CLI. We're working on adding support for all variable types in the CLI as well.

**Comment by sreelakshmi-bruno** [comment]
Hi, this issue has been resolved in the latest release of the CLI. Please check it out and let me know how it goes.

**Comment by Agagnier35** [comment]
Hello, I upgraded the CLI to 1.36.2 (latest on npm)

it does not seems to be working, i have a collection level pre-request script that is no longer being run before the request. A console.log at the start of the script, was used to test, and i could see the output in previous versions.

I added a sample project, that should be pretty close to my use-case, using https://reqres.in to generate responses

[Sample CLI Failing project.zip](https://github.com/user-attachments/files/18064677/Sample.CLI.Failing.project.zip)

**Comment by sreelakshmi-bruno** [comment]
We're looking into it. Thanks for the feedback!

**Comment by sreelakshmi-bruno** [comment]
Hi @Agagnier35, did you pass the parameter `--env Test` while running your collection in the CLI?

**Comment by Agagnier35** [comment]
I can confirm v1.36.3 is working, all my tests are back to green 👍 

Thank you very much!

**Comment by sreelakshmi-bruno** [comment]
Closing this issue since it had been resolved!
