### ISSUE TITLE
Application Hangs when accessing the Large Bearer Token Value

### ISSUE THREAD

**Issue by theinhumaneme** [usebruno/bruno#3460]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

The application becomes slow when accessing any request which has long bearer tokens configures

### .bru file to reproduce the bug

have a 1571 or longer JWT bearer token

**Comment by sreelakshmi-bruno** [comment]
Hi @theinhumaneme, thanks for reporting, we're working on this!

**Comment by sreelakshmi-bruno** [comment]
Related #2842. We're tracking the issue here.

**Comment by helloanoop** [comment]
@theinhumaneme We are prioritising this issue and are looking into this week.
I deleted the video in your description as I felt it had some sensitive tokens.

We are tracking the issue here - #2842 Hence closing this as a duplicate.

**Comment by theinhumaneme** [comment]
Thank you team, could you please update this comment thread when the issue is fixed? Until then I'll be using postman although, I love Bruno's git integration :)

**Comment by sreelakshmi-bruno** [comment]
Hi @theinhumaneme, this issue was resolved and released yesterday. Please check it out!

**Comment by theinhumaneme** [comment]
thank you @sreelakshmi-bruno
