### ISSUE TITLE
Oauth2 with client credentials sent as header

### ISSUE THREAD

**Issue by ivank** [usebruno/bruno#3468]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

The Access Management system that we are using (]Gravitee](https://documentation.gravitee.io/am)) similar to Okta requires client credentials to be sent as a `Authorization: Basic` header rather than parameters.
Postman already has [a dropdown for that for that](https://learning.postman.com/docs/sending-requests/authorization/oauth-20/#requesting-an-oauth-20-token:~:text=Client%20Authentication%20%2D%20Send%20a%20Basic%20Auth%20request%20in%20the%20header%2C%20or%20client%20credentials%20in%20the%20request%20body.%20After%20upgrading%20to%20a%20new%20version%2C%20change%20the%20value%20here%20to%20avoid%20problems%20with%20client%20authentication.) 

This is a blocker for us for using Bruno unfortunately as we cannot change how access management requires its client credentials. 

### Mockups or Images of the feature

This could be a similar feature:
https://github.com/postmanlabs/postman-app-support/issues/2296#issuecomment-335093383

**Comment by pietrygamat** [comment]
This has been reported before in #2106

**Comment by ivank** [comment]
indeed, sorry - closing this as a duplicate of #2106
