### ISSUE TITLE
[Feature] Specify meta along with file name

### ISSUE THREAD

**Issue by majkinetor** [usebruno/bruno#347]
When we are naming the request, we specify file name. However, in the saved bru file there is a `meta.name` which, when changed manually, reflects on the UI request name.

It would be more user friendly to allow setting it via GUI:

Something like this:

<img src=https://github.com/usebruno/bruno/assets/85767/88eb9ade-40b1-45a0-9411-6df813d4ba8e width=200px/>

Bruno should offer automatically `<Verb>-<Name>` or equivalent to set as a file name as you type it (and file name should be editable by the user). So if you have two `/list` request, one GET one PUT, you will have `get-list.bru` and `put-list.bru` which are both named the same (`list`) as we already have verb visible in the GUI next to the name.

**Comment by helloanoop** [comment]
Closing this issue as this effort is being tracked [here](https://github.com/usebruno/bruno/issues/2996)
There is also a PR that's mostly in a good shape - https://github.com/usebruno/bruno/pull/3094

Looking forward to have this feature in Bruno by end of Dec 2024
