### ISSUE TITLE
 Error invoking remote method 'send-http-request': VMError: Cannot find module '@faker-js/faker'

### ISSUE THREAD

**Issue by ashameem123** [usebruno/bruno#3480]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

How to use faker for generating random data in our request??

Using this guide to insatll and use faker library:

https://docs.usebruno.com/scripting/external-libraries

### .bru file to reproduce the bug

NA

### Screenshots/Live demo link

NA

**Comment by cyrilgeorge153** [comment]
@ashameem123 Can I know which Javascript sandbox mode you are using. If you are using safe mode you will get this error. If that's the case switch to developer mode and check again.

**Comment by ashameem123** [comment]
> @ashameem123 Can I know which Javascript sandbox mode you are using. If you are using safe mode you will get this error. If that's the case switch to developer mode and check again.

I am using Developer mode.

**Comment by ashameem123** [comment]
@sreelakshmi-bruno  - Any help is greatly appreciated.

**Comment by sreelakshmi-bruno** [comment]
Hi, I tried faker for generating random data using the guide in the docs and it works fine for me. Can you share the collection if possible for me to test it out?

**Comment by sreelakshmi-bruno** [comment]
See here
<img width="1234" alt="Screenshot 2024-11-19 at 2 28 30 PM" src="https://github.com/user-attachments/assets/56f6fac5-5471-49a3-9054-d1c2e7d8bec7">

**Comment by ashameem123** [comment]
@sreelakshmi-bruno  - Could you please also share the package.json for me to compare?

**Comment by sreelakshmi-bruno** [comment]
Sure, here you go
[package.json](https://github.com/user-attachments/files/17825835/package.json)

**Comment by ashameem123** [comment]
@sreelakshmi-bruno  Thanks for sharing the file. It's weird that I have the same exact steps but it won't work for me.
Is it possible for you to generate randomuuid in the example you provided above and check if you could generate it?

**Comment by sreelakshmi-bruno** [comment]
Hi @ashameem123, I was able to generate RandomURL. See here
<img width="1211" alt="Screenshot 2024-11-24 at 12 35 17 PM" src="https://github.com/user-attachments/assets/a6044b1f-7802-4cbb-80ad-baca085cd6a1">

**Comment by ashameem123** [comment]
I am unable to add randomurl still but clearly the issue is on my end.
Thanks for your support and assistance.

**Comment by sreelakshmi-bruno** [comment]
Hi @ashameem123, can you try running `npm list` in your collection directory and see if the `faker` module is getting listed?

**Comment by jonathonc** [comment]
@ashameem123 I had a similar issue, and removing `@faker-js/faker` from the `moduleWhitelist` worked for me

```json
 "scripts": {
    "moduleWhitelist": ["chai", "@faker-js/faker"],
    "filesystemAccess": {
      "allow": true
    }
  }
```

**Comment by sreelakshmi-bruno** [comment]
Ah, @ashameem123  that could be one reason why it didn't work for you. Thanks @jonathonc for sharing this.

**Comment by ashameem123** [comment]
> @ashameem123 I had a similar issue, and removing `@faker-js/faker` from the `moduleWhitelist` worked for me
> 
> ```json
>  "scripts": {
>     "moduleWhitelist": ["chai", "@faker-js/faker"],
>     "filesystemAccess": {
>       "allow": true
>     }
>   }
> ```

Thanks @jonathonc This resolved my issue. Thank you!!

I have one more question around it,

I have to create multiple random urls in a single request but if I'm referencing the variable multiple times, it keeps using the same value everytime and not randomly creating a new url and uuid, How to get through this? I am sorry not too familiars with JS hence unable to resolve it,

![image](https://github.com/user-attachments/assets/c216b053-7865-49f4-82cc-2064eaac8dcd)

**Comment by Bhyan** [comment]
Hi, I have the same problem. Reproducing the solution given here, but still having the problem.

![Image](https://github.com/user-attachments/assets/504eec53-b8fd-4e1b-a4de-80e82c7c5814)

![Image](https://github.com/user-attachments/assets/19884b1c-b0ac-440a-a2fd-2ffb95f3c308)

![Image](https://github.com/user-attachments/assets/5c00d350-ab50-4c52-abde-396b2981ccc7)

**Comment by anusree-bruno** [comment]
> Hi, I have the same problem. Reproducing the solution given here, but still having the problem. I need to do something more ?
> 
> Version 2.0.1
> 
> ![Image](https://github.com/user-attachments/assets/fcee097d-20bc-4e4b-9b0b-e6b1cfb3bbd8)
> 
> ![Image](https://github.com/user-attachments/assets/19884b1c-b0ac-440a-a2fd-2ffb95f3c308)
> 
> ![Image](https://github.com/user-attachments/assets/5c00d350-ab50-4c52-abde-396b2981ccc7)

Can you confirm the sandbox mode? You have to be in developer mode

**Comment by anusree-bruno** [comment]
> > [@ashameem123](https://github.com/ashameem123) I had a similar issue, and removing `@faker-js/faker` from the `moduleWhitelist` worked for me
> >  "scripts": {
> >     "moduleWhitelist": ["chai", "@faker-js/faker"],
> >     "filesystemAccess": {
> >       "allow": true
> >     }
> >   }
> 
> Thanks [@jonathonc](https://github.com/jonathonc) This resolved my issue. Thank you!!
> 
> I have one more question around it,
> 
> I have to create multiple random urls in a single request but if I'm referencing the variable multiple times, it keeps using the same value everytime and not randomly creating a new url and uuid, How to get through this? I am sorry not too familiar with JS hence unable to resolve it,
> 
> ![image](https://github.com/user-attachments/assets/c216b053-7865-49f4-82cc-2064eaac8dcd)


One option here is to call the function instead of using a variable, this will generate random urls and ids

![Image](https://github.com/user-attachments/assets/fa42d354-8a38-4518-a093-d9b47f5e4047)

Then set the body via script

**Comment by Bhyan** [comment]
> > Hi, I have the same problem. Reproducing the solution given here, but still having the problem. I need to do something more ?
> > Version 2.0.1
> > ![Image](https://github.com/user-attachments/assets/fcee097d-20bc-4e4b-9b0b-e6b1cfb3bbd8)
> > ![Image](https://github.com/user-attachments/assets/19884b1c-b0ac-440a-a2fd-2ffb95f3c308)
> > ![Image](https://github.com/user-attachments/assets/5c00d350-ab50-4c52-abde-396b2981ccc7)
> 
> Can you confirm the sandbox mode? You have to be in developer mode

That's it, I wasn't using dev mode. Thanks.
