### ISSUE TITLE
Github release URL on https://www.usebruno.com/downloads is incorrect

### ISSUE THREAD

**Issue by GarlicPunk** [usebruno/bruno#3494]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

The download page https://www.usebruno.com/downloads

> The release notes along with the release and source artifacts can be found under the[ GitHub release](https://github.com/releases).

The link incorrect points to https://github.com/releases not https://github.com/usebruno/bruno/releases

`The release notes along with the release and source artifacts can be found under the[ GitHub release](https://github.com/releases).`

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/353f3b3d-eafc-47a5-a2d9-0b89d24d154e)

**Comment by itsarijitray** [comment]
@GarlicPunk Can I take this up?

**Comment by GarlicPunk** [comment]
@itsarijitray Sure. After logging this I assume the fix will be in the [bruno-website](https://github.com/usebruno/bruno-website) or [bruno-docs](https://github.com/usebruno/bruno-docs) repos.

**Comment by itsarijitray** [comment]
@GarlicPunk The change already seems to be on the main branch
https://github.com/usebruno/bruno-website/blame/main/src/pages/downloads.js

**Comment by sreelakshmi-bruno** [comment]
Hi, thanks for reporting, we'll push an update soon!
