### ISSUE TITLE
[User experience] When closing a tab with request containing unsaved changes, I should be prompted whether those changes should be discarded or not

### ISSUE THREAD

**Issue by lared** [usebruno/bruno#351]
When I close a tab with a request that has some unsaved changes (modified script or headers), those changes are not saved *or* discarded. They just sit there quietly, I can reopen the tab and they are still going to be there.

This means that:

- I have absolutely no idea which requests I made changes to that might need saving (when the tab is closed, there is no indication that request has pending changes in it)
- when I close Bruno, I might unknowingly lose some data from unsaved requests, as Bruno also doesn't prompt about pending changes when exiting the application AND doesn't save them anywhere

**Comment by almirjakubaitis** [comment]
Same problem in Ambient windows. 

- Does not save changes to modified requests. 

- But when I clone a request, the data is saved in the new request. 

I manually open anyrequest.bru to view the parameters and it really isn't changing.

**Comment by lared** [comment]
I see that core part (closing request doesn't prompt for changes) has been resolved in v0.21.1, but there are two areas left:

- closing the application itself
- closing variables window

**Comment by eliasb-usafacts** [comment]
In addition to a `File -> Save` menu, a `File -> Save All` (and or a keyboard shortcut to save all unsaved requests) would be nice too

**Comment by sanjai0py** [comment]
I'm marking this issue as closed since it has already been implemented.

https://github.com/usebruno/bruno/pull/1317
