### ISSUE TITLE
[1.34.2] isArray assertions incorrectly failing on CLI

### ISSUE THREAD

**Issue by fantpmas** [usebruno/bruno#3514]
### I have checked the following:

- [X] I use the newest version of bruno.
- [x] I've searched existing issues and found nothing related to my issue.

### Describe the bug

isArray assertions work fine in Bruno itself but incorrectly show as failing when executed via the CLI.

### .bru file to reproduce the bug

```
meta {
  name: todo
  type: http
  seq: 2
}

get {
  url: https://jsonplaceholder.typicode.com/todos/
  body: none
  auth: none
}

assert {
  res.body: isArray 
}
```

### Screenshots/Live demo link

![Screenshot 2024-11-20 at 09 46 32 (1)](https://github.com/user-attachments/assets/d751c92e-6777-419a-9882-2ba55e4d7bf0)
![Screenshot 2024-11-20 at 09 46 05 (1)](https://github.com/user-attachments/assets/6014046d-bb2b-43b2-be1e-1f43e6668b66)
![Screenshot 2024-11-20 at 09 46 19 (1)](https://github.com/user-attachments/assets/6cca3a8f-0d22-43a0-8348-f62324fec19e)

**Comment by stupidly-logical** [comment]
I'd like to work on this.

**Comment by sreelakshmi-bruno** [comment]
Hi @fantpmas, thanks for reporting. I tried to run the bru file posted here, in the CLI and the assertions got passed. Not sure why this doesn't work on your side. Are you using the latest version of the cli (1.34.1)?

<img width="281" alt="Screenshot 2024-11-21 at 11 10 43 AM" src="https://github.com/user-attachments/assets/dae6ef66-ea70-4036-8af3-d240441855d6">

**Comment by fantpmas** [comment]
![Screenshot 2024-11-21 at 08 20 50](https://github.com/user-attachments/assets/46dcd8ae-f9d6-4401-a07f-a47d7bdb863c)
Ah weird, the cli version seems to be stuck on `1.11.0`. Reinstalling does not help.

**Comment by fantpmas** [comment]
Ah, totally forgot you have to install the CLI separately. 🤦 
Updated to 1.34.1 and now it works indeed.
