### ISSUE TITLE
Comment keybind no longer supports XML formatted comment

### ISSUE THREAD

**Issue by jdunster-bw** [usebruno/bruno#3519]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I often use the `⌘ + /` keybind to comment out certain parts of a request that I'm debugging. I recently updated my Bruno version to the latest version though (`1.34.2`) and this seems to have broken that functionality for XML. Prior to the upgrade, I was using version `1.23.0`.

Previously, when using the keybind, it would comment out sections in XML style, wrapping it in `<!-- -->` or removing the wrapping from a commented-out line or section. Now, it just adds or removes `//` from the start of the line which produces invalid XML. This is especially annoying in existing Bruno files which have commented-out lines that I'd like to include, as now they need to be commented/uncommented manually.

I suspect this was introduced by #2634, as this made some changes meant to allow the comment keybind to work with JSON, but the behavior might be spilling over to XML editing as well.

### .bru file to reproduce the bug

[Example Collection.json](https://github.com/user-attachments/files/17833413/Example.Collection.json)

### Screenshots/Live demo link

Behavior before updating:

https://github.com/user-attachments/assets/df7adbb4-af7f-4c26-addd-47d26e799446

Behavior after updating:

https://github.com/user-attachments/assets/936b3a4a-5b7b-48eb-91c1-8d1eef50bf9e

**Comment by sreelakshmi-bruno** [comment]
Hi @jdunster-bw, thanks for reporting this issue. We'll work on it and will post the updates here.

**Comment by sreelakshmi-bruno** [comment]
Hi, just found out this issue happens only in Mac.

**Comment by jdunster-bw** [comment]
@sreelakshmi-bruno thank you for the quick response! I just downloaded the latest version and re-tested, and the functionality seems to be working as expected for XML. I'll go ahead and close this issue.
