### ISSUE TITLE
[User experience] When creating a new collection, folder name should be suggested based on the collection name

### ISSUE THREAD

**Issue by lared** [usebruno/bruno#353]
I guess that for most people the collection folder is going to be same-ish as the collection name. 

I suggest that create collection pop-up should:

- keep folder name in sync with name of collection, escaping all non-filesystem friendly characters like /  or :
- if somebody puts a cursor into the folder name field, this sync mechanism should be disabled (to allow changing that generated name)

**Comment by helloanoop** [comment]
Bruno now automatically suggests the folder name to be used based on the collection name.

<img width="370" alt="image" src="https://github.com/user-attachments/assets/1830cc10-6127-427b-a9b2-4788638b6bcd">
