### ISSUE TITLE
Jsonpath not working in Bruno while doing assertion

### ISSUE THREAD

**Issue by cyrilgeorge153** [usebruno/bruno#3536]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Response
`{
  "data": {
    "createPost": {
      "id": "12",
      "title": "title1",
      "views": 100,
      "user_id": "10"
    }
  }
}`

### .bru file to reproduce the bug

meta {
  name: Mock
  type: http
  seq: 4
}

get {
  url: https://run.mocky.io/v3/ad186501-abbe-4f01-b029-7bd19c5105e7
  body: none
  auth: none
}

assert {
  res.data.createPost.id: eq 12
}

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/5af0c95b-3a27-4304-a21b-b0557e3d08d0)

**Comment by ganesh-bruno** [comment]
Hey @fantpmas @cyrilgeorge153,

The assertion should be `res.body.data.createPost.id`, and the value is a string `'12'`, not a number 12. 

Please update that and give it another try. Let me know if it works or if you run into any issues!

**Comment by cyrilgeorge153** [comment]
Oops missed the body in the assertion. Will close the bug.
