### ISSUE TITLE
Default to HTTP for "cURL" Request Option in Collection, Not GraphQL

### ISSUE THREAD

**Issue by ganesh-bruno** [usebruno/bruno#3539]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When creating a request from a collection in Bruno and selecting the cURL option, the default request type is currently set to GraphQL, which is not expected. The default should be HTTP when generating a cURL request.

Additionally, when a user pastes a cURL command, Bruno should automatically detect whether the request is HTTP or GraphQL based on the content of the command and adjust the settings accordingly

### .bru file to reproduce the bug

NA

### Screenshots/Live demo link

https://github.com/user-attachments/assets/da140e38-5494-453e-b9b1-c0e860aa973b

**Comment by sreelakshmi-bruno** [comment]
This issue has been fixed and is available in our latest release (1.36)!
