### ISSUE TITLE
PostHog API key missing

### ISSUE THREAD

**Issue by SpoooKyHammer** [usebruno/bruno#3571]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

On Latest version (v1.35), I cannot access the app. Refer to the uploaded image. Clicking on "Return to app" results in same behavior.

I rollbacked to v1.34.2 and the app works fine.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/821da0a8-62fe-4d51-9fdb-f09623dae296)
![image](https://github.com/user-attachments/assets/515c8079-b97a-4373-8891-ead290a7cc2c)

**Comment by SpoooKyHammer** [comment]
@helloanoop Yes

**Comment by helloanoop** [comment]
`v1.35.1` patch for snap is live
You should be able to update by running - `snap refresh bruno`
