### ISSUE TITLE
Application not able to start "Error: You must pass your PostHog project's api key."

### ISSUE THREAD

**Issue by Jojoooo1** [usebruno/bruno#3572]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Application is not able to start.
bruno version: 1.35

### Screenshots/Live demo link

![Screenshot From 2024-11-29 11-56-37](https://github.com/user-attachments/assets/129bf74a-0655-4d85-8ebc-73ee95c7f376)

**Comment by sreelakshmi-bruno** [comment]
Hi, thanks for reporting. Would you be able to share a video of this bug?

**Comment by rbideau** [comment]
Looks like the same problem as #3570 and #3571

**Comment by anusree-bruno** [comment]
This has been fixed please upgrade to 1.35.1.

I am closing this issue. Please feel free to reopen if the issue persists
