### ISSUE TITLE
[Bug] Preview for PNG files results in white screen/crash

### ISSUE THREAD

**Issue by bholm** [usebruno/bruno#359]
When making a request that returns a PNG, the application freezes at a white screen and I need to restart it.

Steps to reproduce:
- To reproduce this issue, you can simply try sending a request to `https://github.com/usebruno/bruno/blob/main/assets/images/landing-2.png?raw=true`.

Expected result:
- To see the image in the preview pane.

**Comment by helloanoop** [comment]
Reopening: https://github.com/usebruno/bruno/pull/519#issuecomment-1756958177
