### ISSUE TITLE
Stale Folder Settings Tab Causes Crash on Rename/Delete

### ISSUE THREAD

**Issue by Pragadesh-45** [usebruno/bruno#3606]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When a folder settings tab is open and the folder is either renamed or deleted, the tab becomes stale. Its UID is not cleared or updated correctly. As a result:  
1. The stale tab remains visible in the UI.  
2. Clicking on the stale tab to interact with it causes the application to crash.  

**Steps to Reproduce:**  
1. Open the folder settings tab for any folder.  
2. Rename or delete the folder while the settings tab is active.  
3. Attempt to click on the stale folder settings tab.  

**Expected Behavior:**  
- On renaming the folder, the settings tab should update with the new UID and remain functional.  
- On deleting the folder, the settings tab should automatically close to avoid staleness.  

**Actual Behavior:**  
- The tab remains in the UI with the stale UID.  
- Clicking the stale tab crashes the application. 

### Screenshots/Live demo link

--Not required--

**Comment by Davo00** [comment]
@helloanoop Is it possible to restore the deleted request (on Mac)? File is not in trash or in the bruno folder

**Comment by helloanoop** [comment]
@Davo00  Bruno would not be able to restore the deleted request as it directly relies on the filesystem. If the file isn't in your Trash or the Bruno folder, it might unfortunately be permanently deleted.
