### ISSUE TITLE
[Bug] Disabling SSL doesn't seem to work

### ISSUE THREAD

**Issue by deanveloper** [usebruno/bruno#362]
At the company I work for, we use self-signed certificates for our development environment. In Postman, we need to add our own CA, which is done (in postman) via Settings > Certificates > CA Certificates > PEM File.

It doesn't appear that bruno supports this, although there is an option to disable SSL Certificate Authentication. But when I do that, I get the error `Error invoking remote method 'send-http-request': Error: Key is required`.

**Comment by lared** [comment]
Can you replicate it with any of those domains?

https://badssl.com/

**Comment by TbirdDuncan** [comment]
Resolved it. There's no documentation on this except for https://github.com/usebruno/bruno/issues/168. You go to the bottom left of the app and theres a tiny gear cog with the options to disable ssl

**Comment by deanveloper** [comment]
> Can you replicate it with any of those domains?
> 
> https://badssl.com/

Unfortunately not. Not sure if it's at all helpful, but the error that I get is `Error invoking remote method 'send-http-request': Error: unable to verify the first certificate`

**Comment by Lotti** [comment]
@deanveloper you just have to do a get call to https://self-signed.badssl.com/ to reproduce the problem.

Disabling SSL self-signed check doesn't work (I used the cog in the bottom left corner)

**Comment by helloanoop** [comment]
@Lotti Are you on the latest version `v0.22.0` ?

This is working on my system. MacOS Moneterey Intel x64

![image](https://github.com/usebruno/bruno/assets/9350733/b1bc8d4a-fbe1-4b6f-b503-2cc8cf0253c8)

**Comment by Lotti** [comment]
Thank you for your fast reply.
I'm running in windows 10 with v0.22.0 (installed this morning to replace postman)

**Comment by helloanoop** [comment]
Can you join our [discord community](https://discord.com/invite/KgcZUncpjq). I'll ask our windows user there to check this if they are experiencing the same.

**Comment by deanveloper** [comment]
Can the findings be posted here? It'd be nice to have a solution posted in an indexable/archivable location

**Comment by Lotti** [comment]
We find out that the bug exists only when using a proxy

**Comment by lllama** [comment]
Echoing what @Lotti says: if I enable a proxy (Burp in this case) then I get the cert error.

**Comment by cwilper** [comment]
I got the same issue when using a proxy that self-signs certs in proxied HTTPs traffic, even after checking "SSL Certificate Verification" is un-checked. This is still happening as of `v0.25.0`.

**Workaround:**

What worked for me was to set the `NODE_TLS_REJECT_UNAUTHORIZED` env var to `0` before running.

For example, on macOS, launch the UI from Terminal via:

```
NODE_TLS_REJECT_UNAUTHORIZED=0 open -a Bruno.app
```

**Comment by ebricca** [comment]
on preference save error

one has to set the proxy.port to a number e.g. 1000 even when not used

( output from devtools :)
Error: Error invoking remote method 'renderer:save-preferences': ValidationError: proxy.port must be a number type, but the final value was: NaN (cast from the value ""). )

**Comment by helloanoop** [comment]
@Lotti @lllama @ebricca @deanveloper 
The issue of SSL Disabling not working when used with proxies has been fixed by @cwilper and is available in `v0.27.0`
