### ISSUE TITLE
Bruno does not import the collection settings (Headers, Auth, Scripts, etc.)

### ISSUE THREAD

**Issue by Az-aj** [usebruno/bruno#3638]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I am using Bruno v1.34.0 . I exported a Bruno collection that contains some Headers, Auth and Scripts at collection level. 
 Then , I re-imported it into Bruno, but i found taht the setting part of collection level is empty .
 is it planned to  fix this bug in the upcoming versions? ( To allow importing the settings part as well)

### Screenshots/Live demo link

![Uploading bruno.png…]()

**Comment by ganesh-bruno** [comment]
Hey @Az-aj,

Thanks for reporting this issue.

I'm able to reproduce it. 
This issue has been resolved in the latest version of Bruno (1.36.1). 
Could you please test this on the latest version and let me know if the issue persists?

Thanks!

**Comment by Az-aj** [comment]
Hey @ganesh-bruno ,
I've just tested  V1.36.1 version
Indeed, the issue is resolved in this version
Thanks

**Comment by ganesh-bruno** [comment]
Hey @Az-aj,

Thanks for sharing the update.

I'm closing this issue as it has already been resolved.

Let us know if you encounter with any other issues.
