### ISSUE TITLE
` Error: Error invoking remote method 'renderer:create-collection': ReferenceError: dir is not defined` when new collection folder contains `+`

### ISSUE THREAD

**Issue by mwoz123** [usebruno/bruno#3645]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

` Error: Error invoking remote method 'renderer:create-collection': ReferenceError: dir is not defined` on windows 11 when creating new collection for foldername that contains `+` 

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/a1a46ca3-2325-46f7-934c-11fdab4ad675)
Result: 
![image](https://github.com/user-attachments/assets/dc48a79e-ae46-46b8-a276-3c875ed738a4)

**Comment by sreelakshmi-bruno** [comment]
Hi, thanks for reporting. We're working on this!

**Comment by Pragadesh44-Bruno** [comment]
Hey @mwoz123,

We already have a PR in place to fix this issue and #2193.

**Comment by helloanoop** [comment]
Just merged the PR. This should go out in `v1.37.0` release.

**Comment by mavericardo** [comment]
I encountered this error today (08/09/2026), and I installed Bruno last week.

<img width="537" height="438" alt="Image" src="https://github.com/user-attachments/assets/e815c038-94f4-453e-a6f7-f9a602ad2fc3" />

**Comment by elliot-kauffmann-inpart** [comment]
Hello, I am also experiencing this issue after installing Bruno version 3.1.2

<img width="529" height="426" alt="Image" src="https://github.com/user-attachments/assets/a76eb42e-d272-4c0c-9b6c-8f86b3ba7789" />

<img width="347" height="251" alt="Image" src="https://github.com/user-attachments/assets/dcdc5790-a7d8-4cf6-816a-4c0c20f9f694" />

**Comment by lucksidedown** [comment]
Same. Using 3.1.2.

**Comment by VictorMoura00** [comment]
Same. Using 3.1.2

<img width="672" height="495" alt="Image" src="https://github.com/user-attachments/assets/f23de782-abfc-4cb5-89f5-3665dab7fbba" />

**Comment by Asorano** [comment]
Cloning an existing request or trying to copy and paste triggers the same error in 3.1.2
<img width="895" height="219" alt="Image" src="https://github.com/user-attachments/assets/a0388e14-b548-4a4f-830d-5f1d6d159871" />

Removing the collection and opening it again fixed it for me.

**Comment by marianolc** [comment]
Same . windows 3.1.2

**Comment by star-jay** [comment]
☝️ Fixed in 3.1.3

**Comment by LucasWBritz** [comment]
Had same issue today. Tested with 3.1.4 and it works. Thanks!
