### ISSUE TITLE
[User experience] Let potential users know that bruno is available as a Homebrew cask

### ISSUE THREAD

**Issue by lared** [usebruno/bruno#367]
The release page and/or [downloads page](https://www.usebruno.com/downloads)  should point out that bruno is available via Homebrew, this is a lot less cumbersome way of updating it than installing it via `.dmg` files every other day.

**Comment by rreyn-bruno** [comment]
Hey @lared - sorry for the very delayed response. You've likely noticed, but this has been prominent on the downloads page per your suggestion - it was a very good one.
