### ISSUE TITLE
[Bug] Remove character limit for "Request Name" in the UI

### ISSUE THREAD

**Issue by Rzpeg** [usebruno/bruno#378]
Because:
a) you can import a postman collection with longer names.
b) you can just rename in the .bru file without the limitation

**Comment by santhosh-chinnasamy** [comment]
@helloanoop is there a reason we have 50 char's limit ? if not I can work on this

**Comment by helloanoop** [comment]
This has been fixed in the latest version of Bruno. Closing this issue.
