### ISSUE TITLE
[Feature Request] content-type should be application/xml when XML is selected on the body editor 

### ISSUE THREAD

**Issue by pove** [usebruno/bruno#398]
As per [RFC 7303](https://www.rfc-editor.org/rfc/rfc7303), application/xml is the standard while text/xml is an alias, so I suggest that content-type can be application/xml by default when XML is selected on the body editor.

Related: [#333](https://github.com/usebruno/bruno/issues/333)

**Comment by helloanoop** [comment]
This should be a fairly straightforward update.
@anusree-bruno please have this picked up and delivered in dec sprint

**Comment by helloanoop** [comment]
Just merged the PR. This should go out in `v1.37.0` release.

**Comment by ramki-bruno** [comment]
For anyone who still wants to use `text/xml`, you can always explicitly specify the `content-type` header like below.

![Image](https://github.com/user-attachments/assets/78dbfdee-ddf5-46a9-81a4-a89096a36d72)
