### ISSUE TITLE
[Bug] Styling of GraphQL docs

### ISSUE THREAD

**Issue by grubersjoe** [usebruno/bruno#415]
The panel showing the GraphQL documentation works in general, but it seems to lack styling making it hard to read:

<img width="227" alt="image" src="https://github.com/usebruno/bruno/assets/3109364/7b69734d-b617-41bf-a517-b6284cb59bc8">

I think this can be improved a lot with a bit of CSS.

**Comment by jonian** [comment]
Maybe graphiql can be used for the docs https://github.com/graphql/graphiql/tree/main/packages/graphiql-react.

**Comment by grubersjoe** [comment]
This seems to have been a bug that was fixed here https://github.com/usebruno/bruno/pull/434 :)

**Comment by helloanoop** [comment]
Yup..Will be shipped in a couple of hours.

**Comment by helloanoop** [comment]
This has been fixe by @oscarpas and is available in the latest release `v0.21.0`
