### ISSUE TITLE
feat: ability to see the request (with variables replaced) without running it

### ISSUE THREAD

**Issue by cvmocanu** [usebruno/bruno#418]
Add a feature to see the request (with variables replaced) without running it. It should show the request method, URL, and headers.

This will allow us to check if the request is OK (if we used the correct variables in the correct place), **before** sending the request.

**Comment by UnleashSpirit** [comment]
Hi, 
I personnaly use the "Generate Code > Curl" option on a request for that
![image](https://github.com/usebruno/bruno/assets/6216968/4dc72349-4cd0-4904-b7b0-3672ab454156)

**But there still a bug with it, Auth Header (like Bearer token) are not present**

**Comment by cvmocanu** [comment]
That's actually a very nice way to do it.

From my side, this ticket can be closed as WON'T FIX (or ALREADY DONE).

**Comment by helloanoop** [comment]
I think the feature - "Request Preview" is valuable. We don't want to introduce a button/icon to for this.
This is low priority, but I'd like to keep this issue open and come back to this later.

**Comment by helloanoop** [comment]
Just adding here that Bruno now shows the value of the variables when hovering over them.

<img width="291" alt="image" src="https://github.com/user-attachments/assets/8d7d5c3a-f071-4996-86f2-50d5a3d8b9b0">

I am closing this issue.
I’m closing this issue for now. We’ll revisit it if there’s significant interest from the community.
