### ISSUE TITLE
fix: generate code breaks app if the url is empty

### ISSUE THREAD

**Issue by cvmocanu** [usebruno/bruno#419]
If the URL is empty, choosing "Generate code" will show a blank page with "index.html" as the title.
The only way to get back to the collection is to close Bruno and open it again.

**Comment by HondaChan14** [comment]
Hello may I be assigned this issue? 😊

**Comment by cvmocanu** [comment]
I'm sure the author wouldn't mind a PR :)

**Comment by not-known-person** [comment]
Hi @HondaChan14, I'm actively addressing this issue and it's about to be resolved. Feel free to focus on other matters. Thank you for showing your interest.

**Comment by helloanoop** [comment]
This has been fixed by @not-known-person and is now available in `v0.21.0`
