### ISSUE TITLE
Bruno is on 🔥! 2.8K stars in a week!

### ISSUE THREAD

**Issue by mindreframer** [usebruno/bruno#427]
<img width="1336" alt="Screenshot 2023-10-06 at 15 58 20" src="https://github.com/usebruno/bruno/assets/1232/07f9b7f3-6086-4c24-a7dd-1573f85b2eb7">
Congratulations @helloanoop, Bruno has got 2.8k stars this week alone! (https://github.com/trending/javascript?since=weekly)

Thank you for providing a lean alternative to Postman & Insomnia.

**Comment by helloanoop** [comment]
Thanks you @mindreframer 

Its surreal :)

2 years of slow growth, and then a sudden vertical take-off.

We have a dedicated discussion thread for testimonials [here](https://github.com/usebruno/bruno/discussions/343)
Feel free to share your feedback on Bruno as well as what you'd like to see from the app in the long-term. 

Some other links
* [our roadmap](https://github.com/usebruno/bruno/discussions/384)
* [our long term vision](https://github.com/usebruno/bruno/discussions/269)
