### ISSUE TITLE
feat: Allow json formatting of response body even when content-type is not application/json.

### ISSUE THREAD

**Issue by neecholaus** [usebruno/bruno#435]
I have a few apis that, for whatever reason, intentionally return a content-type header of `text/plain` or similar for json payloads. It is my understanding that Bruno does not format the response body as json unless the content type is `application/json`.

It would be great if we could configure Bruno to still format responses as json even when the server misleads us.

**Comment by iAmRoland** [comment]
I found myself in same situation today, thought I'd try override the content-type header via Script tab and it worked!

This did the trick for me.
<img width="495" alt="20231010093653_Bruno" src="https://github.com/usebruno/bruno/assets/10901772/bcb126e8-b571-4f7b-a502-eec9896ece64">

**Comment by neecholaus** [comment]
Clever! Will be using that for now.

**Comment by helloanoop** [comment]
@iAmRoland @neecholaus Here is a tiny piece of code to do it at one place inside the collection level script.

```javascript
function isValidJSON(str) {
  try {
    JSON.parse(str);
    return true;
  } catch (e) {
    return false;
  }
}

if(isValidJSON(res.getBody())) {
  res.headers['content-type'] = 'application/json';
}
```

**Comment by iAmRoland** [comment]
@helloanoop Oh wow! TIL you can do stuff on collection level as well, not sure how I missed that. Thanks!

**Comment by helloanoop** [comment]
Closing this issue. Feel free to reopen if there are further questions.
