### ISSUE TITLE
The "startWith" and "endWith" assertions do not work

### ISSUE THREAD

**Issue by xaviermarchegay** [usebruno/bruno#437]
![image](https://github.com/usebruno/bruno/assets/658523/075870b7-2d0a-4590-81fa-149605c25382)

assert {
  res.status: 200
  res.body.data.url: startsWith "https://gateway.test.com"
}

https://github.com/usebruno/bruno/blob/6db36513c50a7af2d4c58b35d017db81ff0ca43b/packages/bruno-js/src/runtime/assert-runtime.js#L265

I don't see those assertions in the chai library but in the chai-string library: https://www.chaijs.com/plugins/chai-string/

Also, apparently the syntax should be : expect('abcdef').to.startsWith('abc');

**Comment by helloanoop** [comment]
This is now available in `v0.23.0`
