### ISSUE TITLE
Electron app doesn't store window state/size

### ISSUE THREAD

**Issue by jarne** [usebruno/bruno#451]
Surely a minor issue, but implementing it would improve user experience.

**Current state:**

Window state (position, size, etc.) are not kept when closing and re-opening the application

**Way to reproduce:**

1. Resize or move application window

<img width="1102" alt="Bildschirmfoto 2023-10-07 um 12 29 42" src="https://github.com/usebruno/bruno/assets/15860314/79055d20-e7bc-4c5d-b396-bcb2aae08f49">

2. Close app
3. Open again (starts in default size/position)

<img width="1210" alt="Bildschirmfoto 2023-10-07 um 12 29 25" src="https://github.com/usebruno/bruno/assets/15860314/37538a62-44a1-4434-a592-185ae565bd58">

**Should be:**

Store the window state, persist and load when opening the application.

Likely I'll submit a PR for this soon.

**Comment by helloanoop** [comment]
Reopening: https://github.com/usebruno/bruno/pull/452#issuecomment-1755101199

**Comment by jarne** [comment]
completed with #536
