### ISSUE TITLE
RFC - Test Scripts

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#46]
I have tried to reason from first principles as much as possible while building bruno, and not be blinded by the current status quo (which is how postman does the same stuff).

Here is a page on how bruno thinks differently: https://www.usebruno.com/design

Test scripts are very big and important feature. And I'd like to take this opportunity to rethink from first principles before we build this feature.
Being a developer, I have used api clients mostly to connect with api's, but not to write automation tests for them.

So I'd like to hear out from the community
1. What are your biggest pain points while writing test scripts in postman ?
2. What are some of the features that you adore in postman or other similar tools ?
3. Any additional suggestions or comments

**Comment by helloanoop** [comment]
Testing support is now available in Bruno.
You can refer the docs at https://docs.usebruno.com/testing/introduction.html

**Comment by carlinmack** [comment]
Links don't resolve with .html anymore, fixed link: https://docs.usebruno.com/testing/introduction
