### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#47]
We need to support developers to run bruno on docker

Once you run `npm run build:dev`, it will create a build in the `packages/bruno-app/out` folder.
We need to take the contents of the "out" folder and create a docker image and be able to run the docker image on your local and use bruno.

`Dockerfile` will be located at the root of the project directory

A nice video to get NextJS builds running on docker
https://youtu.be/Pd2tVxhFnO4

**Comment by helloanoop** [comment]
@vijayh1907 Assigning this to you !

**Comment by vijayh1907** [comment]
Sure! I have started with this

**Comment by helloanoop** [comment]
Closing this as we are not going to need docker support since bruno now directly works on top of your ,bru files.
