### ISSUE TITLE
[Bug] Showing Unreadable Text Instead of Displaying Images in Response Pane

### ISSUE THREAD

**Issue by not-known-person** [usebruno/bruno#470]
When making API requests intended to retrieve images, the response in the request pane is displaying unreadable text instead of rendering the image 

![Screenshot 2023-10-09 091003](https://github.com/usebruno/bruno/assets/134089980/02aeade5-c6be-44dc-a0a8-ed4e8599bb93)

**Comment by helloanoop** [comment]
Related PR on image rendering: https://github.com/usebruno/bruno/pull/480

**Comment by Sl-Alex** [comment]
Fixed in 4b297f3

**Comment by helloanoop** [comment]
Closing this. Please re-open if needed.

**Comment by gmajcen** [comment]
This issue still persist if request is post with json body

**Comment by Its-treason** [comment]
> This issue still persist if request is post with json body. mode is `image`, but image is not shown

Yeah, currently the Image preview does a separate GET request to the URL and does not show the original image response. I want to tackle this in the next week or something, but we currently already a lot of PR's open. Can you create a new issue for this? Maybe with an example request?
