### ISSUE TITLE
Impossible to use built-in AJV library 

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#473]
In a request script or test, impossible to import the AJV library:

`const Ajv = require("ajv")` 
leads to an error message 
`Error invoking remote method 'send-http-request': VMError: cannot find module 'ajv'`

**Comment by lared** [comment]
I'll take it

**Comment by arnaduga** [comment]
Seems to be good in UI version 0.24+
Thanks

However I opened the #612 for a similar problem with the bru-cli
