### ISSUE TITLE
[Bug] GraphQL query validation not working

### ISSUE THREAD

**Issue by grubersjoe** [usebruno/bruno#474]
Hey. When writing GraphQL I would expect to see errors like referencing non-existing fields in my query. For example here it should show a red squiggly underline for `unknownField` since this field does not exist for a `Machine`:

![image](https://github.com/usebruno/bruno/assets/3109364/394d64ef-6d73-434b-a58b-ce3c40dc6d72)

I've looked a bit at the [`<QueryEditor />`](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/components/RequestPane/QueryEditor/index.js) component and it seems like this should be handled by Codemirror but errors are not shown. Not sure what's wrong. Does anyone have an idea?

Edit: found the issue, there's a PR now

**Comment by grubersjoe** [comment]
Seems like Codemirror initialization is not correct. If I add the respective `codemirror-graphql` imports in the QueryEditor file it works:

![image](https://github.com/usebruno/bruno/assets/3109364/34417432-2f25-43fb-ba3a-5b6977e8e94b)

**Comment by grubersjoe** [comment]
Fixed by #480

**Comment by helloanoop** [comment]
Thanks for working on this @grubersjoe 
This is now available in `0.22.1`
