### ISSUE TITLE
[Feature Request] - extend save prompt to closing of entire window

### ISSUE THREAD

**Issue by flaik-wayne** [usebruno/bruno#477]
When closing the entire program window, if tabs are open with unsaved changes, the changes are lost without warning

**Comment by flaik-wayne** [comment]
When closing the entire program window, if tabs are open with unsaved changes, the changes are lost without warning

**Comment by helloanoop** [comment]
Hmm..  Need to see if electron supports a pre quit hook to perform an action before closing the app.

**Comment by rsilvr** [comment]
@flaik-wayne @helloanoop I think I did it here: https://github.com/usebruno/bruno/pull/1317
