### ISSUE TITLE
highlight with green color the collection variables for the body

### ISSUE THREAD

**Issue by tinchoz49** [usebruno/bruno#483]
Hey guys! Could it be possible to provide highlight for the body variables, to know that we have those variables setup correctly?

> similar to the headers section

https://github.com/usebruno/bruno/assets/819446/5d6a3db5-2161-4929-8a5f-52488f2f38c0

**Comment by duncandejong** [comment]
Also, in the same extend. Maybe in the GET/POST url if a variable is set in the Vars tab, also highlight in green.
in this case the movieId:
<img width="736" alt="Scherm­afbeelding 2023-10-11 om 12 17 07" src="https://github.com/usebruno/bruno/assets/3210606/ea37693a-2a16-4dc6-a44a-358692efed3a">

**Comment by lllama** [comment]
In a similar vein, if a post-response script has set a variable, it would be nice to see that in green in any request templates.

**Comment by helloanoop** [comment]
Closing this as the latest version of Bruno now supports this
<img width="376" alt="image" src="https://github.com/user-attachments/assets/994745c9-35ed-4836-9ddc-ccb91f068c30">
