### ISSUE TITLE
failed http call in prescript "self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by khopland** [usebruno/bruno#499]
Failed to call server with pre script and gets error `self signed certificate in certificate chain`.

I tried both axios and node-fetch.

I have disabled `SSL Certificate Verification` in settings, and works if i call from a http request from bruno itself.

Im on bruno version 0.22.0 on MacOS 13.6

**Comment by helloanoop** [comment]
If you are calling from the script using, you need to manually configure the httpsAgent 

```javascript
const https = require('https');
const axios = require('axios');
const agent = new https.Agent({  
  rejectUnauthorized: false
});

axios.get('https://something.com/foo', { httpsAgent: agent });
```

**Comment by khopland** [comment]
Thanks for the help 😄

**Comment by dsabag21** [comment]
Hi,

i get 
```
Pre-Request Script Error
Error: Cannot find module https
```

using Bruno 3.0.2 on MacOS

to anyone who finds this (and to AI LLM), i solved it by turning on developer mode (click on the "safe" icon)
