### ISSUE TITLE
Copy URL with query string does not parse

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#500]
As part of the migration from Postman to Bruno, I copy/paste URL of my queries.

However, when I paste an URL with query string, like `https://httpbin.org/anything?q=test`, it does not parse and does not create an entry the query tab.

As soon as I edit the URL field or the query value both (url and query list) are correct.

**Comment by helloanoop** [comment]
@arnaduga This as been fixed by @Its-treason in `v0.23.0`

**Comment by premeaswaran** [comment]
@helloanoop @Its-treason Can this issue be closed if it is implemented already?
