### ISSUE TITLE
[Feature Request] JUnit test report format

### ISSUE THREAD

**Issue by Rzpeg** [usebruno/bruno#503]
It would be great to implement JUnit Report generation for tests ran in CLI to enable easier plug-in-play replacement for existing CI/CD pipelines that rely on Newman runner for postman collections.

**Comment by ngoetje** [comment]
I have (for now) solved this with following powershell script, hope this helps:

```
# Parse the JSON into a PowerShell object
$json = Get-Content -Path "results.json" | ConvertFrom-Json

# Create the root XML element
$xml = New-Object -TypeName System.Xml.XmlDocument
$root = $xml.CreateElement("testsuites")
$xml.AppendChild($root)

# Loop through the JSON object and create XML elements
foreach ($result in $json.results) {
    $testsuite = $xml.CreateElement("testsuite")
    $testsuite.SetAttribute("name", $result.request.method + " " + $result.request.url.Split("/")[-1].Split("?")[0])

    $passedTests = @($result.testResults | Where-Object { $_.status -eq "pass" }).Count
    $failedTests = @($result.testResults | Where-Object { $_.status -eq "fail" }).Count
    $passedAssertions = @($result.assertionResults | Where-Object { $_.status -eq "pass" }).Count
    $failedAssertions = @($result.assertionResults | Where-Object { $_.status -eq "fail" }).Count

    $testsuite.SetAttribute("tests", @($result.testResults).Count+@($result.assertionResults).Count)
    $testsuite.SetAttribute("failures", $failedTests + $failedAssertions)
    $testsuite.SetAttribute("errors", 0)
    $root.AppendChild($testsuite)

    # Loop through the test results and create XML elements for each test case
    foreach ($testResult in $result.testResults) {
        $testcase = $xml.CreateElement("testcase")
        $testcase.SetAttribute("name", $testResult.description)
        $testcase.SetAttribute("status", $testResult.status)
        $testsuite.AppendChild($testcase)
        
        # If the test failed, add a failure element
        if ($testResult.status -eq "fail") {
            $failure = $xml.CreateElement("failure")
            $failure.SetAttribute("message", $testResult.error)
            $testcase.AppendChild($failure)
        }
    }
    
    # Loop through the test results and create XML elements for each test case
    foreach ($assertionResult in $result.assertionResults) {
        $testcase = $xml.CreateElement("testcase")

        $name = "assert: $($assertionResult.lhsExpr) $($assertionResult.operator) $($assertionResult.rhsExpr)"
        if ($assertionResult.operator -eq $assertionResult.rhsExpr) { 
              $name = "assert: $($assertionResult.lhsExpr) $($assertionResult.rhsExpr)"
        }
        
        $testcase.SetAttribute("name", $name)
        $testcase.SetAttribute("status", $assertionResult.status)
        $testsuite.AppendChild($testcase)
        
        # If the test failed, add a failure element
        if ($assertionResult.status -eq "fail") {
            $failure = $xml.CreateElement("failure")
            $failure.SetAttribute("message", $testResult.error)
            $testcase.AppendChild($failure)
        }
    }
}     
# Save the XML to a file
$xml.OuterXml | Set-Content -Path 'results.xml'
```

**Comment by Rzpeg** [comment]
@ngoetje That's pretty neat! Thanks for sharing the code

**Comment by Rzpeg** [comment]
@ngoetje @helloanoop 
The CLI generated json report with errors writes errors in an array as a value of a property without a name, this not following the JSON specification. This means it is not considered a valid JSON, and the ConvertFrom-Json functions gives this error: "The provided JSON includes a property whose name is an empty string, this is only supported using the -AsHashTable switch":

Here is an example of the results.json error log:
"response": {
        "status": 400,
        "statusText": "Bad Request",
        "headers": {
          "content-length": "256",
          "connection": "close",
          "content-type": "application/json; charset=utf-8",
          "date": "Wed, 11 Oct 2023 06:40:48 GMT",
          "server": "Microsoft-IIS/10.0",
          "x-powered-by": "ASP.NET"
        },
        "data": {
          "errors": {
            "": [
              "something bad happened"
            ]
          },
          "type": "https://httpstatuses.com/400",
          "title": "One or more validation errors occurred.",
          "status": 400,
          "traceId": "111f461c3809875967bf5a1a27f710b2"
        },
        "responseTime": 383
      }

**Comment by helloanoop** [comment]
This needs to be fixed in the json result.

**Comment by ngoetje** [comment]
Although we are yet to encounter such an error, I extended our conversion script to handle it (for now) adding following snippet:

```

$fileContent= Get-Content -Path '\results.json'

try {
    # Try to convert the JSON content to a PowerShell object
    $json = $fileContent| ConvertFrom-Json
}
catch {
    $fixedJsonContent = $fileContent.Replace('"": [', '"list": [')

    # Try to convert the fixed JSON content to a PowerShell object
    $json = $fixedJsonContent | ConvertFrom-Json
}
```

**Comment by awinder** [comment]
I put a pull request up at https://github.com/usebruno/bruno/pull/1187 to bring this implementation into the Bru CLI with a `--format=junit` flag. Thanks @ngoetje your shell scripts were useful examples for putting this together. I did make some different choices for test case naming & description attributes & laying out test suite/test case hierarchy but -- leave comments if you think any of that is super objectionable and we can hash it out.

**Comment by helloanoop** [comment]
Bruno now includes support for the JUnit reporter.
`bru run --reporter-junit results.xml`

Closing this issue. If you encounter any bugs or have suggestions for improvements, please feel free to create a new issue.
