### ISSUE TITLE
[Bug] Shortcuts should be displayed based on OS type

### ISSUE THREAD

**Issue by martinsefcik** [usebruno/bruno#505]
The following shortcuts on request tab should be displayed based on operating system. So e.g. `Cmd + Enter` on Mac and `Ctrl + Enter` on other OS type.

![image](https://github.com/usebruno/bruno/assets/1073299/97b61c53-16fb-4ae8-86c9-9d95445293ba)

**Comment by helloanoop** [comment]
This is now available in `v0.23.0`
