### ISSUE TITLE
Response Size Not Shown

### ISSUE THREAD

**Issue by vivaladan** [usebruno/bruno#508]
![CleanShot 2023-10-10 at 11 26 19@2x](https://github.com/usebruno/bruno/assets/1514212/ca932d8b-4625-4ccf-ab03-c724167a027e)

If content length is missing from the response, Bruno shows 0B. It would be super useful to show what was actually transferred.

Compare this to Insomnia, where it will show what was actually transferred. Mousing over this will show the separate Read and Content info. In the case of compression these two values would differ.

![CleanShot 2023-10-10 at 11 29 43@2x](https://github.com/usebruno/bruno/assets/1514212/120491eb-f1d0-43b6-bd62-fba407366d0a)

**Comment by snippetkid** [comment]
Can you please take a look at the closely related issue and confirm if this is a duplicate? https://github.com/usebruno/bruno/issues/497

**Comment by vivaladan** [comment]
Good spot, it's a duplicate. I must have missed that when I searched.
