### ISSUE TITLE
Rename dialog ignores capitalisation changes

### ISSUE THREAD

**Issue by vivaladan** [usebruno/bruno#510]
Operating System
macOS 14

Version
v0.22.1

Expected Behaviour
I want to rename requests to correct the capitalisation of some of the names.

Actual Behaviour
Typing in the new name into the rename dialog and pressing return or clicking rename button, results in the dialog closing but no change to the name, when only the capitalisation changes.

**Comment by Kavinkumar07** [comment]
Assign this to me I am interested in fixing this issue.

**Comment by Its-treason** [comment]
This seems to be a windows only problem, because the windows file-system is case-insensitive. And probably has to do with a duplicate file check in `bruno-electron/src/ipc/collection.js:251`

**Comment by Kavinkumar07** [comment]
I fixed this and have raised a pull request.
