### ISSUE TITLE
Shortcut Ctrl+W close the window, not the tab

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#529]
When pressing the Ctrl+W, the whole Bruno application is closed, without saving the current request edition.

Expected behavior: whatever the object closed (window or tab), it should be offered to save current edit.

Ideally (but maybe larger discussion), shortcut Ctrl+M should close tab only

**Comment by martinsefcik** [comment]
For me it is happening only if focus is in Search edit box located in sidebar, when focus is somewhere else this shortcut does not close whole application.  Is it happening the same way for you @arnaduga ?

**Comment by snippetkid** [comment]
Not only the sidebar search, whenever **any** text field is in focus and you press <kbd>Ctrl</kbd> + <kbd>W</kbd> the whole application gets closed. I've tried with the following text fields

- Sidebar Search
- Request URL
- Rename Request

**Comment by helloanoop** [comment]
Closing this issue as it has already been resolved in Bruno. The `Ctrl+W` shortcut now closes the tab
