### ISSUE TITLE
Search and Copy functionality need to be supported in response

### ISSUE THREAD

**Issue by vyskh2498** [usebruno/bruno#53]
Currently, the functionality to search is limited to the request body and not available in the response body. In case of large response received for certain requests the user is unable to search in the response body. Similarly in case of copying the response also the user is restricted.

**Comment by helloanoop** [comment]
Thanks for reporting this @vyskh2498 
Will get this fixed this weekend.

**Comment by helloanoop** [comment]
@vyskh2498 This has been fixed in the latest release.

Thanks for reporting this.
Closing this ticket now.
