### ISSUE TITLE
[Feature request] Remember last used environment per collection and add ability to store default environment in collection

### ISSUE THREAD

**Issue by martinsefcik** [usebruno/bruno#530]
Currently If I start Bruno app then there is no environment chosen and I have to always switch it to be able to run requests.
So It would be fine If:

- it would be possible to define default environment in collection.bru or bruno.json file
- Bruno app would store last used environment in application settings 

Then application would automatically set environment based on application settings (if this is not present in application settings) then it would be set based on the default environment configured in collection.bru/bruno.json file.

**Comment by grubersjoe** [comment]
https://github.com/usebruno/bruno/issues/303
