### ISSUE TITLE
[Bug] HTTP Method name and request name collidates in sidebar

### ISSUE THREAD

**Issue by martinsefcik** [usebruno/bruno#533]
Longer method names like DELETE, OPTIONS collides in sidebar with request name or cause that request name is indented more then it should be. This behavior depends on sidebar width.

Probably It would be better for this longer method names to use just shortcuts like DEL, OPT the same way as it is in other popular clients as Postman, ...

![image](https://github.com/usebruno/bruno/assets/1073299/8bdd2e0e-30d5-4e4d-9374-4659be966fbd)
![image](https://github.com/usebruno/bruno/assets/1073299/74382c52-2522-4918-be69-b1d6903195fa)

**Comment by theavitw** [comment]
@martinsefcik can I work on this?

**Comment by martinsefcik** [comment]
@theavitw there is already #538
