### ISSUE TITLE
Autocomplete for Request headers

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#54]
Autocomplete for request header keys.
Like the user should not have to type the entire work "Content-Type"

![image](https://user-images.githubusercontent.com/9350733/198833396-b950aa89-ab71-462c-b135-a5ed5f6194d6.png)

We need to support the commonly used request header types as well as allow the user to enter custom headers.

Lets see if we can make this work without having to use any autocomplete react library.
I have implemented dropdown like this in an older project (that is not completed yet) see [here](https://github.com/helloanoop/kgraph/blob/main/renderer/pageComponents/Page/Editor/Block/SearchResults/index.js)

We will implement the _Header Value_ autocomplete once this has been done for _Header Names_.

**Comment by shash68i** [comment]
I have started reading the codebase and will work on this feature.

**Comment by shash68i** [comment]
@helloanoop Can I get some more details on how to style the component? What kind of style should pop up or what should happen interactively, as we start typing?

**Comment by helloanoop** [comment]
@shash68i 
How far are you in developing this?

I am thinking that it might not be a bad idea to use a lightweight library like https://github.com/reactjs/react-autocomplete
The list of headers can be taken from here https://github.com/for-GET/know-your-http-well/blob/master/headers.md

Here is the demo of the interaction https://jsbin.com/fireqebamo/edit?js,output

I would recommend not to worry too much about styling. You can keep it very simple and minimalist as seen in the above jsbin demo.

**Comment by helloanoop** [comment]
Sounds good!

Sorry for having you redo stuff. Thanks for understanding!

**Comment by helloanoop** [comment]
This has been completed. And is available in release `0.19.0`
