### ISSUE TITLE
Version information in site

### ISSUE THREAD

**Issue by gjrivero** [usebruno/bruno#543]
Please, put the current version on the download page.
Current version and stable version.
Because there is no information about it

**Comment by j0k3r** [comment]
That issue belong to https://github.com/usebruno/bruno-website

**Comment by helloanoop** [comment]
@gjrivero I have updated the website to display the current version.

If you are on Linux, we now support snap and apt based installation.

PS: At the moment we don't have seperate release for stable and current. I don't see us introducing that split anytime soon.
