### ISSUE TITLE
Button for pretty printing in POST body

### ISSUE THREAD

**Issue by mathiasbockwoldt** [usebruno/bruno#550]
I tend to edit my json in the POST body a lot and it's easy to destroy the formatting. It would be great if there were some button to automatically fix the formatting (aka pretty print) in the body (json, xml, ...) and response.

**Comment by j0k3r** [comment]
I pushed sth to [prettify the body of a GraphQL query](https://github.com/usebruno/bruno/pull/526). Once merged (and UI validated) I can work on the JSON / XML formatting (at least on the body part).

**Comment by donus3** [comment]
@j0k3r I've opened the PR for the json request body formatting on #604. You can check it out.

**Comment by ChielTimmermans** [comment]
Would this also be possible to implement on the response side? 
It would make reading your responses a lot easier.

**Comment by benjamin-allion** [comment]
I also need the "pretty printing" for XML,
Is it ok for you if I start to work on this topic, and try to send a PR before the end of the week ?

I can try to take a look for prettier on response at the same time.

**Comment by helloanoop** [comment]
Closing this issue as this feature has already been implemented.
