### ISSUE TITLE
[META] Allow sponsoring?

### ISSUE THREAD

**Issue by max-wittig** [usebruno/bruno#551]
Hi! I really like the approach that Bruno wants to go and I switched from Insomnia already as their software got really buggy with 8.X. and also because they are introducing all the forced sync functionalities.

Some companies have a way to sponsor open-source projects with GitHub sponsors. Maybe there would be some interest if this project would support it!

**Comment by helloanoop** [comment]
Hey @max-wittig !

Yes, I will open-up for Github Sponsors as well as Corporate Sponsors.
Too tied up at the moment with development.

**Comment by azzamsa** [comment]
@max-wittig https://github.com/sponsors/helloanoop

Would you like to close this issue?

**Comment by azzamsa** [comment]
@helloanoop  However, it is strange. We don't have `sponsor` button here

![image](https://github.com/usebruno/bruno/assets/17734314/17e11ce3-fae7-464d-8408-42cf70c8fcc4)

Even though we have the funding file setup correctly https://github.com/usebruno/bruno/blob/bc70bba0b614c8e190cd704f0e5893bfd9cd3198/.github/FUNDING.yml#L1

**Comment by helloanoop** [comment]
Thanks @azzamsa !
It appears to be a github issue

**Comment by helloanoop** [comment]
Closing this issue.
Sponsor link is: https://github.com/sponsors/helloanoop
