### ISSUE TITLE
Body is not read in case of a 403

### ISSUE THREAD

**Issue by peterbosch89** [usebruno/bruno#552]
Using a post response script
`bru.setEnvVar("mfa-token", res.body.mfa_token);`

This does not work when the HTTP response status is a 403
But it does work when the HTTP response status is a 200

Could it be that Bruno does not read the body in case the call was not successful?

**Comment by rayoz12** [comment]
I was just investigating this and yes it seems when Axios detects an error, it bails out and any post response code (vars and scripts at least isn't run). I think this is the case at least and happy to be proven wrong. Not sure how we can ignore this and force the post response to run.

**Comment by rayoz12** [comment]
Just wondering @helloanoop if not running vars and scripts after an error was a design choice? If it's not, and a bug I'm happy to create a PR for my changes.

**Comment by rayoz12** [comment]
And if we're wondering about one use case, one API that does error is the Transmission API: https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#231-csrf-protection

Here without a supplied header it returns a 409 with the required header's value. I was trying to set an env var in a post script until I realised nothing was happening.
