### ISSUE TITLE
Parse variables in request JSON body

### ISSUE THREAD

**Issue by svenluijten** [usebruno/bruno#553]
[This comment](https://github.com/usebruno/bruno/issues/8#issuecomment-1284257729) refers to Bruno not being able to parse variables in the request body. For now this can be solved by setting them in the "Script" tab like so:

```js
// In the Pre Request field:
req.setBody({
  "date": bru.getVar("date")
});
```

However, I would like to propose an option to make this possible in the JSON request body so that the "Body" tab is the only place to look for the request body. This would look (something like) this in the "Body" tab:

```json
{
  "date": {{date}}
}
```

I realize this is probably a pretty difficult thing to tackle, but I would argue it's core to the use of variables. The current workaround also isn't very intuitive (at least to me). We might even have to think about another way to denote variables in the JSON (or any) request body, since parsing out `{{` would be pretty tough to do in JSON. Maybe `={{`?

**Comment by svenluijten** [comment]
Also, this seems to be related to #352

**Comment by othyn** [comment]
Also would like to see this added 👍

**Comment by GarthTeixeira** [comment]
if you use:
```
{
 "date": {{date}}
}
```
it should work, it did for me.

**Comment by zaloster** [comment]
You can do `bru.setVar('date', 'from script tab')` in the script tab  and `date` would be available in the Body tab
