### ISSUE TITLE
Feature: Collection and Folder Documentation

### ISSUE THREAD

**Issue by nomorsug** [usebruno/bruno#554]
Related to #361, sometimes is useful to put documentation per collection and folder. Same as for requests, it will make sense to support markdown

**Comment by helloanoop** [comment]
Request Level will being released in another hour.
Collection level should also be quickly implemented.

Folder level may take some time (1-2 weeks)

**Comment by fgalaf** [comment]
Hi @helloanoop, is it still a required feature to implement folder level docs? As far as I know, it was not yet implemented.

**Comment by fgalaf** [comment]
Hi @helloanoop, @sanjai0py. I implemented this feature in PR #3206. Please, let me know what you think. Thanks

**Comment by helloanoop** [comment]
Thanks @fgalaf 
We'll take a look at it this week.

cc @sreelakshmi-bruno

**Comment by helloanoop** [comment]
Just merged the PR. This will go out in `v1.37.0` release.
