### ISSUE TITLE
[FEATURE] Configurable request timeout

### ISSUE THREAD

**Issue by Sl-Alex** [usebruno/bruno#557]
It would be nice to have a configurable request timeout both on request and environment levels.

If the request doesn't have a configured timeout, then the one from the environment is used.
If the environment doesn't have a configured timeout, then the default timeout is used.

In my case, for example, the default timeout is about 2 minutes, which is a bit too much if the target device is not available.
A very small collection with just 10 requests runs for about 20 minutes before giving up.

It seems that axios supports configurable timeouts.

**Comment by helloanoop** [comment]
If anyone in the community has bandwidth, please pick this up.
Changes need to be done like how we have done here: https://github.com/usebruno/bruno/blob/main/packages/bruno-js/src/bruno-request.js#L50-L52

**Comment by snippetkid** [comment]
@helloanoop I will work on this issue.

**Comment by snippetkid** [comment]
Adding link to a WIP PR, which right now only has the UI changes.

![image](https://github.com/usebruno/bruno/assets/16718733/56ea0f3a-d3ce-4cd1-be02-f3d7ffd4e017)

**Comment by snippetkid** [comment]
The PR is now ready to review!

**Comment by helloanoop** [comment]
Thanks for working on this @snippetkid !

Merged.
