### ISSUE TITLE
Request Save Button

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#56]
Reported by @vyskh2498

Currently the shortcut for Save is Ctrl+S / Cmd+S
Need to see if we can add a save button in the UI 

Also, When you close a tab which has unsaved changes, we need to show a popup whether they want to save the changes OR close the tab without saving

**Comment by ljohnston** [comment]
Would add a vote for this feature. I just started with Bruno and it took me a little while to figure out how to save things (had to search through the issues). Now that I know, that's fine, but having to google or search issues for something as simple as this upon first usage feels a little clumsy.

**Comment by merc1er** [comment]
@helloanoop you probably want to close this as already implemented 👍🏻

**Comment by sanjai0py** [comment]
Closing this as the feature already implemented.
