### ISSUE TITLE
Feature: Auto update the Bruno App when there is a new release

### ISSUE THREAD

**Issue by cchunduri** [usebruno/bruno#562]
At the moment Bruno doesn't have a way to auto update when there is a new release happens. As Bruno is in development phase I see a release for every two days at least. Having auto update feature will be nice. We can give two options, 

1. User can update manually by going to Preferences>Update
2. User can enable auto update, then when ever there is a update it automatically download and refresh the app something like VS Code does.

**Comment by j0k3r** [comment]
Duplicate of #103

**Comment by sanjai0py** [comment]
Closing this as it is a duplicate of #103
