### ISSUE TITLE
[Feature request]: no proxy setup

### ISSUE THREAD

**Issue by qck4fun** [usebruno/bruno#568]
Could you please add support for no proxy addresses? Basically option to exclude certain addresses from proxying such as other tools have eg. screenshot from Insomnia below.

![image](https://github.com/usebruno/bruno/assets/7276555/be4531a5-8aad-46ab-96ad-b40d75db965e)

Thanks for you effort & feedback! :pray:

**Comment by mirkogolze** [comment]
I'am working on it. Its finished in the next days

**Comment by qck4fun** [comment]
> I'am working on it. Its finished in the next days

Thank you very much!

**Comment by martinsefcik** [comment]
@qck4fun I guess you should leave this issue open until it is done

**Comment by qck4fun** [comment]
Okay, let's wait until it's released and close it then

**Comment by qck4fun** [comment]
Released, closing this. Thank you! :pray:
