### ISSUE TITLE
[User Experience] Add ability to drag active tabs on top pane

### ISSUE THREAD

**Issue by n00o** [usebruno/bruno#572]
Most web browsers allow you to drag your active tabs to change the order for organizing reasons. It would be convenient if Bruno could do the same. The alternative method is to close and open tabs to change the order but this is inconvenient because you lose the response of the request.

**Comment by Ayush-Vish** [comment]
@n00o  I would like to work on this issue so please assign it to me.

**Comment by helloanoop** [comment]
We currently don't have a process around assigning issues. You can pick it up and work ok it and post updates on the issue regarding the process.

**Comment by Ayush-Vish** [comment]
@helloanoop  Ok.

**Comment by Ayush-Vish** [comment]
@helloanoop  Can we use external libraries for the drag-and-drop feature ?

**Comment by mdacosta** [comment]
Hi!
Sorry for digging up this subject but I was wondering if there is any chance this will be implemented in the very next future?
This is something I really miss about Postman.

**Comment by anusree-bruno** [comment]
This fetaure is currently available 
Reference PR https://github.com/usebruno/bruno/pull/5669, https://github.com/usebruno/bruno/pull/5413
