### ISSUE TITLE
Font Customization Options

### ISSUE THREAD

**Issue by newtoallofthis123** [usebruno/bruno#577]
The current response Codemirror div of bruno seems to use the default font for the output

![image](https://github.com/usebruno/bruno/assets/78465651/16f2e444-097e-4327-9635-4860b3fe050d)

However, I couldn't find any option to customize the font. That would be a good quality of life improvement

**Comment by helloanoop** [comment]
There is a PR for this already by @qweme32 
Will be me merging it for our upcoming release.

**Comment by newtoallofthis123** [comment]
Oh cool!

**Comment by helloanoop** [comment]
@newtoallofthis123 This is now available in 0.25.0

Please checkout the preference tab in the latest release
