### ISSUE TITLE
Improve Windows Scrollbar

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#580]
Mac has beautiful scrollbars which only appear when you try to scroll.
The windows one is not pretty. Not sure how the experience is in linux.

Improve scrollbar on windows.
Transparent scroll track, and thinner scroll thumb.

**Comment by Sahilm416** [comment]
hey @helloanoop  screenshots will really help to understand the issue

**Comment by helloanoop** [comment]
@Sahilm416 are you on windows?

**Comment by Sahilm416** [comment]
@helloanoop yes on windows!

**Comment by helloanoop** [comment]
Closing this issue as the latest version of the app has the scrollbar issues fixed.
