### ISSUE TITLE
Collection Level Docs

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#583]
As a user, I want to store documentation at the root of the collection. (like a readme)

**Comment by helloanoop** [comment]
Done. Will be shipping in the next outgoing release.

![image](https://github.com/usebruno/bruno/assets/9350733/874e9cf5-b797-4438-a28d-54f0418849bc)

**Comment by sanjai0py** [comment]
I am closing this issue as the feature has already been released in [v0.25.0](https://github.com/usebruno/bruno/releases/tag/v0.25.0).
