### ISSUE TITLE
Collections icons partially working

### ISSUE THREAD

**Issue by shash68i** [usebruno/bruno#59]
On clicking icons, the action should be the same as clicking on the text alongside the icon. 'Import Collection' and 'Load Sample Collection' icons are clickable, but the Icons of 'Create Collection' and 'Add Collection to Workspace' has no action.

On hovering the icons, cursor should become pointer.

![bruno-issue](https://user-images.githubusercontent.com/37452438/198947226-0d32bd61-b120-4248-b95e-379c64d8be53.png)

**Comment by helloanoop** [comment]
Nice catch!
And I agree that cursor should become pointer as you hover over the icon.

The fix should be fairly easy. @shash68i Would you like to pick this up ?

**Comment by shash68i** [comment]
Sure, will work on this.

**Comment by shash68i** [comment]
Thanks!
Looking forward to contribute more.

**Comment by helloanoop** [comment]
This has been released. Closing the issue.
@shash68i  you should checkout the latest version of bruno.

Lots of new features are available: https://docs.usebruno.com/
