### ISSUE TITLE
Is bruno unable to render images in response?

### ISSUE THREAD

**Issue by IamLizu** [usebruno/bruno#593]
My Bruno version is v0.24.0

I am getting this in response,
![image](https://github.com/usebruno/bruno/assets/26184316/a1264568-4ec8-4630-81af-687a86371320)

**Comment by hasan-zaag** [comment]
For another response, I am getting
![image](https://github.com/usebruno/bruno/assets/136310205/e8fb6933-987e-4b11-ba63-a5e017a2caa0)

**Comment by Its-treason** [comment]
Hey @IamLizu,

currently, Bruno does not render the original response body as an Image. Instead, it tries to load the image using a separate GET request to the requested URL.

We are definitely going to update the preview to render the original Image response! Thank you for opening an issue.

**Comment by IamLizu** [comment]
Thank you, I am closing this now as it already planned.

**Comment by helloanoop** [comment]
@IamLizu let's keep this open. Will close this once this is delivered.

**Comment by sanjai0py** [comment]
Closing this as the PR implementing feature #622 has already been merged and delivered in [v0.26.0](https://github.com/usebruno/bruno/releases/tag/v0.26.0).
