### ISSUE TITLE
[User experience] Warn/error if request JSON body has syntax error

### ISSUE THREAD

**Issue by Allypost** [usebruno/bruno#594]
I think it would be nicer if the app warns the user when they have invalid JSON in a JSON body type.
Currently it just silently serializes it to a string.

Current behaviour:

> POST request with invalid JSON body (trailing comma):
>
```json
{ "key": "value", }
```
> Gives the timeline:
```
> POST http://example.com
> content-type: application/json
> data "{ \"key\": \"value\", }"
```
> Instead of the expected:
```
> POST http://example.com
> content-type: application/json
> data { "key": "value", }
```

Instead it should give an error (eg. a highlight like it is here) or a warning at least instead of just quietly serializing it "incorrectly"

**Comment by UnleashSpirit** [comment]
Hi,
the ideal would even be to have a beautify button

**Comment by anusree-bruno** [comment]
This is available, bruno shows warning if there is an error in the json and on hover you can see the error message.
![image](https://github.com/user-attachments/assets/b3087468-8bd8-459d-b5ef-3e736ec40581)

Also there is now an option to prettify json.

Closing this issue.
