### ISSUE TITLE
[Bug] Collection Runner does not use client certificates

### ISSUE THREAD

**Issue by mjhcorporate** [usebruno/bruno#611]
When using client-certificates like this (`bruno.json`)
```json
{
  "version": "1",
  "name": "hello",
  "type": "collection",
  "clientCertificates": {
    "enabled": true,
    "certs": [
      {
        "domain": "*.test.tech",
        "certFilePath": "/Users/Martin/.local/share/certs/some-service.client.crt",
        "keyFilePath": "/Users/Martin/.local/share/certs/some-service.client.key",
        "passphrase": ""
      }
    ]
  }
}
```
then individual requests work and properly use the certificate.

However, when using the collection runner, the certificate does not seem to be used, and I run into `http 401` errors on each of my requests:
![image](https://github.com/usebruno/bruno/assets/49681105/6f645352-6f82-496e-a28d-3e5b339adbf2)

fyi @phoval

**Comment by helloanoop** [comment]
@panda7789 refactor is a priority for v2.

Right now, we copy paste code :)

**Comment by mjhcorporate** [comment]
Just retested to make sure -- it works! 🎉
