### ISSUE TITLE
Built-in module not found in CLI

### ISSUE THREAD

**Issue by arnaduga** [usebruno/bruno#612]
Similarly to #473 , the built-in modules are not found in `bru-cli`.

I used the `node-fetch` module.  
It works fine in the UI, but when using bru-cli, I got the error message: `Cannot find module 'node-fetch'`

**Comment by rodrigogs** [comment]
Just had the same issue with `@aws-sdk/client-cognito-identity` lib.

**Comment by rodrigogs** [comment]
🫠

**Comment by helloanoop** [comment]
Closing this issue as this has been fixed in Bruno. Please reopen if the issue persists.
