### ISSUE TITLE
Split line should have max squeeze limit

### ISSUE THREAD

**Issue by shash68i** [usebruno/bruno#62]
The split line should only be allowed to go up to a certain limit on both sides. Allowing it to go till the end is making stuffs overflow and non-readable.

![bruno-issue](https://user-images.githubusercontent.com/37452438/199087801-2ebc6268-4aea-41a1-9a79-8b413af146d9.png)

![bruno-issue-2](https://user-images.githubusercontent.com/37452438/199088260-2d890260-6451-4e30-b8a2-0ab2f8e3641b.png)

**Comment by Anx450z** [comment]
Hi @helloanoop, I would like to contribute to this issue, please add me to the contributors.

**Comment by helloanoop** [comment]
Hey @Anx450z !!

You can fork the project, and work on this feature.
Once done, you can raise a pull request.

There are instructions in [here](https://github.com/usebruno/bruno/blob/main/contributing.md) to help you bring up the app on local 

Let me know if you get blocked and need help. Also feel free to join the discord chat for adhoc assistance.

**Comment by Anx450z** [comment]
Closes #64

**Comment by helloanoop** [comment]
Thanks for the work on this @Anx450z 
PR is merged.

Fix should be available in the web app in the next 5 min at play.usebruno.com

Will release the fixes to the desktop app soon (hopefully in a couple of days)

**Comment by shash68i** [comment]
Thanks for your contribution @Anx450z 

However, right side of split pane is still going till the last. Please have a look into that.
