### ISSUE TITLE
[Feature Request] Flatpak support

### ISSUE THREAD

**Issue by tywil04** [usebruno/bruno#623]
As the title suggests, support packaging Bruno as a flatpak so it can be used on any linux distro that supports flatpak.

**Comment by helloanoop** [comment]
Working on this. I have a flatpak build ready. Will be submitting to the flatpak repo this week.

**Comment by azzamsa** [comment]
Yes. As the Bruno releases increasing frequently, it will be more convenient to run `flatpak update` than download the whole new Bruno binary.

**Comment by rjshrjndrn** [comment]
> Working on this. I have a flatpak build ready. Will be submitting to the flatpak repo this week.

Amazing. Was about to use for api documentation. But for installation, hesitated once. Will wait for flatpak :)
Keep up the amazing work :+1:

**Comment by azzamsa** [comment]
> Working on this. I have a flatpak build ready. Will be submitting to the flatpak repo this week.

Any update about this? 🙏🏼

**Comment by ludberg** [comment]
I'm also interested - any updates?

**Comment by Gabriel-Espinoza** [comment]
You know what would be great? - to start 2024 with flatpak support :fireworks: :fireworks: :fireworks:

**Comment by helloanoop** [comment]
Bruno can now be installed via Flatpak 🎉 🎊

`flatpak install flathub com.usebruno.Bruno`

Link: https://flathub.org/apps/com.usebruno.Bruno

<img width="1016" alt="image" src="https://github.com/usebruno/bruno/assets/9350733/aefd738e-6d7f-4e6b-a49b-948887802d90">
