### ISSUE TITLE
Autocomplete possible request headers

### ISSUE THREAD

**Issue by roelofjan-elsinga** [usebruno/bruno#628]
The request headers are already autocompleted: Authorization, Content-Type, etc. But I'd like the same for the possible values for each. When I type "Content-Type" It'd save me a lot of time if I can just type an "a" and use my arrow keys to find "application/json".

**Comment by helloanoop** [comment]
Closing this as this is now available in Bruno

<img width="486" alt="image" src="https://github.com/user-attachments/assets/b1543bbd-cdaa-4ce9-b317-135d8f3b3352">
