### ISSUE TITLE
Remove star counter from the UI

### ISSUE THREAD

**Issue by Dragas** [usebruno/bruno#641]
It looks like bruno is also following the same self masturbation that insomnia is by showing how many stars the software has on github. In addition, I have concerns about bruno not being truly offline. As a result, I would like that button removed.

**Comment by helloanoop** [comment]
> It looks like bruno is also following the same self masturbation that insomnia is by showing how many stars the software has on github. 

That's pretty sad you feel that way.
I opensource 2 years of my hard work, try to do the [right thing](https://github.com/usebruno/bruno/discussions/269) and you are annoyed by a star button that is placed at the left bottom corner.

>  I have concerns about bruno not being truly offline

what are your concerns

> As a result, I would like that button removed.

I actually have plans to monetize the product via a supported edition, If a star counter is causing so much frustration, please choose other alternatives in the market

**Comment by Dragas** [comment]
You claim your tool is fully offline, yet at the same time you depend on github's integration to fetch the star counter. That's incompatible with what you're saying. Why should that counter be there in the application? What does it add?

**Comment by helloanoop** [comment]
Not going to answer. If the star counter is frustrating you, please use other alternatives.
There are plenty minimalist, bloatfree opensource api clients with a great vision that might interest you.

**Comment by helloanoop** [comment]
Contributors and Users who genuinely care, love and adore Bruno - My apologies. I kind of lost my cool here.

I feel it's reasonable to have it be displayed in the left bottom corner. The app is utterly minimalist and carefully crafted. It's reasonable to have a star counter in a place where you rarely look.

That being said. After v1 launch, I will add a UI toggle in the App Settings which allows you to hide the star counter.

**Comment by mj-h** [comment]
@helloanoop : Thank you, I think that is a reasonable decision. A couple weeks ago, I would not have had a problem with a star counter, but then events happened, an now any project prominently displaying their stars looks a bit suspect to me.

**Comment by Dragas** [comment]
It is true that I am annoyed by what is currently going on with postman, insomnia and other possible replacements. As for your questions:

> Why do you think Github has a star counter for projects?

If it was added post microsoft acquisation I'd argue it's to make github more like social media. Since the feature predates microsoft, it's intended use is to subscribe to project's updates.

> Why do you look at the Github stars / Npm Downloads before you use a project?

I can see people using those two metrics to gauge how popular a project is, but both metrics can be easily inflated. The latter suffering a lot from CI/auto builds downloads, while former suffering from users bookmarking your project but outside of that not really interacting with the project. 

Personally, I don't depend on those metrics, but rather check if the issue tracker is managed by stalebot, and whether issues are interacted with (ex. resolved, closed without resolution), and what issues other people have with the project. After all - people do not complain about the tools they do not use.

> Do you think that the number of stars / downloads is a good indicator of the quality of the project?

No.

> If you have created an open source project, do you see the number of stars / downloads as a measure of success?

Also no. I have yet to quantify the "success" metric when it is by definition a qualitative measure.

**Comment by thehorse2000** [comment]
Of course, there is a GitHub stars button, It is an open-source project.
Close the issue, you are not making any sense here

**Comment by helloanoop** [comment]
The star counter has been removed from the Sidebar.
Closing this issue.

![image](https://github.com/usebruno/bruno/assets/9350733/53ff6626-6e87-4950-ad03-7acf60a858fe)
