### ISSUE TITLE
Relative client certificate paths do not work

### ISSUE THREAD

**Issue by tibeer** [usebruno/bruno#653]
relates #275

Even though mentioned in the PR that relative certificate path should work, I cannot get them to work.
I placed them directly within my collection folder next to my bruno.json which looks like this:

```json
{
  "version": "1",
  "name": "tibeer",
  "type": "collection",
  "clientCertificates": {
    "enabled": true,
    "certs": [
      {
        "domain": "api.tibeer.de",
        "certFilePath": "prod.cer",
        "keyFilePath": "prod.key",
        "passphrase": ""
      },
      {
        "domain": "api-test.tibeer.de",
        "certFilePath": "test.cer",
        "keyFilePath": "test.key",
        "passphrase": ""
      }
    ]
  }
}
```

Might also be an user error.

**Comment by mj-h** [comment]
Interesting: They work in the CLI, but not in the UI. I'm having a look.

**Comment by tibeer** [comment]
Aweseome job @jwetzell! Closing this :)
