### ISSUE TITLE
[Bug - Minor] Http Method update doesn't get saved as expected

### ISSUE THREAD

**Issue by premeaswaran** [usebruno/bruno#658]
Let the HTTP method of a Request be GET initially.

**What works as expected:**
- Change to POST
- Press Ctrl + S
- Saves just fine. And the Amber dot next to the Request name goes off.

**What doesn't work as expected:**
- Change to POST
- **Now change it back to GET** 
- Press Ctrl + S
- 'Request saved successfully' toast is displayed. However, the Amber dot next to the Request doesn't go off. And when tried to close the request, the 'Unsaved changes' dialog pops up.

**Comment by helloanoop** [comment]
The latest version of Bruno includes fixes for this issue. If the problem continues, feel free to reopen the issue.
