### ISSUE TITLE
[Bug] Trailing zeros in JSON response

### ISSUE THREAD

**Issue by pove** [usebruno/bruno#659]
Bruno is removing trailing zeros on float fields.

Postman response:
` "Numeric": 250.00`

Bruno response:
` "Numeric": 250`

This is an axios/js known limitation: https://github.com/axios/axios/issues/2279

**Comment by helloanoop** [comment]
This has been fixed is a part of https://github.com/usebruno/bruno/issues/2767

**Comment by helloanoop** [comment]
A much better fix was built in [PR](https://github.com/usebruno/bruno/pull/6026) and is live in `v2.14.0` 🎉 🎉
