### ISSUE TITLE
Vars in asserts are not evaluated

### ISSUE THREAD

**Issue by benwalder** [usebruno/bruno#660]
When pre request var `EXPECTED_TYPE is 'teamMember'` and response is `{ "type": "teamMember" }`

assert `res('type') equals teamMember` correctly results in:
```
(ok) res('type'): eq teamMember
```

assert `res('type') equals {{EXPECTED_TYPE}}` incorrectly results in:
```
(fail) res('type'): eq {{TYPE}}
     expected 'teamMember' to equal '{{TYPE}}'
```
The var `{{TYPE}}` is being used as a literal string rather than a var that needs evaluated.

**Comment by KaniZ0r** [comment]
Hi!

I reported this issue couple days ago: https://github.com/usebruno/bruno/issues/624
It's allready fixed in this merged pr: https://github.com/usebruno/bruno/pull/632

When @helloanoop releases next version it should be fixed 👍
