### ISSUE TITLE
Variable values are not interpolated

### ISSUE THREAD

**Issue by KaniZ0r** [usebruno/bruno#676]
When adding a variable as Pre Request value the UI displays the values correctly in tooltips.
Info toolbox also tells that I can use any valid JS template literal.
However it doesn't interpolate the values and I end up sending literal string in request body.

![image](https://github.com/usebruno/bruno/assets/13645181/6a9f2351-f8c9-4b77-a7b7-69ce91412f9e)

Here's the data that i got from the GET request that I use to fetch previously saved data:

![image](https://github.com/usebruno/bruno/assets/13645181/de00283b-cec3-4a7f-9f13-f3098153b857)

Here's the actual body of my request:

![image](https://github.com/usebruno/bruno/assets/13645181/6d0563f7-3eb3-41f8-84d6-03c915941f5c)

**Comment by helloanoop** [comment]
The latest version of Bruno has fixes for this.
Please reopen the issue if the problem persists.
