### ISSUE TITLE
[Bug] Unable to rename folder due to lock hold by Bruno.exe process

### ISSUE THREAD

**Issue by martinsefcik** [usebruno/bruno#678]
Sometimes it happens that I'm not able to rename collection folder in Bruno UI or in any other File manager (e.g. Windows Explorer) because Bruno.exe process is holding some lock on it.

I'm not sure when exactly it happens. Probably it is Windows only issue.

Version: 0.25.0 also in some earlier versions

**Comment by ahuemmer** [comment]
Same (or similar?) issue here. Windows 11, x64, Bruno v1.6.1. Can't rename a folder (just nothing will happen). The Dev console shows:

```
Uncaught (in promise) Error: Error invoking remote method 'renderer:rename-item': Error: EPERM: operation not permitted, rename 'D:\Desktop\Bruno Test\Test-Projekt\Foldername' -> 'D:/Desktop/Bruno Test/Test-Projekt/Othername'
```

**Comment by sjcompan** [comment]
Same here (still)

Uncaught (in promise) Error: Error invoking remote method 'renderer:rename-item': Error: EPERM: operation not permitted, rename 'C:\.....\claim\attachments' -> 'C:/.../claim/01attachments'

- Win 11 / 64 
- Bruno 1.10.0
- Started as administrator 


Collection which contains the folder was created via import from postman.
﻿

**Comment by helloanoop** [comment]
I have merged the PR https://github.com/usebruno/bruno/pull/3236 that fixes this.
This will go out in the upcoming v1.36.0 release scheduled to be released on 4 Dec 2024
