### ISSUE TITLE
Removing added Client certificates crash

### ISSUE THREAD

**Issue by madisvain** [usebruno/bruno#679]
When clicking on the remove icon for the client certificate the application crashes with this exception

<img width="1373" alt="Screenshot 2023-10-19 at 14 22 06" src="https://github.com/usebruno/bruno/assets/727994/78ff3ee3-8da2-40de-899d-63d3bd4b1de4">

Otherwise looking very much forward to moving to Bruno from Insomnia. A nice clean looking application!

**Comment by sanjai0py** [comment]
Issue closed as it has already been fixed ([commit](https://github.com/usebruno/bruno/commit/72df441)) and released in [v0.26.0](https://github.com/usebruno/bruno/releases/tag/v0.26.0).
