### ISSUE TITLE
[Bug] Collection variable is defined and has value but still displayed as red in request address or query params tab

### ISSUE THREAD

**Issue by martinsefcik** [usebruno/bruno#680]
Sometimes it happens that collection variable is defined and has any value set (I can see it on Variables tab), but it is still displayed with red color in address bar or in Query params table on request's tab. Also it is not possible to see value on tooltip during moving cursor over it. If I run request then this variable is correctly send with proper value.

![image](https://github.com/usebruno/bruno/assets/1073299/5e29d536-55fe-4eda-aec4-29a061b5e510)
![image](https://github.com/usebruno/bruno/assets/1073299/6fb9fe85-3171-420e-a0cf-5e9e9d19f2bb)
![image](https://github.com/usebruno/bruno/assets/1073299/f1dcdb27-a571-4a44-94ff-20daff358956)

It's happening somehow randomly and I don't know how to reproduce it.

Bruno version: 0.25.0

**Comment by bholm** [comment]
From what I've found, is that it shows red if the variable only contains numeric values, wrapping the number in quotation marks should make it turn green. Also variables with only numeric values, it strips any leading zeros which is also quite annoying. Wrapping in quotations is the work around I'm using for now, but it would be nice for the variable to insert exactly as written.
