### ISSUE TITLE
Variable Names - Enforce Strictness

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#682]
Enforce strict variable naming rules.

A variable name must start with a letter or `_`
A variable name cannot start with a digit
A variable name can only contain alpha-numeric characters, `_` (a-z, A-Z, 0-9, _ )

If a variable is found to not adhere to these rules, display an error in the UI. The user shouldn't get frustrated as to why the request its not working as expected.

Variable Naming rules apply to
1. Env Vars
2. Request Vars
3. Collection Vars
4. Dynamic Vars `bru.setVar()` and `bru.getVar()`

Also see: https://github.com/usebruno/bruno/issues/345

**Comment by mirkogolze** [comment]
Hi @helloanoop, @Its-treason,

In the implementation am missing the "_" defined in the requirement. And "-" should be allowed too.

**Comment by helloanoop** [comment]
> missing the "_" defined

We should add this immediately

> And "-" should be allowed too.

The `-` is atypical for a variable name (in the javascript world), but I see that other apps (#853) use it. I am fine with loosening the restriction around `-`

**Comment by lujop** [comment]
This is greatly impacting us because we have collections from previous versions that heavily use variable names with `-`.

**Comment by helloanoop** [comment]
@lujop This will be fixed in our upcoming release 1.1.0 which will be live in the next few hours.

**Comment by helloanoop** [comment]
@lujop You can use `-` in the latest release 1.1.0

Thanks @Its-treason for getting this done !
