### ISSUE TITLE
Values in .env file that contain # are not parsed correctly

### ISSUE THREAD

**Issue by dcampagnone** [usebruno/bruno#690]
version 0.26

I have a .env file configured with a password like the below
`TEST_PASSWORD1=ABC#123`

In collections and requests this is parsed as `ABC`.

![image](https://github.com/usebruno/bruno/assets/6098195/edab7a5a-b864-4977-a7fb-b149de567e69)

Not sure if it happens with other characters or not.

**Comment by helloanoop** [comment]
This is because it is treating it as a comment. This is a convenient in all env files.

Can you wrap iy in quotes and try `"TEST_PASSWORD1=ABC#123<"`

**Comment by dcampagnone** [comment]
Wrapping the entire entry in quotes isn't recognized by the UI.  Wrapping just the value in quotes does work.

Example:
`TEST_PASSWORD1="ABC#123"` - WORKS

**Comment by helloanoop** [comment]
Cool. That was typo on my side. I actually meant to wrap the value part.
