### ISSUE TITLE
[Bug] error occurred while saving preferences

### ISSUE THREAD

**Issue by ebricca** [usebruno/bruno#692]
version 0.26.0 gives an error when trying to save preferences:
"An error occurred while saving preferences"
(tested on windows with a new install or portable)

happens e.g. on change of SSL/TLS Certificate Verification
to make it work, one has to set the proxy.port to a number e.g. 1000 even when not used

( devtools output 
Error: Error invoking remote method 'renderer:save-preferences': ValidationError: proxy.port must be a number type, but the final value was: NaN (cast from the value ""). )

**Comment by aliasgar55** [comment]
Not able to reproduce the issue
I was able to reproduce the issue just once
after that it didn't occured

**Comment by braveterry** [comment]
![an-error-occurred-while-saving-preferences](https://github.com/usebruno/bruno/assets/527650/b08c5570-7b03-4a1b-91e7-5aed826376c6)

This is happening for me on an Intel Mac running Sonoma.  It started when I downloaded Bruno v0.26.0.  I was running v0.17.0 before.  My settings were reset after the update to v0.26.0.

**Comment by aliasgar55** [comment]
I guess to issue occurs when [this](https://github.com/usebruno/bruno/blob/f8f38802a97f7c22134e25c1b218c5f7ce96f6eb/packages/bruno-app/src/components/Preferences/ProxySettings/index.js#L28) condition evaluates to a NaN
Would be great if someone can share more light Thank you
