### ISSUE TITLE
[feature] mouse over variable show the current value

### ISSUE THREAD

**Issue by survivant** [usebruno/bruno#712]
like postman, when we pass the mouse over a variable we should be able to see the value of the variable
![image](https://github.com/usebruno/bruno/assets/191879/cecda8d7-da41-4ac5-9446-99d6ab058af8)

and when we click on it, we should be able to edit the value or go to the variable environment screen

**Comment by mybeon** [comment]
I am looking forward to addressing this feature once I can schedule some time for it.

**Comment by helloanoop** [comment]
Bruno now highlights the variable value when you hover over it.

<img width="531" alt="image" src="https://github.com/user-attachments/assets/615da988-1ddc-4ead-9ed3-fd9a734e8f7b">
