### ISSUE TITLE
[Feature Request] Search in the response 

### ISSUE THREAD

**Issue by smdedar** [usebruno/bruno#716]
- Users can search in response
![image](https://github.com/usebruno/bruno/assets/30989286/48239e90-770d-4a7e-85c1-642d9809b72d)

**Comment by emptyflask** [comment]
CTRL-F in the response window brings up a search prompt (with regex support)

**Comment by helloanoop** [comment]
@smdedar As @emptyflask pointed out, you should be be able to click on the response view and hit `ctrl/cmd + f` to search the response

**Comment by sanjai0py** [comment]
I'm closing this issue because the requested feature is already available in Bruno.
