### ISSUE TITLE
Improvement: Move from axios to redaxios

### ISSUE THREAD

**Issue by lil5** [usebruno/bruno#719]
> Axios has a great API that developers love. Redaxios provides that API in 800 bytes, using native fetch().

https://www.npmjs.com/package/redaxios

This should be a drop in replacement:

```js
// from
import axios from 'axios';
// to 
import axios from 'redaxios';
```

**Comment by helloanoop** [comment]
Not sure if the size of the library is the a worthy tradeoff to move away from the battle tested `axios` and especially for a large scale project such as bruno

**Comment by lil5** [comment]
Understandable, `Fetch API` works ever so slightly different than `XMLHttpRequests` and changing that now might for some people using bruno create regressions.

There are some issues on redaxios of edge cases e.g. this one https://github.com/developit/redaxios/issues/96 

Thanks for the awesome program!

Closing issue now 👋
