### ISSUE TITLE
Can't get environment variable from post body request

### ISSUE THREAD

**Issue by fab-uleuh** [usebruno/bruno#721]
Hello 

I try bruno but I've problem to get environment variable from post body request : 

<img width="961" alt="image" src="https://github.com/usebruno/bruno/assets/91676342/a5330c0f-dd10-42ac-80a6-a96468d80509">

As you can see it's really send {{username}} instead of the data who is write into environment collection. 

(v0.26.0, MacOS)

Thank you !

**Comment by aliasgar55** [comment]
Hi 
There is already a open issue #676 and a PR for the same #677

**Comment by fab-uleuh** [comment]
Thanks @aliasgar55
