### ISSUE TITLE
Support GitHub Codespaces and VS Code Dev Containers

### ISSUE THREAD

**Issue by andrewbrey** [usebruno/bruno#722]
Providing `devcontainer` configuration files in the repository enables the use of GitHub Codespaces, VS Code Dev Containers, JetBrains Dev Containers, and any other editor environments that support the [devcontainer specification](https://containers.dev).

This allows contributors to work on the project all with the same developer setup, fully built up and configured on their behalf with no work required for the contributor. Ultimately it lowers the barrier to entry for contribution to helps empower those with weaker hardware to be able to contribute using cloud based IDEs.

I would love to get your project set up with devcontainer configuration as a Hacktoberfest contribution.

**Comment by DrPye** [comment]
Seconded, this would be a great feature!
