### ISSUE TITLE
[Small bug] - first preferences change blocked due to http proxy port not being set

### ISSUE THREAD

**Issue by l0new4nder3r** [usebruno/bruno#728]
_Small but annoying bug, since version 0.25 or 0.26_

When one, for the first time, tries to edit something in the preferences (by example disabling the SSL validation) and then saves, the preference pane crashes because the proxy http port default value (in another tab of the preferences) is empty, and there is an attempt to save its value (with a numerical type I suppose, and NaN...).

Workaround: go to the proxy tab, set something (even if the proxy is not in use), 0 by example, and then you can save with the modification taken into account.

To fix the issue : set up a default hardcoded numerical value for the http proxy port, or do not attempt to save this empty value when proxy is disabled?

**Comment by helloanoop** [comment]
Just release a fix for this in the `v0.27.0` release. Can you test it ?
