### ISSUE TITLE
[Feature] Add YAML support file for OpenApi Specification

### ISSUE THREAD

**Issue by survivant** [usebruno/bruno#729]
For now, we can only import Json file, we need to add yaml support too

**Comment by scop** [comment]
Nice :+1: While at it, perhaps add Insomnia YAML import support, too? ;) #743

**Comment by survivant** [comment]
Sure 😂

Le lun. 23 oct. 2023, 13 h 12, Ville Skyttä ***@***.***> a
écrit :
