### ISSUE TITLE
Saving and / or copying responses to a file or clipboard

### ISSUE THREAD

**Issue by bramhoven** [usebruno/bruno#73]
It would be great if there was a possibility to save or copy a response to the clipboard. The right click context menu also does not work in this field.

**Comment by helloanoop** [comment]
@bramhoven Are you on v0.2 or v0.3

Thinking if its similar to #53 Fixes to this was released in v0.3
Currently auto update functionality is not added to electron app. Plan to add that soon.

**Comment by bramhoven** [comment]
@helloanoop My bad! After updating it does indeed work. Although still no context menu, but copying does work.

**Comment by sanjai0py** [comment]
Closing this issue as it has already been implemented!
