### ISSUE TITLE
Suggestion: Import from Insomnia

### ISSUE THREAD

**Issue by vicenterusso** [usebruno/bruno#74]
Please add Insomnia format when importing

**Comment by helloanoop** [comment]
@vicenterusso Sure. Will add support for this soon!

**Comment by AmalChandru** [comment]
Hi, @helloanoop is this still in scope? I would like to explore this further and work on it.

**Comment by helloanoop** [comment]
Yes, @AmalChandru This is still in scope. You can work on this.

**Comment by helloanoop** [comment]
@vicenterusso Support is now available in v0.11.0 for importing Insomnia Collections
