### ISSUE TITLE
German translation of documentation files

### ISSUE THREAD

**Issue by x0vr** [usebruno/bruno#747]
Add german translation to the project documentation files.

**Comment by wheinze** [comment]
this has been resolved ;)

**Comment by krummbar** [comment]
[publishing_de](https://github.com/usebruno/bruno/blob/main/docs/publishing/publishing_de.md), [contributing_de.md](https://github.com/usebruno/bruno/blob/main/docs/contributing/contributing_de.md), [readme_de.md](https://github.com/usebruno/bruno/blob/main/docs/readme/readme_de.md) are included in the meantime.
@lohxt1 @helloanoop @x0vr 
I think this issue can be closed
