### ISSUE TITLE
Upload a file

### ISSUE THREAD

**Issue by medilies** [usebruno/bruno#769]
How to upload a file?

This is what I do on postman:

![image](https://github.com/usebruno/bruno/assets/35309918/eb58a3a6-f50d-4512-8528-a1ca12a39543)

![image](https://github.com/usebruno/bruno/assets/35309918/02aa7d35-043d-4a14-8f6d-4de4493455fd)

**Comment by lucaskbr** [comment]
I had the same issue, it would be nice to have this feature

**Comment by Nahuel92** [comment]
Please bump. I checked and there is this PR to address this feature:

https://github.com/usebruno/bruno/pull/1130

Will it be merged and released any time soon?

**Comment by ash-eng-spin** [comment]
Also requesting as a UI feature.

**Comment by ash-eng-spin** [comment]
Would also like for user to edit the content-type for each part.

**Comment by rhenandias** [comment]
[1.8.0 Release](https://github.com/usebruno/bruno/releases/tag/v1.8.0) implemented file uploads, the current releases from 1.8. have this feature as built in
