### ISSUE TITLE
Download file (when response is a file)

### ISSUE THREAD

**Issue by medilies** [usebruno/bruno#770]
How to achieve the equivalent of this from Postman?

![image](https://github.com/usebruno/bruno/assets/35309918/77087fee-acb0-4c43-8793-90896f1d590a)

**Comment by martinsefcik** [comment]
Related to #539

You can check my PR #766 if it is OK for you or you want to have it working exactly as on your screenshot. But it is only one additional button to be added to my implementation and the rest is the same, so it shouldn't be complicated to implement it.

**Comment by sanjai0py** [comment]
Closing this issue as the pull request (https://github.com/usebruno/bruno/pull/766) implementing the feature has already been merged.
