### ISSUE TITLE
GraphQL load schema is not using custom headers.

### ISSUE THREAD

**Issue by Dom4n** [usebruno/bruno#78]
I have tried to use bruno with Shopify GraphQL. 
It requires `X-Shopify-Access-Token` header to be set for authorization purposes.

Load schema function does not use custom headers, so fetch fails with status 401 and response:
`{"errors":"[API] Invalid API key or access token (unrecognized login or wrong password)"}`

Simple request works as expected, header is used normally. Schema load fails.

**Comment by helloanoop** [comment]
@Dom4n Sorry for the late reply on this. Was tied up getting a major release out.
Please note that in the latest release, we have gone all in on filesytem based collections.

Made a demo video on the same
https://www.youtube.com/watch?v=b_ctmKlEOXg

Please let me know if this is still an issue.

**Comment by helloanoop** [comment]
The latest release also includes the response timeline viewer which should help you check if the token was being sent in the headers
![image](https://user-images.githubusercontent.com/9350733/215289854-1ca15990-2e0c-4918-aa83-b140e27f98b1.png)

**Comment by helloanoop** [comment]
@Dom4n Closing this issue, Please reopen it if you are still facing this issue.
