### ISSUE TITLE
Cannot rename items with same name when switching between cases

### ISSUE THREAD

**Issue by NooclearWessel** [usebruno/bruno#800]
Hello. I am unable to rename items to switch between case. For example, "My API Artifact" accepts the change to "My API artifact" but does not actually save it. I have to clone and rename to something else, then delete the old and replace the cloned name with what I want it to look like.

Excellent app, by-the-way. You are doing hero's work.

**Comment by NooclearWessel** [comment]
I am also on v0.27.2.
![image](https://github.com/usebruno/bruno/assets/45074696/479e0d31-6438-4098-aabb-a70f151ff4c2)

Interestingly enough, I was able to update my collection name. Even got the Toast notification. I just created a test with all words capitalized in a collection, folder, and request. My test was to try renaming the last word in each item to lower case. Only the collection was successful. And only the collection gave me the toast notification. 
![image](https://github.com/usebruno/bruno/assets/45074696/5bd2973e-a34f-4fad-aa84-fd5be8ec924e)

FWIW, I am on a Mac with Ventura 13.6

**Comment by jwetzell** [comment]
I'll check on a Mac when I get a chance.

**Comment by Its-treason** [comment]
There is already an open issue for this problem: #510 and a PR #531 to fix it.

**Comment by NooclearWessel** [comment]
Solid. Thanks for the follow-up. I searched for similar issues, but not well enough. Apparently.

**Comment by NooclearWessel** [comment]
Duplicate of 510
