### ISSUE TITLE
cli should support "--insecure"

### ISSUE THREAD

**Issue by mj-h** [usebruno/bruno#806]
In the UI, I can globally disable SSL certificate verification. This is not yet possible in the CLI

![image](https://github.com/usebruno/bruno/assets/20513065/fee13ff1-f0a9-4bc0-b80b-a09c1bb5337d)

I would love to be able to disable it with `bru run --disable`.

-----
Note: There is a workaround available:
```sh
export NODE_TLS_REJECT_UNAUTHORIZED='0'
bru run
```

Also note: There are discussions making this a collection or even a environment property: https://github.com/usebruno/bruno/issues/739#issuecomment-1777245610

**Comment by helloanoop** [comment]
@mj-h 

CLI will disable SSL validation when `--insecure` is passed.

![image](https://github.com/usebruno/bruno/assets/9350733/47c4afa9-5af0-479b-ac97-d5214a1e1a4e)

**Comment by mj-h** [comment]
Yes, of course it does, and I actually used it in the past 🤦 
I ran `bru --help` instead of `bru run --help`, and did not see the CLI options.
