### ISSUE TITLE
[Feature Request] Specify a "trusted" _server_ PEM bundle to use with TLS

### ISSUE THREAD

**Issue by JoelDSmith** [usebruno/bruno#821]
Rather than just disabling TLS certificate verification wholesale within the entire app for all collections, I'd like the ability to load a PEM bundle that contains certain trusted root certs used by the server.

_Ideally_, this could be specified per-collection, but even just being able to specify it globally would be a massive improvement over what we've currently got available.

---

EDIT: looks like someone else requesting something similar here on #1080.

**Comment by helloanoop** [comment]
This is now available in Bruno.
<img width="494" alt="image" src="https://github.com/user-attachments/assets/fa8c5ff5-dcbc-42e6-a81c-27ce81d2693b">

Closing this issue.

**Comment by JoelDSmith** [comment]
> This is now available in Bruno.
> 
> [image snip]
>
> Closing this issue.

Sweet, though is that only accepting a single server CA certificate, rather than a bundle of one or more? (The label is not pluralised...)
