### ISSUE TITLE
Hello Team I am facing following issue

### ISSUE THREAD

**Issue by arullpm06** [usebruno/bruno#835]
Error invoking remote method 'send-http-request': Error: write EPROTO 55633544:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\..\third_party\boringssl\src\ssl\tls_record.cc:242:

**Comment by Dawsson** [comment]
I had this issue when I had multiple env variables with the same name configured even if one was disabled. Just make a new env.

**Comment by sanjai0py** [comment]
Hey @arullpm06, I'm closing this issue as stale. Please open a new issue if the bug still persists.
