### ISSUE TITLE
Can't open GraphQL queries met with a white screen.

### ISSUE THREAD

**Issue by zarkroc** [usebruno/bruno#836]
I get a white screen and in developer console I see this.
Same if I try and create a new GraphQL request or import a collection from postman. But http type works fine...

framework-49f1e091cbf6b261.js:1 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fs (framework-49f1e091cbf6b261.js:1:116899)
    at d (framework-49f1e091cbf6b261.js:1:58070)
    at h (framework-49f1e091cbf6b261.js:1:59431)
    at e (framework-49f1e091cbf6b261.js:1:61492)
    at wu (framework-49f1e091cbf6b261.js:1:73208)
    at xi (framework-49f1e091cbf6b261.js:1:122261)
    at bs (framework-49f1e091cbf6b261.js:1:109370)
    at gs (framework-49f1e091cbf6b261.js:1:109298)
    at vs (framework-49f1e091cbf6b261.js:1:109161)
    at as (framework-49f1e091cbf6b261.js:1:105941)

{
    "error": {},
    "errorInfo": {
        "componentStack": "\n    at div\n    at file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:441998\n    at file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:444639\n    at div\n    at M (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at Ot (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:445800)\n    at div\n    at Xt (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/916-5dd5fda478436956.js:1:83729)\n    at div\n    at div\n    at M (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at $t (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/916-5dd5fda478436956.js:1:85187)\n    at div\n    at section\n    at section\n    at div\n    at M (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at to (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/916-5dd5fda478436956.js:1:177958)\n    at section\n    at div\n    at M (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at div\n    at Ii (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/916-5dd5fda478436956.js:1:238427)\n    at main\n    at div\n    at u\n    at div\n    at Ar (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:555572)\n    at div\n    at M (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at he (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:518218)\n    at div\n    at ge (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:519260)\n    at Te (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1087577)\n    at v (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:608097)\n    at l (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1050323)\n    at Rr (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:558663)\n    at div\n    at Pr (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:558566)\n    at r (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:480388)\n    at Ir (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:558778)\n    at r (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/main-ad5649da2d8f61d3.js:1:6769)\n    at Y (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/main-ad5649da2d8f61d3.js:1:8704)\n    at ie (file:///C:/Users/s8168f/AppData/Local/Programs/bruno/resources/app.asar/web/_next/static/chunks/main-ad5649da2d8f61d3.js:1:11344)"
    }
}

**Comment by martinsp** [comment]
I have the same issue with v1.0.0. The same collection works when I downgrade bruno to v0.27.2. This seems to indicate that a recent change from v0.27.2 to v1.0.0 causes the issue

**Comment by martinsp** [comment]
I have narrowed issue down to this commit: 834014b5d130b39d435235e28471867c12ba2198 

It looks like `@tabler/icons` does not have `IconCheckmark` as specified on this line: https://github.com/usebruno/bruno/blob/834014b5d130b39d435235e28471867c12ba2198/packages/bruno-app/src/components/RequestPane/GraphQLSchemaActions/index.js#L34

Replacing `IconCheckmark` with other icons solves the issue. Meybe it should be `IconCheck` instead?

**Comment by techinpark** [comment]
<img width="1015" alt="image" src="https://github.com/usebruno/bruno/assets/45546296/c29ff60d-47f4-42b5-88a9-f77543ced73e">

I think same issue..  (version v1.0.0)

**Comment by helloanoop** [comment]
Thanks for narrowing down the issue @martinsp !

Fixed the issue. Releasing a patch now.

**Comment by martinsp** [comment]
Thank you for the quick fix and release. The v1.0.1 is working correctly for me!

**Comment by zarkroc** [comment]
Can confirm that it works for me as well :)
