### ISSUE TITLE
JSON in the ResponsePane / QueryResult is not indented for broken APIs

### ISSUE THREAD

**Issue by Joschasa** [usebruno/bruno#837]
Some APIs return JSON payload using the Content-Type "application/html" header.

This is parsed as JSON by Bruno, but without added indentation.

Before:
![image](https://github.com/usebruno/bruno/assets/213920/4ff3206f-c668-443b-9f7d-00911353ad79)
(Headers:)
![image](https://github.com/usebruno/bruno/assets/213920/7d926f20-b1fa-4432-9ff1-ac075ef32da3)

If the JSON is parsable it should (in my opinion) be indented as well. This makes working with those broken APIs a lot easier.

**Comment by sanjai0py** [comment]
Closing this issue as your [PR](https://github.com/usebruno/bruno/pull/838) implementing the feature has already been merged and released in [v1.5.0](https://github.com/usebruno/bruno/releases/tag/v1.5.0).

Thanks for taking the time to report this suggestion and also a big thanks for the fix PR!
