### ISSUE TITLE
Save all requests feature

### ISSUE THREAD

**Issue by mustafa-ans** [usebruno/bruno#846]
I have seen this feature in the [DBeaver](https://dbeaver.io/) database tool that I use for work. So in the tool you can open multiple scripts (scripts are akin to the requests we open in Bruno) and make changes to it as needed to run the queries, but to save the changes there are two options to save these scripts, either one by one by pressing `Ctrl + s` on your keyboard or there is more efficient and faster way to save multiple scripts at once by pressing `Ctrl + Shift + s` both of these keyboard shortcuts are on windows and I have personally found the _save all_ feature to be particularly useful. Before using Bruno I was using the Insomnia API client and there was no need to actually save any requests on there unlike on Bruno where only the saved ones will have the progress saved. I wanted to propose the save all feature for all requests in Bruno as well. I can provide more details if need be, feel free to ask any questions.
Thank you for reading :)

**Comment by MaikelH** [comment]
I think the feature you are describing already has an open issue, see #737.

**Comment by Mustafa-ans** [comment]
Thank you for responding @MaikelH , I hope it gets added sometime soon, it's very handy lol

**Comment by sanjai0py** [comment]
I have marked this issue as a duplicate as it is already being tracked here: https://github.com/usebruno/bruno/issues/737
