### ISSUE TITLE
No UI feedback when moving a request between folders in a collection

### ISSUE THREAD

**Issue by glokta1** [usebruno/bruno#849]
There's no feedback to the user when dragging  a request between folders as shown above. Either a border around the destination folder or highlighting it (as VSCode does in the video below)would be appreciated

**Current Behavior**

https://github.com/usebruno/bruno/assets/71697384/a3228839-71b2-49d7-bee4-3d94db478f6f

**Expected Behavior (taken from VSCode)**

https://github.com/usebruno/bruno/assets/71697384/faa57044-8079-44cd-a949-b4092cb92327

**Comment by mikaoelitiana** [comment]
Hello all. I have created a PR to handle this small change https://github.com/usebruno/bruno/pull/863
