### ISSUE TITLE
Importing Postman collection doesn't import documentation

### ISSUE THREAD

**Issue by vboctor** [usebruno/bruno#851]
Even though the documentation exists in Postman collection export, it is not imported into Bruno.

**Comment by TheRealRyanReynolds** [comment]
Hi @vboctor - I know this is an old issue, but nonetheless updating that Bruno supports this flow and imports docs that are included in a Postman collection.

**Comment by vboctor** [comment]
Good to know @TheRealRyanReynolds - thanks for the update.
