### ISSUE TITLE
Support for path parameters

### ISSUE THREAD

**Issue by vboctor** [usebruno/bruno#852]
Postman supports ":param" in path as a first-class concept which is convenient compared to having to use pre-request variables. It is also useful when importing a Postman collection into Bruno to have support for such case.

If for some reason it is not desired to add such support, then during importing Postman collection convert ":param" to "{{param}}" and add it to the pre-request variables. Though it will be much better to support path parameters.

**Comment by Kenneth-Macharia** [comment]
Adding just this one thing, say in your next release, will make me shfit from Postman immediately

**Comment by DrGrognon** [comment]
+1

**Comment by 1Mark** [comment]
+1

**Comment by mikekosulin** [comment]
Any updates?
It’s terrible to use API tool w/o path variables.

**Comment by RemekGdansk** [comment]
Looks like there is a PR for it: <https://github.com/usebruno/bruno/pull/484>

**Comment by theMK2k** [comment]
+1 Insomnia does, too

**Comment by casperghst42** [comment]
This is right now the only thing which keeps me from switching from Postman.

**Comment by TheRealBenForce** [comment]
> This is right now the only thing which keeps me from switching from Postman.

same

**Comment by mikekosulin** [comment]
> > This is right now the only thing which keeps me from switching from Postman.
> 
> 
> 
> same

Soon:
https://github.com/usebruno/bruno/pull/484#issuecomment-2084892477

**Comment by pasalino** [comment]
same, is very useful to switch from Postman

**Comment by mikekosulin** [comment]
#484 has been merged!

Thanks, @game5413

**Comment by magnetik** [comment]
What a great news ! This was the main blocker for us to migrate to bruno. 

Looking forward for a release including this.

Good job to everyone involved! ❤️

**Comment by Kenneth-Macharia** [comment]
Can’t wait, either, super excited!On 23 May 2024, at 11:43, Baptiste Lafontaine ***@***.***> wrote:﻿
What a great news ! This was the main blocker for us to migrate to bruno.
Looking forward for a release including this.
Good job to everyone involved! ❤️

**Comment by yulin-dong** [comment]
Which release includes https://github.com/usebruno/bruno/pull/484?

**Comment by yulin-dong** [comment]
Which release has included https://github.com/usebruno/bruno/pull/484?

**Comment by helloanoop** [comment]
We merged #2357 to main today.
The main build will go out on Tuesday June 4th 2024.

Meanwhile we will also share a dedicated build later today so that community can test this and report any issues.

Thank you so much @game5413 for working on this.
Thanks @edbrannin @bsleczko @Its-treason for the reviews.
Thanks @sanjai0py @lohxt1 for getting this polished and merged.

**Comment by helloanoop** [comment]
Please test this build out and report issues if you find them: https://github.com/usebruno/bruno-nightly-builds/releases/tag/v1.19.0-31may2024

**Comment by magnetik** [comment]
I've tested it. When loading a request that have a `:param` in the URL created in the 1.18 version, the box that allows `param` to be configured is now shown.
Working fine when editing it afterwards.

**Comment by noavarice** [comment]
Will it be possible to escape colon? You can't use colons in URLs in Postman adequately bc of path parameter support. Colon is reserved symbol in URLs, so it's kind of strange to use such symbol for embedding stuff at the syntax level (at least without escaping)

**Comment by Ukrainis** [comment]
Hello to all.
Having an issue with pathParams, created a bug: https://github.com/usebruno/bruno/issues/2439 .

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/2357) by @game5413 improvised by me has been merged and released in [v1.19.0](https://github.com/usebruno/bruno/releases/tag/v1.19.0)

**Comment by Estevete** [comment]
How can I use the pathParam value in the pre-request?
