### ISSUE TITLE
[Feature Request] Any selected directory or file hide from collection

### ISSUE THREAD

**Issue by devded** [usebruno/bruno#859]
Similar to the way we use a .gitignore file to exclude specific files or directories from appearing in a commit, in the Bruno config, user can specify files or folders that should not be displayed.

OR

Hide all directories whose names begin with a period `.`

![image](https://github.com/usebruno/bruno/assets/60034035/63bd3f91-afb9-49d9-97e3-c65e33999b76)

Here I don't need this file but it always shows

**Comment by pove** [comment]
Related: #787

**Comment by sanjai0py** [comment]
Closing this as the requested feature has already been implemented and released in version 1.8.0.
