### ISSUE TITLE
Adding query parameters in the url crashes the UI

### ISSUE THREAD

**Issue by Lordi999** [usebruno/bruno#86]
Bruno Version: 0.6.1
OS: Mac OS 13.2 (M1 Pro)

When adding query parameters like '?' or '&' to the URL the UI turns totally white.
After Reloading it says, that the Collection is still open, but there is nothing visible.

Adding the query parameters in the bru file and executing it with Bruno works totally fine

**Comment by helloanoop** [comment]
Hey @Lordi999 !

This issue has been fixed in the latest version of the app.

**Comment by Lordi999** [comment]
Oh. Thx :D
*quickly updating*

**Comment by helloanoop** [comment]
Hey @Lordi999 

We just released v0.9.0
We have simplified the language greatly. Checkout the [docs](https://docs.usebruno.com/bru-language-design.html)

After downloading, and opening an api collection repo, it will automatically take care of converting the old format to new format.

Let me know if you face any issues, happy to help.
