### ISSUE TITLE
Import Collection: Postman collection imported but requests are not shown

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#88]
Import the postman collection and check all the requests display properly in the collections 
Actual issue: Collection imported but no request found in it 

V0.9.2

![image](https://user-images.githubusercontent.com/44080743/218086746-e7542887-ea95-4dec-89e1-11dc7a3f87af.png)

**Comment by helloanoop** [comment]
@sseenivasan89 

I have released v0.9.3 for Windows.
Can you please reinstall and check if this fixes your issue ?

**Comment by sseenivasan89** [comment]
@helloanoop - it's working fine now
