### ISSUE TITLE
Orange dot in request tab doesn't always go away on save

### ISSUE THREAD

**Issue by RobCupples** [usebruno/bruno#882]
Bruno v1.1.0
OS: Windows 10 Enterprise

While editing my request bodies I frequently use Ctrl+s to save.  Usually this makes the orange dot on the request's tab on the top of the screen go away but sometimes it stops working .  I will use Ctrl+s, I will get the brief message at the top indicating that the request saved successfully but then the orange dot is still there.  I can close the tab and reopen it and the orange dot will still be there.  It will go away if I restart Bruno.

It seems to be a repro if I open the request, add a single character and then change my mind and delete that character and then try to save.  At that point I am back to the original request I opened but the orange dot appeared and I instinctively Ctrl+s to make the orange dot go away.

A workaround is to add 1 extra character, Ctrl+s, delete the extra character, Ctrl+s.

**Comment by sanjai0py** [comment]
Closing this issue as it has been tracked here https://github.com/usebruno/bruno/issues/1491
