### ISSUE TITLE
[Bug] Graph QL variable replacement leads to exception

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [usebruno/bruno#884]
It looks like the variable replacement is not working in all cases:

<img width="1301" alt="Screenshot 2023-11-04 at 06 38 02" src="https://github.com/usebruno/bruno/assets/1157580/8da86635-ed65-4a23-b279-3d8c1eca728c">

```
{
    "id": {{UNSUBSCRIBABLE_WIDGET_ID}}
}
```

leads then to an invalid json, I guess because it come out as 
```
{
    "id": 
}
```

If I try 
```
{
    "id": "{{UNSUBSCRIBABLE_WIDGET_ID}}"
}
```
it is properly replaced, but the graphQl api rightfully rejects it then, because the field is Int! not String!

This is unexpected and a bug.

**Comment by Andreas-Schoenefeldt** [comment]
It works if I use it in the query:

```
query widgetQuery {
    widget(id: {{UNSUBSCRIBABLE_WIDGET_ID}}) {
      ...WidgetFragment
    }
}
```

still, both should be possible.

**Comment by Andreas-Schoenefeldt** [comment]
@helloanoop, I think this would be a good way to go: https://github.com/usebruno/bruno/pull/887 

I would consider this a mayor issue and would be greatfull, if it could be part of the next release. 

Thx a lot for this excellent tool!
Andreas

**Comment by aliasgar55** [comment]
Hi @Andreas-Schoenefeldt 

The bug also happens for http-request if the body contains a variable, the json is not parsed correctly
instead if we can move the json parsing all together after the interpolation would make the code consistent for all the graphql and http-request
Please share your thoughts @helloanoop

**Comment by Andreas-Schoenefeldt** [comment]
@aliasgar55 that would absolutely make sense 👍

**Comment by Andreas-Schoenefeldt** [comment]
I found one additional issue. `{{UNSUBSCRIBABLE_WIDGET_ID}}` in here is not replaced at all:

```json
{
    "filter": "{\"andX\":[{\"andX\":[{\"eq\":{\"parentType\":\"widget\"}},{\"eq\":{\"parentId\":{{UNSUBSCRIBABLE_WIDGET_ID}}}}]},{\"orX\":[{\"like\":{\"data\":\"%\\\"country\\\":\\\"INT\\\"%\"}},{\"like\":{\"data\":\"%\\\"country\\\":\\\"DE\\\"%\"}}]}]}",
    "limit": 10,
    "offset": 0
}
```

**Comment by Andreas-Schoenefeldt** [comment]
Ok, the last comment can be solved by adding a space: 
```
{
    "filter": "{\"andX\":[{\"andX\":[{\"eq\":{\"parentType\":\"widget\"}},{\"eq\":{\"parentId\":{{UNSUBSCRIBABLE_WIDGET_ID}} }}]},{\"orX\":[{\"like\":{\"data\":\"%\\\"country\\\":\\\"INT\\\"%\"}},{\"like\":{\"data\":\"%\\\"country\\\":\\\"DE\\\"%\"}}]}]}",
    "limit": 10,
    "offset": 0
}
```

This appears to be an issue of handlebar.js - @helloanoop I don't think it is as critical as the original issue here, but we might consider replacing handlebar by a "simple" selfmade regex.
