### ISSUE TITLE
[bug] javascript exception in collection run leads to endless loop

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [usebruno/bruno#886]
If one of the test in a collection throws an exception during the collection run, the run never stops and can not be closed manuallz anymore. The only solution is to restart bruno at the moment.

It never stops, because of an exception thrown in the current test:
<img width="662" alt="Screenshot 2023-11-04 at 18 29 40" src="https://github.com/usebruno/bruno/assets/1157580/357e8b70-4afd-479c-9826-32c96c34b622">

**Comment by sanjai0py** [comment]
Closing this issue as it couldn't be reproduced. Please open a new issue if it still persists.
