### ISSUE TITLE
[bug] Decomment dosent work if varibles are used in http-request body

### ISSUE THREAD

**Issue by aliasgar55** [usebruno/bruno#888]
Decomment does not work if there are variables present in the request body of a http-request
Example: 
```json
//test
{
 "name": "{{name}}"
}
```
would result in server receiving ```"//test\n{\n  \"name\": bruno\n}"```

if there are no variables in the request body then the comments are removed and server receives correctly parsed JSON

**Comment by asonkeri** [comment]
The example in the issue description does not send the comments anymore, but the issue still occurs when the variable in the request body is not quoted.

With quotes:
![image](https://github.com/usebruno/bruno/assets/19153764/d026053b-0b52-46b3-aea8-f06ee04ae421)

Without quotes:
![image](https://github.com/usebruno/bruno/assets/19153764/d79237cf-8b96-456f-b292-be7dd7e75d22)

Vars:
![image](https://github.com/usebruno/bruno/assets/19153764/0f04b1dd-31bc-419c-812b-9e5eb599c491)

**Comment by helloanoop** [comment]
I have merged the PR for the fix.
This is set to go out in the upcoming `v1.20.0` release
