### ISSUE TITLE
Request Creation: Not able to create the request in collection

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#89]
When i try to create the request inside the collection getting the below error saying the request is already available 
but actually, this is the first time I tried to add the request 

![image](https://user-images.githubusercontent.com/44080743/218088382-1e817052-8783-4aaf-bf94-2322fe81a4df.png)

**Comment by helloanoop** [comment]
Looks like we have an issue in Windows. Can you confirm your OS and which version you are using ?

**Comment by sseenivasan89** [comment]
Hi @helloanoop 

Yes it windows machine

**Comment by helloanoop** [comment]
@sseenivasan89 

I was able to reproduce your issue on windows. Will release a fix for this tonight. Please standby.

**Comment by helloanoop** [comment]
@sseenivasan89 Thank you so much 🙏 for submitting this issue.
There was some filename related issues for windows which has been fixed.

I have release v0.9.3
Can you please reinstall and check if this fixes your issue ?

**Comment by sseenivasan89** [comment]
@helloanoop - its working fine now

**Comment by helloanoop** [comment]
Awesome, Thanks @sseenivasan89 !
