### ISSUE TITLE
Publish package for Gentoo Linux

### ISSUE THREAD

**Issue by martin-kokos** [usebruno/bruno#895]
I've prepared packaging for Bruno in the GURU portage repository which is available to Gentoo Linux users.

https://github.com/gentoo/guru/pull/116

**Comment by martin-kokos** [comment]
ping

**Comment by helloanoop** [comment]
Hey @martin-kokos 

Just took a quick look at the PR. Looks good.
Can you also add me as a co-maintainer ? 

My info
```
<maintainer type="person">
    <email>anoop.md1421@gmail.com</email>
    <name>Anoop M D</name>
</maintainer>
```

**Comment by helloanoop** [comment]
@martin-kokos Please also update the Mainfest file to point to the latest version

**Comment by martin-kokos** [comment]
Updated GURU PR to 1.6.1 and included you as a maintainer. Please register in bugzilla and set email in order to receive bug notifications: https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors

**Comment by martin-kokos** [comment]
Updated version to 1.9.0
Merged
https://github.com/gentoo/guru/commit/f279ba4ae27f3f637cc8e3dd8a71e25fd652bf6d
