### ISSUE TITLE
Not able to make any request using Bruno

### ISSUE THREAD

**Issue by tushar5526** [usebruno/bruno#897]
Each API call, resolves to 
```
Error invoking remote method 'send-http-request': Error: header name must be a non-empty string
```

To reproduce. 

Create a GET request to any URL, and hit send.

**Comment by Its-treason** [comment]
Hey @tushar5526, you probably have an empty header in the headers list of your request/collection. Removing empty headers should fix this.

But this is not really intuitive, we should look into improving the UX here.

**Comment by tushar5526** [comment]
Hi @Its-treason, I read the error and tried debugging it. I am pretty sure there were no empty headers and I even tried importing working CURLs from the browser, postman etc. every request popped this error. However, I just restarted Bruno to share some screenshots and it seems to work fine. 

I am not sure why it was behaving that way earlier, but a restart fixed it.
