### ISSUE TITLE
[feature request] Persist the state of the app

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [usebruno/bruno#899]
Currently the ui state of the app is lost on restart. It's not a big deal but would improve user experience, especially if one has a lot of collections:

* persist the state of opened folders
* persist the selected environment for every collection
* persist the opened tabs

**Comment by martinsefcik** [comment]
Similar to #565

**Comment by Andreas-Schoenefeldt** [comment]
Jep, kind of + selected environment for every collection

**Comment by Andreas-Schoenefeldt** [comment]
I'll leave it open and see how #565 develops.

**Comment by sanjai0py** [comment]
Closing this as a duplicate of https://github.com/usebruno/bruno/issues/565
