### ISSUE TITLE
[bug] main content is too big

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [usebruno/bruno#900]
Steps to reproduce:

* open bruno
* open any request
* **Issue:** The collection select is hidden and there is an unnecessary/annoying scrollbar on the right

<img width="1303" alt="Screenshot 2023-11-06 at 10 28 23" src="https://github.com/usebruno/bruno/assets/1157580/8f96fcce-8071-47b6-855e-a85d9fbdaed4">

* **Expected:** No content overflow on the main content

**Comment by martinsefcik** [comment]
I should be fixed by #755

**Comment by Andreas-Schoenefeldt** [comment]
Awesome!

**Comment by martinsefcik** [comment]
@Andreas-Schoenefeldt Probably you should leave this ticket open until this PR is merged and problem definitely resolved.

**Comment by Andreas-Schoenefeldt** [comment]
also true, I'll double check, once a new version is out 👍

**Comment by vayalildanie** [comment]
I believe this was fixed by #1058?

**Comment by vayalildanie** [comment]
@sanjai0py or @Andreas-Schoenefeldt, LGTM in newest version now, close pending

**Comment by anusree-bruno** [comment]
Closing this as this is has been fixed
