### ISSUE TITLE
Unwanted field appears in the headers

### ISSUE THREAD

**Issue by jeanchristopheMICHEL** [usebruno/bruno#901]
When I create a new simple GET request, without body and without any field in header, the request sending add "Content-Type: application/json".
You can do that, by creating a request and use "generate code" (with any format you want).

Thanks,

**Comment by helloanoop** [comment]
Agreed, We need to fix the `Code Generator` not to add additional headers.

**Comment by martinsefcik** [comment]
@helloanoop I guess this issue was fixed by #938 and can be closed.

**Comment by anusreesubash** [comment]
Closing this issue as this has been fixed. Please reopen if the issue persists.
