### ISSUE TITLE
[Feature-Request] request-level environment variables

### ISSUE THREAD

**Issue by lrotermund** [usebruno/bruno#902]
Hi, is it possible to specify variables for the URL at the level of a request environment? We would like to start using Bruno in the team, if we customize IDs in REST URIs, which is the rule, then they should not be updated in the `.bru`, but rather be quickly replaceable as request-level environment variables.

Sorry if this already exists in the documentation or as an issue, I searched both for a long time but found nothing specific.

**Edit**, 2023-11-10:
As I haven't heard anything about this, I assume it doesn't exist yet, so I've turned it into a feature request.

What does not work at the moment?
=> Quick and easy management of environment variables at the request level, without writing them to a `.bru` file.

How might this feature be implemented?
- Handle request level environment variables like normal variables, i.e. simply using {{var_name}}
- Request-level environment variables **override** global variables.
- They could be placed in the Vars tab like pre- and post-request variables.
- Unlike pre- and post-request variables, they are not synchronised in the `.bru` file, but behave like global **secret environment variables**. 

Unfortunately I only have a basic knowledge of Electron, I work more in the Go & PHP backend. If I have the time, I can try to submit a merge request, but I doubt it will be implemented correctly or "nicely". Maybe someone else here has more skills than me.

Here is a screenshot that perhaps shows better what I mean by the request-level environment variable:

![bruno_req_level_environment_var](https://github.com/usebruno/bruno/assets/22943809/23374d01-ce01-4f43-8bd4-e26e4e6f2f9d)

**Comment by David-Lannion** [comment]
This issue seems quite related with #292

**Comment by helloanoop** [comment]
[Request Variables](https://docs.usebruno.com/get-started/variables/request-variables) implementation has been updated in Bruno.

They are scoped to be access only within the context of the specific request.

When a variable is accessed, the following precedence is used to determine which value is used:
* Collection Variables
* Environment Variables
* Folder Variables
* Request Variables
* Runtime Variables

Runtime variables get the highest precedence.

We’re closing this issue, but feel free to reopen it if you have further feedback on this behavior.

**Comment by lrotermund** [comment]
I just downloaded the update and reviewed the implementation. It's not what I had in mind when I submitted the feature request. **_Of course, I understand that you can't take that into account._** Unfortunately, though, it's still impractical for my daily work; nothing has changed.

**Comment by anusree-bruno** [comment]
@lrotermund
Would you be able to share more details about your specific use case that's currently not supported?

**Comment by lrotermund** [comment]
Of course! The biggest problem our team has is that we have a shared request collection via Git. As you know, requests often have dynamic values that need to be transported via the URL without changing the actual request.

There are variables for that case: `{{some_url}}/some-api/{{some_number}}`

We as a team understand `{{some_url}}` as a classic environment variable and manage it as such.

On the other hand, `{{some_number}}` is not. We set this specifically for each request, and its value can change six times in a row. If we use classic pre-request variables, which continuously change with the request, then we have to remember to close the request without saving or clean up all the requests with changed values from the registered pre-request variables before committing.

It would be nice to have either a checkbox on the pre-request variables that saves the variable but not its value in the file or a separate block with only request-related environment variables. We would also be okay with a global setting, which guarantees that any changes to the values of pre-request variables are never stored as changes to the request. In that case, there would be no need for a checkbox.

Here are a few more screenshots of the problem:

The following screenshot shows the initial state: a "freshly" checked-out request collection with a prepared request, a maintained test environment, and an **empty pre-request variable**, product_number.

<img width="2060" height="681" alt="Image" src="https://github.com/user-attachments/assets/1baffb38-2200-4b2e-96b3-5bf25c9a9de0" />

The following screenshot shows a pre-request variable that has been set and unfortunately marks the request as changed.

<img width="1955" height="695" alt="Image" src="https://github.com/user-attachments/assets/158721ac-3c7d-4d29-a6f8-1a92de609f01" />

As you can see in the last screenshot, this was accidentally saved, even though the developer only intended to add a header to the request for all other developers. Now, he must either remember to clean up the pre-request variables before saving or remove them before committing. This creates unnecessary extra work for us, which would not be the case if changes to pre-request variables did not result in a change and were not saved.

<img width="2104" height="650" alt="Image" src="https://github.com/user-attachments/assets/b97982ac-10fb-4542-b6c2-39b7f4fef382" />

There is already a solution for this, but it is unusable. We could create an environment variable and mark it as secret; then, its value would not be committed. However, since these values change frequently during the work process and are only valid per request, this is not a practical solution via the modal menu.

**Comment by anusree-bruno** [comment]
I think the request here is similar to https://github.com/usebruno/bruno/issues/5039, can you take a look?

**Comment by anusree-bruno** [comment]
Also, thanks for the thorough explanation!

**Comment by lrotermund** [comment]
Yes, I think the problem is the same as in the referenced issue.

**Comment by helloanoop** [comment]
@lrotermund I'm fairly positive that we will be able to add support for this. We'll continue the conversation in #5039
