### ISSUE TITLE
Feature Request: close Tabs on 3rd Mouse Button Click

### ISSUE THREAD

**Issue by ravermeister** [usebruno/bruno#908]
Hi, 
I'm very used to close browser tabs via 3rd Mouse Button. 
It would be great if bruno would support that as well.

**Comment by Its-treason** [comment]
We already have a PR https://github.com/usebruno/bruno/pull/586 and another issue open for this: https://github.com/usebruno/bruno/issues/485.

**Comment by ravermeister** [comment]
Cool!
