### ISSUE TITLE
Some of the editors make the layout scrollable and it's not needed

### ISSUE THREAD

**Issue by LeonardoMussato** [usebruno/bruno#911]
I noticed that on the JSON editor when it opens it shifts the layout and the entire page becomes scrollable. This is caused by defined values similar to calc(100vh - 22px) and not using only height: 100% and display flex. I already created a pull request to fix this issue.

**Comment by martinsefcik** [comment]
Probably it will be also resolved by PR #755 which handles more related issues with scrolling.

**Comment by vayalildanie** [comment]
since #912 was closed this also should be as per: https://github.com/usebruno/bruno/pull/912#issuecomment-2268946402 probably

**Comment by sanjai0py** [comment]
The issue is now closed as completed. Please make sure to use the [v1.25.0](https://github.com/usebruno/bruno/releases/tag/v1.25.0) version of Bruno.
