### ISSUE TITLE
italian translation

### ISSUE THREAD

**Issue by rickyl3aks** [usebruno/bruno#917]
ive added an italian translation for readME and contributing, added a link in the readME to go to the italian translate file

**Comment by rickyl3aks** [comment]
id like to add a publishing translate as well, in a separate folder alongside the English version as for the moment only available in English

**Comment by Efois** [comment]
> id like to add a publishing translate as well, in a separate folder alongside the English version as for the moment only available in English

Could I join you in doing this?
Which platform are you using to translating it in italian?

**Comment by rickyl3aks** [comment]
yeah sure! for the most part i translate it myself, but i suggest to use "reverso" for a better translation, just make sure you review the text afterwards!

**Comment by rickyl3aks** [comment]
> > id like to add a publishing translate as well, in a separate folder alongside the English version as for the moment only available in English
> 
> Could I join you in doing this? Which platform are you using to translating it in italian?

yeah sure! for the most part i translate it myself, but i suggest to use "reverso" for a better translation, just make sure you review the text afterwards!

**Comment by sanjai0py** [comment]
Hey @rickyl3aks, thanks for your work on the Italian translation. Grazie mille! The [PR](https://github.com/usebruno/bruno/pull/916) including the Italian translation has already been merged into Bruno and released in [v1.2.0](https://github.com/usebruno/bruno/releases/tag/v1.2.0).

Closing this!
