### ISSUE TITLE
Sub menus have empty rows which has clickable action

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#92]
1. Open the application
2. Click on the top menu on _View_ tab 
3. There are some empty rows which has clickable action

![image](https://user-images.githubusercontent.com/44080743/218440949-6b2cc064-e415-4886-addd-999254ac0560.png)

**Comment by helloanoop** [comment]
Woaah @sseenivasan89 !
You are a rockstar QA.

Will have these fixed in our upcoming release.

**Comment by helloanoop** [comment]
@sseenivasan89 

I have fixed this in the latest v0.9.4 release

Please install the latest release and let me know if the issue still persists.
