### ISSUE TITLE
Cannot apply global Settings. 

### ISSUE THREAD

**Issue by dark-squirrel** [usebruno/bruno#921]
I have a problem with confirming the global settings. I wanted to add a proxy (global). So I added the specific settings and pressed save. But all my collections did not use this proxy and ignored it. But when I use the settings for a single collection, it works. But there is no field for SSL/ TLS certification validation there. So my problem is that the global settings are not applied. Has anyone had the same problem? Is this a bug? I am using the Windows version and have tested version 1.1.0.

**Comment by mirkogolze** [comment]
For me it is working. I tried out different combinations between global and collection level proxy. All settings are applied and used as configured.  In Release 1.1.1 nothing at this part was changed. But you could try to update to this version.

**Comment by mirkogolze** [comment]
I think your are right. When 'global' is not set on collection level, as default nothing is set on collection level, then the global proxy is not taken. We have to change the order. First take the global config and then check if anything is set on collection level.

FYI: @helloanoop

**Comment by martinsefcik** [comment]
@mirkogolze @helloanoop 
I think this issue was fixed by PR #951 and should be closed
