### ISSUE TITLE
Application crash when we click the delete button on query param

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#93]
1. Open the application
2. Open the request tab
3. Go to _Params_ tab and click on _delete_ button
4. Now the application crashed and turned the application like below

OS: Windows 
Version: V 0.9.3

![image](https://user-images.githubusercontent.com/44080743/218444956-9339b832-e006-4bc6-a48d-15db422e8563.png)

![image](https://user-images.githubusercontent.com/44080743/218444983-a55d42eb-7189-4a5c-9d80-e38e81222c77.png)

**Comment by helloanoop** [comment]
Good one! @sseenivasan89 

Will have this fixed in our upcoming release.

Thanks for your effort in finding and filing these bugs!

**Comment by helloanoop** [comment]
@sseenivasan89 This has been fixed in v0.10.0
Please test it when your have some time.
