### ISSUE TITLE
Allow variable names to begin with a digit

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#931]
### Background
Recently we enforced strict validation on variable names in https://github.com/usebruno/bruno/issues/682

Rules
* A variable name must start with a letter or _
* A variable name cannot start with a digit
* A variable name can only contain alpha-numeric characters, `_` or `-`

The reasoning was
* In the future, we want to support special variables `$` Ex: `$randomName`, `$randomEmail` etc. So enforcing some strictness early on made sense
* Its also good to nudge users to adhere to Javsacript variable naming rules since Bruno has powerful scripting capabilities

### Problem Description
Some of users would still like the option to allow a variable name with a digit.

### Solution
I don't think we should change our strict validation since this might only be needed for a smaller audience.
And as a project, we also don't want to take a hard stance on variable naming strictness. I would like us to be flexible and allow overrides on the default behaviour.

I am thinking of supporting an additional config in `bruno.json`
```json
{
  "overrides": {
    "allowVarNameToStartWithDigit": true
  }
}
```

Looking for feedback.

cc @Its-treason @martinsefcik @mirkogolze

**Comment by martinsefcik** [comment]
I really would like to hear what exactly is behind that request. Why they cannot just use for example underscore at the beginning of variable name in such cases , e.g. `_8blabla`.

If you allow variable names to start with number and minimal length is 1 character then they create variable with name `1`. In case such variable has value `10` what is then the result of 1 + 5 ? 6 or 15 ? You know where I am heading. It is confusing. And I think this is the reason why it is not allowed in many (if not in all) programing languages. So I personally would be strict and I would not allow it.

And introducing any new flag which will override default behavior makes your source code complexity higher and it means it is more error prone. So I would always think twice before introducing such flag. I think in this case benefit of such flag is low and I would not introduce it.

BUT for example Postman allows variable to start with number. They even allow override predefined variables. E.g. I can create new variable with name `$timestamp` which normally (if not manually defined) returns current Unix timestamp. 

So really I don't know now what direction would be the best.

**Comment by helloanoop** [comment]
Yeah,

A lot of users who come from postman world are used to not having strictness around variable naming, and makes it hard for them to migrate. (#964 by @ljohnston and #345 by @haneev) 

I think we should keep the strictness, and optionally allow the users to override the variable naming strictness altogether via a config override. Folks who have big collections with a lot of env variables use dot `.` as a delimiter - `url.webService`, `url.paymentService`, `password.admin`, `password.user` etc

**Comment by helloanoop** [comment]
Given the huge number of users facing issues, I have relaxed the strictness

* Variables can begin with digits
* `.` is allowed in variable names
