### ISSUE TITLE
[Bug] Variable not showing if it has a leading or trailing white space

### ISSUE THREAD

**Issue by giuliano-macedo** [usebruno/bruno#936]
when having spaces in the left or right of a variable inside the `{{ }}` syntax bruno does not find the variable that is defined in the environment, example:
![image](https://github.com/usebruno/bruno/assets/13181797/130a9ea0-16ea-43ce-b25b-21fbe84286b0)

**Comment by helloanoop** [comment]
For now, we'd like to maintain strict interpolation logic. We may revisit this in the future if there’s broader community interest or a compelling reason to trim the variable.
