### ISSUE TITLE
Collection disappears when we reload the application

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#94]
1. Open the application
2. Make sure you have some collection available in the application
3. Go to _View_ menu on the top and click on the Reload option in sub menu
4. Now the _collection_ is disappeared in the left side 

OS : Windows
Version : 0.9.3

https://user-images.githubusercontent.com/44080743/218458652-69b01659-5647-4cbd-86e5-ee6742731d09.mp4

**Comment by helloanoop** [comment]
Thanks for reporting this @sseenivasan89 

Actually, at this point, we don't want to support reload.
Reloading will need us to do the save the entire state of the app in local storage and rehydrate it upon reload.

For now, I will disable reload option, and we can think about supporting this feature at a later point.
I will have this done in our upcoming release in a couple of days.

**Comment by helloanoop** [comment]
@sseenivasan89 

I have disabled the reload option in the latest v0.9.4 release
You should no longer see the reload button.

Please install the latest release and let me know if the issue still persists.
