### ISSUE TITLE
Request opening unexpectedly in the UI

### ISSUE THREAD

**Issue by bzh4bzh** [usebruno/bruno#941]
Currently I have 1 collection with subfolders so I can share external JavaScript libraries along all my requests. With this setup, any time I expand/collapse a folder or the collection or run a folder or the collection, the very last request opens in the main window & showed the last run result. Ideally it shouldn't open at all.

**Comment by sanjai0py** [comment]
Closing this issue as it could not be recreated in the latest version of Bruno [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0).

Please open a new issue if the bug persists.
