### ISSUE TITLE
[User Experience] Add "Generate Code" Button

### ISSUE THREAD

**Issue by giuseppemilicia** [usebruno/bruno#945]
I would like to propose an enhancement to improve the user experience of the "Generate Code" function. Currently, the process involves navigating to a separate section to generate code. To streamline this process, I suggest adding a "Generate Code" button directly within the open request view, perhaps positioned to the left of the existing "Save" button.

**Comment by eshan-one** [comment]
hey @giuseppemilicia  can I work on this issue?

**Comment by sanjai0py** [comment]
Closing this issue as the requested generate code button is already present in the request bar. 

<img width="187" alt="image of generate code button in request panel" src="https://github.com/usebruno/bruno/assets/84461672/47281b9d-4374-4367-b7c6-e1d84eea8a82">
