### ISSUE TITLE
Connexion to localhost without http specified

### ISSUE THREAD

**Issue by yorffuoj** [usebruno/bruno#946]
Hello,
I'm trying Bruno v1.1.1 and I found out that specifying `http://` is mandatory. I wanted to know if this was intended because it is no mandatory in postman or insomnia.
I created simple API to try Bruno that I run locally on the port 8080 and here is what I get:

- `GET http://localhost:8080/` works fine
- `GET http://127.0.0.1:8080/` works fine
- `GET localhost:8080/` throws an error: Error invoking remote method 'send-http-request': AxiosError: Unsupported protocol localhost:
- `GET 127.0.0.1:8080/` throws an error: Error invoking remote method 'send-http-request': Error: connect ECONNREFUSED 127.0.0.1:80

Thanks for your work anyway, this is a really cool software

**Comment by martinsefcik** [comment]
It looks like Postman is prepending `http://` in case the protocol is not provided and it does not matter if hostname is localhost or any other.

**Comment by yorffuoj** [comment]
Indeed. Wouldn't it be a nice feature to add to bruno? It happens quite often that I'm too lazy or forget to write that `http://`.

**Comment by sushmithasv** [comment]
How to use inherit auth from parent in buron, I tried Basic Auth and Digest auth , getting below error
{
  "errors": [
    {
      "code": "Global.Internal.Error",
      "description": "Unspecified Error on the system which prevented execution.",
      "message": "The requested version is not supported."
    }
  ]
}
