### ISSUE TITLE
[Postman] - Import Multipart Collection

### ISSUE THREAD

**Issue by ymeunier** [usebruno/bruno#948]
Hi, 
When we import our collection, we've lost all multipart configuration.

When importing, my mulitpart fields are stored by Bruno in  this format
```
body:form-urlencoded {
  document: json_data
  file: undefined
}
```

when I'm create multipart fields they are store in this format :
```
body:multipart-form {
  document: json_data
  file: undefined
}
```
Could you correct the import ?
Best Regards,
Yann

**Comment by sanjai0py** [comment]
Closing this issue as it could not be recreated in the latest version of Bruno [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0)
