### ISSUE TITLE
Collection Runner is not working

### ISSUE THREAD

**Issue by sseenivasan89** [usebruno/bruno#95]
1. Create some collection
2. Run the collection using runner option
3. The collection is not running

check the recorded video

https://user-images.githubusercontent.com/44080743/218461475-c711d66c-39e5-4b56-8a7e-00a69832913c.mp4

**Comment by helloanoop** [comment]
Nice catch @sseenivasan89 !
Thanks for taking the time to record and file the bug.

Will have this fixed in our upcoming release in a couple days.

**Comment by helloanoop** [comment]
@sseenivasan89 This issue has been fixed in `v0.16.0` 🎉
