### ISSUE TITLE
[Bug] Application crash when attempting to configure env variables after setting a digit

### ISSUE THREAD

**Issue by Josh-V-PAL** [usebruno/bruno#950]
Create an environment variable, can be secret or non secret. 
In the scripting tab, set the value to a non string digit and run the request.
`bru.setEnvVar("secret_variable", 10)`

Click on the environment configuration button and the app will crash to a white screen with the below error.
<img width="470" alt="image" src="https://github.com/usebruno/bruno/assets/142516326/1de8a53b-5dcd-4a64-92cc-315952ecb31c">

**Comment by Josh-V-PAL** [comment]
Didn't see this already exists:
https://github.com/usebruno/bruno/issues/847

**Comment by Andr444777** [comment]
![image](https://github.com/usebruno/bruno/assets/99760119/8e7ff438-1f62-4715-9269-6fa743f9d99a)

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/1285) fixing the bug has already been merged and released in [v1.6.0](https://github.com/usebruno/bruno/releases/tag/v1.6.0)
