### ISSUE TITLE
Large Postman Imports are Incomplete

### ISSUE THREAD

**Issue by solsticesurfer** [usebruno/bruno#955]
### What I was trying to do
Import a large Postman collection into Bruno

### What was supposed to happen
All folders and requests should have been imported

### What happened
Out of 24 folders and 191 requests, only 21 folders and 169 requests were imported. No errors were reported to indicate that the full collection could not be imported. Import file size was ~200KB

The failure was caused by two folders that have the same name at the same folder level in Postman. Postman stores collections as data, whereas Bruno stores collections as a file structure. Since you cannot have two folders at the same directory level with the same name, the import of that second folder fails. However, this is done without any notification to the user.

There should be a check during the import of a folder to ensure that the folder does not exist. If it does, either notify the user or, possibly better, add a number to the end of the folder so that the import can be successfully continued. The user should be notified of this so that they can then go in and clean up the second folder as needed.

**Comment by gonzark** [comment]
Facing the same issues. 

I want to import a Postman collection that has 3 folders in it: 

- V1
- V2
- V3

I'm only seeing the V1 folder after importing it into Bruno

Thanks!

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/993) fixing the bug had already been merged and released in [v1.3.0](https://github.com/usebruno/bruno/releases/tag/v1.3.0)
