### ISSUE TITLE
[Bug] Collection environment not saving properlly

### ISSUE THREAD

**Issue by AffDNeto** [usebruno/bruno#958]
Version: 1.1.1
Problem:
Environment is not saved, and no error is shown on the UI, when at least one the secrets are empty.

How to reproduce:
Create an environment on a collection with one variable marked as secret and the field value is empty. Clicking on the save button does nothing.

Expected behavior:
Environment is saved with empty values or an message is shown with the reason it was not saved.

**Comment by sobelek** [comment]
Hey. I would love to tackle the issue.

Can some maintainer chime in with how we would like to handle it? I think it's reasonable to save empty value if user requests it.

**Comment by timo-abele** [comment]
I cannot quite reproduce it. Here is what I did:
OS: Windows 10
Method of installation: bruno_1.1.1_x64_win.exe

1. remove all collections in existing Bruno installation
2. remove existing Bruno installation
3. install Bruno version 1.1.1
4. open Bruno
5. click on `+ Create Collection`
    1. Name: bruno_reproduce
    2. Location: an empty folder bruno_experiments
    3. Folder Name: bruno_reproduce
6. create new request
    1. Name: myrequest
    2. URL: GET + google.com
7. "No Environment" -> Configure -> create environment
    1. Environment Name: testenv
8. click `+ Add Variable`
    1. Name: "test"
    2. Value: <skip>
    3. Secret: selected
9. click on the dark blue `Save` button

`Changes saved successfully` appears. 

But I do have problems editing an environment with dashes in the variable names in a collection that has created with Bruno `0.27.0` .... I'm not sure if I have the same or a separate issue.

@AffDNeto can you please check again whether you get the issue if you create everything anew and without dashes?

**Comment by AffDNeto** [comment]
OS: Mac OS
Hi @timo-abele , after some more testing and checking the issues linked the issues seems to be the same as 920.
Just one addition to it, similar to #920. If I save the secret variable as empty and open again saving does nothing, not even show that there is no changes.

I downloaded the newest version 1.2.0 and the issue was fixed.

Will close this issue.
