### ISSUE TITLE
Getting 'Error invoking remote method 'send-http-request': SyntaxError: Unexpected token '{' while using script:post-response in Bruno under Script tab.

### ISSUE THREAD

**Issue by cyrilgeorge153** [usebruno/bruno#959]
This error is happening while using script:post-response. No issues found while using collection variable. 
Bruno version: v0.27.2
![Bruno Github Error Post Response](https://github.com/usebruno/bruno/assets/52770689/f20853d0-e3de-4df8-a23c-f69d34cc673e)

**Comment by n00o** [comment]
Try removing the `script:post response {}` part of the script and make it something like this:
```JavaScript
bru.setVar("tokenValue",res.body.token)
```
You may have manually edited the `.bru` file without noticing that you added script:post-response twice. In the UI, all the code should be written in JavaScript.

**Comment by cyrilgeorge153** [comment]
@n00o  Thanks for the help. Issue is solved.
