### ISSUE TITLE
Creating PATCH request doesn't create in Bruno application but .bru file is created in the folder

### ISSUE THREAD

**Issue by barathrajramachandran** [usebruno/bruno#96]
The version used: v0.9.1

**Steps to replicate:**

- Create a local collection and choose a folder
- Create a New Http request, fill in the name and URL, select the method as PATCH
- Click on "Create"
- The request doesn't appear in Bruno application but navigate to the selected folder, .bru file would have been created.

**Comment by helloanoop** [comment]
@barathrajramachandran 
I have fixed this in the latest v0.9.4 release

Please install the latest release and let me know if the issue still persists.

**Comment by barathrajramachandran** [comment]
@helloanoop I tested it and it works fine now. This ticket can be closed now. Thank you for the update and fix.
