### ISSUE TITLE
[Bug] Cannot override Collection Basic Auth with request specific Bearer Token

### ISSUE THREAD

**Issue by kpau** [usebruno/bruno#960]
I have a collection with Auth set to `Basic Auth`:
![image](https://github.com/usebruno/bruno/assets/1583751/7a5d80e2-5422-4a81-aea6-c22250188885)

In the collection there is a GET Request, which has a `Bearer Token` auth:
![image](https://github.com/usebruno/bruno/assets/1583751/0ac41898-299c-41b5-b69e-84f3e7911519)

When I execute the request and observe the "Timeline" tab on the right, I see that it still uses the `Basic Auth` credentials:
![image](https://github.com/usebruno/bruno/assets/1583751/2e446ab7-11b0-4a73-a755-3aaa48f10d17)

I would expect that it will use the `Bearer Token` Auth specified in the request.

If I disable the Collection Auth (set it to `No Auth`), then the request correctly uses the `Bearer Token` auth:
![image](https://github.com/usebruno/bruno/assets/1583751/403d6889-2ca6-46cd-8bae-e915b9cc5ecb)

I am using Bruno v1.1.1

**Comment by n00o** [comment]
You can fix this by using the Collection's **Headers** tab and add a `Authorization` header and make the value:
`Bearer {{accessToken}}`

Then every request inside of this collection will use that same header for its authentication. This is not the most ideal solution but fortunately others have voiced this issue too in #816 and it should be fixed in #907.

**Comment by btgs-0** [comment]
@kpau if you're able, please try out my feature branch https://github.com/btgs-0/bruno/tree/feature/auth-from-collection and let me know if it works for you

**Comment by kpau** [comment]
@n00o , Thanks for the info. But my issue is a bit different. I understand that `No Auth` uses Collection auth, but in my case I am explicitly setting another type of Auth and it is still using the Collection auth. The issues are related so the root cause _might_ be the same.

@btgs-0 , Thanks for the PR. If I have time today, I'll test the branch. 

Even if the issue is fixed with this PR, it is good to have both issues documented for future reference.

**Comment by btgs-0** [comment]
thanks for testing my PR @kpau. And thanks @n00o for connecting the dots, my PR incidentally fixes this issue by making the collection auth inheritance explicit

**Comment by karloluis** [comment]
It appears that https://github.com/usebruno/bruno/pull/1667 addresses this by explicit requirement of inheritance.

**Comment by sanjai0py** [comment]
Closing this issue as the [PR](https://github.com/usebruno/bruno/pull/1667) implementing the feature has already been merged. Check out this https://github.com/usebruno/bruno/issues/816#issuecomment-2202065577 comment demonstrating the PR's behavior.
