### ISSUE TITLE
[Bug] Empty variable leads to request error

### ISSUE THREAD

**Issue by nakaori** [usebruno/bruno#962]
When an empty variable is configured in the requests vars tab, it leads to the error "Error invoking remote method 'send-http-request': Error: Key is required" which is not really indicative on what to do.

This should either lead to a request that still works anyways or tell me, that i have an empty variable set. 

![empty](https://github.com/usebruno/bruno/assets/35380075/28781044-4bae-4d75-8044-6040ff64cb86)

**Comment by mikaoelitiana** [comment]
@nakaori would the following error makes it clearer? 

![image](https://github.com/usebruno/bruno/assets/674667/d3faf124-d660-4357-98a2-7c5a7f100fc0)

**Comment by nakaori** [comment]
Perfect. Thanks!
