### ISSUE TITLE
 Lack of Multi-Part File Upload Support in Bruno HTTP Client

### ISSUE THREAD

**Issue by this-rafael** [usebruno/bruno#967]
## Description:
Currently, Bruno, our HTTP client, boasts impressive capabilities, but it falls short in a fundamental aspect: the ability to handle multi-part file uploads. This limitation hinders users from performing a basic task - sending files to the server. As a result, users are compelled to resort to alternative tools like Hoppscotch and Postman for this specific functionality.
> In bruno
![image](https://github.com/usebruno/bruno/assets/32933220/9e161bd5-03fb-497a-92f1-25a604be7fd5)

## Request:
We propose the addition of support for multi-part file uploads in Bruno, enabling users to seamlessly send files to the backend. This enhancement would not only make Bruno a more comprehensive HTTP client but also position it as a viable alternative to existing tools like Postman.

> In postman
![image](https://github.com/usebruno/bruno/assets/32933220/745364ae-1093-4298-97f9-a9df3d20fd5d)

## Impact:
The absence of this feature has led users to rely on other tools for file upload functionality, limiting Bruno's adoption as an all-in-one HTTP client solution. Addressing this issue would significantly enhance the user experience and broaden Bruno's utility, aligning it more closely with the expectations of users seeking a Postman alternative.

**Comment by Sl-Alex** [comment]
Here is a PR that addresses the issue: #258

**Comment by sanjai0py** [comment]
Closing this feature request as the requested feature has already been added to bruno through this [PR](https://github.com/usebruno/bruno/pull/1130) and released in [v1.8.0](https://github.com/usebruno/bruno/releases/tag/v1.8.0).
