### ISSUE TITLE
Environment variables are not saved 

### ISSUE THREAD

**Issue by MerwinRod89** [usebruno/bruno#97]
Steps:
1. Create a new environment
2. Add variables and values
3. Click on the Save button
4. Close the window 
5. Open the Environment again

Expected Result
The variables should be visible with all their values

Actual Result
The variables and values disappear

**Comment by helloanoop** [comment]
Hey @MerwinRod89 

I tried to replicate the issue on my mac. Was not able to.

Can you share which version of bruno you are using (you can see it left bottom corner of app)
Also, which OS you are using ?

**Comment by MerwinRod89** [comment]
> Hey @MerwinRod89
> 
> I tried to replicate the issue on my mac. Was not able to.
> 
> Can you share which version of bruno you are using (you can see it left bottom corner of app) Also, which OS you are using ?

Bruno v0.9.2
Mac OS Monterey  v12.5.1

**Comment by helloanoop** [comment]
Can you share a recording of this.
Here is what I am seeing on my mac.

![bruno env vars](https://user-images.githubusercontent.com/9350733/219309888-18ab4a7d-7de4-4157-879f-5cf50352538f.gif)

**Comment by helloanoop** [comment]
In case you don't have a GIF capture tool. You can use the free app GIPHY CAPTURE from app store.

**Comment by MerwinRod89** [comment]
https://user-images.githubusercontent.com/125536563/219316067-e7899bd0-f00b-4cb2-8f63-8e2fc08ed6ff.mov

I think it happens when the variables are not given any values

**Comment by helloanoop** [comment]
Nice catch @MerwinRod89 !
Will have this fixed today and update you.

**Comment by helloanoop** [comment]
@MerwinRod89 
I have fixed this in the latest v0.9.4 release

Please install the latest release and let me know if the issue still persists.

**Comment by MerwinRod89** [comment]
Works now, Thanks @helloanoop
