### ISSUE TITLE
Preview PDF response

### ISSUE THREAD

**Issue by Nightbr** [usebruno/bruno#970]
Hey, 
first of all this project is really refreshing in this space and we already loving it! Congrats for this OpenSource initiative :clap: 

What could be great is like it can preview images, it can preview PDF.

![image](https://github.com/usebruno/bruno/assets/4228646/0e5da057-05bd-42af-a524-85177f9a1a10)

For example in Insomnia:

![image](https://github.com/usebruno/bruno/assets/4228646/45784293-b4b8-49e9-991e-c61e9d1c0c24)

**Comment by Nightbr** [comment]
[PDFViewer.webm](https://github.com/usebruno/bruno/assets/4228646/1dc17a35-7574-4baf-a925-45154ba49371)

LGTM! :clap:

**Comment by helloanoop** [comment]
PR Merged. Will close the issue once I cut a release.

Awesome work @n00o 🎉

**Comment by AlexMeyerPMU** [comment]
Hi @helloanoop awesome work with bruno. Do you have any idea when you'll be able to launch this pdf preview feature ? Thank you.

**Comment by Its-treason** [comment]
> Hi @helloanoop awesome work with bruno. Do you have any idea when you'll be able to launch this pdf preview feature ? Thank you.

This feature is already implemented. @sanjai0py This Issue can also be closed.

**Comment by AlexMeyerPMU** [comment]
Ok. I upgraded bruno this morning, I'm using version 1.20.0, but not seeing any preview. The response is considered application/json. Am I missing something?

**Comment by Its-treason** [comment]
The response's content-type should be `application/pdf` for the preview to work.

**Comment by AlexMeyerPMU** [comment]
Yes of course. The endpoint produces application/pdf, same endpoint, same configuration works fine with insomnia.

**Comment by helloanoop** [comment]
Closing this issue as this functionality is already available in Bruno.
@AlexMeyerPMU please reopen this ticket if you are still facing issues
