### ISSUE TITLE
cert failure in bru cli and as well in bruno UI with SSL validation set.

### ISSUE THREAD

**Issue by charlesvchandran** [usebruno/bruno#975]
Why the bru cli run fails with certificate expired, please share how to fix this and also from UI, how to run with SSL validation set.

Please share the following

1. Steps to  create the cert
2. How to use it ?

(base) ➜  Heimdall Admin UI bru run
Running Folder Recursively

getConfig (certificate has expired)
Admin UI (certificate has expired)

Requests:    0 passed, 2 failed, 2 total
Tests:       0 passed, 0 total
Assertions:  0 passed, 0 total
Ran all requests - 0 ms
(base) ➜  Heimdall Admin UI

**Comment by mlestoquoy** [comment]
You can see below some parameters you can use for bru CLI:
https://github.com/usebruno/bruno/blob/main/packages/bruno-cli/changelog.md
You should consider the following:
`bru cli --insecure`
