### ISSUE TITLE
Environment created only in collection scope - any way to define Global Environments

### ISSUE THREAD

**Issue by AmikWork** [usebruno/bruno#979]
Hi,
Environment created only in collection scope - any way to define Global Environments.
anyway to create Global env or at least have option to duplicate Environments between collections?

Is there also way to define Global variables ?

**Comment by mkrain** [comment]
I agree this is needed.  I'm trying to help my team migrate from Postman to Bruno and this functionality would be helpful to avoid needing to duplicate values across collections.  Similarly this should be considered for .env files as well.

**Comment by Josh-V-PAL** [comment]
Would it be possible to combine your collections into folders inside a single collection instead? I think global variables goes against the current manifesto.

**Comment by AmikWork** [comment]
> Would it be possible to combine your collections into folders inside a single collection instead? I think global variables goes against the current manifesto.

will give it a try - can be good solution for this requirement

**Comment by paulrudy** [comment]
See also #115. I'd really appreciate having a global environments option as well.

**Comment by sanjai0py** [comment]
Issue closed as duplicate. This feature has already been tracked here: https://github.com/usebruno/bruno/issues/115
