### ISSUE TITLE
[feature] Add delVar

### ISSUE THREAD

**Issue by rabbittsoup** [usebruno/bruno#981]
I would like the ability to unset variables, to remove them completely.  In some scripting situations, I will end up with many variables that can clutter up exports or the user interface.  The ability to have the script clean up its variables through an unset operation would be helpful.  Either delVar() or setVar(name, null) or similar style solution would work.

**Comment by helloanoop** [comment]
This is now supported.
https://docs.usebruno.com/scripting/javascript-reference#deletevar
