### ISSUE TITLE
[BUG] res is not a function

### ISSUE THREAD

**Issue by joe-gre** [usebruno/bruno#984]
The [docs mention](https://docs.usebruno.com/scripting/response-query.html) that the `res` function can be used to get data from the response body. However it is an object, not a function, in scripting and vars. 

![image](https://github.com/usebruno/bruno/assets/22748761/c66cd41c-4ef7-4ae6-92ca-8b6604ed54b0)

![image](https://github.com/usebruno/bruno/assets/22748761/1895b6e2-ac9d-4e10-b918-a13c526697d7)

![image](https://github.com/usebruno/bruno/assets/22748761/b8634241-26f3-4859-a0b7-a174fba1aea9)

After printing the stringified object I can see that `res` is the object [described here](https://docs.usebruno.com/scripting/javascript-reference.html#response), and it cannot be called like a function.

I'm using v1.1.1 on Windows 10.

**Comment by JStuve** [comment]
@joe-gre Totally agree that the docs you linked are miss-leading. In the mean-time, reference the [Javascript docs](https://docs.usebruno.com/scripting/javascript-reference.html#getbody-1) for accessing the response data.

**Comment by joe-gre** [comment]
Thanks, yeah I'm currently using `res.getBody()`.

**Comment by sanjai0py** [comment]
Closing this issue as it could not be recreated in the latest version of Bruno [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0)
