### ISSUE TITLE
Wrong GPG key

### ISSUE THREAD

**Issue by Piloair** [usebruno/bruno#986]
$ sudo mkdir -p /etc/apt/keyrings
$ sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266

gpg: caja de claves '/etc/apt/keyrings/bruno.gpg' creada
gpg: failed to create temporary file '/root/.gnupg/.#lk0x000055b3dcf2aed0.pilo-E402SA.16344': No existe el archivo o el directorio
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No existe el archivo o el directorio
gpg: recepción del servidor de claves fallida: No existe dirmngr

$ dirmngr
....
OK Dirmngr 2.2.27 at your service

$ sudo apt update
Ign:1 http://packages.linuxmint.com victoria InRelease
Obj:2 http://packages.linuxmint.com victoria Release                           
Des:3 http://debian.usebruno.com bruno InRelease [1 812 B]                     
Des:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]      
Obj:5 http://archive.ubuntu.com/ubuntu jammy InRelease        
Des:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Err:3 http://debian.usebruno.com bruno InRelease                    
  Las firmas siguientes no se pudieron verificar porque su clave pública no está disponible: NO_PUBKEY 56333D3B745C1FEC
Obj:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease    

$ sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 56333D3B745C1FEC
gpg: clave 9FA6017ECABE0266: clave pública "Anoop M D <anoop.md1421@gmail.com>" importada
gpg: Cantidad total procesada: 1
gpg:               importadas: 1

$ sudo apt update
............................
N: Omitiendo el uso del fichero configurado «stable/binary-i386/Packages» ya que el repositorio «http://debian.usebruno.com bruno InRelease» no admite la arquitectura «i386»

$ sudo apt install bruno

OK

**Comment by jornj** [comment]
I had a similar issue with a `gpg: failed to create temporary file '/root/.gnupg/......` message.

The fix for me was to run this first:

    $ sudo dirmngr
    ...
    dirmngr[54194.0]: failed to open cache dir file '/root/.gnupg/crls.d/DIR.txt': No such file or directory
    dirmngr[54194.0]: creating directory '/root/.gnupg'
    dirmngr[54194.0]: creating directory '/root/.gnupg/crls.d'
    dirmngr[54194.0]: new cache dir file '/root/.gnupg/crls.d/DIR.txt' created
    ...

The rest of the instructions with the `sudo gpg`-command line then works as expected.

**Comment by sanjai0py** [comment]
I have closed the issue as it seems to be fixed!
