### ISSUE TITLE
Collection Location

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#989]
Display the collection location inside collection settings.

![image](https://github.com/usebruno/bruno/assets/9350733/092abfc2-cf41-498b-be63-dc0483037253)

**Comment by sanjai0py** [comment]
Closing this feature request as the [PR](https://github.com/usebruno/bruno/pull/718) implementing the feature has already been merged into Bruno and released in [v1.2.0](https://github.com/usebruno/bruno/releases/tag/v1.2.0).
