### ISSUE TITLE
When importing from openApi, the summary gets ignored

### ISSUE THREAD

**Issue by gianpo86** [usebruno/bruno#994]
In case of a collection imported from an openApi definition, the summary gets ignored and just the operationId gets shown in the collection list. This causes the collection of being not good readable when imported in the UI

**Comment by Nevario** [comment]
Thanks for creating this issue and PR! Looking forward to seeing it merged :)

<img width="596" alt="image" src="https://github.com/usebruno/bruno/assets/2949564/36eb625c-cc08-4ffe-8820-84e67d380b9a">
