### ISSUE TITLE
Error invoking remote method 'send-http-request': ReferenceError: request is not defined

### ISSUE THREAD

**Issue by cyrilgeorge153** [usebruno/bruno#996]
Used npm library @faker-js/faker 8.3.1 to generate fake data but getting the error mentioned in title.
package.json
{
  "dependencies": {
    "@faker-js/faker": "8.3.1"
  }
}
Bruno version:1.2.0 snap version
OS version:Ubuntu 22.04
![image](https://github.com/usebruno/bruno/assets/52770689/3d003fb6-f66e-4c63-83e6-9124de2145ed)

**Comment by n00o** [comment]
Oh I see, that is my bad. The then you want to to be:
```JavaScript
req.setBody({
  email: randomEmail,
  password: randomPassword
})
```
I didn't notice that you had `setData()` which is not a function.

**Comment by cyrilgeorge153** [comment]
@n00o Thanks for the quick help, req.setBody() worked. The documentation needs an update.
