### ISSUE TITLE
[Feature Request] Add link from runner to request

### ISSUE THREAD

**Issue by gmajcen** [usebruno/bruno#997]
When using runner for whole collection there is no way to move to actual request. You can see response, but can not edit request without manual search.

This is useful when you have status 400/500 and want to quick look whats wrong with request.

Thank you.

**Comment by sanjai0py** [comment]
Closing this feature request as it has already been incorporated into Bruno. Also, closing your other [issue](https://github.com/usebruno/bruno/issues/998) as it has also been implemented into Bruno. 

https://github.com/usebruno/bruno/assets/84461672/62e29c63-b8ac-4e91-b29c-0a4dcb53db69
